### ISSUE TITLE
Cannot find function 'entry0' 

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2#8952] opened 2017-12-04 11:01 UTC
Hi,
with some binaries, I obtain the error

>Cannot find function 'entry0'  at 0x0040a42f entry0 (aa)

when I analyze them with aa/aaaa and thus I can obtain any information about functions with afl
IDA can extract all the functions without any manual intervention 
There are any suggestions?

**Comment by Maijin** [comment] 2017-12-04 11:48
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment] 2017-12-04 12:11
please provide a testcase with a binary, commands and screenshots.i cant reproduce

**Comment by GiuseppeLaurenza** [comment] 2017-12-04 12:32
in the evening I load a binary on drive
I use aa and aaaa
![schermata 2017-12-04 alle 13 31 15](https://user-images.githubusercontent.com/20904860/33553058-7ef13582-d8f7-11e7-8a80-77efbefb9bad.png)
![schermata 2017-12-04 alle 13 31 36](https://user-images.githubusercontent.com/20904860/33553060-824d85fa-d8f7-11e7-80e6-57d65ab444d7.png)

**Comment by Maijin** [comment] 2017-12-04 13:19
Can you drag and drop binary here in a zip archive ?

**Comment by Maijin** [comment] 2017-12-04 15:57
ping @GiuseppeLaurenza

**Comment by GiuseppeLaurenza** [comment] 2017-12-04 15:59
@Maijin I can upload the file in three-four hours

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 08:49
Hi, sorry about the delay
[entry0_error.zip](https://github.com/radare/radare2/files/1534407/entry0_error.zip)
password infected

**Comment by Maijin** [comment] 2017-12-06 08:55
```
[Sections]
idx=00 vaddr=0x00401000 paddr=0x00000400 sz=8192 vsz=8192 perm=m-r-- name=.rdata
idx=01 vaddr=0x00403000 paddr=0x00002400 sz=30208 vsz=78032896 perm=m-rw- name=.data
idx=02 vaddr=0x04e6e000 paddr=0x00009a00 sz=1536 vsz=4096 perm=m-r-- name=.rsrc

3 sections
```

Sections aren't executables that's why

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 08:56
How I can analyze the functions in it? Ida does some magic and correctly extracts them

**Comment by Maijin** [comment] 2017-12-06 08:56
You can force execution of a function by looking at output of `S*` then add a x like: 
`S 0x00002400 0x00403000 0x00007600 0x04a6b000 .data mrwx`

**Comment by Maijin** [comment] 2017-12-06 08:57
before aaa obv

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 08:59
thanks it appears to be solved, I perform more test and than I close the issue

**Comment by Maijin** [comment] 2017-12-06 09:29
Closing now

**Closed by Maijin** 2017-12-06 09:29 UTC
Labels: anal, rabin2, test-required

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 11:14
Sorry for the stupid question, with S* I obtain

> f section..text 113152 0x401000
S 0x00000400 0x00401000 0x0001ba00 0x0001c000 .text mr-x
f section..rdata 27648 0x41d000
S 0x0001be00 0x0041d000 0x00006c00 0x00007000 .rdata mr--
f section..data 8192 0x424000
S 0x00022a00 0x00424000 0x00002000 0x00006000 .data mrw-
f section..rsrc 280576 0x42a000
S 0x00024a00 0x0042a000 0x00044800 0x00045000 .rsrc mr--
f section..reloc 28672 0x46f000
S 0x00069200 0x0046f000 0x00007000 0x00007000 .reloc mr--

**Comment by Maijin** [comment] 2017-12-06 11:14
Not the file you provided.

**Comment by Maijin** [comment] 2017-12-06 11:16
https://asciinema.org/a/eE99Gmih8w2prcqspg6bAM50Q

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 11:18
Sorry, I confuse the two samples that I submit
The second question remains, which sections I have to make executable? All or only data?

**Comment by Maijin** [comment] 2017-12-06 11:19
The one you consider to be executable, that's up to your analysis work, you can mark them all executable if you want. In the example I marked only the section which have entrypoint executable see the asciinema

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 11:22
thanks for the support, from the video I do not understand how you detect that data is the only section which have entry point executables

**Comment by Maijin** [comment] 2017-12-06 11:38
The * in S display

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 12:39
thanks

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 12:46
Just another question that is not full related to this
using S I obtain the value address value, but from json I obtain an encoded value that I do not know how to convert into the address using python. Can you help me?
