### ISSUE TITLE
Enhance support of Dalvik :)

### ISSUE THREAD

**Issue by cryptax** [radare/radare2#5773] opened 2016-09-15 10:31 UTC
I am using _today's git (Sept 15)_.

Please get classes.dex from _[https://my.owndrive.com/index.php/s/uTrGVCtBh0ko09i](https://my.owndrive.com/index.php/s/uTrGVCtBh0ko09i)_ (it is taken from Android/Crosate malware, please beware ;) I do not believe this DEX is particularly advanced or tricky.
Rename the sample to classes.dex for instance.

**Cross references for the string** controlcenter.com/teapotxxx is not showing:

```
$ r2 classes.dex
0x0001deb8]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x0001deb8]> f~http
...
0x00064fef 49 str.http:__verisign_controlcenter.com_teapot_gate.php
..
[0x0001deb8]> pd 1 @ str.http:__verisign_controlcenter.com_teapot_gate.php
            ;-- str.http:__verisign_controlcenter.com_teapot_gate.php:
            0x00064fef     .string "http://verisign-controlcenter.com/teapot/gate.php" ; len=49 ; compare long
```

Actually, it is used here 0x00030d20, which is contained within the method: Lcom/adobe/flashplayer_/AFC.method.onCreate()V.

Note that **axt** does not provide the xref either:

```
axt str.http:__verisign_controlcenter.com_teapot_gate.php
[0x0001dfb8]> 
```

The method Lcom/adobe/flashplayer_/AFC.method.onCreate()V does not list with **afl**, though it does with **ic**. That's strange too.

```
> afl~Lcom_adobe_flashplayer__AFC
0x00030b50    1 12           sym.Lcom_adobe_flashplayer__AFC_1.method._init__Lcom_adobe_flashplayer__AFC_JJ_V
0x00030bc0    1 8            sym.Lcom_adobe_flashplayer__AFC.method._init___V
0x00030bd8    1 34           sym.Lcom_adobe_flashplayer__AFC.method.writeConfig_Ljava_lang_String_Ljava_lang_String__V
> ic~Lcom/adobe/flashplayer_/AFC
0x00011ed4 class 232 Lcom/adobe/flashplayer_/AFC$1
0x00030b50 method 0 Lcom/adobe/flashplayer_/AFC$1.method.<init>(Lcom/adobe/flashplayer_/AFC;JJ)V
0x00030b5c method 1 Lcom/adobe/flashplayer_/AFC$1.method.onFinish()V
0x00030b78 method 2 Lcom/adobe/flashplayer_/AFC$1.method.onTick(J)V
0x00011ed5 class 233 Lcom/adobe/flashplayer_/AFC
0x00030bc0 method 0 Lcom/adobe/flashplayer_/AFC.method.<init>()V
0x00030bd8 method 1 Lcom/adobe/flashplayer_/AFC.method.writeConfig(Ljava/lang/String;Ljava/lang/String;)V
0x00030c10 method 2 Lcom/adobe/flashplayer_/AFC.method.decrypt(Ljava/lang/String;I)Ljava/lang/String;
0x00030c7c method 3 Lcom/adobe/flashplayer_/AFC.method.onBind(Landroid/content/Intent;)Landroid/os/IBinder;
0x00030c90 method 4 Lcom/adobe/flashplayer_/AFC.method.onCreate()V
0x00030e18 method 5 Lcom/adobe/flashplayer_/AFC.method.onDestroy()V
```

Weird too, the **method does not disassemble correctly**. The first commands of the method are:

``` java
Object v20 = this.getSystemService("phone");
String v18 = this.getSystemService("phone").getLine1Number();
```

but if we disassemble with r2, we see _strange calls_ (see invoke-..) and _no mention of getSystemService or getLine1Number_ (which are implemented by the Android system):

```
pd 10 @ 0x00030c90
            ;-- Lcom/adobe/flashplayer_/AFC.method.onCreate()V:
            ;-- method.Lcom_adobe_flashplayer__AFC.Lcom_adobe_flashplayer__AFC.method.onCreate__V:
            0x00030c90      16000100       const-wide/16 v0, 0x01      ; move literal into the specified register-pair
            0x00030c94      06000000171a   move-wide/16 v0, v6679      ; move the contents of one register-pair to another
            0x00030c9a      0700           move-object v0, v0          ; move the contents of one object-bearing register to anothe
            0x00030c9c      bc00           sub-long/2addr v0, v0       ; subtraction
            0x00030c9e      0000           nop                         ; no operation
            0x00030ca0      750169001500   invoke-super/range {v21..v21}, 0x0 ; call method; CALL: 0x353330, 0x28f04aa6, 0x5b4d71a, 0x3fb920c4
            0x00030ca6      1a02da0f       const-string v2, str.phone  ; str.phone ; move a reference to the string specified by the given index into the specified register
            0x00030caa      08001500       move-object/from16 v0, v21  ; move the contents of one object-bearing register to anothe
            0x00030cae      6e20b00d2000   invoke-virtual {v0, v2}, 0x0 ; 0xdb0 ; call method; CALL: 0x353330, 0x28f04aa6, 0x5b4d71a, 0x3fb920c4
            0x00030cb4      0c14           move-result-object v20      ; move the object result of the most recent invoke-kind into the indicated registe
```

If we try and do it the other way round and _search for the string getLine1Number_, we are _unable to see where it is used._ (well, I am not).

```
> f~getLine1Number
0x00064444 14 str.getLine1Number
[0x0001dfb8]> pd 1 @ str.getLine1Number
            ;-- str.getLine1Number:
            0x00064444     .string "getLine1Number" ; len=14           ; return from a void method
```

We do see the function in the **imports** (which is good), but how do I know where this is used?

```
[0x0001dfb8]> ii~getLine
ordinal=000 plt=0x00000000 bind=NONE type=FUNC name=imp.Landroid/telephony/TelephonyManager.method.getLine1Number()Ljava/lang/String;
```

We see **getLine1Number** in the **strings** as well, but it points to the address of the string, so we won't know who's using it:

```
[0x0001dfb8]> iz~getLine
vaddr=0x00064444 paddr=0x00064444 ordinal=2847 sz=14 len=14 section=data type=ascii string=getLine1Number
[0x0001dfb8]> pd 1 @ 0x00064444
            ;-- str.getLine1Number:
            0x00064444     .string "getLine1Number" ; len=14           ; return from a void method
```

Finally, the **entrypoint** in a Dalvik is shown in the Android manifest. In this case, it is _Lcom/adobe/flashplayer_/FA_. I don't know if you can manage to get that, but the command **ie** not does point to that.

```
ie
[Entrypoints]
vaddr=0x0001deb8 paddr=0x0001deb8 baddr=0x00000000 laddr=0x00000000 type=program

1 entrypoints
```

**Comment by h4ng3r** [comment] 2016-09-23 08:11
Anal is not working and I'm focusing on disas first. The entrypoints cant be parsed from the AndroidManifest so we need to think how should we handle that. I'll check the other issues next week.

**Comment by h4ng3r** [comment] 2016-09-24 16:39
@cryptax I checked the disassamble with the latest version and it seems ok, can you check it again plis? 
This is what I get with r2:
```
[0x0001deb8]> pd 20 @ 0x00030CA0
            ;-- Lcom/adobe/flashplayer_/AFC.method.onCreate()V:
            ;-- method.Lcom_adobe_flashplayer__AFC.Lcom_adobe_flashplayer__AFC.method.onCreate__V:
            0x00030ca0      750169001500   invoke-super/range {v21..v21}, Landroid/app/ServiceonCreate()V
            0x00030ca6      1a02da0f       const-string v2, str.phone  ; str.phone
            0x00030caa      08001500       move-object/from16 v0, v21
            0x00030cae      6e20b00d2000   invoke-virtual {v0, v2}, Lcom/adobe/flashplayer_/AFCgetSystemService(Ljava/lang/String;)Ljava/lang/Object; ; 0xdb0
            0x00030cb4      0c14           move-result-object v20
            0x00030cb6      1f148d01       check-cast v20, Landroid/telephony/TelephonyManager;
            0x00030cba      1a02da0f       const-string v2, str.phone  ; str.phone
            0x00030cbe      08001500       move-object/from16 v0, v21
            0x00030cc2      6e20b00d2000   invoke-virtual {v0, v2}, Lcom/adobe/flashplayer_/AFCgetSystemService(Ljava/lang/String;)Ljava/lang/Object; ; 0xdb0
            0x00030cc8      0c13           move-result-object v19
            0x00030cca      1f138d01       check-cast v19, Landroid/telephony/TelephonyManager;
            0x00030cce      7401a70b1300   invoke-virtual/range {v19..v19}, Landroid/telephony/TelephonyManagergetLine1Number()Ljava/lang/String;
            0x00030cd4      0c12           move-result-object v18
            0x00030cd6      7401a60b1400   invoke-virtual/range {v20..v20}, Landroid/telephony/TelephonyManagergetDeviceId()Ljava/lang/String;
            0x00030cdc      0c08           move-result-object v8
            0x00030cde      7401a80b1400   invoke-virtual/range {v20..v20}, Landroid/telephony/TelephonyManagergetNetworkOperatorName()Ljava/lang/String;
            0x00030ce4      0c0a           move-result-object v10
            0x00030ce6      7401a90b1400   invoke-virtual/range {v20..v20}, Landroid/telephony/TelephonyManagergetSimCountryIso()Ljava/lang/String;
            0x00030cec      0c09           move-result-object v9
            0x00030cee      62101600       sget-object v16, Landroid/os/Build$VERSION;
[0x0001deb8]>
```

**Comment by cryptax** [comment] 2016-09-26 08:38
@h4ng3r yes, you are correct, I get that too now. And that's a correctly disassembly, so that's already one fix :)

**Comment by h4ng3r** [comment] 2016-09-28 15:06
@cryptax, can you try this again with the last version pls? Now, I see some xrefs:
```
[0x0001deb8]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x0001deb8]> axt str.http:__verisign_controlcenter.com_teapot_gate.php
data 0x30d20 const-string v14, str.http:__verisign_controlcenter.com_teapot_gate.php in sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V
[0x0001deb8]>
```

**Comment by cryptax** [comment] 2016-09-30 14:32
@h4ng3r - pulled new version. Yes, I confirm, I see the references too myself. Well done!

**The things that don't work yet**

We don't see where getLine1Number is used:

```
0x0001dfb8]> pd 1 @ str.getLine1Number 
            ;-- str.getLine1Number:
            0x00064444     .string "getLine1Number" ; len=14           ; return from a void method
```

The references from sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V are not correct. They should list for instance getLine1Number, shouldn't they?

```
axf @ sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V
C 0x30ca0 invoke-super/range {v21..v21}, Landroid/app/Service.onCreate()V
```

**The things that now work (congrats!):**

```
[0x0001deb8]> axt str.http:__verisign_controlcenter.com_teapot_gate.php
data 0x30d20 const-string v14, str.http:__verisign_controlcenter.com_teapot_gate.php in sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V
```

I also have the xref using pd 1 @ on the string:
```
0x0001dfb8]> pd 1 @ str.http:__verisign_controlcenter.com_teapot_gate.php
            ;-- str.http:__verisign_controlcenter.com_teapot_gate.php:
            ; DATA XREF from 0x00030d20 (sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V)
            0x00064fef     .string "http://verisign-controlcenter.com/teapot/gate.php" ; len=49 ; compare long
```

It works with afl and ic:
```
[0x0001dfb8]> afl~Lcom_adobe_flashplayer__AFC.method.onCreate
0x00030ca0   12 376          sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V
[0x0001dfb8]> ic~Lcom/adobe/flashplayer_/AFC.method.onCreate
0x00030ca0 method 4 Lcom/adobe/flashplayer_/AFC.method.onCreate()V
```

**Comment by Maijin** [comment] 2016-09-30 14:49
@cryptax I strongly recommend you take a look at the commit that made this possible :)

**Comment by h4ng3r** [comment] 2016-10-09 22:10
@cryptax I think that the problem is that "str.getLine1Number" is not being used, indeed IDA Pro also found this string, so its correct. But of course it does not have any XREF.

What exists is a method called "getLine1Number " and xrefs work for this method:
```
[0x00030cea]> f~getLine1Number
0x00064444 14 str.getLine1Number
0x00007227 0 sym.imp.Landroid_telephony_TelephonyManager.method.getLine1Number__Ljava_lang_String_
[0x00030cea]> axt @ 0x00007227
call 0x30cce invoke-virtual/range {v19..v19}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; in sym.Lcom_adobe_flashplayer__AFC.method.onCreate__V
call 0x31098 invoke-virtual {v9}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; ; 0xba7 in sym.Lcom_adobe_flashplayer__AU.method.sendREP_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Landroid_content_Context__V
call 0x313f2 invoke-virtual/range {v40..v40}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; in sym.Lcom_adobe_flashplayer__AU.method.onCreate__V
call 0x328d0 invoke-virtual {v9}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; ; 0xba7 in sym.Lcom_adobe_flashplayer__FU.method.sendREP_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Landroid_content_Context__V
call 0x36cb4 invoke-virtual {v9}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; ; 0xba7 in sym.Lcom_adobe_flashplayer__UC.method.sendREP_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Landroid_content_Context__V
call 0x3763c invoke-virtual/range {v17..v17}, Landroid/telephony/TelephonyManager.getLine1Number()Ljava/lang/String; in sym.Lcom_adobe_packages_CheckLicense.method.onCreate_Landroid_os_Bundle__V
[0x00030cea]>
```

**Comment by cryptax** [comment] 2016-11-07 13:20
@h4ng3r well it's the way DEX works doesn't it? You reference a method, and actually the method's name goes in the pool of strings in the DEX. So, yes, you don't directly use the string for the method name, but still, it's there because we use the function...
See https://source.android.com/devices/tech/dalvik/dex-format.html and in particular method_id_item.

Said differently, I would somewhat expect str.getLine1Number to be "used"/"referenced" by sym.imp.Landroid_telephony_TelephonyManager.method.getLine1Number, and the code to call sym.imp.Landroid_telephony_TelephonyManager.method.getLine1Number

**Comment by h4ng3r** [comment] 2016-11-07 14:25
@cryptax, If you are familiarised with the DEX format you could help us improving DEX and dalvik analysis ;)

About the "sym.imp.Landroid_telephony_TelephonyManager.method.getLine1Number" it starts with sym.imp so it is an import. Imports are quite special, because they are a type inside de type_ids but is not being referenced by any method in a class. That means that we do not have the code for this method, because code_item is part of encoded_method which is part of class_data_item.

So I think that str.getLine1Number should not have any xref. Do you agree?

**Comment by cryptax** [comment] 2016-11-14 15:18
@h4ng3r hi - I haven't forgotten your question, but the answer is not obvious to me. 
Normally, the strings in the string table are referenced to by where they are used. At some point, we have to have a link between that onCreate() method and getLine1Number().

However, I have loaded the dex in 010 Editor, and getLine1Number() does not appear in the strings table, but  in a strange table at the end of the DEX "injected_data" table which is a table of data after the map section which should not be there 

_"There appears to be extra data injected after the map list @ [ %d ] with a size of [ %d ] that is before the end of the dex file."_

and I can't trace it back to onCreate(). I've asked some help to @strazzere on this, I'll let you know if we can work it out.

**Comment by h4ng3r** [comment] 2017-01-24 22:46
@cryptax, can we close the issue? Thanks

**Comment by radare** [comment] 2017-01-24 22:54
I think so!

**Closed by radare** 2017-01-24 22:54 UTC
Labels: android
