### ISSUE TITLE
Opening second file always fails the first time

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6676] opened 2017-02-03 19:50 UTC
```
$ r2 -d /bin/true  
[0x7f218fef4cd0]> o /bin/ls   # first it fails
= attach 6 6
Cannot open /bin/ls
6
[0x5569cda69580]> o /bin/ls  # then it works
= attach 8 8
8
[0x00005340]>`
```

doesn't happen when starting from `r2 -`

**Comment by condret** [comment] 2017-02-03 20:02
@radare : thats why I don't like io->referer

**Comment by radare** [comment] 2017-02-03 23:17
Should be fixed in the siol branch

**Comment by condret** [comment] 2017-02-04 09:05
yep

**Comment by radare** [comment] 2017-02-04 10:57
cant reproduce on mac

**Comment by SchumBlubBlub** [comment] 2017-02-04 11:35
still repro on linux

**Comment by radare** [comment] 2017-02-04 16:52
Thats just a warning from rbin, because the path is not updated internally the info is loaded.

**Closed** 2017-02-04 16:59 UTC
Labels: bug, Linux OS

**Comment by Maijin** [comment] 2017-02-04 17:04
Test @SchumBlubBlub ?

**Comment by SchumBlubBlub** [comment] 2017-02-04 17:06
Yeah, :+1:
