### ISSUE TITLE
V! glitches when scroll horizontally

### ISSUE THREAD

**Issue by Vane11ope** [radare/radare2#10339] opened 2018-06-13 17:05 UTC
how to reproduce the bug

1. download this ctf binary "serial" https://github.com/ctfs/write-ups-2016/tree/master/su-ctf-2016/reverse/serial-150
2. sys/install.sh radare
3. r2 -dNAA ./serial
4. V!
5. push "l" ten times so that the main panel scrolls to left
6. glitch

tput cols shows 272 and tput lines shows 79

**Comment by radare** [comment] 2018-06-13 21:58
its the same bug about the crop() bug with utf8

do this happens without utf8?

**Comment by Vane11ope** [comment] 2018-06-14 04:23
@radare the issue has been introduced since the commit 83e85ee07f1e0e900a3b15a805c254b1bf801fc5
and it still has been existing 14/06/2018 13:22 JST the latest master. turning off the utf-8 flag does not mean anything for this, it seems.

**Comment by Vane11ope** [comment] 2018-06-14 06:55
woo no sorry panels seems turning on utf8 internally, not depending on the config and seems its always on.

i turned it off and everything works fine. i will fix panels to take the config anyway.

**Comment by radare** [comment] 2018-06-14 08:40
yeah, so it makes sense to me, and imho its a dupe of the other bug i reported

**Comment by Vane11ope** [comment] 2018-06-14 09:16
thought so too but cyanpencil thought he'd fixed the bug i found already, so he asked me the situation in detail and had me issue this and now we are. hope the fix for the other bug would fix this too.

**Closed** 2018-06-14 15:46 UTC
Labels: consoleui
