### ISSUE TITLE
pdfj wrong output - implement pdrj

### ISSUE THREAD

**Issue by VPaulV** [radare/radare2#5432] opened 2016-07-31 22:33 UTC
For some functions pdfj provides wrong fcn_addr for opcodes.
For example:
```
| ,=======< 0x00f29beb      eb03           jmp 0xf29bf0
  |||||||   0x00f29bed      8d4900         lea ecx, [ecx]
| |||||||   ; JMP XREF from 0x00f29beb (fcn.00f29970)
```
```
{"offset":15899627,"fcn_addr":15898992,"fcn_last":15899793,"size":2,"opcode":"jmp 0xf29bf0","bytes":"eb03","family":"cpu","type":"jmp","type_num":1,"type2_num":0,"jump":15899632},
{"offset":15899629,"fcn_addr":0,"fcn_last":0,"size":3,"opcode":"lea ecx, [ecx]","bytes":"8d4900","family":"cpu","type":"lea","type_num":33,"type2_num":0}
```

**Comment by VPaulV** [comment] 2016-07-31 22:38
```
r2 -B 0x00F20000  malware_dump_0x00F20000
[0x00f2ed70]> aaa
[0x00f2ed70]> pdf @0xf29970
[0x00f2ed70]> pdfj @0xf29970
```
[infected.zip (password infected)](https://github.com/radare/radare2/files/392676/infected.zip)

**Comment by radare** [comment] 2016-08-02 16:40
this is not a bug, consider it a feature. this means that those instructions are not part of the function , but they are contained in the range of it. this can happen when there's dead code, or there's code shared between different functions.

**Comment by radare** [comment] 2016-08-02 16:41
this should be fixed with `pdrj` whichi only shows the instructions contained by the function itself, not in range (but pdrj is not yet done)

**Closed** 2016-08-08 09:07 UTC
Labels: easy, enhancement
