### ISSUE TITLE
race condition in socket handling

### ISSUE THREAD

**Issue by dsockwell** [radare/radare2#3400] opened 2015-10-01 22:05 UTC
When using radare2's network code on a less-than-instantaneous network, transmissions get cut off RST, ACK if they aren't finished in about 8ms. I believe the problem is close to https://github.com/radare/radare2/blob/master/libr/socket/socket.c#L489

brief packet trace: http://sprunge.us/DcEe
seriously long packet trace: http://sprunge.us/eVjH

**Comment by dsockwell** [comment] 2015-10-01 22:13
in the http server this causes missing files when accessing the ui with chrome and incomplete files with firefox. Intermittently, the planets align and the UI works fine but trying to do anything with it is painful.

**Comment by dsockwell** [comment] 2015-10-01 22:32
code for the http server has some explicit closing of the socket, too.

https://github.com/radare/radare2/blob/master/libr/socket/http_server.c#L133

**Comment by radare** [comment] 2015-10-03 09:23
Confirmed. This is a regression it was not happening some weeks ago. I will review when i have some time.

Thanks for posting

**Comment by radare** [comment] 2015-10-03 10:55
This bug can be reproduced with curl, but not with wget

**Comment by dsockwell** [comment] 2015-10-04 01:30
I invited 'stevejobsinhell' from IRC to rewrite the send() wrapper. he seems to know his sockets well but hasn't been back online for a little while.

**Comment by radare** [comment] 2015-10-04 17:48
Cool, im a bit busy irl, so it will be good to have another pair of eyes to look at it.

i’ll try to find some time to check it out, but this should be fixed before the release.

**Comment by radare** [comment] 2015-10-08 11:31
i dont have any networking problem with the latest changes in rsocket,. can you confirm?

**Comment by radare** [comment] 2015-10-12 19:35
Ping

**Comment by radare** [comment] 2015-10-13 02:19
Cannot reproduce anymore. please reopen if you are having networking problems with the r2 webui

**Closed by radare** 2015-10-13 02:19 UTC
Labels: bug, regression
