### ISSUE TITLE
Add shortcut for S 0 0 $s $s foo mrwx

### ISSUE THREAD

**Issue by radare** [radare/radare2#6005] opened 2016-10-20 21:01 UTC
needed to make analysis work when loading with -nn

maybe we shuold unset some options and tune anal.noncode a little bit more to ease this thing

**Comment by radare** [comment] 2016-10-20 21:02
this should work with `e io.va=0` and it is not. we need to tune the is_valid_address() function a bit more

**Comment by Maijin** [comment] 2016-10-21 09:31
Duplicate of https://github.com/radare/radare2/issues/5289

**Comment by radare** [comment] 2016-10-29 14:15
I dont think this is a dupe

**Comment by Maijin** [comment] 2016-10-29 15:30
Definitely dup with the other issue

**Closed** 2016-11-05 23:49 UTC
Labels: anal
