### ISSUE TITLE
`pf` doesn't autoload headers information in Cygwin

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2435] opened 2015-04-24 13:51 UTC
Just simple

```
radare2.exe -nn rarun2.exe
[0x000000000]> pf.
```

returns nothing

**Comment by radare** [comment] 2015-04-24 14:45
Check installation paths and such...

**Comment by radare** [comment] 2016-10-27 12:33
hello? im gonna close this because it looks like an installation issue and its more than a year without feedback

**Comment by Maijin** [comment] 2016-10-27 12:34
@radare https://github.com/radare/radare2/issues/5348

**Comment by Maijin** [comment] 2016-10-27 12:34
Probably not fixed

**Comment by radare** [comment] 2016-10-27 15:40
then someone should care of that, it works in all systems and i dont think anybody cares about cygwin nowadays

**Comment by radare** [comment] 2016-10-28 10:12
try with the new ik* command

**Comment by radare** [comment] 2016-11-02 00:17
ping

**Comment by alvarofe** [comment] 2016-11-03 09:01
It doesn't work for me on mac os x. is just me or regression?

**Comment by radare** [comment] 2016-11-03 09:02
regression. it was working when i commited it iirc

**Comment by alvarofe** [comment] 2016-11-03 09:03
http://asciinema.org/a/24ruvcknzqp0054j4wjizaxzx

**Comment by XVilka** [comment] 2017-01-16 16:50
Meh, some new error.
```
~/radare/radare2/radare2-w32-1.2.0-git
$ ./radare2 -nn rabin2.exe
      7 [main] radare2 13052 child_info_fork::abort: D:\Work\radare\radare2\radare2-w32-1.2.0-git\libr_parse.dll: Loaded to different address: parent(0x2D0000) != child(0x410000)
 -- Here be dragons.
[0x00000000]> pf.
```

**Comment by Maijin** [comment] 2017-01-16 16:53
again?

**Comment by XVilka** [comment] 2017-01-16 16:54
Why again? Have you seen the same error before?

**Comment by radare** [comment] 2017-01-20 13:21
its beacuse of the abs vs relative paths?

**Comment by radare** [comment] 2017-01-29 03:02
ping @XVilka

**Comment by radare** [comment] 2017-01-29 18:01
im closing this bug because its not having feedback for a lot of time and nobody is using cygwin . if this is an issue its because of the path is trying which just depends on the way you build r2, and we dont build official cygwin compilations of r2. so if you dont care, i care even less

**Closed by radare** 2017-01-29 18:01 UTC
Labels: pf, regression, Windows
