### ISSUE TITLE
/x issues

### ISSUE THREAD

**Issue by codido** [radare/radare2#4084] opened 2016-02-07 04:52 UTC
- Hits do not overlap:
```
[0x00000000]> w AAAA
[0x00000000]> /x 4141
Searching 2 bytes in [0x0-0x200]
hits: 2
0x00000000 hit0_0 4141
0x00000002 hit0_1 4141
```

Hits at offsets 0x1 and 0x3 are missing.

- nibble any-matches seem to depend on the block size:
```
[0x00000000]> w AAAA
[0x00000000]> /x 41.1
Searching 2 bytes in [0x0-0x200]
hits: 2
0x00000000 hit0_0 4141
0x00000002 hit0_1 4141
[0x00000000]> b 3
[0x00000000]> /x 41.1
Searching 2 bytes in [0x0-0x200]
hits: 1
0x00000000 hit1_0 4141
[0x00000000]> b 2
[0x00000000]> /x 41.1
Searching 2 bytes in [0x0-0x200]
hits: 0
[0x00000000]> /x 4141
Searching 2 bytes in [0x0-0x200]
hits: 2
0x00000000 hit2_0 4141
0x00000002 hit2_1 4141
```

**Comment by jjdredd** [comment] 2016-02-07 05:46
I thought the search bug with block size has already been fixed. Please add more tests.

**Comment by radare** [comment] 2016-02-07 06:59
This is on purpose and theres a var to configure this behaviour

**Comment by gitido** [comment] 2016-02-07 07:03
@radare I assume you're referring only to the first issue, right?
btw, which var configures that behavior?

As for the second issue, I guess that's not the intended behavior, correct?

**Comment by Maijin** [comment] 2016-02-07 09:02
For the first one : `e? search.align` for the second I don't know, ping @radare

**Comment by radare** [comment] 2016-02-07 09:11
e search.contiguous

**Comment by gitido** [comment] 2016-02-07 14:02
@Maijin @radare Changing the search.align to true didn't seem to change the first issue.
Please note that if the first byte isn't 'A', offset 0x1 will be found. I believe the issue is with overlapping, not alignment - probably next search begins after the last processed byte of the pattern.
As for search.contiguous, enabling it limits the hit results even more (a single hit at offset 0) for the test above.

The second issue seems unaffected by either of these variables.

**Comment by radare** [comment] 2016-02-07 16:02
Search.align is not a boolean variable. Its numeric and expects to be the alignment mod to skip unaligned hits.

Please add tests for all those cases. Thanks

**Comment by gitido** [comment] 2016-02-08 05:47
OK, so with the default search.align (=0), I guess it shouldn't limit the results, right?

Pushed tests for these cases here:
https://github.com/radare/radare2-regressions/pull/307

Thanks!

**Comment by radare** [comment] 2016-02-08 05:53
Yep. Align=0 means no alignmwnt restrictions

**Comment by radare** [comment] 2016-02-12 17:03
What you want is the `e search.chunk=1`

**Comment by radare** [comment] 2016-02-12 17:38
Sorry, just added `search.overlap` to address this issue. i have added two test cases for this.

thanks for reporting

**Comment by gitido** [comment] 2016-02-14 04:33
search.overlap indeed fixes the first issue, thanks!
Just wondering, any reason it shouldn't be the default?

As for the second issue reported here, it hasn't been resolved yet, right?

**Comment by radare** [comment] 2016-02-14 07:03
I dont see why anyone wants to catch all the overlapping keyword hits by default. This will result in much more hits in some situations, my main concern here is that this requires soms real testing for a while before it gets enabled by default, to avoid infinite loops or false positives happen.

Sorry for the other cases, can you fill a separate issue for it? Its usually not a good idea to use a single issue for more than one problem.

Please let me know if you test that overlap option, would be good to know if it fails in any case

Thanks

**Comment by radare** [comment] 2016-02-22 23:03
Moving for 0.10.2, not prioritary for the next release that will happen in a week

**Comment by gitido** [comment] 2016-02-23 17:56
Sorry for the delayed response.

Should I still open a separate ticket for the second issue mentioned here?

**Comment by XVilka** [comment] 2016-03-01 21:07
@gitido please do.

**Comment by gitido** [comment] 2016-03-01 21:11
@XVilka Sure, https://github.com/radare/radare2/issues/4205

**Comment by jroimartin** [comment] 2016-04-07 21:33
Closing this issue and moving #4205 to milestone 0.10.2.

**Closed by jroimartin** 2016-04-07 21:33 UTC
Labels: bug, search
