### ISSUE TITLE
Handle 'O' in graph like its done in Visual

### ISSUE THREAD

**Issue by radare** [radare/radare2#9030] opened 2017-12-16 16:32 UTC
switch between normal disasm, pseudocode and esil

**Comment by radare** [comment] 2017-12-16 16:33
and maybe we should have a pDs too

**Comment by sivaramaaa** [comment] 2017-12-17 04:46
Hey hi , 
I have implemented 'O' in graph to toggle between  disasm, pseudocode and esil , made a PR
And about pDs , do u mean to handle disassemble N bytes (pD) in graph ??
I need a little clarification on that , meanwhile i will look at  the regression caused due to that anal.in thing !!

**Comment by Maijin** [comment] 2017-12-17 10:25
@sivaramaaa nop, just add another Vpppp with pds output

**Comment by Maijin** [comment] 2017-12-17 10:28
I think pDs stuff is totally unrelated to graph.

**Comment by radare** [comment] 2017-12-17 11:44
It is not. Pds in graph does recursive emulation, in the shell does linear. It is very related and way more useful when the code reuses register values

**Comment by Maijin** [comment] 2017-12-17 13:33
ok but unrelated to his anal.in fix :p I'd say better use of @sivaramaaa knowledge on continuing fix of anal issue like #8706 not sure why got assigned to this tbh

**Comment by Maijin** [comment] 2017-12-17 13:34
And is also unrelated to the 'O' issue that is now fixed

**Comment by Maijin** [comment] 2017-12-17 13:35
Let's open a new issue for this pDs stuff

**Closed by Maijin** 2017-12-17 13:35 UTC
Labels: good first issue, graph

**Comment by Maijin** [comment] 2017-12-17 13:37
#9038
