### ISSUE TITLE
Zignature curiosities

### ISSUE THREAD

**Issue by pinkflawd** [radare/radare2#5718] opened 2016-09-09 12:02 UTC
Run through of generating zignatures for Visual Studio runtime and scanning for them in a target binary.

Not entirely sure but quite certain I followed the instructions on http://radare.today/posts/zignatures/ correctly. Also checked the .zig file with msvcrt.dll, signatues look fine. 

- [ ] Nr. 1

```
Loading msvcrt.zig 2016-09-09 13:17:00
msvcrt.zig loaded 2016-09-09 13:17:06
Ranges are: 0x00401000 0x00408748
msvcrt.zig scan on code section(s) finished 2016-09-09 13:28:11
```

Scanning for the generated msvcrt.zig file on a 8000h code section takes a bit more than 10 minutes

- [ ] Nr. 2

A check on function 0x4010A5 in the target binary, where various calls to msvcrt._strlen and msvcrt._sprintf etc. happen, showed that the zignatures either did not match or were not renamed accordingly. 

[testbinaries.zip](https://github.com/radare/radare2/files/463872/testbinaries.zip) - pw: infected

**Comment by Maijin** [comment] 2016-09-11 20:57
I see other bugs on the dll analysis (aaa) the entry0 function created via the analysis is size 29.5K
Other functions size are really really big:

![image](https://cloud.githubusercontent.com/assets/1408600/18420440/0fef861a-7873-11e6-93ee-6067c02a23a5.png)

Lot of frames of function are also really really big.
![image](https://cloud.githubusercontent.com/assets/1408600/18420429/bfc6c89c-7872-11e6-9ff4-d3437ec72ef1.png)

**Comment by radare** [comment] 2016-09-15 17:27
cc @zlowram

**Comment by zlowram** [comment] 2016-09-17 19:30
Hi there @pinkflawd, thanks for reporting! Here some quick answers after a first look:

No. 1: In this case, since it's writing to a file, it is not necessary to display that message. Will take a look.

No. 2: This is because the `zg` command spits out a message when the signature is too short. This should be removed since it breaks the signature file and r2 will try to interpret that as commands (and this spitting  random output).

No. 3: scanning for zignatures with `z/` command usually takes a lot of time, since it will try to match a zignature to each of the bytes of the given range. You can try `.z. @@f` after `aaa` analysis, which will be quicker but will miss some hits (completely depends on analysis results)

No. 4: Confirmed behaviour, needs to be checked.

No. 5: Zignatures for that functions are generated but no matches found on that binary. Will have to check with simple hello worlds (stripped and non stripped).

**Comment by Maijin** [comment] 2016-09-18 11:32
@zlowram fixed n*1, n*2 and n*4 you can confirm and check the checkboxes:
![image](https://cloud.githubusercontent.com/assets/1408600/18615339/693bc32e-7da4-11e6-9e89-3fa14ff836d6.png)

**Comment by Maijin** [comment] 2016-09-18 11:40
https://github.com/radare/radare2/commit/f9b70631b2689b730e0234e3f6f99bbb61d59b1b The pull-request for information: 8 lines

**Comment by Maijin** [comment] 2016-09-18 11:53
@zlowram probably adding a treshold to avoid zg to produce 29.5K zignature could be cool to add like cfg.maxzlen ?

**Comment by zlowram** [comment] 2016-09-18 14:09
I think that before trying quick fixes zignatures "design" have to be reviewed. They are really basic now and maybe with a little bit of work could be improved.

A first step might be to create an e-var to avoid generating zignatures for loc.* and sub.* and focus only on lib code.

**Comment by pinkflawd** [comment] 2016-09-20 15:56
I don't have any idea particularly how radare creates/scans for zignatures, but got some ideas that might be useful, only maybe:

- treating zignatures as binary data, if I see correctly right now they are stored in ascii format (?) - I understand that is because it will be parsed by the zg command, but maybe a separate option for dealing with bulk import makes sense?
- zignature "compression" in a format like [offset_byteToMatch][byteToMatch][offset.... where offset calculates from the function address to scan
- scanning for zignatures with a tree approach, maybe with pre-sorting of functions-to-scan based on their first byte, but not sure thats not actually worse in performance; depends on the number of functions-to-scan and couple of other things 

Again, thiss just ideas :) I worked for a short time on the signature matching at an AV, and god forbid, if they're good at one thing then its signature matching...

**Comment by zlowram** [comment] 2016-09-21 09:46
Thanks for this ideas! I'll take them into account for optimising the signature scanning. However, I'll focus first on having them working properly :)

**Comment by Maijin** [comment] 2016-09-26 23:03
@alvarofe check out the dll issues^

**Comment by jroimartin** [comment] 2017-03-19 16:40
> Scanning for the generated msvcrt.zig file on a 8000h code section takes a bit more than 10 minutes

Now r_sign uses r_search under the hood, so it should be much faster.

> A check on function 0x4010A5 in the target binary, where various calls to msvcrt._strlen and msvcrt._sprintf etc. happen, showed that the zignatures either did not match or were not renamed accordingly.

Looks like the functions present in msvcrt.dll are quite different from the ones in unpacked_4962451.exe. For instance,

**strlen**
![strlen](https://cloud.githubusercontent.com/assets/1223476/24082729/a528c75a-0cca-11e7-9307-dace2ddd4f52.png)

**sprintf**
![sprintf](https://cloud.githubusercontent.com/assets/1223476/24082731/a980828e-0cca-11e7-83a2-8fe47ee16dfe.png)

That's why they don't match.

Closing this issue, as the discussion has been moved to #6947.

**Closed by jroimartin** 2017-03-19 16:40 UTC
Labels: anal, bug, enhancement, zignatures
