### ISSUE TITLE
bin.demangle should work not only at load time

### ISSUE THREAD

**Issue by R1kk3r** [radare/radare2#2527] opened 2015-05-08 08:08 UTC
Hi,

I tried to set both asm.demangle = true and bin.demangle = true, but I got nothing than mangled function name:

```
[0x08048a50]> e bin.demangle = true
[0x08048a50]> e asm.demangle = true
[0x08048a50]> af @ main
[0x08048a50]> pdf @ main
/ (fcn) sym.main 1237
|           ;-- main:
|           ;-- sym.main:
|           0x08048bf4    8d4c2404       lea ecx, [esp + 4]             ; 0x4 
|           0x08048bf8    83e4f0         and esp, 0xfffffff0
|           0x08048bfb    ff71fc         push dword [ecx - 4]
|           0x08048bfe    55             push ebp
|           0x08048bff    89e5           mov ebp, esp
|           0x08048c01    53             push ebx
|           0x08048c02    51             push ecx
|           0x08048c03    83ec60         sub esp, 0x60
|           0x08048c06    89cb           mov ebx, ecx
|           0x08048c08    8d45b0         lea eax, [ebp-local_20]
|           0x08048c0b    890424         mov dword [esp], eax
|           0x08048c0e    e8bdfcffff     call sym.imp._ZNSsC1Ev
|              sym.imp._ZNSsC1Ev()
|           0x08048c13    8d45b4         lea eax, [ebp-local_19]
|           0x08048c16    890424         mov dword [esp], eax
|           0x08048c19    e8b2fcffff     call sym.imp._ZNSsC1Ev
|              sym.imp._ZNSsC1Ev()
|           0x08048c1e    8d45b8         lea eax, [ebp-local_18]
|           0x08048c21    890424         mov dword [esp], eax
|           0x08048c24    e8a7fcffff     call sym.imp._ZNSsC1Ev
|              sym.imp._ZNSsC1Ev()
|           0x08048c29    8d45bc         lea eax, [ebp-local_17]
|           0x08048c2c    890424         mov dword [esp], eax
|           0x08048c2f    e89cfcffff     call sym.imp._ZNSsC1Ev
|              sym.imp._ZNSsC1Ev()
|           0x08048c34    8d45c0         lea eax, [ebp-local_16]
|           0x08048c37    890424         mov dword [esp], eax
|           0x08048c3a    e891fcffff     call sym.imp._ZNSsC1Ev
|              sym.imp._ZNSsC1Ev()
|           0x08048c3f    8d45dc         lea eax, [ebp-local_9]
|           0x08048c42    890424         mov dword [esp], eax
|           0x08048c45    e8b6fdffff     call sym.imp._ZNSaIcEC1Ev
|              0x08048a00() ; sym.imp._ZNSaIcEC1Ev
|           0x08048c4a    8b4304         mov eax, dword [ebx + 4]       ; [0x4:4]=0x10101 
|           0x08048c4d    8b00           mov eax, dword [eax]
|           0x08048c4f    8d55dc         lea edx, [ebp-local_9]
```

Did I miss something?

**Comment by jjdredd** [comment] 2015-05-08 08:38
would you please test the latest git

**Comment by crowell** [comment] 2015-05-08 22:02
seems to only work if it is in the radare2rc file

https://asciinema.org/a/19770

this is certainly a bug.

**Comment by XVilka** [comment] 2015-05-09 20:07
@R1kk3r @crowell this is not a bug (i think) since demangling perfomed only at RBin loading stage. So it should be in r2rc or in the r2 command line, not after the loading binary.

**Comment by radare** [comment] 2015-05-09 20:40
Yep it only works like xvilka says. This will be fixed when refactoring rbin with sdb after release

**Comment by radare** [comment] 2016-12-12 23:07
bin.demangle is enabled by default now. so i think we can close this issue

**Closed by radare** 2016-12-12 23:07 UTC
Labels: enhancement, RBin
