### ISSUE TITLE
cmd command with r2pipe fails

### ISSUE THREAD

**Issue by aquynh** [radare/radare2#6666] opened 2017-02-03 13:44 UTC
download ntdll.dll from https://www.dll-files.com/download/03de6de0019ffc0de60759a893bd8b3f/ntdll.dll.html?c=c1BjQ2psa2cyQzBGM0JyQ3NIMTNLZz09

then run the below script on either Mac or Linux:

    $ ./script.py ntdll.dll

and i get below error:

```
$ ./script.py ntdll.dll
Warning: NULL entrypoint
 Traceback (most recent call last):
  File "./script.py", line 15, in <module>
    fcn_ctx = json.loads(r2.cmd("pdfj @%s" % f["name"]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 3486 (char 3485)
```

here is the script:

```
#!/usr/bin/python
import sys
import r2pipe

try:
    import simplejson as json
except:
    import json

filename = sys.argv[1]
r2 = r2pipe.open(filename, ["-A"])
fcns = json.loads(r2.cmd("aflj"))

for f in fcns:
    fcn_ctx = json.loads(r2.cmd("pdfj @%s" % f["name"]))
```

**Comment by aquynh** [comment] 2017-02-03 13:51
this is the issue #6666, you guys should put my name in a hall-of-fame, or something ;-)

**Comment by radare** [comment] 2017-02-03 14:13
cant reproduce

**Comment by aquynh** [comment] 2017-02-03 14:38
works very reliably here on MacOS & Ubuntu

**Comment by aquynh** [comment] 2017-02-03 15:14
so the error is at this output of `r2pipe.cmdj("pdfj @%s" % f["name"])`

```
{"name":"sym.ntdll.dll_RtlUnsubscribeWnfNotificationWithCompletionCallback","size":68,"addr":6442468896,"ops":[{"offset":6442468896,"esil":"0,rcx,rcx,&,==,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468935,"size":3,"opcode":"test rcx, rcx","bytes":"4885c9","family":"cpu","type":"acmp","type_num":16,"type2_num":0,"flags":["sym.ntdll.dll_RtlUnsubscribeWnfNotificationWithCompletionCallback"]},{"offset":6442468899,"esil":"zf,?{,6442468932,rip,=,}","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468936,"size":2,"opcode":"je 0x180004644","bytes":"741f","family":"cpu","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":6442468932,"fail":6442468901},{"offset":6442468901,"esil":"0,rdx,rdx,&,==,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468935,"size":3,"opcode":"test rdx, rdx","bytes":"4885d2","family":"cpu","type":"acmp","type_num":16,"type2_num":0},{"offset":6442468904,"esil":"zf,?{,6442468932,rip,=,}","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468936,"size":2,"opcode":"je 0x180004644","bytes":"741a","family":"cpu","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":6442468932,"fail":6442468906},{"offset":6442468906,"ptr":0,"esil":"0,0x68,rcx,+,[8],==,$z,zf,=,$b64,cf,=,$p,pf,=,$s,sf,=,$o,of,=","refptr":true,"fcn_addr":6442468896,"fcn_last":6442468933,"size":5,"opcode":"cmp qword [rcx + 0x68], 0","bytes":"4883796800","family":"cpu","type":"cmp","type_num":15,"type2_num":0},{"offset":6442468911,"esil":"zf,!,?{,6442468926,rip,=,}","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468936,"size":2,"opcode":"jne 0x18000463e","bytes":"750d","family":"cpu","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":6442468926,"fail":6442468913},{"offset":6442468913,"esil":"rdx,0x68,rcx,+,=[8]","refptr":true,"fcn_addr":6442468896,"fcn_last":6442468934,"size":4,"opcode":"mov qword [rcx + 0x68], rdx","bytes":"48895168","family":"cpu","type":"mov","type_num":9,"type2_num":0},{"offset":6442468917,"esil":"r8,0x70,rcx,+,=[8]","refptr":true,"fcn_addr":6442468896,"fcn_last":6442468934,"size":4,"opcode":"mov qword [rcx + 0x70], r8","bytes":"4c894170","family":"cpu","type":"mov","type_num":9,"type2_num":0},{"offset":6442468921,"esil":"0x180004850,rip,=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468933,"size":5,"opcode":"jmp 0x180004850","bytes":"e912020000","family":"cpu","type":"jmp","type_num":1,"type2_num":0,"jump":6442469456},{"offset":6442468926,"ptr":3221227288,"esil":"3221227288,rax,=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468933,"size":5,"opcode":"mov eax, 0xc0000718","bytes":"b8180700c0","family":"cpu","type":"mov","type_num":9,"type2_num":0,"xrefs":[{"addr":6442468911,"type":"JMP"}]},{"offset":6442468931,"esil":"rsp,[8],rip,=,8,rsp,+=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468937,"size":1,"opcode":"ret","bytes":"c3","family":"cpu","type":"ret","type_num":5,"type2_num":0},{"offset":6442468932,"ptr":3221225485,"esil":"3221225485,rax,=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468933,"size":5,"opcode":"mov eax, 0xc000000d","bytes":"b80d0000c0","family":"cpu","type":"mov","type_num":9,"type2_num":0,"xrefs":[{"addr":6442468899,"type":"JMP"},{"addr":6442468904,"type":"JMP"}]},{"offset":6442468937,"esil":"rsp,[8],rip,=,8,rsp,+=","refptr":false,"fcn_addr":6442468896,"fcn_last":6442468937,"size":1,"opcode":"ret","bytes":"c3","family":"cpu","type":"ret","type_num":5,"type2_num":0}][{"offset":6442469456,"val":40,"esil":"40,rsp,-=,$o,of,=,$s,sf,=,$z,zf,=,$p,pf,=,$b8,cf,=","refptr":false,"fcn_addr":6442469456,"fcn_last":6442469478,"size":4,"opcode":"sub rsp, 0x28","bytes":"4883ec28","family":"cpu","type":"sub","type_num":18,"type2_num":0,"flags":["sym.ntdll.dll_RtlUnsubscribeWnfStateChangeNotification"],"xrefs":[{"addr":6442468921,"type":"JMP"},{"addr":6442793236,"type":"CALL"},{"addr":6442784311,"type":"CALL"}]},{"offset":6442469460,"esil":"rcx,rdx,=","refptr":false,"fcn_addr":6442469456,"fcn_last":6442469479,"size":3,"opcode":"mov rdx, rcx","bytes":"488bd1","family":"cpu","type":"mov","type_num":9,"type2_num":0},{"offset":6442469463,"ptr":48,"esil":"0x30,rsp,+,r8,=","refptr":true,"fcn_addr":6442469456,"fcn_last":6442469477,"size":5,"opcode":"lea r8, [rsp + local_30h]","bytes":"4c8d442430","family":"cpu","type":"lea","type_num":33,"type2_num":0},{"offset":6442469468,"ptr":24,"esil":"0x18,rcx,+,[8],rcx,=","refptr":true,"fcn_addr":6442469456,"fcn_last":6442469478,"size":4,"opcode":"mov rcx, qword [rcx + 0x18]","bytes":"488b4918","family":"cpu","type":"mov","type_num":9,"type2_num":0},{"offset":6442469472,"esil":"rip,8,rsp,-=,rsp,=[],6442469488,rip,=","refptr":false,"fcn_addr":6442469456,"fcn_last":6442469477,"size":5,"opcode":"call 0x180004870","bytes":"e80b000000","family":"cpu","type":"call","type_num":3,"type2_num":0,"jump":6442469488,"fail":6442469477},{"offset":6442469477,"val":40,"esil":"40,rsp,+=,$o,of,=,$s,sf,=,$z,zf,=,$c63,cf,=,$p,pf,=","refptr":false,"fcn_addr":6442469456,"fcn_last":6442469478,"size":4,"opcode":"add rsp, 0x28","bytes":"4883c428","family":"cpu","type":"add","type_num":17,"type2_num":0},{"offset":6442469481,"esil":"rsp,[8],rip,=,8,rsp,+=","refptr":false,"fcn_addr":6442469456,"fcn_last":6442469481,"size":1,"opcode":"ret","bytes":"c3","family":"cpu","type":"ret","type_num":5,"type2_num":0}]}
```

look closer, you can see that the output is like `{"name":"sym.ntdll.dll_RtlUnsubscribeWnfNotificationWithCompletionCallback","size":68,"addr":6442468896,"ops":[{"offset":  ..... "type2_num":0}][{"offset":6442469456, .....`. 

so the complain here is the missing `,` between that `][`.
according to the error, it should be `],[`.

is this more clear now?

**Comment by radare** [comment] 2017-02-03 15:26
yes this seems to be the issue. but the json i get from this command is valid :?

**Comment by Maijin** [comment] 2017-02-03 15:28
You are using `r2.cmd` which is wrong.
For json use `r2.cmdj`.

**Comment by aquynh** [comment] 2017-02-03 15:30
actually i use cmdj. you can change that in the script above, and still get the error.

**Comment by aquynh** [comment] 2017-02-03 15:34
hmm this is confused. do you mean to change all "cmd" to "cmdj", everywhere?

**Comment by radare** [comment] 2017-02-03 15:36
only if the output of the command is json

**Comment by aquynh** [comment] 2017-02-03 15:37
so my code is correct?

**Comment by Maijin** [comment] 2017-02-03 15:37
`json.loads(r2.cmd("aflj"))`
`r2.cmd("pdfj @%s" % f["name"])` 
Incorrect.

**Comment by aquynh** [comment] 2017-02-03 15:42
ok, changing all "cmd" to "cmdj" resulting in the error below.


```
$ ./script.py ntdll.dll
Warning: NULL entrypoint
Traceback (most recent call last):
  File "./script.py", line 12, in <module>
    fcns = json.loads(r2.cmdj("aflj"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by Maijin** [comment] 2017-02-03 15:44
You don't need the json.loads(XXX), cmdj already do that. I can reproduce the error still

**Comment by aquynh** [comment] 2017-02-03 15:46
yes, the root cause is that you are missing that comma between "][".

**Comment by radare** [comment] 2017-02-03 17:26
im busy with real world things, but from the tests i did, seems like a regression in RCons when managing huge buffers. must check in detail to fix that properly. also, having a smaller testcase would be nicer, waiting 3 minutes for each run its a bit boring. will try to fix this weekend on a faster box

**Comment by radare** [comment] 2017-02-03 17:26
Nice issue number ftw.

**Comment by aquynh** [comment] 2017-02-05 01:15
seems to be fixed now with the latest radare & r2pipe, thanks!

**Comment by Maijin** [comment] 2017-02-05 11:05
Then close the issue.

**Closed by Maijin** 2017-02-05 11:05 UTC
