### ISSUE TITLE
radiff2: "Buffer truncated...."

### ISSUE THREAD

**Issue by NaveenBoggarapu** [radare/radare2#4372] opened 2016-03-21 07:48 UTC
I was exploring radiff2 using the below programs

    /* test1.c */
    #include<stdio.h>
    void main(){
        int array[20];
        int k;
        for(k=0; k < 20; k++){
                array[k] = 10;
        }
    }

    /* test1_sim.c */
    #include<stdio.h>
    void main(){
        int array[20];
        int k;
        for(k=0; k < 20; k++){
                array[k] = 5;
        }
    }

Both the programs are compiled using 
```
    $ gcc test1.c -o test1
    $ gcc test1_sim.c -o test1_sim
```
I was able to identify that the change is only in main, as shown below
```
naveen@naveen:~/Workspace$ radiff2 -C test1 test1_sim
                   entry0  42 0x400400 |   MATCH  (1.000000) | 0x400400   42 entry0
sym.imp.__libc_start_main  32 0x4003e0 |   MATCH  (1.000000) | 0x4003e0   32 sym.imp.__libc_start_main
                 sym.main  38 0x4004ed | UNMATCH  (0.973684) | 0x4004ed   38 sym.main
 sym.deregister_tm_clones  48 0x400430 |   MATCH  (1.000000) | 0x400430   48 sym.deregister_tm_clones
   sym.register_tm_clones  64 0x400460 |   MATCH  (1.000000) | 0x400460   64 sym.register_tm_clones
sym.__do_global_dtors_aux  28 0x4004a0 |   MATCH  (1.000000) | 0x4004a0   28 sym.__do_global_dtors_aux
          sym.frame_dummy  42 0x4004c0 |   MATCH  (1.000000) | 0x4004c0   42 sym.frame_dummy
      sym.__libc_csu_fini   2 0x400590 |   MATCH  (1.000000) | 0x400590    2 sym.__libc_csu_fini
                sym._fini   9 0x400594 |   MATCH  (1.000000) | 0x400594    9 sym._fini
      sym.__libc_csu_init 101 0x400520 |   MATCH  (1.000000) | 0x400520  101 sym.__libc_csu_init
                sym._init  26 0x4003a8 |   MATCH  (1.000000) | 0x4003a8   26 sym._init
   loc.imp.__gmon_start__  48 0x4003f0 |   MATCH  (1.000000) | 0x4003f0   48 loc.imp.__gmon_start__
```

And using graph-diff I was able to identify the exact change, which is only at one location ![diff](https://cloud.githubusercontent.com/assets/4930078/13912763/7473e536-ef66-11e5-9c22-bf153b97bc27.png).

But when I perform basic diff using `$ radiff2 test1 test1_sim` or try to get the count `$ radiff2 -c test1 test1_sim` I get a message "Buffer truncated to 8501 bytes (4 not compared)" 

```
naveen@naveen:~/Workspace$ radiff2 -c test1 test1_sim
Buffer truncated to 8501 bytes (4 not compared)
46
```

The output says that there are 46 differences, but there is only one difference.

radiff2 version I am using is radiff2 v0.10.2-git
```
naveen@naveen:~/Workspace$ radiff2 -v
radiff2 v0.10.2-git
```

**Comment by radare** [comment] 2016-03-21 08:53
This is because -c compares bytes and the warning message tells you that one file is 4 bytes bigger than the other.

I dont see anything wrong in here. Maybe just clarifying that radiff have commands to find differences at byte, deltified byte, byte similarities, code graph and disassembly..

**Comment by radare** [comment] 2016-03-21 08:54
As long as you have been successfully using radiff2, can you suggest some ideas for enhancing it? Some different output, or better help messages? Thanks!

**Comment by NaveenBoggarapu** [comment] 2016-03-21 09:05
But, in "https://radare.gitbooks.io/radare2book/content/binary_diffing.html" it is mentioned that 

> If you want more concrete data, it's also possible to count the differences, with the `-c` option:

I was in an impression that it will show the count.

I would suggest to add a feature to compare a specific symbol further in, like in this case, after observing the output using ` -C` option I identify that sym.main is an unmatch, if there is a provision to analyze with respect to a symbol as done in `-g` option, it would help to get a better insight of the difference.

If the above feature is already present, please ignore my comment. I will go through the code and implement it if possible

**Comment by radare** [comment] 2016-03-21 10:22
> On 21 Mar 2016, at 10:05, NaveenBoggarapu <notifications@github.com> wrote:
> 
> But, in "https://radare.gitbooks.io/radare2book/content/binary_diffing.html <https://radare.gitbooks.io/radare2book/content/binary_diffing.html>" it is mentioned that
> 
> If you want more concrete data, it's also possible to count the differences, with the -c option:
> 
> I was in an impression that it will show the count.
> 
> I would suggest to add a feature to compare a specific symbol further in, like in this case, after observing the output using -C option I identify that sym.main is an unmatch, if there is a provision to analyze with respect to a symbol as done in -
> 
isnt -C -g <symbol> not working?

> If the above feature is already present, please ignore my comment. I will go through the code and implement it if possible
> 
> 
awesome!

write test cases for the radare2-regressions repo if you are in the mood, they are really helpful to avoid loosing features when involuntarily breaking stuff.

Thanks!

**Comment by NaveenBoggarapu** [comment] 2016-03-21 10:59
No, -C -g <symbol> doesn't work for that.

After going through the code, I have realized that -C and -g doesn't work together, when both the options are given, last option of these two will work.

I am still confused about the difference shown, it is different from the output shown in radare2 book.

On the other note, there are few minor spelling mistakes in the code comments and few corrections required in the code, these are not major ones and doesn't hamper any functionality. Can you please suggest me how to make this changes. Shall I just create a patch and send it across? or is there a standard way to do it.

**Comment by radare** [comment] 2016-03-21 12:42
fork the repository, create a branch and push the commits with your changes. then the github website will suggest you to create a pull request. press the button and travis/jenkins will rebuild and run the entire testsuite and i’ll review it to merge it or add comments

**Comment by radare** [comment] 2016-03-24 14:23
Ping

**Comment by NaveenBoggarapu** [comment] 2016-03-29 04:09
Ping

**Comment by NaveenBoggarapu** [comment] 2016-03-29 04:10
Ping

**Comment by radare** [comment] 2016-03-30 15:10
any update on this? did you had time to do the patch?

**Comment by NaveenBoggarapu** [comment] 2016-03-31 05:37
No, I was travelling.  I will be working on it this week.

**Comment by XVilka** [comment] 2016-05-12 10:19
@NaveenBoggarapu ping

**Comment by XVilka** [comment] 2016-05-12 10:20
Can you please also write a regression test to check this automatically from now on?

**Comment by Maijin** [comment] 2016-09-19 18:40
ping(2)

**Comment by radare** [comment] 2016-09-21 10:18
please try on latest git

**Comment by radare** [comment] 2016-09-26 15:09
HELLO ANYONE

**Comment by radare** [comment] 2016-10-27 12:39
moving to 1.1 because @NaveenBoggarapu seems dead

**Comment by Maijin** [comment] 2016-10-27 12:41
Closing

**Closed by Maijin** 2016-10-27 12:41 UTC
Labels: bug, radiff2, test-required
