### ISSUE TITLE
License Foo

### ISSUE THREAD

**Issue by sre** [radare/radare2#5869] opened 2016-09-28 04:23 UTC
Hi,

In Debian I disabled a few plugins for license reasons:

- [x] asm.m68k ([BSD-4-clause is incompatible with GPL](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.29))
 -  capstone variant is available anyways, so moving it to r2-extras shouldn't hurt?
- [x] asm.z80 (that German non-commercial license is definitively [DFSG](https://en.wikipedia.org/wiki/DFSG) incompatible most likely GPL incompatible)
 -  maybe replace with https://www.tablix.org/~avian/z80dasm/ (GPL2+)?
- [x] mach support
 - pull request #5868 fixes the problem
- [x] webui
 - Debian packages must contain source and r2 tarball comes with precompiled JS
 - I guess nothing to do on your side and web stuff should be packaged separately using radare2-webui

-- Sebastian

**Comment by XVilka** [comment] 2016-09-28 07:13
Regarding m68k - @oddcoder, I remember you were going to improve it, could be covered by tests and port features from it, then move to extras indeed. And for z80 plugin - this was supposed to be done by @condret.

**Comment by radare** [comment] 2016-09-28 11:24
for 1.0 i would like to clarify all the license issues, so it's great to have you back :)

* asm.m68k we have the capstone implementation that afaik is working fine now (there was some bugs in the past, but they are all gone iirc, i will talk with @killabytenow and @poliva to see if they notice any regression on that change) im not sure if @Maijin wrote tests for that, but that would be great if we can check the difference in the disassembler of all possible instructions in both disassemblers. In addition the only way to get esil working on m68k is via capstone, so +1 for moving it to extras.

* the z80 thing had some problems that must be decided by @condret but he's always disapearing, so i dont know if he can tell us the differences between his disassembler and the german one.

* about mach, thanks!

* there's a radare2-webui repo that contains all the sources for the webuis, but i think its a pain for the users if they have to install 300MB of nodejs dependencies to build a 300KB website, that's why i put it in compact form.. afaik the other debian maintainer just removed the webui frmo the radare2 package in debian to avoid this issue. anyway, the radare2-webui repo makes clear which licenses affect each webui. let me know if the webuis i ship in r2 by default are conflicting with the GPL (iirc no)

**Comment by sre** [comment] 2016-09-28 17:03
> for 1.0 i would like to clarify all the license issues, so it's great to have you back :)

I was in read-only mode, since David Martínez Moreno maintained the package for some time (he also maintained bokken, so that made sense to me). Since he didn't upload anything for quite some time and didn't respond to my mails I will take care of it again :)

> the z80 thing had some problems that must be decided by @condret but he's always disapearing, so i dont know if he can tell us the differences between his disassembler and the german one.

FWIW the license part can be roughly translated like this (the remaining header is a description of the program): »The program is freeware. It may _not_ be used as base for commercial products! I don't take liability for any damage caused by direct or indirect use of this program!«

That license really sucks, since it does not give you any rights. Compare e.g. with [cc-by-sa-nc](https://creativecommons.org/licenses/by-nc-sa/3.0/), which specifies "You are free to share or adapt as long as you follow the following terms: [...]"

> about mach, thanks!

You're welcome. I was not too happy to remove complete mach support in Debian because of some simple magic numbers and structs (=API), which is basically not copyrightable (the apple header contains lots of comments, so they probably are).

> there's a radare2-webui repo that contains all the sources for the webuis, but i think its a pain for the users if they have to install 300MB of nodejs dependencies to build a 300KB website, that's why i put it in compact form.. afaik the other debian maintainer just removed the webui frmo the radare2 package in debian to avoid this issue. anyway, the radare2-webui repo makes clear which licenses affect each webui. let me know if the webuis i ship in r2 by default are conflicting with the GPL (iirc no)

webui is not linked against GPL, so shouldn't be a problem. I understand your reasoning for the bundling the prebuilt JS. It makes sense for users building r2 from git. In Debian we don't have that problem, since users install the binary package and don't need to install dependencies required for building it. I just mentioned it in case anybody looking at the package is wondering. The problem for Debian is, that we don't consider uglified JS as source and have are requirement about source being used to build the packages.

I currently solved it by removing the webui. I think the solution for Debian would be to continue removing the bundled webui and packaging radare2-webui separately. I don't plan to do it immediately, though. As you mentioned it's a bit of work to gather the builds deps e.t.c.

**Comment by ghostbar** [comment] 2016-09-28 17:17
@sre let me know any changes you make so I can merge them into https://github.com/ghostbar/radare2.deb (I'm building backports there as well so I'll keep it going)

**Comment by sre** [comment] 2016-09-29 03:09
https://anonscm.debian.org/cgit/collab-maint/radare2.git

**Comment by radare** [comment] 2016-09-29 09:32
> On 28 Sep 2016, at 19:03, Sebastian Reichel <notifications@github.com> wrote:
> 
> for 1.0 i would like to clarify all the license issues, so it's great to have you back :)
> 
> I was in read-only mode, since David Martínez Moreno maintained the package for some time (he also maintained bokken, so that made sense to me). Since he didn't upload anything for quite some time and didn't respond to my mails I will take care of it again :)
> 

oh i see, nice to see you again :)

> the z80 thing had some problems that must be decided by @condret <https://github.com/condret> but he's always disapearing, so i dont know if he can tell us the differences between his disassembler and the german one.
> 
> FWIW the license part can be roughly translated like this (the remaining header is a description of the program): »The program is freeware. It may not be used as base for commercial products! I don't take liability for any damage caused by direct or indirect use of this program!«
> 
> 

yeah, fucking scary stuff. we already fixed a bunch of vulns in there iirc, but anyway, @maijin do we have z80 tests to check the differences between those two z80 disassemblerls? if not maybe its time to just blindly move to extras and wait for complains, but making it available via r2pm should be fine

ok.. i had a look at this and looks like main missing feature is “assembler”. the z80.cr plugin doesnt supports assembling, only the german one does. what about trying to contact the author and ask for a license change? :D

> That license really sucks, since it does not give you any rights. Compare e.g. with cc-by-sa-nc <https://creativecommons.org/licenses/by-nc-sa/3.0/>, which specifies "You are free to share or adapt as long as you follow the following terms: [...]"
> 
> about mach, thanks!
> 
> You're welcome. I was not too happy to remove complete mach support in Debian because of some simple magic numbers and structs (=API), which is basically not copyrightable (the apple header contains lots of comments, so they probably are).
> 
> 

i though include files cant be licensed as long as they are used for interoperatbility

> there's a radare2-webui repo that contains all the sources for the webuis, but i think its a pain for the users if they have to install 300MB of nodejs dependencies to build a 300KB website, that's why i put it in compact form.. afaik the other debian maintainer just removed the webui frmo the radare2 package in debian to avoid this issue. anyway, the radare2-webui repo makes clear which licenses affect each webui. let me know if the webuis i ship in r2 by default are conflicting with the GPL (iirc no)
> 
> webui is not linked against GPL, so shouldn't be a problem. I understand your reasoning for the bundling the prebuilt JS. It makes sense for users building r2 from git. In Debian we don't have that problem, since users install the binary package and don't need to install dependencies required for building it. I just mentioned it in case anybody looking at the package is wondering. The problem for Debian is, that we don't consider uglified JS as source and have are requirement about source being used to build the packages.
> 
> 
you can always build the webuis from the radare2-webui repo

> I currently solved it by removing the webui. I think the solution for Debian would be to continue removing the bundled webui and packaging radare2-webui separately. I don't plan to do it immediately, though. As you mentioned it's a bit of work to gather the builds deps e.t.c.
> 

sounds good. thanks!

**Comment by oddcoder** [comment] 2016-09-29 10:43
@XVilka not compatiable with gpl ? well we I can just re implement it from scratch ? and make it gpl ? 
totally independent of the old imepelmentation ?

**Comment by Maijin** [comment] 2016-09-29 12:51
@oddcoder no, capstone already have m68k.cs with ok license, now the point was to improve/test it so it is ok to remove m68k and put in r2e

**Comment by radare** [comment] 2016-10-08 00:49
This is what happens when i remove the z80 plugin replacing it with the .cr one

https://s3.amazonaws.com/archive.travis-ci.org/jobs/165964004/log.txt

**Comment by radare** [comment] 2016-10-27 12:41
next step in my todo list is to move the m68k plugin to extras and make the _cs one the default. if it's not that yet

**Comment by radare** [comment] 2016-10-27 12:41
for the webui thing i think we can mark it as done as long as it can be fixed at packaging time

**Comment by Svenito** [comment] 2016-10-28 13:28
All items addressed.

**Closed by Svenito** 2016-10-28 13:28 UTC
