### ISSUE TITLE
Debugging on x86/64 no longer works.

### ISSUE THREAD

**Issue by giuscri** [radare/radare2#9263] opened 2018-01-29 19:14 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 17142 @ linux-x86-64 git.2.2.0-334-g3e8a5b567 commit: 3e8a5b5677abcef82867447d70fa1923fd73da55 build: 2018-01-29__19:40:07
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/giuscri/2300a72eeaf88751148ad71d51a392c8

### Expected behavior
~It~ The debuggee should _not_ segfault.

### Actual behavior
```
$ r2 -q -AAd -c "db main; dc" ./main
Process with PID 22796 started...
= attach 22796 22796
bin.baddr 0x55f8c5f94000
Using 0x55f8c5f94000
asm.bits 64
= attach 22796 22796
22796
child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0x00000000 code=128 ret=0
```

### Steps to reproduce the behavior 
Compile via `gcc -o main main.c`. Break at main. Run.

### Additional Logs, screenshots, source-code,  configuration dump, ...
```
$ cat main.c
int main() {
    puts("Hello, world");
    return 0;
}
```
[issue9261.zip](https://github.com/radare/radare2/files/1674919/issue9261.zip)

**Comment by xarkes** [comment] 2018-01-29 21:53
Reproduced using master, the debugee segfaults but not radare.

**Comment by radare** [comment] 2018-01-31 15:54
this issue is completely unrelated to the debugger.

If you do -AA you are basically running `aaaa`., which basically enables esil, memory writes and io cache which modifies the register state, memory layout and such. so its crashing because the process is not starting with the expected environment.

So the issue here is using the analysis within the debugger.

You can basically reduce the problem to run `afta` and you get the same behaviour.

fixed in master by skipping afta when in debugger mode.

**Closed by radare** 2018-01-31 15:54 UTC
Labels: bug, debugger

**Comment by radare** [comment] 2018-02-06 13:51
cc @leberus

**Comment by leberus** [comment] 2018-02-06 15:01
Uhm, maybe I'm missing something but:

`
leberus@localhost:~> r2 -d  -c "db main;dc" main
Process with PID 3407 started...
= attach 3407 3407
bin.baddr 0x00400000
Using 0x400000
Unknown DW_FORM 0x06
asm.bits 64
r_debug_native_continue: pid: 3407, tid: 3407
r_debug_continue: ret: 3407
waitpid: ret: 3407
r_debug_wait: 3
hit breakpoint at: 400507
r_debug_continue: reason: 3
 -- No fix, no sleep
[0x00400507]> dc
waitpid: ret: 3407
r_debug_wait: 3
r_debug_native_continue: pid: 3407, tid: 3407
r_debug_continue: ret: 3407
Hello, world
waitpid: ret: 3407
r_debug_wait: 17
r_debug_continue: reason: 17
[0x7fb978ddd338]> dc
r_debug_native_continue: pid: 3407, tid: 3407
r_debug_continue: ret: 3407
waitpid: ret: 3407
child exited with status 0
r_debug_wait: -1

==> Process finished

r_debug_continue: reason: -1
[0x00400507]>`

Looks like it works?

**Comment by radare** [comment] 2018-02-06 15:04
yes you are missing several things

1) use dcu main instead of db+dc
2) dont pass commandline flags after -d
3) specify relative or absolute path to exeuctable, otherwise you can be debugging the one in $PATH

**Comment by Maijin** [comment] 2018-02-06 15:36
(and use markdown for pasting output please)

**Comment by leberus** [comment] 2018-02-07 09:54
Using <b>r2 -d [path_binary]</b> works:

<pre>
leberus@localhost:~> cat $HOME/main.c
int main() {
    puts("Hello, world");
    return 0;
}
leberus@localhost:~> gcc $HOME/main.c -o $HOME/main
/home/leberus/main.c: In function ‘main’:
/home/leberus/main.c:2:5: warning: implicit declaration of function ‘puts’ [-Wimplicit-function-declaration]
     puts("Hello, world");
     ^~~~
leberus@localhost:~> r2 -d $HOME/main
Process with PID 5472 started...
= attach 5472 5472
bin.baddr 0x00400000
Using 0x400000
Unknown DW_FORM 0x06
asm.bits 64
 -- TIRED OF WAITING
[0x7fa58de64ea0]> dcu main
Continue until 0x00400507 using 1 bpsize
r_debug_native_continue: pid: 5472, tid: 5472
r_debug_continue: ret: 5472
waitpid: ret: 5472
r_debug_wait: 3
hit breakpoint at: 400507
r_debug_continue: reason: 3
[0x00400507]>
</pre>

But when using <b>r2 -q -d [path_to_binary]</b>, it hangs

<pre>
leberus@localhost:~> r2 -q -d $HOME/main
Process with PID 5563 started...
= attach 5563 5563
bin.baddr 0x00400000
Using 0x400000
Unknown DW_FORM 0x06
asm.bits 64

</pre>

I'll take a look

**Comment by leberus** [comment] 2018-02-07 09:57
Forget what I said about "q", I didn't realize there was no prompt. (it's working as well)
