### ISSUE TITLE
z80-cr is wrong

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2075] opened 2015-02-11 12:58 UTC
I spent some time trying to make z80-cr pass more tests, but it seems that it is wrong on a lot of opcodes. It would be great to fix this, in order to replace the current (ugly) z80 disassembler with this one.

**Comment by condret** [comment] 2015-03-28 01:00
found the bug, docwho pointed it. will fix it soon (tm)

**Comment by condret** [comment] 2015-04-01 18:08
should be fixed

**Comment by radare** [comment] 2015-04-01 20:44
Any other issue?

**Comment by radare** [comment] 2015-04-03 02:35
looks like changes need to be reviewed carefully before fixing the tests

**Comment by Maijin** [comment] 2015-04-03 07:53
z80-cr tests have been removed from radare2-regression repo as requested

**Comment by XVilka** [comment] 2015-04-18 21:58
Postponing this after the release. Next time :)

**Comment by radare** [comment] 2016-06-17 15:06
z80 plugin is GPL, but at least have an assembler, which condre'ts implementation does not. The reason for removing it from the core is because of the license mainly, but i have been waiting for about a year to have feedback on that thing...

**Comment by radare** [comment] 2016-06-17 15:06
cc @condret

**Comment by Maijin** [comment] 2016-10-24 12:24
Thanks @Svenito

**Closed** 2016-10-24 12:24 UTC
Labels: architecture, enhancement

**Comment by kolen** [comment] 2016-10-25 12:06
BTW, there's comprehensive doc about z80 opcodes, including undocumented: http://www.myquest.nl/z80undocumented/, and it contains opcode table. But it's under GNU Free Documentation License, which is, I heard, incompatible even with GPL. Or such tables are not copyrightable because it's data, not creative works, so we can take that table from LaTeX source of the book and use it with GPL/LGPL code?

**Comment by Maijin** [comment] 2016-10-25 12:10
@kolen https://github.com/radare/radare2/blob/master/libr/asm/d/z80
