### ISSUE TITLE
Dump sections problem

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#9968] opened 2018-04-26 14:28 UTC
Hello.
I need to dump memory sections. But I didnt get them. May be I do something wrong...
I tried to get memory for PE and ELF files through "Sda" or "dmd".
"Sda" gives me 0xff content always.
"dmd" didnt work at all.
Also I noticed, that "Sda" for minidump-files works, but memory contents didnt accordance original addresses.

###My environ:
```
Debian 4.6.4 x64
PE and ELF
PE x86/32, ELF x86/64
radare2 2.6.0-git 17895 @ linux-x86-64 git.2.5.0-24-g7b2752880
commit: 7b27528807b5d6ecfac6ef9d0498a8eefbabb31d build: 2018-04-13__23:29:57
```

### Expected behavior
I expected to give stored contents of the memory pages.

### Actual behavior
But I have just like this:
```
hexdump -C 0x00401000-0x00410600-r-x.dmp 
00000000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
0000f600
```

### Steps to reproduce the behavior 
I used usual /bin/ls (x64)
```
r2 /bin/ls
Sda
```

**Comment by radare** [comment] 2018-04-26 14:31
the S command will be deprecated soon or late. use wtf text@$S!$SS

**Comment by radare** [comment] 2018-04-26 14:31
and yep. i can reproduce this bug, probably a va/pa problem after the siol merge

**Comment by s0i37** [comment] 2018-04-26 17:00
Whats about "dm"? It is usable only in debug mode?

**Comment by radare** [comment] 2018-04-27 07:03
Maps are not sections, and yes, all d subconmands are debugger specific

**Comment by s0i37** [comment] 2018-04-28 07:04
Ok. I dumped all memory like this:
```
(dump ,  s $0,  wtf `?v $S` @ $S!$SS)
fs sections
.(dump $$) @@ *!end
```
Its a little bit cumbersome but its seems worked.

**Comment by radare** [comment] 2018-04-28 08:05
Ideally this sjould be done reusing the rabin2 -O option but making it available inside r2 as iO

**Comment by radare** [comment] 2018-05-09 21:10
Also, as long as you want to dump the section, the IO must happen at physical level. So that's why it dumps ffff, this was working before the siol merge, because the pa was mapped at address 0, which was wrong, but handy. I think that to solve this issue we have to implement iO command

**Comment by s0i37** [comment] 2018-05-10 06:33
rabin2 -O d/S/.section_name don't comfortable for me because rabin2 returns hex-string. And also I have around 1k sections (minidump file). So "wtf" command still is good solve for me now.

**Comment by radare** [comment] 2018-05-10 07:47
I know. And thats why we should improve that to dump raw to stdout and create files directly too

**Comment by radare** [comment] 2018-05-10 07:47
But its imho the way to go

**Comment by radare** [comment] 2018-05-21 00:40
[0x100001200]> iO d/S/0.__TEXT.__text |rax2 -s > text

**Comment by radare** [comment] 2018-05-21 00:41
you can also do `wtf dumped $SS @ $S`

**Comment by radare** [comment] 2018-05-21 00:41
let's close this issue as long as the S command will be deprecated soon and there are other ways to achieve the same

**Closed by radare** 2018-05-21 00:41 UTC
Labels: io
