### ISSUE TITLE
Will not step passed breakpoint when debugging

### ISSUE THREAD

**Issue by slimjim2234** [radare/radare2#4560] opened 2016-04-08 20:34 UTC
My scenario for reproducing the issue.

r2 -d 32-bit_elf
V
do
db main
dc
s

When attempting to step through after the breakpoint has been hit, a message briefly states "hit breakpoint at 0xaddresshere" and "interrupted by a breakpoint" at the bottom and does not continue.  To maneuver around this I have to remove the breakpoint take a step and reapply the breakpoint on the previous line.
This is ran in a docker container from the radare/radare2 image which I frequently update.  This bug has not been seen any more than a week ago.

**Comment by Maijin** [comment] 2016-04-08 21:07
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by slimjim2234** [comment] 2016-04-08 22:14
Thanks for getting back to me Maijin.  Here is the output from r2 -d

root@7c79fda18a05:/# r2 -v
radare2 0.10.2-git 10883 @ linux-little-x86-64 git.0.10.1-429-g4476720
commit: 4476720aa8ce09e2aa13a9d08cc870b2b9886cb9 build: 2016-04-08

**Comment by radare** [comment] 2016-04-09 08:29
Only happens when debugging 32bit bins on a 64bit system? Or it is also reprodiucble on 64bit programs? Is this a linux-specific problem?

**Comment by slimjim2234** [comment] 2016-04-09 16:43
This issue is also reproducible on 64bit bins as well.

I cannot verify that this is limited to linux-based systems? Do you have suggestions on how to verify this?

**Comment by radare** [comment] 2016-04-09 23:29
Well. it's all `do` fault. which is broken.

**Comment by radare** [comment] 2016-04-09 23:30
@alvarofe looks like `do` aka `oo` is not working now, not even in osx:

```
[0x00000000]> oo
p/io_mach.c:431 __close io_mach: Bad file descriptor
File dbg:///bin/ls reopened in read-write mode
attach 63603 63603
fail to deallocate port p/native/xnu/xnu_debug.c:460
fail to deallocate port p/native/xnu/xnu_debug.c:460
error to get task for the debuggee process xnu_start_exception_thread
error setting up exception thread
PID=63603
fail to deallocate port p/native/xnu/xnu_debug.c:460
r_debug_reg: error reading registers
fail to deallocate port p/native/xnu/xnu_debug.c:460
r_debug_reg: error reading registers
fail to deallocate port p/native/xnu/xnu_debug.c:460
fail to deallocate port p/native/xnu/xnu_debug.c:460
r_debug_reg: error reading registers
fail to deallocate port p/native/xnu/xnu_debug.c:460
r_debug_reg: error reading registers
fail to deallocate port p/native/xnu/xnu_debug.c:460
r_debug_reg: error reading registers
```

**Comment by radare** [comment] 2016-04-09 23:36
Btw, 's' does not steps, what you want is 'ds'. and also, bear in mind that the prompt will not be updated after every step. so you have to `e cmd.prompt=sr PC` or so. please confirm

**Comment by slimjim2234** [comment] 2016-04-10 07:30
Thank you so much for following up on this.

I'm using 's' in visual mode ('V') which I believe is still the "step" function if I'm not mistaken.

I have set the config variable cmd.prompt=sr PC and have not noticed any differences.  Is this expected behavior?

**Comment by Maijin** [comment] 2016-04-10 07:45
you can also use f7, f8, f9

**Comment by radare** [comment] 2016-04-10 07:55
Yep. Should be ok

**Comment by slimjim2234** [comment] 2016-04-10 12:35
Ok, excellent.

BTW, radare2 is awesome.  Mad props to ya!

**Comment by radare** [comment] 2016-04-10 23:07
You dont need to `do` at all. this thing works fine if you dont use `do`. Let's move for the next release

**Comment by jduck** [comment] 2016-05-15 00:29
Guys in the interest of closing this out I have a couple questions.

1. (for @slimjim2234) Is the original issue reported still present?
2. About "oo", if there's an issue there we should open a separate ticket. (It's working for me, but maybe not on OSX).

@slimjim2234 if the issue is still reproducing, please provide a bin and elaborate on your test environment.

**Closed** 2016-05-15 09:01 UTC
Labels: bug, debugger, regression
