### ISSUE TITLE
psz is broken on fat mach0

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2#6318] opened 2016-12-14 09:26 UTC
Strings seems to be referenced using physical address instead of virtual address, this breaks references on fat binaries where physical !== virtual.

Here is a session in which `psz` shows the wrong result, unless provided with manually calculated physical address (using offset from section start):

```
$ r2 -b 64 bins/mach0/TestApp.ios
[0x100005e0c]> izz~6dc1
vaddr=0x00006dc1 paddr=0x00006dc1 ordinal=114 sz=35 len=34 section=unknown type=ascii string=application:didUpdateUserActivity:
[0x100005e0c]> psz@0x6dc1

[0x100005e0c]> iS~methname
idx=03 vaddr=0x1000062a4 paddr=0x0001a2a4 sz=4255 vsz=4255 perm=m-r-x name=3.__objc_methname
[0x100005e0c]> psz@0x0001a2a4+0xb1d
application:didUpdateUserActivity:
[0x100005e0c]>
```

The same problem shows up in `asm.emu` resolved strings.

Thinning the binary workarounds the problem, but only because by default strings are mapped with vaddr = paddr.

I can write a r2r test for this if useful.

**Comment by radare** [comment] 2016-12-14 09:30
fat binaries are incorrectly loaded since this summer after the rsoc broke it. since then use rabin2 -x.

anyway, if you can write a test, or find time to fix it i’ll really appreciate that :)

**Comment by mrmacete** [comment] 2016-12-14 09:45
yes, i'm seeing now, it's more complex than that, actually those kind of strings are mapped at `0x100006dc1`, but it seems references from code are of type `0x6dc1`

**Comment by radare** [comment] 2016-12-14 10:00
Yep its not a problem with psz, but with the sections that map the subbin in memory

**Comment by alvarofe** [comment] 2016-12-14 12:38
Write a test please

**Comment by mrmacete** [comment] 2016-12-14 12:42
yes, i'm on it. the above binary is not good for the test. i'm reproducing the problem with an apple's framework but i'm unsure if i can just push it on r2r repo, so maybe i have to dig for another suitable binary or produce one.

**Comment by radare** [comment] 2016-12-14 13:23
you can reproduce this with a hello world in C compiling it with -arch armv7 -arch arm64

**Comment by alvarofe** [comment] 2016-12-14 19:26
I have a fix but trying to understand what is going on

**Comment by radare** [comment] 2016-12-14 19:48
Awesome!

**Comment by alvarofe** [comment] 2016-12-15 20:07
Fixed in master plus 1min time saved in travis

**Closed by alvarofe** 2016-12-15 20:07 UTC
Labels: test-required
