### ISSUE TITLE
Build fail on windows

### ISSUE THREAD

**Issue by circleous** [radare/radare2#6341] opened 2016-12-18 23:15 UTC
I'm trying to build radare2 on windows using mingw-w64 (MSYS2). 
Following [radare gitbooks windows compilation](https://radare.gitbooks.io/radare2book/content/introduction/windows_compilation.html) instruction.
```
zip_close.c:645:28: error: ‘_O_BINARY’ undeclared (first use in this function)
     _setmode(_fileno(tfp), _O_BINARY );
```
Fails when trying to run `make`

**Comment by circleous** [comment] 2016-12-18 23:26
https://github.com/HPCE/hpce-2015-cw2/issues/3
Seems like this has same issue. After comment out the line, build is fine.
```patch
diff --git a/shlr/zip/zip/zip_close.c b/shlr/zip/zip/zip_close.c
index 42fa58c..d32f84a 100644
--- a/shlr/zip/zip/zip_close.c
+++ b/shlr/zip/zip/zip_close.c
@@ -642,7 +642,7 @@ _zip_create_temp_output(struct zip *za, FILE **outp)
       According to Pierre Joye, Windows in some environments per
       default creates text files, so force binary mode.
     */
-    _setmode(_fileno(tfp), _O_BINARY );
+    //_setmode(_fileno(tfp), _O_BINARY );
 #endif
 
     *outp = tfp;
```

**Comment by XVilka** [comment] 2016-12-19 10:10
@circleous Why are you closed it?

**Comment by circleous** [comment] 2016-12-19 11:15
The program runs fine so far. So, i thought for closing this.

**Comment by XVilka** [comment] 2016-12-19 11:17
No, but the bug itself remains.

**Comment by radare** [comment] 2016-12-19 14:31
commenting this fixes the build but breaks the usage. O_BINARY should be available on windows. mainly because its windows-only flag

**Comment by radare** [comment] 2016-12-19 14:35
pushed a fix. pls confirm i dont have such env to test

**Comment by radare** [comment] 2016-12-19 19:26
Ping?

**Comment by circleous** [comment] 2016-12-19 23:49
`warning: implicit declaration of function ‘_fileno’` This isnt only happen on `_fileno` but `_snprintf`, `_read`, ... winapi related. After digging out a bit, it needs -D_POSIX_SOURCE. It trigger another error, meanwhile the first problem is solved.
`sys.c:419:4: error: unknown type name ‘fd_set’`
ref: http://stackoverflow.com/questions/15749184/fileno-not-available https://cygwin.com/ml/cygwin-apps/2013-04/msg00413.html

`-fPIC` is ignored in windows. This will trigger `warning: -fPIC ignored for target (all code is position independent)`. Weird thing is that mk/platform.mk isnt filtering msys. Somewhat related #40 Since its intended so i leave it as is.

**Comment by radare** [comment] 2016-12-20 02:23
Maybe the instructions are wrong? i just do sys/mingw32.sh and it builds fine on osx and linux

**Comment by circleous** [comment] 2016-12-20 04:34
Oddly enough, build runs fine on cygwin x86 windows.

**Comment by XVilka** [comment] 2016-12-20 09:37
Well, Cygwin 32/64, Mingw32 on Windows and Mingw32 on *nix, Mingw-w64, MSYS2, etc - everything is different and use different architectures. @circleous Can you please provide a full build log?

**Comment by radare** [comment] 2016-12-20 15:00
I dont see the point on providing support for over9000 reimplementations of the same crappy abstractions of unix on top of windows when native windows builds work fine

**Comment by XVilka** [comment] 2016-12-20 15:04
well, Mingw32 is not very 'native' one, unlike Mingw-w64. Cygwin provides unix-like experience of radare2 on windows - true colors, piping with unix utils, etc. Mingw32 can be easily integrated with Visual Studio and so on. It's different target auditory.

**Comment by XVilka** [comment] 2016-12-22 06:41
I can't reproduce it on my environment. @circleous are you?

**Comment by circleous** [comment] 2016-12-23 09:55
Sorry for the wait. http://sprunge.us/ihHC

**Comment by radare** [comment] 2016-12-23 11:32
For reference

**Comment by radare** [comment] 2017-01-02 20:07
_fileno should be defined in stdio.h . see https://msdn.microsoft.com/en-us/library/zs6wbdhx.aspx

**Comment by radare** [comment] 2017-01-02 20:08
So, as long as the fopen is done with the 'b' bit. this thing is totally unnecessary, i have just commented out. pls confirm its fixed

**Comment by circleous** [comment] 2017-01-04 02:01
Yep, build is fine now.

**Comment by Maijin** [comment] 2017-01-04 11:31
Then close

**Closed** 2017-01-04 11:31 UTC
Labels: bug, release, Windows
