### ISSUE TITLE
bool instead of int

### ISSUE THREAD

**Issue by condret** [radare/radare2#8264] opened 2017-08-22 10:01 UTC
We had this discussion ~a year ago, where we decided to go for r_io_read_at returning bool, not int, because returning int, does not provide more accurate information, about how r_io_read_at worked, than bool could do. So please, rename r_io_read_at_all to r_io_read_at back, and remove the current r_io_read_at

**Comment by Maijin** [comment] 2017-08-22 10:06
@MaskRay ^

**Comment by alvarofe** [comment] 2017-08-22 10:15
SIOL was boolify already and it was working iirc. The code using IO layer should be updated accordingly after the changes, I dislike `r_io_read_all_at` too but I should see where the int is really necessary if any

**Comment by condret** [comment] 2017-08-22 11:55
it isn't, I gave him a finger. I saif him I would do another r_io_read_at that returns a list of all pread-operations and to which map they belong, but he insists on his patch. He asked me for things, that he could help me with, I told him to try his hands on the desc-lock, but he did this

**Comment by MaskRay** [comment] 2017-08-22 16:25
Duplicate here. 



I felt terrible that the misconception was so deeply ingrained in your mind.

It is possible for `r_io_{p,v,}{read,write}_at` to return partial result, that is `0 <= ret && ret < len`. This does not necessarily indicate an error. For a read operation, it might be reading from a pipe/fifo/block dev/char dev/socket. By returning `int`, the return type indicates one of three possibilities:

* success, `ret == len`, this is what we desire
* fail, `ret == -1`, can be fine grained to return `-errno` in the future if more detailed error messages are needed
* partial, `0 <= ret < len`. If signal handlers are properly set to `SA_RESTART`, this indicates the read of the underlying file descriptor succeeded, but did not return the full length.

With `bool r_io_pread_at`, the third case (partial) is lost. In the analysis module, we may want to do:

```
while ((len = r_io_pread_at(io, addr, buf, blocksize) > 0) {
  // [buf, buf+len)
}
if (len < 0) {
  // error handling
}
```

In `cmd_yank`, we do not necessarily know the length beforehand and the generic `r_io_pread_at` should accommodate these reasonable needs.

You can find examples for `r_io_write_at`. There will certainly be other places where a partial read/write fits better because of the more information they convey.

`r_io_vread_at` may have more or less different behaviors. This is expected, after all, it is one layer above `r_io_pread_at` and some abstractions have to be made and some details have to hide. However, please make return types of `r_io_{,p,v}{read,write}_at` consistent. This is what everyone with *NIX developing experience would expect at the first glance of the API.

In the future, return values of multiple mappings would be desired to handle if we ever moved forward to that point, a POSIX like `readv` interface could be invented. They would:
```
RETURN VALUE
       On success, readv() and preadv() return the number of bytes read; writev() and pwritev() return the number of bytes  written.
       On error, -1 is returned, and errno is set appropriately.
```

The art of carving is to make noses bigger while eyes smaller. If you have doubt about the precise size, by doing this, you can always make noses smaller and eyes bigger. However, if you made noses smaller or eyes bigger, there would be no remedial measures. My English is not so good, this is also not a good translation of the original text《韓非子· 說林下》, which I learned in my junior middle school.

You would leave more space for future amendment if `int read()` was used instead of `bool read()`. Last but not least, how return values of `r_io_read_at` were kind of messy in the codebase, but taking it as `int r_io_read_at()` was what I had seen most frequently.

Now you are happy, the number of `FAILED` targets largely increased.

```
[679]UCCESS                       
[0] FIXED                         
[42]BROKEN                        
[0] FATAL                         
[318]AILED                        
[34%]      BROKENNESS   
```

```
[959]UCCESS                       
[0] FIXED                         
[42]BROKEN                        
[0] FATAL                         
[38]FAILED                        
[1039]  TOTAL 
```

I had told you repeatedly, to incorporate my fixes to your `opsalamence` branch the sooner the better, it saved time. Because I believed these fixes decreased the number of test failures dramatically. I had also argued countlessly, please did not change the return type from `int r_io_read_at` to `bool r_io_read_at`. You counted me on fixing threads.  But I had no priori knowledge and thought they were not the most urgent things.  The highest priority was to keep an eye on what happened on the `opsalamence` branch and remedied it. I also rebased so many times in the weekend, just because I thought pancake might merge your `opsalamence` in a few hours and I should be prepared to send out my patch to help put off the forest fires. The half-merged status had lasted for quite a long time and had caused much trouble.

As I had said in the Telegram group, I was just losing my passion, little by little, seeing more and more changes that i couldn't accept, happen out of my control (i should not have too much expectation of myself. i was an idiot), vector, `-std=gnu90`, abused sdb, abused list, `r_str_ncpy (dst, src, sizeof (dst) - 1)` instead of `sizeof (dst)`, `bool r_io_read_at`.

I was bitterly disappointed, just to see all my `ophydreigon` goodies was ruined, by a brutal revert, with all trouble bringing back, indiscriminately.

An incomplete listing

```diff
-                       print->cb_printf ("f section.%s %"PFMT64d" 0x%"PFMT64x"\n", n, s->size, s->vaddr);
+                       print->cb_printf ("f section.%s %"PFMT64d" 0x%"PFMT64x"\n", n, s->vaddr, s->vsize);
```

mem leaks
```diff
-       free (uri);
```

```diff
-       r_io_desc_free (desc);
```

cache regression
```diff
        if (io->cached_read) {
-               (void)r_io_cache_read (io, addr, buf, len);
+               ret &= !!r_io_cache_read (io, addr, buf, len);
        }
```

**Comment by radare** [comment] 2017-08-22 18:17
Agree

**Comment by wargio** [comment] 2017-08-22 18:34
i was thinking to start on siol from this, but i was too much drama :|
Should this be done or not?

**Comment by MaskRay** [comment] 2017-08-23 00:05
> SIOL was boolify already and it was working iirc. The code using IO layer should be updated accordingly after the changes, I dislike r_io_read_all_at too but I should see where the int is really necessary if any

https://github.com/radare/radare2/commit/3adcfea524777c5e65efedac80090cc8f1cf5c10

@alvarofe Have you ever noticed your mistake here?

```diff
-		ret = r_io_read_at (core->io, at, b, core->blocksize);
-		if (ret != core->blocksize) {
+		if (!r_io_read_at (core->io, at, b, core->blocksize)) {
  			break;
  		}
-		if (r_search_update (core->search, &at, b, ret) == -1) {
+		if (r_search_update (core->search, &at, b, core->blocksize) == -1) {
```

**Comment by condret** [comment] 2017-08-23 01:33
well, now we have RIOAccessLog, which already did a great job fixing things. I think we can make the code more beautiful, but as a concept this is great

**Comment by MaskRay** [comment] 2017-08-23 02:46
> SIOL was boolify already and it was working iirc. The code using IO layer should be updated accordingly after the changes, I dislike r_io_read_all_at too but I should see where the int is really necessary if any
> It isn't, I gave him a finger, he took the hand. I said him I would do another r_io_read_at that returns a list of all pread-operations and to which map they belong, but he insists on his patch. He asked me for things, that he could help me with, I told him to try his hands on the desc-lock, but he did this...

I hope you are all very happy after cutting down the 1 or 2 heads of Hydreigon and it can no longer fly (neither Deino nor Zweilous can learn [Fly](https://bulbapedia.bulbagarden.net/wiki/Fly_(move)))

IO is in a very weird status now (see `s 0; x`) and note the potential lost trailing bytes when total_len % blocksize != 0. You should revisit the `bool r_io_read_at` change nonsense and whether they are doing things wrong.

**Comment by radare** [comment] 2017-08-27 16:40
isnt this clear yet? can we close this issue?

**Comment by MaskRay** [comment] 2017-08-27 16:47
it can be closed because we have discussion there https://github.com/radare/radare2/pull/8332 https://github.com/radare/radare2/pull/8279 . THough I am still suspicious of the `bool` as return type.

**Closed** 2017-08-27 18:43 UTC
Labels: io, opfix, opsiol, refactor
