### ISSUE TITLE
Problem with pipes and variables

### ISSUE THREAD

**Issue by q6r** [radare/radare2#2406] opened 2015-04-18 21:17 UTC
Commands like :

```
[0x00000bc7]> axt @@ `afl ~fcn[3]` ~[1]
0x12d4
0xbd6
[0x00000bc7]> db @@ `axt @@ `afl ~fcn[3]` ~[1]`
[0x00000bc7]> db
[0x00000bc7]> db
```

does not work. I tried using vars

```
[0x00000bc7]> $hello="afl ~fcn"
[0x00000bc7]> $*
$hello="afl
[0x00000bc7]> $hello
[0x00000bc7]> $hello?
unknown key '$hello?'
[0x00000bc7]> $hello="afl |grep fcn"
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
[0x00000bc7]> $hello
[0x00000bc7]> 
```

using r2 9392424e3005....

**Comment by XVilka** [comment] 2015-04-18 22:15
@q6r for the
```
[0x00000bc7]> $hello="afl ~fcn"
[0x00000bc7]> $*
$hello="afl
```
you need to place all command in quotes if command contains spaces:
```
[0x00000bc7]> "$hello=afl ~fcn"
[0x00000bc7]> $*
$hello=afl ~fcn
```

**Comment by radare** [comment] 2015-04-18 22:27
Full command quotation is way simpler for the parser, i plan to support better quotes support after 1.0, for now i think that if you need to do more complex stuff is better to relay on a real programming language or scripting.

The current syntax is documented, and thats the expected behaviour. But im aware it may not look much intuitive, and problematic for some oneliner constructions.

**Comment by XVilka** [comment] 2015-04-18 22:29
@radare yep, thats about a variables part, still don't know about the first part - is this expected behaviour also?

**Comment by radare** [comment] 2015-04-18 23:06
is not expected, but it's a known bug. This should be fixed with r_cons_push/_pop which was recently added and already used in the graph generation to avoid this kind of issues when running multiple console buffers filtered at different nesting levels. I have moved this issue to 1.0 because its tricky to solve before the release, and it can be solved by using `k` or other intermediate steps like files:
```
axt @@ `afl ~fcn[3]` ~[1] > offsets
db @@ `cat offsets`
```

**Comment by radare** [comment] 2015-04-18 23:08
`db@@.offsets` should work too

**Comment by jduck** [comment] 2016-05-12 23:12
After just getting off track on this for a couple of hours I think the entire cons handling needs revisiting / refactoring / re-writing... I have a partial changeset stashed. If interested, please ping me.

**Comment by radare** [comment] 2016-12-12 23:06
the rcons(push,pop) has been implemented. so i think we can close this issue for now.

Could you provide tests for specific commands that doesnt work for the radare2-regressions repo if you find any other issue.

**Closed by radare** 2016-12-12 23:06 UTC
Labels: blocker
