### ISSUE TITLE
rasm2 wrong assembly value for ARM instruction

### ISSUE THREAD

**Issue by sylvainpelissier** [radare/radare2#5954] opened 2016-10-12 15:43 UTC
I found that the command:
```
$ rasm2 -d -a arm `rasm2  -a arm "orr r0,r0,r1"`
```
outputs
```
and r0, r0, r1
```
It seems the assembled value is wrong:
```
$rasm2  -a arm "orr r0,r0,r1"
010000e0
```
But the correct value is 010080E1. However I do not know where to correct that.

**Comment by radare** [comment] 2016-10-12 15:45
the code is in libr/asm/arch/arm/armass.c

in case you miss some instructions in the assemblers you can:

* implement them in the embedded assembler

or just go use an alternative assembler

* arm.as (which uses GAS)
* arm.ks (using keystone and available via r2pm)

thanks!

**Comment by j123123** [comment] 2016-10-12 20:39
https://github.com/radare/radare2/blob/c0c0cba3398466661afed716f709f1fc404a752e/libr/asm/arch/arm/armass.c#L101 <-- I think this place is wrong
``	{ "orr", 0x0, TYPE_ARI },``


for example, let's try ``eor`` instruction :
````
$ rasm2  -a arm "eor r0,r0,r1"
010020e0
````
this mask is used: ``{ "eor", 0x2000, TYPE_ARI },``

And keystone output for ``orr``: 
````
$ rasm2  -a arm.ks "orr r0,r0,r1"
010080e1
````
so I think it must be ``{ "orr", 0x8001, TYPE_ARI },``

**Comment by Maijin** [comment] 2016-10-12 20:40
Then make a PR

**Comment by Maijin** [comment] 2016-10-12 20:40
https://help.github.com/articles/editing-files-in-your-repository/

**Comment by Maijin** [comment] 2016-10-12 22:01
@j123123 next time use "Fix #XXXX" in your body or title commit message so the issue is closed after being merged automatically

**Closed by Maijin** 2016-10-12 22:01 UTC
