### ISSUE TITLE
rabin2 -V not implemented on mach0

### ISSUE THREAD

**Issue by radare** [radare/radare2#9518] opened 2018-02-26 15:11 UTC
protip:

```
$ rabin2 -H /bin/ls 2>&1 | grep VERSION
0x00000620  cmd          0x24 LC_VERSION_MIN_MACOSX
0x00000630  cmd          0x2a LC_SOURCE_VERSION
```

**Comment by Maijin** [comment] 2018-02-26 18:37
Already tracked but was missing example thanks, duplicate of #4216

**Closed by Maijin** 2018-02-26 18:37 UTC
Labels: good first issue
