### ISSUE TITLE
q on comments in RakhniDecryptor.exe

### ISSUE THREAD

**Issue by chairkov** [radare/radare2#7755] opened 2017-06-15 23:33 UTC
Hi, 

is this wrong? 

,r2 -v
radare2 1.6.0-git 15066 @ linux-x86-64 git.1.5.0-123-g0b4eb17
commit: 0b4eb1740c723996c3843791faec2fc7b1a620fe build: 2017-06-15__19:00:22

https://asciinema.org/a/f0i7hpvflvwhjxn0c2kgfaalz

**Comment by chairkov** [comment] 2017-06-15 23:33
the question is about the lot of addresses in the comments as seen by the video

**Comment by radare** [comment] 2017-06-26 13:55
<img width="1335" alt="screen shot 2017-06-26 at 15 54 46" src="https://user-images.githubusercontent.com/917142/27542540-d19f24ae-5a87-11e7-83aa-7ed4c36e9148.png">

**Comment by radare** [comment] 2017-06-26 13:55
seems lika regression introduced recently. maybe @alvarofe can have a look at it

**Comment by radare** [comment] 2017-06-28 10:43
cc @kazarmy

**Comment by radare** [comment] 2017-06-28 11:03
related https://github.com/radare/radare2/commit/91ba43a161259a75a8267e0729adfb31fc1cd875

**Comment by kazarmy** [comment] 2017-06-28 12:35
> is this wrong?

@chairkov binary? Internet at current location is currently so bad that I can't see your video.

**Comment by kazarmy** [comment] 2017-06-29 11:28
1. The `ffffff` is sign extension that shouldn't happen.
1. Radare thinks there's a wide string at 0x414178.
1. Commit 91ba43a161259a75a8267e0729adfb31fc1cd875 appears to be in the clear.

**Comment by radare** [comment] 2017-06-29 15:35
1. should be fixed with &0xff or (ut8)
2. wide or wide32?
3. uh?

**Comment by kazarmy** [comment] 2017-06-29 23:14
> 1. should be fixed with &0xff or (ut8)

(ut8) works but I prefer that #7834 goes through first.

> 2. wide or wide32?

wide

> 3. uh?

It appears that commit 91ba43a161259a75a8267e0729adfb31fc1cd875 is not the cause of this issue.

**Closed** 2017-07-01 08:08 UTC

**Comment by kazarmy** [comment] 2017-07-15 15:57
@chairkov @radare http://netbeisser.de/chairkov/RakhniDecryptor.exe

Can this binary be added to the [radare2-regressions repository](https://github.com/radare/radare2-regressions/tree/master/bins/pe)?

**Comment by kazarmy** [comment] 2017-07-16 01:05
> Can this binary be added to the radare2-regressions repository?

nvm
