### ISSUE TITLE
rabin2 ignores bit's passed in with -a for some formats

### ISSUE THREAD

**Issue by yrp604** [radare/radare2#2438] opened 2015-04-26 08:01 UTC
Specifying the bits with `-a`, using elf format
```
$ rabin2 -a x86_32 -c elf:cc 32
Dumped 85 bytes in '32'
$ file 32
32: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, corrupted section header size
$ rabin2 -a x86_64 -c elf:cc 64
Dumped 85 bytes in '64'
$ file 64
64: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, corrupted section header size
```

Specifying the bits with `-a`, using elf64 format
```
$ rabin2 -a x86_32 -c elf64:cc 32-2
Dumped 121 bytes in '32-2'
$ file 32-2
32-2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, corrupted section header size
$ rabin2 -a x86_64 -c elf64:cc 64-2
Dumped 121 bytes in '64-2'
$ file 64-2
64-2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, corrupted section header size
```

Everything gets properly set as far as I can tell and nothing changes if I use -b, I think the issue is that the module is looked up by name, and elf != elf64. Alternatively, you could just update the docs.

**Comment by radare** [comment] 2015-04-29 08:39
Nothing stops you from creating 32bit code in a 64bit binary, or on arm for example.. assemble 16bit (thumb) code into a 32bit executable. Not sure if this should be considered a bug or a feature. I find it handy sometimes.

**Comment by yrp604** [comment] 2015-04-30 19:55
Agreed, but the -b and -a arguments don't affect the assembling of code, correct? The code inside the generated binary is specified by the hexpairs, and ignores -b and -a.

I'm under the impression -b/-a should affect the binary it's reading/writing. This obviously isn't a huge deal, it just surprised me that when I specified an x86_64 ELF, the resulting elf specified 32bit in the header.

**Comment by radare** [comment] 2015-05-01 10:36
Agree, this may be confusing. Any proposal in C form?

**Comment by Maijin** [comment] 2015-12-16 20:41
ping ?

**Comment by yrp604** [comment] 2015-12-17 05:48
I can look over this this weekend. I started looking at the codebase, but wasn't sure where the appropriate spot to chance this behaviour was.

**Comment by Maijin** [comment] 2016-09-19 18:42
ping(2)

**Comment by radare** [comment] 2016-09-19 23:05
I think theres  atest for the fatmach0-3true and it is passing :? Or it was last time i checked but the recent changes could broke it somwhow

**Comment by Maijin** [comment] 2016-09-19 23:32
There is no test for that in https://github.com/radare/radare2-regressions/blob/master/t.tools/rabin2/rabin2

**Comment by radare** [comment] 2016-09-19 23:51
see t.formats/mach0/fatmach0

**Comment by Maijin** [comment] 2016-09-19 23:54
ah ok then let's close this.

**Closed by Maijin** 2016-09-19 23:54 UTC
Labels: easy, question

**Comment by alvarofe** [comment] 2016-09-20 10:37
I opened another issue cause in fatmach seems to be a regression https://github.com/radare/radare2/issues/5645 so is safe to close this issue
