### ISSUE TITLE
2.3.0 build failure on macOS

### ISSUE THREAD

**Issue by ilovezfs** [radare/radare2#9323] opened 2018-02-05 06:54 UTC
```
clang++ -fPIC -shared r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -undefined dynamic_lookup -I/usr/local/include -I/usr/local/Cellar/radare2/2.3.0/include/libr -I/usr/local/Cellar/openssl/1.0.2n/include -I/usr/local/Cellar/radare2/2.3.0/include/libr -o r_core.so -ldl -lr_util -lr_hash -lr_crypto -lr_magic -lr_socket -lr_io -lr_fs -lr_syscall -lr_search -lr_reg -lr_cons -lr_flag -lr_parse -lr_lang -lr_asm -lr_egg -lr_bp -lr_anal -lr_bin -lr_debug -lr_config -lcrypto -lssl -lr_core -L/usr/local/Cellar/radare2/2.3.0/lib -L/usr/local/Cellar/openssl/1.0.2n/lib -L/usr/local/Cellar/radare2/2.3.0/lib -L/usr/local/lib -llua -lm -llua -lm -llua -lm
r_core_wrap.cxx:3687:10: error: no matching function for call to 'r_anal_fcn_get_refs'
                list = r_anal_fcn_get_refs (self);
                       ^~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/radare2/2.3.0/include/libr/r_anal.h:1405:14: note: candidate function not viable: requires 2 arguments, but 1 was provided
R_API RList *r_anal_fcn_get_refs(RAnal *anal, RAnalFunction *fcn);
             ^
r_core_wrap.cxx:3698:10: error: no matching function for call to 'r_anal_fcn_get_xrefs'
                list = r_anal_fcn_get_xrefs (self);
                       ^~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/radare2/2.3.0/include/libr/r_anal.h:1406:14: note: candidate function not viable: requires 2 arguments, but 1 was provided
R_API RList *r_anal_fcn_get_xrefs(RAnal *anal, RAnalFunction *fcn);
             ^
r_core_wrap.cxx:3977:3: error: no matching function for call to 'r_syscall_setup'
                r_syscall_setup(self, arch, os, bits);
                ^~~~~~~~~~~~~~~
/usr/local/Cellar/radare2/2.3.0/include/libr/r_syscall.h:94:12: note: candidate function not viable: requires 5 arguments, but 4 were provided
R_API bool r_syscall_setup(RSyscall *s, const char *arch, int bits, const char *cpu, const char *os);
           ^
r_core_wrap.cxx:3980:3: error: use of undeclared identifier 'r_syscall_setup_file'; did you mean 'RSyscall_setup_file'?
                r_syscall_setup_file(self, file);
                ^~~~~~~~~~~~~~~~~~~~
                RSyscall_setup_file
r_core_wrap.cxx:3979:17: note: 'RSyscall_setup_file' declared here
SWIGINTERN void RSyscall_setup_file(RSyscall *self,char *file){
                ^
... r_bin.so
4 errors generated.
make: *** [r_core.so] Error 1
```
full log https://gist.github.com/ilovezfs/7d86e767589e02fbc42d3a858ef94409

**Comment by radare** [comment] 2018-02-05 17:07
This is not an issue in r2

**Comment by radare** [comment] 2018-02-05 17:08
You are compiling the bindings

**Comment by sivaramaaa** [comment] 2018-02-06 13:31
@radare , if it's not an issue in r2 , can we close this issue ??

**Comment by radare** [comment] 2018-02-06 13:33
This is a bug in radare2-bindings, that i cant reproduce, this is probably because you are building r2b with an incompatible version of r2

**Comment by ilovezfs** [comment] 2018-02-06 13:33
Can someone tell me where to file this issue? I simply updated the Homebrew formula with the new files from https://radare.mikelloc.com/get/2.3.0 and it went :boom:

**Closed by radare** 2018-02-06 13:33 UTC
Labels: OS X

**Comment by ilovezfs** [comment] 2018-02-06 13:34
@radare in particular, what is wrong with https://github.com/Homebrew/homebrew-core/pull/23693

**Comment by ilovezfs** [comment] 2018-02-06 13:37
Are you saying https://radare.mikelloc.com/get/2.3.0/radare2-bindings-2.1.0.tar.gz isn't the correct bindings tar ball for 2.3.0 to use? What is? Why is that in the 2.3.0 directory?

**Comment by radare** [comment] 2018-02-06 13:39
2.3 != 2.1

**Comment by ilovezfs** [comment] 2018-02-06 13:40
@radare can you please put the correct bindings tarball in https://radare.mikelloc.com/get/2.3.0/ then?

**Comment by ilovezfs** [comment] 2018-02-06 13:41
ditto radare2-extras if that is also wrong.

**Comment by radare** [comment] 2018-02-06 13:43
thats what im doing right now

**Comment by ilovezfs** [comment] 2018-02-06 13:43
@radare thanks :bowing_man:

**Comment by radare** [comment] 2018-02-06 13:48
done

**Comment by ilovezfs** [comment] 2018-02-06 13:50
@radare perfect. New CI job triggered https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/17947/
