### ISSUE TITLE
radare2 stopped loading functions properly since 1e89dddd87a67ce920b9764ed8a7fe2b254bd2c7

### ISSUE THREAD

**Issue by arno01** [radare/radare2#5852] opened 2016-09-26 13:39 UTC
Since the change done in 1e89dddd87a67ce920b9764ed8a7fe2b254bd2c7:libr/bin/bin.c at r_bin_load_io_at_offset_as_sz  https://github.com/radare/radare2/commit/1e89dddd87a67ce920b9764ed8a7fe2b254bd2c7#diff-caf08efa1bd7b633b9cc695a8681a9cfR794 , radare2 doesn't load functions properly:

```
$ cat c.c 
void main()
{
    write(1, "TEST\n", 5);
}

$ gcc -o c c.c

$ radare2 -A -d ./c

[0x3ecdd70dcc0]> s sym.main
[0x00000000]> pdr
Cannot find function at 0x00000000
[0x00000000]> dm
sys   4K 0x0000000000400000 - 0x0000000000401000 s -r-x /home/arno/c /home/arno/c
sys   8K 0x0000000000600000 - 0x0000000000602000 s -rw- /home/arno/c /home/arno/c
sys 6.6M 0x0000000000602000 - 0x0000000000c9e000 s ---- unk0 unk0
sys   4K 0x0000000000c9e000 - 0x0000000000c9f000 s -rw- [heap] [heap]
sys 152K 0x000003ecdd70d000 - 0x000003ecdd733000 s -r-x /lib/x86_64-linux-gnu/ld-2.23.so /lib/x86_64-linux-gnu/ld-2.23.so
sys   8K 0x000003ecdd92e000 - 0x000003ecdd930000 s -r-- [vvar] [vvar]
sys   8K 0x000003ecdd930000 - 0x000003ecdd932000 s -r-x [vdso] [vdso]
sys   8K 0x000003ecdd932000 - 0x000003ecdd934000 s -rw- /lib/x86_64-linux-gnu/ld-2.23.so /lib/x86_64-linux-gnu/ld-2.23.so
sys   4K 0x000003ecdd934000 - 0x000003ecdd935000 s -rw- unk1 unk1
sys 136K 0x000003f30b621000 - 0x000003f30b643000 s -rw- [stack] [stack]
sys   4K 0xffffffffff600000 - 0xffffffffff601000 s -r-- [vsyscall] [vsyscall]
```

Thanks to fix!

**Comment by arno01** [comment] 2016-09-26 13:57
It looks like that it should:

```
iob->desc_seek (io, desc, seekaddr);       
buf_bytes = iob->desc_read (io, desc, &sz);
```

within ```if (!buf_bytes) {``` , at least that worked for me :-)

**Comment by radare** [comment] 2016-09-26 13:59
git pull, there have been several fixes after that, in fact the testsuite was failing in travis, the problem is that there's no way to test the cornercase i was fixing. plase git pull and confirm the issue is fixed in master or not, because it works for me on linux and osx

**Comment by Maijin** [comment] 2016-09-26 14:02
Looks like `sym.main` doesn't exist see it's seeking to `[0x00000000]>`
Did you look at the flags list and see if it hasn't took another name ? `V_` main

**Comment by arno01** [comment] 2016-09-26 14:32
How sym.main doesn't exist... here is when radare2 is without the subj.commit:

```
radare2 -A -d ./c
Process with PID 18440 started...
= attach 18440 18440
bin.baddr 0x00400000
Assuming filepath /home/arno/c
asm.bits 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[Cannot determine xref search boundariesr references (aar)
[x] Analyze len bytes of instructions for references (aar)
[Oops invalid rangen calls (aac)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
 -- Press 'C' in visual mode to toggle colors
[0x3bfc07dfcc0]> s sym.main
[0x00400526]> pdr
  ;-- main:
/ (fcn) sym.main 32
|   sym.main ();
| ; DATA XREF from 0x0040044d (entry0)
| 0x00400526      55             push rbp
| 0x00400527      4889e5         mov rbp, rsp
| 0x0040052a      ba05000000     mov edx, 5
| 0x0040052f      bed4054000     mov esi, str.TEST_n                   ; "TEST." @ 0x4005d4
| 0x00400534      bf01000000     mov edi, 1
| 0x00400539      b800000000     mov eax, 0
| 0x0040053e      e8bdfeffff     call sym.imp.write
| 0x00400543      90             nop
| 0x00400544      5d             pop rbp
\ 0x00400545      c3             ret

```

**Comment by arno01** [comment] 2016-09-26 14:56
@radare I have just tried the very latest version, it did not work.
Seems like there is some problem in reading the file structure with the subj. commit. I have manually changed couple of lines and it was working for me,.. but I am not entirely certain my fix is a good one...

**Comment by arno01** [comment] 2016-09-26 15:00
When I was doing `git pull`, sometimes I've seen that HEAD rolled 5 days back (to 21 Sept), it looks like there is some github issue, though nothing at the status github com .... so I just want to make sure that neither you have been trying the wrong radare2 version .. :-)

**Comment by radare** [comment] 2016-09-26 15:02
just run sys/install.sh it will git pull cleanup the build and install everything in a generic way if you want i can show you an asciinema demonstrating that it works

**Comment by arno01** [comment] 2016-09-26 15:04
I used `make uninstall`, `make purge`, `git pull upstream master`, followed by `sys/user.sh` in the end.

At the point of `git pull` I had some issue. My colleagues at work are also experiencing some nasty issues with the github right now.

And for the sake of cleanliness, I did `rm -rf radare2` and `git clone` it again. The issue described in subj. is still there.

```
radare2 --version
radare2: invalid option -- '-'
radare2 0.10.6-git 12485 @ linux-x86-64 git.0.10.5-363-g62de135
commit: 62de135861ed1d615e61b2e5bc749902dc9504b8 build: 2016-09-26
```

**Comment by alvarofe** [comment] 2016-09-26 15:15
What about `s main`??

**Comment by arno01** [comment] 2016-09-26 15:17
@alvarofe yep, that is working :-)  So `sym.` is dropped then?

**Comment by alvarofe** [comment] 2016-09-26 15:18
What about `s main` 

```
[alvaro@void tmp]$ r2 -d ./prueba
Process with PID 2155 started...
= attach 2155 2155
bin.baddr 0x00400000
Assuming filepath /tmp/prueba
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
asm.bits 64
 -- I didn't said that it was working, I said that it's implemented
[0x7fc7a554fc80]> dcu entry0
Continue until 0x00400400 using 1 bpsize
hit breakpoint at: 400400
= attach 2155 1
[0x00400400]> s main
[0x004004f6]> pd 10
            ;-- main:
            0x004004f6      55             push rbp
            0x004004f7      4889e5         mov rbp, rsp
            0x004004fa      ba05000000     mov edx, 5
            0x004004ff      bea4054000     mov esi, 0x4005a4
            0x00400504      bf01000000     mov edi, 1
            0x00400509      b800000000     mov eax, 0
            0x0040050e      e8ddfeffff     call 0x4003f0
            0x00400513      5d             pop rbp
            0x00400514      c3             ret
            0x00400515      662e0f1f8400.  nop word cs:[rax + rax]
```

**Comment by alvarofe** [comment] 2016-09-26 15:19
Though there is an issue cause there is not symbols whatsoever when loading with the debugger.

**Comment by radare** [comment] 2016-09-26 15:19
r2 doesnt uses getopt long because its an ugly gnuism. dont use double dash in cmdline r2 -v

and yep, this seems like good version now

**Comment by radare** [comment] 2016-09-26 15:20
main is detected without symbols, sym.main comes from the symbol table, but main will override sym.main naming because its just shorter.

r2 analizes the code in the entrypoint to define where the main is. but this is done by the rbin layer, so we can close this now?

**Comment by alvarofe** [comment] 2016-09-26 15:21
but `call 0x4003f0` should be `call sym.imp.write` and when you do `is` you don't get nothing so it seems to me a regression

**Comment by arno01** [comment] 2016-09-26 15:22
@alvarofe taking the moment, does the following work for you ?

```
pdr
db 0x0040050e
dc
vi  (switch to visual mode Esc, Esc, Shift+! )
```

then `s`, `s`, ... after 3rd `s` I am getting

```
TEST
PTRACE_EVENT_EXIT pid=18438, status=1280
```

right after:

```
=----------------------------------------------------------------------------
|   Disassembly                                                              
|        ||   ;-- rip:                                                       
| / (fcn) fcn.00400400 6                                                     
| |   fcn.00400400 ();                                                       
| \      ||   0x00400400      jmp qword [0x00601018]                         
|        ||   0x00400406      push 0                                         
|        `==< 0x0040040b   4  jmp 0x4003f0                               ;[1]
| / (fcn) fcn.00400410 6                                                     
| |   fcn.00400410 ();                                                       
| \       |   0x00400410      jmp qword [0x00601020]                         
|         |   0x00400416      push 1 ; rdi                                   
|         `=< 0x0040041b      jmp 0x4003f0                               ;[1]
```

**Comment by radare** [comment] 2016-09-26 15:27
ok i see, im fixing now wait

**Comment by radare** [comment] 2016-09-26 15:38
Chk again

**Comment by radare** [comment] 2016-09-26 16:45
pls confirm now

**Comment by arno01** [comment] 2016-09-26 17:39
on my way...

**Comment by arno01** [comment] 2016-09-26 17:46
@radare confirming, it is working now!

Taking this opportunity, I would like to ask, why does debugging stop after it goes through the `write` syscall ? e.g. `db sys.imp...`, `dc`, `ds` (3 times) and it exits... here is the recorded session https://asciinema.org/a/4875w8tzx0u20m60erkv32vqq

Thanks in advance!

**Comment by radare** [comment] 2016-09-26 18:05
Closing it, im 99% sure that this step in problem is related to dbg.swstep and the latest changes in RAnalOp by doing the software based breakpoints on memjmp instructions, also you dont need to do db+dc+db-... and i dont see you removing the breakpoint after hitting it, so this can be another reason for that issue. please confirm both, and open a new issue to track this problem.

you can just do `dcu entry0` or `dcu main`. this will do the bp+cont+drop.bp for you in a single command.

**Closed by radare** 2016-09-26 18:05 UTC
