### ISSUE TITLE
ARM (32bit) only: 16bit (THUMB) setting was turned back to 32bit during virtual mode

### ISSUE THREAD

**Issue by unixfreaxjp** [radare/radare2#4798] opened 2016-05-07 09:24 UTC
in arm cpu linux latest pull  (radare2 0.10.3-git 11147 @ linux-arm-32 git.0.10.2-204-g6c7d91c)
tested after purge previous versions, did the test 2 times (with and without root)
```asm
$ r2 /bin/cp
 -- How about a nice game of chess?
[0x0000b200]> e asm.bits
32
[0x0000b200]> e asm.bits = 16
[0x0000b200]> e asm.bits
16
[0x0000b200]> (virtual)
 
[0x0000b200 11% 120 /bin/cp]> ?0;f tmp;s.. @ entry0
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000004  0101 0100 0000 0000 0000 0000 0200 2800  ..............(.
0x00000014  0100 0000 00b2 0000 3400 0000 68a3 0100  ........4...h...
0x00000024  0200 0005 3400 2000 0900 2800 1c00 1b00  ....4. ...(.....
0x00000034  0100 0070 9894 0100 9814 0200 9814 0200  ...p............
  sb 0x00000000       sl 0x00000000       fp 0x00000000       ip 0x00000000
  sp 0x00000004       lr 0x00000000       pc 0x0000b20c       r0 0x00000000
  r1 0x464c457f       r2 0x00000000       r3 0x00000000       r4 0x00000000
  r5 0x00000000       r6 0x00000000       r7 0x00000000       r8 0x00000000
  r9 0x00000000      r10 0x00000000      r11 0x00000000      r12 0x00000000
 r13 0x00000004      r14 0x00000000      r15 0x0000b20c      r16 0x00000000
 r17 0x00000000     cpsr 0x00000000
            ;-- entry0:
            0x0000b200      00b0a0e3       mov fp, 0
            0x0000b204      00e0a0e3       mov lr, 0
            0x0000b208      04109de4       pop {r1}
            ;-- pc:
            ;-- r15:
            0x0000b20c      0d20a0e1       mov r2, sp
            0x0000b210      04202de5       str r2, [sp, -4]!
            0x0000b214      04002de5       str r0, [sp, -4]!
            0x0000b218      10c09fe5       ldr ip, [pc, 0x10]          ; [0xb23
            0x0000b21c      04c02de5       str ip, [sp, -4]!
 
Press <enter> to return to Visual mode.    ldr ip, [pc, 0x10]          ; [0xb23
:> e asm.bits
32
[0x0000b200]> r2 -v;!dmesg|grep -i 'arm'
radare2 0.10.3-git 11147 @ linux-arm-32 git.0.10.2-204-g6c7d91c
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=00093177
[    0.000000] Machine: ARM PB
[0x0000b200]> date
Sat, 07 May 2016 08:53:48 GMT + 0
[0x0000b200]>
```
 this does not happen in the x86-32 or x86-64
```asm
$ r2 /bin/cp
 -- License server overloaded (ETOOMANYCASH)
[0x0804af14]> e asm.bits
32
[0x0804af14]> e asm.bits = 16
[804000:af14]> pd 5 @0x0804af14
            ;-- entry0:
            4000:af14      31ed           xor bp, bp
            4000:af16      5e             pop si
            4000:af17      89e1           mov cx, sp
            4000:af19      83e4f0         and sp, 0xfff0
            4000:af1c      50             push ax
[804000:af14]> (virtual)

[0x00000047 0% 185 /bin/cp]> ?0;f tmp;s.. @ ip
- offset -  0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0000:000a  0000 0000 0000 0200 0300 0100 0000 14af  ................
0000:001a  0408 3400 0000 d053 0200 0000 0000 3400  ..4....S......4.
0000:002a  2000 0900 2800 1b00 1a00 0600 0000 3400   ...(.........4.
0000:003a  0000 3480 0408 3480 0408 2001 0000 2001  ..4...4... ... .
  ip 0x00000047       ax 0x00000000       bx 0x00000101       cx 0x00000000
  dx 0x00000000       sp 0x0000000a       bp 0x00000000       si 0x00000001
  di 0x00000000     flags 0x00000000
            ;-- ip:
            0000:0047      0020           add byte [bx + si], ah
            0000:0049      0100           add word [bx + si], ax
            0000:004b      0005           add byte [di], al
            0000:004d      0000           add byte [bx + si], al
            0000:004f      0004           add byte [si], al
            0000:0051      0000           add byte [bx + si], al
            0000:0053      0003           add byte [bp + di], al
:> e asm.bits
16
:>

```
should be a bug.

**Comment by alvarofe** [comment] 2016-05-07 12:10
could you share the bin to test locally?

**Comment by radare** [comment] 2016-05-09 23:46
Cant reproduce on rpi

**Comment by unixfreaxjp** [comment] 2016-05-10 14:34
> could you share the bin to test locally?

I will send the archive of the whole directory in 24h

> Cant reproduce on rpi

If you use older ARM or QemuARM in Jessie or Wheezy, it will shows the same.

**Comment by radare** [comment] 2016-05-10 17:08
Just one bin is fine. Are you sure you are reunning a clean build of r2?

**Comment by Maijin** [comment] 2016-05-10 22:04
Do you still have the warning when doing r2 -v ? If so, it's still not clean !

**Comment by unixfreaxjp** [comment] 2016-05-11 02:57
Nope, no warning, as per you suggested and we discussed, make purge and brand new image. I am on it now..

**Comment by unixfreaxjp** [comment] 2016-05-11 04:04
This is the demonstration video of this "phenomenon":
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/7elyrhem9Eg/0.jpg)](https://www.youtube.com/watch?v=7elyrhem9Eg)
Still uploading the archive.. please see the video first

**Comment by radare** [comment] 2016-05-11 09:00
Virtual -> Visual
Debug -> Emulate

I missed the point where you stepped into using esil, will try again with this.

Btw you can also use radare.tv

**Comment by unixfreaxjp** [comment] 2016-05-11 09:39
> Virtual -> Visual
> Debug -> Emulate

Dully noted :)

**Comment by radare** [comment] 2016-05-11 09:41
confirmed issue on rpi3. will look at it, it only happens when stepping with esil, so it must be something related to saving and restoring the state. funnily this bug doesnt happens on x86 when loading the arm binary.

thanks

**Comment by unixfreaxjp** [comment] 2016-05-11 09:45
> confirmed issue on rpi3. will look at it, it only happens when stepping with esil, so it must be something related to saving and restoring the state. 

yay! thank you for confirming, but remember this is not the top priority since a reverser  can always re-set environment back (workaround).

> funnily this bug doesnt happens on x86 when loading the arm binary.

I tried several platforms and multiple arch binaries actually (have ton of them to test here), and only arm has this 'pnenomenon'

**Comment by radare** [comment] 2016-05-11 09:50
it’s probably related to the code that checks the thumb bit in the cpsr register, which should be disabled or fixed to not interfer in non-debugger mode. that’s my guess. will try later if that’s the reason :)

**Comment by radare** [comment] 2016-05-11 13:42
It is fixed now. i just disabled that cpsr logic :P

**Comment by radare** [comment] 2016-05-11 13:42
The testcase is: `e asm.bits=16;aes;e asm.bits'

**Closed by radare** 2016-05-11 13:42 UTC
Labels: ARM

**Comment by radare** [comment] 2016-05-11 13:43
Added into r2r to avoid future breakage, but we need to run the testsuite on arm to detect this

**Comment by unixfreaxjp** [comment] 2016-05-11 18:54
Please give me 24h to confirm, need to remake the OS now.
_( I just used it on experimenting to run 3 IoT stupid botnets.. It's fun to watch they killing, deleting & takeover each other)_

**Comment by unixfreaxjp** [comment] 2016-05-11 20:33
> The testcase is: `e asm.bits=16;aes;e asm.bits'

Pulling & cleanly build on ARM:
```asm
Unpacking objects: 100% (45/45), done.
From https://github.com/radare/radare2
   9a86edb..6464e44  master     -> origin/master
Updating 9a86edb..6464e44
```
The problem is confirmed fixed. Thank's!

**Comment by radare** [comment] 2016-05-11 20:44
👍
