### ISSUE TITLE
Invalid commands in Visual Mode

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3640] opened 2015-10-31 10:45 UTC
When you open file in Vp mode and press up&down keys some commands converted to invalid

![2015-10-31-110640_1440x900_scrot](https://cloud.githubusercontent.com/assets/1186777/10863145/a2bc92fa-7fd4-11e5-9f84-9e7a2ccd0833.png)

File for tests https://dl.dropboxusercontent.com/u/10688770/ex3.1.bin

**Comment by radare** [comment] 2015-10-31 10:47
wat

**Comment by XVilka** [comment] 2015-10-31 10:57
Not a bug, this is how radare2 works, it starts disassembling from the current offset. Thus, if the current offset is in the middle of opcode -> it returns 'invalid' instruction. Closing.

**Closed by XVilka** 2015-10-31 10:57 UTC
Labels: invalid
