### ISSUE TITLE
Cannot view any memory in gdb

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#9255] opened 2018-01-27 20:29 UTC
I'm using the latest (as of yesterday) Docker build for r2.

I can connect up to gdbserver with r2, continue execution and such, but i cannot view any memory.

Connecting and verifying it can run
```
= attach 2121 0
hit breakpoint at: 8048af7
 -- Hello Mr. Anderson
[0x08048af7]> dc
[0xf77a0c89]> drr
   eax 0xfffffe00  eax
   ecx 0xffcb8d68  ecx stack R W 0xffffffff
   edx 0x00000020  edx ascii
   ebx 0x00000000  ebx
   esp 0xffcb8d08  esp stack R W 0xffffffff
   ebp 0xffcb8d48  ebp stack R W 0xffffffff
   esi 0x00000000  ebx
   edi 0x00000000  ebx
   eip 0xf77a0c89  ([vdso]) eip R X 'invalid' '[vdso]'
eflags       .PZI  eflags
    cs 0x00000023  cs ascii
    ss 0x0000002b  es ascii
    ds 0x0000002b  es ascii
    es 0x0000002b  es ascii
    fs 0x00000000  ebx
    gs 0x00000063  gs ascii
orig_eax 0x00000000  ebx
 mxcsr 0x00000000  ebx
[0xf77a0c89]> 
```

Trying to view memory
```
[0xf77a0c89]> dmm
0x08048000 /home/r2/radare_work/acebear_ctf/rev/secure_login/secure_login
0xf75e9000 /lib/i386-linux-gnu/i686/cmov/libc-2.19.so
0xf77a2000 /lib/i386-linux-gnu/ld-2.19.so
[0xf77a0c89]> px @ 0x08048000
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x08048000  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048030  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048040  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048050  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048080  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048090  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x080480f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
[0xf77a0c89]> oba 0x08048000 /home/r2/radare_work/acebear_ctf/rev/secure_login/secure_login
[0xf77a0c89]> px @ 0x08048000
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x08048000  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x08048010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
```

This is the same for the libraries as well.

**Comment by radare** [comment] 2018-01-27 22:18
Probably related to this?

https://github.com/radare/radare2/issues/9159

**Comment by XVilka** [comment] 2018-02-12 08:06
Issue still can be reproduced it seems

**Comment by XVilka** [comment] 2018-02-12 08:08
@SrimantaBarua can you please check this issue if you have time?

**Comment by radare** [comment] 2018-02-12 21:44
Works for me :?

**Comment by radare** [comment] 2018-02-23 23:56
closing until someone complains or tests again

**Closed by radare** 2018-02-23 23:56 UTC
Labels: debugger, gdb, regression
