### ISSUE TITLE
`aac` hangs out

### ISSUE THREAD

**Issue by JavierYuste** [radare/radare2#14782] opened 2019-08-10 09:53 UTC
## Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86/64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0 22681 @ linux-x86-64 git.3.7.0-48-g7684a03d3 commit: 7684a03d31b106da8d6b21d3fc97f4f4b83a47fd build: 2019-08-10__11:37:18

### Behavior
R2 hangs out when running `aac`

### Steps to reproduce the behavior 
- Open the file
- Run `aa`
- Run `aac`

### Additional Logs, screenshots, source-code,  configuration dump, ...

Password: infected
[0b7f0654cc8d2aa40f9f28c0fcd8dcd810ae04a0de7007f1dc82f8a45015088b.zip](https://github.com/radare/radare2/files/3488729/0b7f0654cc8d2aa40f9f28c0fcd8dcd810ae04a0de7007f1dc82f8a45015088b.zip)

**Comment by radare** [comment] 2019-08-10 13:00
takes a long nwhile to repro this issue because the bin is pretty huge but it hangs analyzing the function in here: 29627863 coming from 24621053, this is the 318th function created.. 

The hang seems related to analyzing a function that was previously analyzed but covering a different boundary because of invalid code.

will be good to have a smaller testcase, but this bin seems like an interesting sample to improve our analysis times

**Comment by radare** [comment] 2019-08-10 13:03
and i think i cant repro the issue if i run aac before aa, but didnt wait that much time

**Comment by radare** [comment] 2019-08-10 13:04
also the amount of functions found is pretty low for the same reason

**Comment by radare** [comment] 2019-09-01 18:44
i have a wip fix, but better not merge it the same day of the release

**Comment by radare** [comment] 2019-09-09 18:16
can you try to reproduce again?

**Comment by radare** [comment] 2019-09-09 19:17
nvm  not fixed yet

**Comment by radare** [comment] 2019-09-10 09:41
ok  i can confirm my code was fixing this, but there was a bottleneck that was making the whole thing a bit slow, i will make a couple of PRs today and hopefully get travis green with this solved, btw after the fix it takes 10s to finish aac

**Comment by JavierYuste** [comment] 2019-09-10 17:04
Thanks a lot for the fix! I will try it as soon as it is merged

**Comment by radare** [comment] 2019-09-15 10:51
its merged. so have fun :)

**Closed by radare** 2019-09-15 10:51 UTC
Labels: bug, optimization

**Comment by Maijin** [comment] 2019-09-15 11:02
It's fixed on this one.

**Comment by radare** [comment] 2019-09-15 11:51
Sadly we cant use it for tests
