### ISSUE TITLE
pdf command instruction parsing error.

### ISSUE THREAD

**Issue by hdarwin** [radare/radare2#7352] opened 2017-04-25 13:44 UTC
```python
import r2pipe as r2
r = r2.open('target', ['-A', '-B 0x555555554000'])
print '*'*80
print 'pdf @sym.parse~0x5555555567c3'
print r.cmd('pdf @sym.parse~0x5555555567c3')
print '*'*80
print 'pd 1500 @sym.parse~0x5555555567c3'
print r.cmd('pd 1500 @sym.parse~0x5555555567c3')
print '*'*80
r.quit()
"""result
********************************************************************************
pdf @sym.parse~0x5555555567c3
| |||||||   0x5555555567c3      0f             invalid
********************************************************************************
pd 1500 @sym.parse~0x5555555567c3
| ========< 0x5555555567c3      0f8f59070000   jg 0x555555556f22
  ||||||!      ; JMP XREF from 0x5555555567c3 (sym.parse)
********************************************************************************
"""
```
I tried to display whole instructions in a function. but 'pdf' command work improperly.. when 'pd' command works well.
my test binary is https://ghostbin.com/paste/ty3ww. it is a CTF challenge binary.

**Comment by radare** [comment] 2017-04-25 19:50
just as a side note, usually pdr is more accurate than pdf because it recusively shows the disasm of the function without unrelated code or data. But yep that should work

**Comment by XVilka** [comment] 2017-04-26 04:03
@hdarwin please craft testcase for radare2-regressions if you can.

**Comment by hdarwin** [comment] 2017-04-26 08:23
@radare  I tried it but same issue :(
```python
[0x555555554a40]> pdr @sym.parse~0x5555555567c3
| 0x5555555567c3      0f             invalid
```

@XVilka ok I will. but I need some time to do it :)

**Comment by radare** [comment] 2017-04-26 17:05
are those invalids suposed to not be invalid? maybe using a bigger block size may fix the issue, didnt had a chance to check yet

**Comment by hdarwin** [comment] 2017-04-27 05:55
@radare when I load binary without -B option it works well so I thought it is a issue.

**Comment by radare** [comment] 2017-05-27 23:06
r = r2.open('target', ['-A', '-B 0x555555554000'])
 ^- this is wrong . -B and 0x5555.. are different paramteres

**Comment by radare** [comment] 2017-07-09 23:25
ping

**Comment by radare** [comment] 2017-07-31 13:05
use pdr instead of pdf, because pdf shows the boundaries of the function, not the recursive basic blocks of code that are used by the function

**Comment by radare** [comment] 2017-10-16 20:00
closing

**Closed by radare** 2017-10-16 20:00 UTC
Labels: anal, disassembly, test-required
