### ISSUE TITLE
Endianness problems for wopO command

### ISSUE THREAD

**Issue by diouziou** [radare/radare2#5352] opened 2016-07-19 13:04 UTC
hi

line `240` in `write_cmd.c`, namely:
```	core->num->value = r_debruijn_offset (len, 0 /* use LE */);```
is problematic for several reasons:

- the 0 value (BE) is incompatible with the comment mentionning LE
- the endianness is hardcoded
- when using wopO on a LE vm in LE host, the result is wrong (obvious since 0 is passed as an argument)

**Comment by diouziou** [comment] 2016-07-19 21:48
@XVilka : i tested the behavior of an old r2 version and the new one, and they differ: return values for argument 0x41424141 and 0x41414241 are exchanged between the 2 versions. And the old version gave correct results

**Comment by radare** [comment] 2016-07-20 01:16
Yeah some of the damo22 changes are wrong i have noticed this also in the ef parser that it is unusable on big endian machines which is q big pain to fix but im on the works for this. Can you send a pr? Some tests for r2r will be helpful too

Thanks!

**Comment by diouziou** [comment] 2016-07-20 06:21
i'm not sure to understand how i could send a pr. i have no patch for this except changing the 0 to a 1 to make it work on usual x86 arch. is this what you'd like ?

**Comment by radare** [comment] 2016-07-20 09:31
0 is little endian.. Or it should. Why do u say 0 is be? (Didnt read the code im afk)

Should just use core->assembler->bigendian

Little endian is what u may find in 99% of modern hardware so u dont need to use any virtual machine for that

**Comment by diouziou** [comment] 2016-07-20 09:41
i said LE=1, BE=0 because i read this in `debruijn.c` lines 116 and 117:

`// Guest endian = 1 if little, 0 if big.`
`// Host endian = 1 if little, 0 if big.`

i know most machines are LE
i think i did not understand what guest and host mean, i thought they referred to virtual machines...

**Comment by radare** [comment] 2016-07-26 23:57
send a pr if you can

**Comment by diouziou** [comment] 2016-08-02 20:15
I don't have enough knowledge about the inner workings of r2 and how the endianness is handled to submit a pr

**Comment by alvarofe** [comment] 2016-08-02 21:23
should be fixed now and pancake just told you the solution ;). At least could you create a test for regression?

**Closed** 2016-08-02 21:22 UTC
Labels: blocker, regression, test-required

**Comment by diouziou** [comment] 2016-08-02 21:28
Thx!
I guess i'm to shy to modify code like this...
By test for regression, you mean testing if this works?

**Comment by radare** [comment] 2016-08-02 21:42
See the radare2-regressions repo and add another snippet to verify that the behaviour is correct

**Comment by alvarofe** [comment] 2016-08-03 07:35
@diouziou check this https://github.com/radare/radare2-regressions/blob/master/t/cmd_wop#L16 because after the change is broken or it should be updated

**Comment by diouziou** [comment] 2016-08-26 13:27
hi, sorry for the long delay
i just update r2 and checked the behavior of wopO (on a simple example, not on the cmd_wop you linked) and it seems to work fine now
thx!

**Comment by Maijin** [comment] 2016-08-26 18:03
Add more tests if you can!

**Comment by radare** [comment] 2016-08-26 20:55
Yep i fixed this two weeks ago :) and i added 4 or 5 tests already
