### ISSUE TITLE
OSX build failing

### ISSUE THREAD

**Issue by akorchemniy** [radare/radare2#7354] opened 2017-04-25 23:04 UTC
Final report:
 - PREFIX = /Users/dev/bin/prefix/radare2/
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - USE_CAPSTONE = 0
 - HAVE_FORK = 1
 - VERSION = 1.5.0-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - DEBUGGER = 1
 - CC = gcc <-- ???
 - USERCC = gcc
 - USEROSTYPE = darwin
 - LIBVERSION = 1.5.0-git
 - BUILD = x86_64-unknown-darwin
 - HOST = x86_64-unknown-darwin
 - TARGET = x86_64-unknown-darwin
Generating r_version.h file
...
CC PIC array.c
CC PIC fmt.c
CC PIC journal.c
LIB libsdb.so.0.11.1
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libsdb.so.0.11.1] Error 1
make[3]: *** [shared] Error 2
make[2]: *** [all] Error 2
make[1]: *** [sdb_version] Error 2
make: *** [all] Error 2

$ make all
...
make[4]: Entering directory `/Volumes/DevData/development/software/radare2/shlr/sdb/src'
ln -fs libsdb.so.0.11.1 libsdb.so
cc -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -Wno-initializer-overrides -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -shared -Wl,-soname,libsdb.so.0-o libsdb.so.0.11.1 cdb.o.o buffer.o.o cdb_make.o.o ls.o.o sdbht.o.o ht.o.o sdb.o.onum.o.o base64.o.o match.o.o json.o.o ns.o.o lock.o.o util.o.o disk.o.o query.o.o array.o.o fmt.o.o journal.o.o
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libsdb.so.0.11.1] Error 1

**Comment by radare** [comment] 2017-04-26 11:40
are you using sys/install.sh ? osx is the main dev platform, and it builds fine. so the problem is in your side

**Comment by akorchemniy** [comment] 2017-04-26 16:28
Yes this is with sys/install.sh. Same deal with sys/user.sh. Is it expected to work with clang 4.2.1 osx 10.10? 

It's probably a problem with my machine, but figured I'd post my experience since others might be struggling as well. Once I get some free time I'll debug the build scripts and let you know what I find. I got Linux building, but unable to build on msys2, cygwin.

**Comment by Maijin** [comment] 2017-04-26 16:35
Build fine https://travis-ci.org/radare/radare2/builds/226046265

**Comment by radare** [comment] 2017-04-26 16:52
> On 26 Apr 2017, at 18:28, Alexandr Korchemniy <notifications@github.com> wrote:
> 
> Yes this is with sys/install.sh. Same deal with sys/user.sh. Is it expected to work with clang 4.2.1 osx 10.10?
> 

Yes
> It's probably a problem with my machine, but figured I'd post my experience since others might be struggling as well. Once I get some free time I'll debug the build scripts and let you know what I find. I got Linux building, but unable to build on msys2, cygwin.
> 

Please provide build errors . I dont have any windows machine for about 20 years at home so i dont really maintain anything else than the mingw build. When i was maintaining radare for windows i was basically supporting cygwin and mingw, usually fixing all those issues is pretty easy. And now there's a guy focusing in building for msvc.

From your build log error it seems like theres a problem identifying the OS. But my main machine is a 10.10 mac

**Comment by akorchemniy** [comment] 2017-04-26 17:36
Looking at the official Jenkins log it looks like the official Mac build is using export CC=gcc-6. I'll give that a shot.

**Comment by radare** [comment] 2017-04-26 17:39
can you share your full build log of sys/install.sh ?

**Comment by akorchemniy** [comment] 2017-04-26 17:47
I added set -xv to see more details.
[r2-build.txt](https://github.com/radare/radare2/files/959305/r2-build.txt)

**Comment by akorchemniy** [comment] 2017-04-26 18:17
Forced it to use clang. Still not sure where "soname" is coming from.
[manual-config.txt](https://github.com/radare/radare2/files/959360/manual-config.txt)

**Comment by akorchemniy** [comment] 2017-04-26 18:42
shlr/sb/src/Makefile was including shlr/sdb/config.mk which was forcing soname (probably not detecting Darwin correct). Manual patched and got the build to finish.

**Comment by Maijin** [comment] 2017-04-26 19:23
Again, works on OSX with `./sys/install.sh` so must be coming from your side.

Closing here

**Closed by Maijin** 2017-04-26 19:23 UTC
Labels: buildsystem, OS X

**Comment by king6cong** [comment] 2019-03-19 10:23
Maybe related to https://github.com/radare/radare2/pull/13431
