### ISSUE TITLE
Scrolling is very slow if vertical split is enabled in visual mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11815] opened 2018-10-15 08:59 UTC
Just do `r2 /bin/ls; aaa; VpP`, press `|` and write `pd`, then try to scroll back and forth - it is very slow.

**Comment by radare** [comment] 2018-10-15 09:03
i can confirm

**Comment by radare** [comment] 2018-10-15 10:38
Here's the bottleneck :3

<img width="700" alt="screenshot 2018-10-15 at 12 37 15" src="https://user-images.githubusercontent.com/917142/46946150-22e63d00-d077-11e8-9de7-0518bcb9f317.png">
<img width="1025" alt="screenshot 2018-10-15 at 12 37 31" src="https://user-images.githubusercontent.com/917142/46946151-22e63d00-d077-11e8-82cd-b23b651cd0b6.png">

**Comment by radare** [comment] 2018-10-15 10:45
workaround (didnt notice any regression) pls @cyanpencil confirm this change

```diff
pmb:util pancake$ git diff
diff --git a/libr/util/print.c b/libr/util/print.c
index 1644a2584..f744a9474 100644
--- a/libr/util/print.c
+++ b/libr/util/print.c
@@ -720,7 +720,8 @@ R_API void r_print_set_screenbounds(RPrint *p, ut64 addr) {
        }

        (void) p->consbind.get_size (&r);
-       (void) p->consbind.get_cursor (&rc);
+.      rc = r-1;
        if (rc > r - 1 && p->screen_bounds == 1) {
                p->screen_bounds = addr;
```

**Comment by radare** [comment] 2018-10-15 10:54
the reason why its slow is because showing "pd" is disassembling 4KB of code.. and you probably want to do "pd $r"

**Comment by radare** [comment] 2018-10-15 11:07
i dont get why the set_screenbounds() should be taking the cursor position, which should be always inside the console boundaries... but this is because the function name is misleading.

**Comment by ret2libc** [comment] 2018-10-15 12:03
Please let's move this to milestone 3.1. Release is today, the issue was discovered/reported 3 hours ago, so I'd prefer to not rush ANY fix.

**Comment by ret2libc** [comment] 2018-10-15 12:11
> the reason why its slow is because showing "pd" is disassembling 4KB of code.. and you probably want to do "pd $r"

That's right. Do you already have an idea/suggestion about how to fix this?

**Comment by XVilka** [comment] 2018-10-15 12:12
Agree, no rush, it is not so commonly used feature.

**Comment by ret2libc** [comment] 2018-10-31 08:53
@cyanpencil IIRC the cursor may be outside the screen if you enable cursor in one mode (e.g. hex mode) and then you switch to another mode which shows less bytes (e.g. disassemble mode). It could happen that in hexmode you are to the +2000 offset with the cursor and when you switch back to disasm mode (which can only shows at most ~100bytes in the screen), the previous value of the cursor is out of limits, so the screen bounds need to be set again.

What I'm seeing is that when you are in disassembly mode, screen_bounds is always reset to 1 and I don't know why... We could do something like:
```
	
	if (p->screen_bounds == 1) {
                (void) p->consbind.get_size (&r);
	        (void) p->consbind.get_cursor (&rc);

		if (rc > r -1) {
		      p->screen_bounds = addr;
                }
	}
```
but it wouldn't improve the situation in the disassembly case, given that screen_bounds is, apparently, always set to 1 :(

**Comment by radare** [comment] 2018-10-31 11:41
its a pretty slow check, so any improvmenet to reduce its usage is welcome

**Comment by ret2libc** [comment] 2018-10-31 16:55
ok so the main problem is that `r_print_set_screenbounds` is called on every loop iteration when printing instructions in `pd`. This is used because we don't have other better ways to know which instruction is the last one (e.g. comments may be printed in a new line, there may be flags, etc. so it's hard to predict how many disassembly lines there will be in a "screen"). The fact is that `r_cons_get_cursor` is quite slow and on my screen it is called multiple times and each time it iterates over ~240k characters.

I'm not sure how to fix this... the patch I proposed in https://github.com/radare/radare2/issues/11815#issuecomment-434608046 is just a very small improvement but it doesn't resolve the issue. Other ideas?

**Comment by radare** [comment] 2018-11-19 22:36
what's not going to work if we just remove this line? its an important performance issue and i dont see any difference in the interaction

**Comment by ret2libc** [comment] 2018-11-20 08:22
AFAIR the cursor won't work well.

**Comment by ret2libc** [comment] 2018-11-20 10:29
We could... but I'm not that comfortable doing this 4 days before release... :( Especially because this is a problem only in some particular cases and only when you have `hex | disassembly`. The problem indeed is that when you are in `hex` mode, the blocksize is very big and if you do `| pd` the blocksize will be the same as the hex mode, so you end up disassembling a lot of lines... Let me try to play a bit with this thing.

**Comment by ret2libc** [comment] 2018-11-21 09:40
This was improved a bit with https://github.com/radare/radare2/pull/12243 . However, it's not fully fixed. So moving it to 3.2.0. BTW, one possible solution is to stop the disassembly loop once you detect the next lines won't be printed anymore (screen_bounds says exactly this)

**Comment by radare** [comment] 2018-11-21 10:10
thanks

**Comment by radare** [comment] 2019-01-03 12:22
i think this behaviour have improved enough to close this issue, but i would like to remove this completely if possible  because the slow path is still there

**Closed by radare** 2019-01-03 12:22 UTC
Labels: optimization, visual
