### ISSUE TITLE
Add anal.timeout to avoid analyzing for a long time

### ISSUE THREAD

**Issue by radare** [radare/radare2#6070] opened 2016-10-29 11:21 UTC

**Comment by Maijin** [comment] 2016-10-29 11:30
Duplicate of #649

**Comment by radare** [comment] 2016-11-02 11:23
well its not duplicate, is just a way to have a single issue for each issue, and not have one with several checkboxes

**Comment by Maijin** [comment] 2016-11-02 11:25
Well still duplicate, if you search timeout, you find #649 directly :P

**Comment by Maijin** [comment] 2016-11-02 11:25
I can reopen and put in the issue

**Comment by radare** [comment] 2016-11-02 11:26
This issue requires the push/pop rcons.break() thing

**Comment by Maijin** [comment] 2016-11-02 11:26
#5986

**Comment by Maijin** [comment] 2016-11-02 11:27
#5994

**Comment by radare** [comment] 2016-11-02 11:27
rcons{push,pop} != rcons.break{push,pop}

**Comment by Maijin** [comment] 2016-11-02 11:27
There is no issue for this

**Comment by radare** [comment] 2016-12-12 16:50
I think we can implement this inside RCons. checking the time if a timeout is set in is_breaked()

**Closed** 2016-12-12 22:57 UTC
Labels: diaphora, easy
