### ISSUE TITLE
[Windows] Loaded pdb, but symbols are not correct

### ISSUE THREAD

**Issue by Sn00z3r** [radare/radare2#8599] opened 2017-09-27 12:09 UTC
Dear,

Loaded ntdll with radare2:
>> radare2.exe -A ntdll.dll

Loaded pdb file
>> .idp*

But still functions are in the form of fcn....
What am I missing here?

Best regards!

**Comment by XVilka** [comment] 2017-09-28 03:31
Please provide the sample file[s]. Are you sure the PDB is of the right version?

**Comment by XVilka** [comment] 2017-10-02 14:08
@Sn00z3r PING!

**Comment by Maijin** [comment] 2017-10-02 20:25
.idp* is now idp and should be typed before analysis. Remove -A, do idp then do `aaa`

Without the files we can't reproduce therefore I'm closing until this can be reproduced and file provided.

**Closed by Maijin** 2017-10-02 20:25 UTC
Labels: debug-info
