### ISSUE TITLE
Incorrect jump taken

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4430] opened 2016-03-25 21:16 UTC
Seems like the actual run takes the `true` path, but ESIL emulation seems to
take the `false` branch. Not much information is available to check what
instruction set zf. I'll continue to dig into this later.

If someone has the ubuntu 14.04 binary, please do post it here.
I'll add in more cases in comments to get more examples.

Binary: Ubuntu 14.04 /bin/ls
Instruction: je 0x402fcb
ESIL: zf,?{,4206539,rip,=,}
Offset: 0x402962

| REGISTER | GDB | ESIL |
| --- | --- | --- |
| rip | 0x402962 -> 0x402fcb | 0x402962 -> 0x402968 |

**Comment by sushant94** [comment] 2016-03-25 21:17
__MORE__

Binary: Ubuntu 14.04 /bin/ls
Instruction: je 0x4031b4
ESIL: zf,?{,4207028,rip,=,}
Offset: 0x4031a8

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rip     | 0x4031a8 -> 0x4031b4                  | 0x4031a8 -> 0x4031aa                  |

**Comment by sushant94** [comment] 2016-03-25 21:18
__MORE__

Binary: Ubuntu 14.04 /bin/ls
Instruction: je 0x4032b8
ESIL: zf,?{,4207288,rip,=,}
Offset: 0x4031f7

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rip     | 0x4031f7 -> 0x4032b8                  | 0x4031f7 -> 0x4031fd                  |

**Comment by sushant94** [comment] 2016-03-25 21:19
__MORE__

Binary: Ubuntu 14.04 /bin/ls
Instruction: je 0x40769a
ESIL: zf,?{,4224666,rip,=,}
Offset: 0x407bf7

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rip     | 0x407bf7 -> 0x40769a                  | 0x407bf7 -> 0x407bfd                  |

**Comment by sushant94** [comment] 2016-03-25 21:33
`jne`

Binary: Ubuntu 14.04 /bin/ls
Instruction: jne 0x410a20
ESIL: zf,!,?{,4262432,rip,=,}
Offset: 0x410a2f

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rip     | 0x410a2f -> 0x410a31                  | 0x410a2f -> 0x410a20                  |

**Comment by sushant94** [comment] 2016-03-25 21:38
__MORE__

Binary: Ubuntu 14.04 /bin/ls
Instruction: jg 0x40d0a0
ESIL: sf,of,!,^,zf,!,&,?{,4247712,rip,=,}
Offset: 0x40d0ca

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rip     | 0x40d0ca -> 0x40d0cc                  | 0x40d0ca -> 0x40d0a0                  |

**Comment by crowell** [comment] 2016-03-25 21:45
Prev instrs here would be helpful. I'd guess it's due to a memory read

**Comment by radare** [comment] 2016-03-26 20:22
branch not taken?

On 25 March 2016 at 22:38, Sushant Dinesh <notifications@github.com> wrote:

> *MORE*
>
> Binary: Ubuntu 14.04 /bin/ls
> Instruction: jg 0x40d0a0
> ESIL: sf,of,!,^,zf,!,&,?{,4247712,rip,=,}
> Offset: 0x40d0ca
> REGISTER GDB ESIL
> rip 0x40d0ca -> 0x40d0cc 0x40d0ca -> 0x40d0a0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4430#issuecomment-201524171>
>



-- 
--pancake

**Comment by radare** [comment] 2016-06-28 23:07
ping. can we have prev instructions here?

**Comment by Maijin** [comment] 2016-06-29 08:02
^ See this @condret

**Comment by radare** [comment] 2016-08-15 23:03
ping anyone is still alive?

**Comment by Svenito** [comment] 2016-11-23 12:25
Reproducable with

```
[0x00000000]> wa test rdx, rdx
Written 3 bytes (test rdx, rdx) = wx 4885d2
[0x00000000]> aer?rdx
0x00000000
[0x00000000]> aer?zf
0x00000000
[0x00000000]> aes
[0x00000000]> aer?zf
0x00000001
[0x00000000]> wa je 0x4444
Written 6 bytes (je 0x4444) = wx 0f843e440000
[0x00000000]> aer?zf
0x00000001
[0x00000000]> ao
address: 0x0
opcode: je 0x4444
prefix: 0
id: 259
bytes: 0f843e440000
refptr: 0
size: 6
type: cjmp
esil: zf,?{,17476,rip,=,}
jump: 0x00004444
fail: 0x00000006
stack: null
cond: eq
family: cpu
[0x00000000]> aer?zf
0x00000001
[0x00000000]> aes
[0x00000000]> aer?rip
0x00000006
```

BUT

```
[0x00000000]> wa je 0x4444
Written 6 bytes (je 0x4444) = wx 0f843e440000
[0x00000000]> ao
address: 0x0
opcode: je 0x4444
prefix: 0
id: 259
bytes: 0f843e440000
refptr: 0
size: 6
type: cjmp
esil: zf,?{,17476,rip,=,}
jump: 0x00004444
fail: 0x00000006
stack: null
cond: eq
family: cpu
[0x00000000]> aer?zf
0x00000000
[0x00000000]> aer zf=1
[0x00000000]> aes
[0x00004444]> aer?rip
0x00004444
```

**Comment by Svenito** [comment] 2016-11-23 21:53
Adding Ubuntu 14.04.5 x64 ls file. Closest I can get to 14.04
[ls.zip](https://github.com/radare/radare2/files/610082/ls.zip)

**Comment by Svenito** [comment] 2016-11-23 22:22
Unable to reproduce. All the jumps seem to follow expected behaviour. Closing until further notice

**Closed by Svenito** 2016-11-23 22:22 UTC
Labels: esil, x86
