### ISSUE TITLE
can not step over using F8 in visual mode and some others...

### ISSUE THREAD

**Issue by naijim** [radare/radare2#1934] opened 2015-01-03 20:35 UTC
It looks like the debugger is not so stable... I encountered some odd problems. I debug program over ssh connection. The program runs in a virtual machine which managed by vagrant. I am not sure if I understand it right. The `do` command is equivalent to the `run` of gdb? I got this:

```
○ → r2 -d a.out
Process with PID 9520 started...
PID = 9520
pid = 9520 tid = 9520
r_debug_select: 9520 9520
Using BADDR 400000
bits 64
pid = 9520 tid = 9520
 -- -bash: r2: command not found
[0x7f0a8a5d4dc0]> do
Wait event received by different pid 9520
Process with PID 9521 started...
PID = 9521
File dbg://./a.out reopened in read-write mode
r_debug_select: 9521 9521
p/debug_native.c:410 ptrace_setoptions: No such process
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
[0x7f0a8a5d4dc0]> pd 20@sym.main
           ;-- sym.main:
           0x00400506    0000         add byte [rax], al
           0x00400508    0000         add byte [rax], al
           0x0040050a    0000         add byte [rax], al
           0x0040050c    0000         add byte [rax], al
           0x0040050e    0000         add byte [rax], al
           0x00400510    0000         add byte [rax], al
           0x00400512    0000         add byte [rax], al
           0x00400514    0000         add byte [rax], al
           0x00400516    0000         add byte [rax], al
           0x00400518    66           add byte [rax], al
           0x00400519    07           add byte [rax], al
           0x0040051a    0000         add byte [rax], al
           0x0040051c    1200         adc al, byte [rax]
           0x0040051e    0000         add byte [rax], al
           0x00400520    0000         add byte [rax], al
           0x00400522    0000         add byte [rax], al
           0x00400524    0000         add byte [rax], al
           0x00400526    0000         add byte [rax], al
           0x00400528    0000         add byte [rax], al
           0x0040052a    0000         add byte [rax], al
[0x7f0a8a5d4dc0]> dc
sys.c:480 ptrace-traceme: Operation not permitted
r_debug_reg: error reading registers
r_debug_select: 9521 1
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
[0x7f4c46c9f70f]> pd 20@sym.main
           ;-- sym.main:
           0x00400506    ff
           0x00400507    ff
           0x00400508    ff
           0x00400509    ff
           0x0040050a    ff
           0x0040050b    ff
           0x0040050c    ff
           0x0040050d    ff
           0x0040050e    ff
           0x0040050f    ff
           0x00400510    ff
           0x00400511    ff
           0x00400512    ff
           0x00400513    ff
           0x00400514    ff
           0x00400515    ff
           0x00400516    ff
           0x00400517    ff
           0x00400518    ff
           0x00400519    ff
r_debug_reg: error reading registers
```
And for visual mode:
```
○ → r2 -d a.out
Process with PID 9636 started...
PID = 9636
pid = 9636 tid = 9636
r_debug_select: 9636 9636
Using BADDR 400000
bits 64
pid = 9636 tid = 9636
 -- rax2 -s 20e296b20ae296b220e296b20a
[0x7fa8de913dc0]> pd 20@sym.main
           ;-- sym.main:
           0x00400506    55           push rbp
           0x00400507    4889e5       mov rbp, rsp
           0x0040050a    4883ec10     sub rsp, 0x10
           0x0040050e    c745fc01000. mov dword [rbp - 4], 1
           0x00400515    8345fc01     add dword [rbp - 4], 1
           0x00400519    bfd4054000   mov edi, 0x4005d4
           0x0040051e    b800000000   mov eax, 0
           0x00400523    e8b8feffff   call sym.imp.printf
              0x004003e0(unk) ; sym.imp.printf
           0x00400528    c745f801000. mov dword [rbp - 8], 1
           0x0040052f    8345f801     add dword [rbp - 8], 1
           0x00400533    bfd8054000   mov edi, 0x4005d8
           0x00400538    b800000000   mov eax, 0
           0x0040053d    e89efeffff   call sym.imp.printf
              0x004003e0() ; sym.imp.printf
           0x00400542    b800000000   mov eax, 0
           0x00400547    c9           leave
           0x00400548    c3           ret
           0x00400549    0f1f8000000. nop dword [rax]
           ;-- sym.__libc_csu_init:
           0x00400550    4157         push r15
           0x00400552    4156         push r14
           0x00400554    4189ff       mov r15d, edi
[0x7fa8de913dc0]> db 0x00400519
[0x7fa8de913dc0]> db
0x00400519 - 0x0040051a 1 --x sw break enabled cmd=""
[0x7fa8de913dc0]> dc
hit breakpoint at: 400519
r_debug_select: 9636 1
[0x00400519]> V

...[snip]... ; hit F7 2 times to reach this...

[0x00400519 195 ./a.out]> f tmp;sr s.. @ main+19 # 0x400519
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7fff8c3c6410  0065 3c8c ff7f 0000 0000 0000 0200 0000  .e<.............
0x7fff8c3c6420  5005 4000 0000 0000 4000 59de a87f 0000  P.@.....@.Y.....
0x7fff8c3c6430  0865 3c8c ff7f 0000 0865 3c8c ff7f 0000  .e<......e<.....
0x7fff8c3c6440  0000 0000 0100 0000 0605 4000 0000 0000  ..........@.....
 r15 0x00000000         r14 0x00000000         r13 0x7fff8c3c6500
 r12 0x00400410         rbp 0x7fff8c3c6420     rbx 0x00000000
 r11 0x7fa8de58ff50     r10 0x00000831          r9 0x7fa8de922660
  r8 0x7fa8de90ee90     rax 0x00000000         rcx 0x00000000
 rdx 0x7fff8c3c6518     rsi 0x7fff8c3c6508     rdi 0x004005d4
orax 0xffffffffffffffff rip 0x00400523         rflags = 1I
 rsp 0x7fff8c3c6410
           0x00400519 b  bfd4054000   mov edi, 0x4005d4 ; "123" @ 0x4005d4
           0x0040051e    b800000000   mov eax, 0
           ;-- rip:
           0x00400523    e8b8feffff   call sym.imp.printf ;[1]
              0x004003e0() ; sym.imp.printf
           0x00400528    c745f801000. mov dword [rbp - 8], 1
           0x0040052f    8345f801     add dword [rbp - 8], 1
           0x00400533    bfd8054000   mov edi, 0x4005d8
           0x00400538    b800000000   mov eax, 0
           0x0040053d    e89efeffff   call sym.imp.printf ;[1]
              0x004003e0() ; sym.imp.printf
           0x00400542    b800000000   mov eax, 0
           0x00400547    c9           leave
           0x00400548    c3           ret
           0x00400549    0f1f8000000. nop dword [rax]
           ;-- sym.__libc_csu_init:
           0x00400550    4157         push r15 ; orax
           0x00400552    4156         push r14 ; orax
           0x00400554    4189ff       mov r15d, edi
           0x00400557    4155         push r13 ; orax
           0x00400559    4154         push r12 ; orax
           0x0040055b    4c8d25a6012. lea r12, qword [rip + 0x2001a6]
           0x00400562    55           push rbp ; orax
           0x00400563    488d2da6012. lea rbp, qword [rip + 0x2001a6]
           0x0040056a    53           push rbx ; orax
           0x0040056b    4989f6       mov r14, rsi
```
Now I want to step over the `call`. Hit F8.
```
[0x7fb4972359e9 195 ./a.out]> f tmp;sr s.. @ r11+621209 # 0x7fb4972359e9
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  0123456789ABCD
0x7fffbe0c6bc8  ffff ffff ffff ffff ffff ffff ffff  ..............
0x7fffbe0c6bd6  ffff ffff ffff ffff ffff ffff ffff  ..............
0x7fffbe0c6be4  ffff ffff ffff ffff ffff ffff ffff  ..............
0x7fffbe0c6bf2  ffff ffff ffff ffff ffff ffff ffff  ..............
0x7fffbe0c6c00  ffff ffff ffff ffff                 ........
           0x7fb4972359e9    ff
           0x7fb4972359ea    ff
           0x7fb4972359eb    ff
           0x7fb4972359ec    ff
           0x7fb4972359ed    ff
           0x7fb4972359ee    ff
           0x7fb4972359ef    ff
           0x7fb4972359f0    ff
           0x7fb4972359f1    ff
           0x7fb4972359f2    ff
           0x7fb4972359f3    ff
           0x7fb4972359f4    ff
           0x7fb4972359f5    ff
           0x7fb4972359f6    ff
           0x7fb4972359f7    ff
           0x7fb4972359f8    ff
           0x7fb4972359f9    ff
           0x7fb4972359fa    ff
           0x7fb4972359fb    ff
           0x7fb4972359fc    ff
           0x7fb4972359fd    ff
           0x7fb4972359fe    ff
           0x7fb4972359ff    ff
           0x7fb497235a00    ff
           0x7fb497235a01    ff
           0x7fb497235a02    ff
           0x7fb497235a03    ff                                                                                                                                                                 0x7fb497235a04    ff
           0x7fb497235a05    ff
           0x7fb497235a06    ff
           0x7fb497235a07    ff
           0x7fb497235a08    ff
```
I think `step over` should mean `proceeds to the next line in your current scope (i.e. it goes to the next line), without descending into any method calls on the way`. So I should reach the next line of `call`...

If I am wrong pls forgive me. I am just a newbie trying to make this tool better. :)

**Comment by Maijin** [comment] 2015-01-03 21:48
For dc and do If you look in the help `d?` `dc?`

    | dc                   Continue execution of all children
    ...
    | do            Open process (reload, alias for 'oo')

For the step over it should indeed goes to the next line without descending into any method calls on the way. Maybe you could share the binary + more infos on your build (arch,os?)

**Comment by naijim** [comment] 2015-01-03 22:14
Maybe I use r2 wrong. But I have tried visual mode many times... Always the same.
I am running Archlinux x64 and r2 0.9.8.
The source code:
```
#include <stdio.h>

int main()
{
  int a = 1;
  a++;
  printf("123");
  int b = 1;
  b++;
  printf("456");
  return 0;
}
```
The binary: https://mega.co.nz/#!58QEjKoC!0kbbgul81jYXSeO4_OYptxefABb7dyR6kTmI1IuuG14

**Comment by Maijin** [comment] 2015-01-03 22:34
Seems to work for me http://radare.tv/a/75

**Comment by crowell** [comment] 2015-01-04 00:30
ugh... mega.co.nz

On Sat, Jan 3, 2015 at 5:34 PM, Maijin <notifications@github.com> wrote:

> Seems to work for me http://radare.tv/a/75
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/1934#issuecomment-68612329>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by crowell** [comment] 2015-01-04 00:38
works fine for me too. can not repro

**Comment by radare** [comment] 2015-01-04 02:09
i would recommend you to pass the proper execution path to avoid confussions:

  r2 -d ./a.out

also, when starting to debug in r2 you always get a running instance of the target process, so it’s
already opened, and the debugger stops as soon as possible, which is in ld.so usually. if you
want to jump to the program code type:

  dcu entry0

**Comment by naijim** [comment] 2015-01-04 08:49
https://asciinema.org/a/15165
I just recorded the session. Thanks for the website, really cool, I like it.:)
When r2 highlighted `0x00400523`, I pressed F8. Was that right?

**Comment by radare** [comment] 2015-01-04 12:07
Can you try setting a breakpoint after the call and then tun continue? When this happens is usually because the function doesnt returns (calls exit or crashes)

**Comment by naijim** [comment] 2015-01-04 12:34
I can not record the session. 
I set 2 breakpoints.
```
db main
db 0x00400533 ; an instruction behind the first `call`
```
And again hit F8 when r2 highlighted the first `call`.
Then r2 prompted infinite 'hit breakpoint at: 400533' and I can not kill the process using ctrl-c. So I can not record the session.

**Comment by naijim** [comment] 2015-01-05 18:06
If you guys would like to debug, I can publish the vagrant box(1.82 GB).

**Comment by radare** [comment] 2015-01-12 13:33
if you step over main it will fall in exitland. so its expected behaviour

**Comment by radare** [comment] 2015-01-12 13:35
Well, that asciinema shows that the breakpoint handling doesnt works fine with step over, so it's a bug. Thanks for reporting, Will take care of it

**Comment by radare** [comment] 2015-01-13 13:41
Should be fixed now in git.

**Closed by radare** 2015-01-13 13:41 UTC
