### ISSUE TITLE
Radare2 segfault in cygwin

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2249] opened 2015-03-26 17:57 UTC
```
 ~/radare/radare2/radare2-w32-0.9.9-git
$ ./radare2.exe /bin/ls
Segmentation fault (core dumped)

 ~/radare/radare2/radare2-w32-0.9.9-git
$ gdb radare2.exe
GNU gdb (GDB) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from radare2.exe...done.
(gdb) run /bin/ls
Starting program: /cygdrive/d/Work/radare/radare2/radare2-w32-0.9.9-git/radare2.exe /bin/ls
[New Thread 15072.0x25ec]
[New Thread 15072.0x42a0]
[New Thread 15072.0x41e8]
[New Thread 15072.0x1be4]
      0 [main] radare2 15072 cygwin_exception::open_stackdumpfile: Dumping stack trace to radare2.exe.stackdump
[Thread 15072.0x42a0 exited with code 35584]
[Thread 15072.0x41e8 exited with code 35584]
[Inferior 1 (process 15072) exited with code 0105400]
(gdb)
```

**Comment by XVilka** [comment] 2015-03-26 17:59
```
 Exception: STATUS_ACCESS_VIOLATION at rip=001801784C6^M
  2 rax=0000000000000000 rbx=3838323636413340 rcx=8080808080808080^M
  3 rdx=000000000022BE88 rsi=FEFEFEFEFEFEFEFF rdi=000000000022BFA0^M
  4 r8 =000000000000001A r9 =0000000000010300 r10=3939333737423441^M
  5 r11=0000000000000008 r12=0000000000000001 r13=0000000000000000^M
  6 r14=0000000000000000 r15=000000000022CB80^M
  7 rbp=000000000022BEE0 rsp=000000000022BE48^M
  8 program=D:\Work\radare\radare2\radare2-w32-0.9.9-git\radare2.exe, pid 15072, thread main^M
  9 cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B^M
 10 Stack trace:^M
 11 Frame        Function    Args^M
 12 0000022BEE0  001801784C6 (0000022BE80, 00000000040, 00000000000, 3939333737423441)^M
 13 0000022BEE0  004E3FF4E22 (00400000003, 00600107430, 004E403D6D0, 00600123B30)^M
 14 0000022C020  004E3FB2353 (00600104030, 00000000000, 006000FD9C0, 0000022C090)^M
 15 0000022C0B0  004E3FB3D74 (00600075680, 00000000000, 00000000000, 00000000000)^M
 16 0000022C130  004E3FB4358 (0060009BAC0, 006000C4D60, 0000001C61D, 0000001C61D)^M
 17 0000022C200  004E3FB3052 (0060009BA70, 00000000000, 00000000000, 00600000000)^M
 18 0000022C260  004E3FB310D (0060009BA70, 00000000000, 00000000000, 00000000000)^M
 19 0000022C2B0  004E3FB2B61 (0060009BA70, 00000000000, 00000000000, 00600000000)^M
 20 0000022C340  005BE6E6F4D (00000000000, 00000000000, 005BE6E7F11, 0060008DA40)^M
 21 0000022C3D0  005BE6E7327 (0060009BAC0, 00000000000, 00000000000, 0000022C660)^M
 22 0000022C460  00100402AB5 (0000022CB20, 006000281A0, 001800484E0, 00000000000)^M
 23 0000022CBD0  00180048551 (15000000340230, 00300000015, 00000000070, 00000000000)^M
 24 00000000000  001800463EC (39003200320031, 00E00000030, 0000034026C, 00067474D7F)^M
 25 00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)^M
 26 00000000000  00100403B01 (00000000000, 00000000000, 00000000000, 00000000000)^M
 27 00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)^M
 28 End of stack trace (more stack frames may be present)
```

**Comment by radare** [comment] 2015-03-27 12:45
can you reproduce the same issue with mingw32?

**Comment by XVilka** [comment] 2015-03-27 12:47
@radare nope, mingw works smoothly, I'm trying to figure how-to debug programs under the cygwin.

**Comment by radare** [comment] 2015-03-27 13:06
Good luck :) cygwin is a huge fuckup

**Comment by radare** [comment] 2015-03-27 14:28
Can you check if was working fine in 1465cdca2a2b68c42e363475ee416b52dc31da47

this is before the rbininfo change. this should be easy to fix by just closing coverity issues related to “null deref"

**Comment by crowell** [comment] 2015-03-27 14:46
you can install gdb in cygwin, I used to use it in another life.

On Fri, Mar 27, 2015 at 8:48 AM, Anton Kochkov <notifications@github.com>
wrote:

> @radare <https://github.com/radare> nope, mingw works smoothly, I'm
> trying to figure how-to debug programs under the cygwin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2249#issuecomment-86930754>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment] 2015-04-03 02:14
still there?

**Comment by crowell** [comment] 2015-04-15 00:40
seems fixed

**Closed by crowell** 2015-04-15 00:40 UTC
Labels: blocker, regression

**Comment by laclen** [comment] 2021-11-25 21:58
Can you explain how did you solve this issue because I get the same error when I try to debug with gdb

**Comment by trufae** [comment] 2022-02-26 13:29
Not sure if related to this specific issue, but usually the problem trying to debug windows binaries with cygwin executables and viceversa, or even using mingw is related to wrong function signatures or wrong calling convention definitions, which end up causing random segfaults with useless and corrupted backtraces. the only decent way to debug on windows is using printfs here and there in my experience
