### ISSUE TITLE
Radiff2 example doesn't work right

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#13171] opened 2019-02-22 04:32 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0 1 @ linux-x86-64 git.3.3.0 commit: 460d55ea83d00d8c4b5b1d13620ae05236b76323 build: 2019-02-22__04:02:57

### Expected behavior
See xdot visualization

### Actual behavior
Error:

```
radiff2 -g main ./ls ./ls.diff | xdot -
(locked: no new keys can be created (anal.split))
(locked: no new keys can be created (anal.split))
Traceback (most recent call last):
  File "/usr/bin/xdot", line 4, in <module>
    main()
  File "/usr/lib/python3/dist-packages/xdot/__main__.py", line 75, in main
    win.set_dotcode(sys.stdin.read())
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 597, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 141, in set_dotcode
    if self._set_dotcode(dotcode, filename):
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 127, in _set_dotcode
    assert isinstance(dotcode, bytes)
AssertionError
```

### Steps to reproduce the behavior 
Just try making a change in a binary and running the command documented here:

http://radare.today/posts/binary-diffing/

I.e.: `radiff2 -g main /bin/true /bin/false | xdot - `

### Additional Logs, screenshots, source-code,  configuration dump, ...
The issue appears to be the code that ends up at the top of the output. If you dump the output to file, then manually remove all code before `digraph code`, the xdot will run.

**Comment by kellyj4** [comment] 2019-03-01 22:09
Hello XVilka,
    I am happy to look at this issue.  Could you assign me the issue.

**Comment by Maijin** [comment] 2019-03-02 04:18
We can't assign you on github but go ahead

**Comment by kellyj4** [comment] 2019-03-02 12:27
@bannsec This looks like an xdot issue?  I had the same issue on xdot version 0.9.4 but applied the patch from this page [https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/Eoa_S114XWo] and now I am able to display the dot graph without the assert error.  It sounds like this is fixed in xdot 1.0 onwards?

**Comment by alfasi** [comment] 2019-03-09 19:35
@kellyj4 Can confirm, was able to reproduce in 0.9. The issue was gone in 1.0
Unfortunately the package repo i was using only had 0.9 as the latest version (arch https://www.archlinux.org/packages/community/any/xdot/).

**Comment by Maijin** [comment] 2019-03-10 04:52
thanks for checking @kellyj4 @alfasi I will now close the issue on our side.

**Closed by Maijin** 2019-03-10 04:52 UTC
Labels: good first issue, radiff2
