### ISSUE TITLE
Using the debugger with arm. Did not update the cpsr register

### ISSUE THREAD

**Issue by mandl** [radare/radare2#2086] opened 2015-02-13 14:10 UTC
starting:

r2 -a arm -b32 -D gdb gdb://localhost:1234

doing some debug ....

cpsr stays at  0x0000000

"r_reg_get_value: 32bit oob read 172" should be the problem

r15 = 0x080000cc
cpsr = 0x00000000
r_reg_get_value: 32bit oob read 172
r_reg_get_value: 32bit oob read 172
[0x080000b0]>

**Comment by jjdredd** [comment] 2015-02-13 14:35
messed up bitness?

**Comment by radare** [comment] 2015-02-13 15:00
Looks like the register profile is wrong, i know this was working fine a
while ago because i tested it against a raspberry pi.

Will try to fix it, by maybe @xvilka or @defragger can have a look at
this issue too.

thanks for reporting

**Comment by mandl** [comment] 2015-02-15 11:24
yes - 
a short look in  /radare2/libr/debug/p/debug_gdb.c:
************************************************************************
case R_SYS_ARCH_ARM:
		if (dbg->bits == R_SYS_BITS_32) {
			return strdup (
.......
"gpr	cpsr	.32	172	0\n"
**********************************************************************
the offset is 172

look in /radare2/libr/reg/value.c
*************************************************************************************


		if (off+4<=regset->arena->size) {
			r_mem_copyendian ((ut8*)&v32, (ut8*)regset->arena->bytes+off, 4, !reg->big_endian);
			ret = v32;
		} else eprintf ("r_reg_get_value: 32bit oob read %d\n", off);
****************************************************************
so i think the arena->size is wrong in this case....
But i have not enough inside -  providing a patch here....

**Comment by XVilka** [comment] 2015-02-16 00:49
Looks like size of the register profile can be different for the various modifications of arms. May be we need something like cpu.features but not only for disasm but also for the debugger.

**Comment by XVilka** [comment] 2015-11-18 06:04
@radare  `r_reg_get_value: 32bit oob read 172` and regarena size is 168. It is strange, because in libr/debug/p/debug_gdb.c:379 there is a declaration of the `cpsr` register at the offset of 172. Why regarena size is 168 then? Speaking about ARM 32bit

**Comment by radare** [comment] 2015-11-18 10:46
I have refactored the drp code and now you have the new drps command to show the reg profile and.. ocasionally you can fake it by passing a numeric argument. This will ease the debugging. About arm32 gdb profile the size is 172, not 168. at least with latest code in git. can you confirm?

**Comment by XVilka** [comment] 2015-11-18 10:49
@radare I can't check right now, this doesn't work at cygwin at all.
I'm using my version of qemu - https://github.com/XVilka/qemu
Then I run "run_qemu.sh", then "connect_r2.sh" from https://github.com/XVilka/hacklu/tree/master/demos/Firmware/demo1_arm_boot

(In case you'll want to reproduce it by yourself, or wait until evening).

**Comment by radare** [comment] 2015-11-18 18:18
I dont have time for checking this stuff now, and its not a priority for me. thanks for sharing this stuff, maybe it will be good to write a blog post or put them in the radare2-extras repo for keeping them.

**Comment by XVilka** [comment] 2015-11-18 22:09
Added some insane debug:
Note two things - arena->size was a write value 176 at first place, then after syncronizing registers it's dropped down to the 168. The 2nd thing that for the `pc` and `lr` registers offsets are too big - 480 and 448 respectively, which is obviously wrong.
```
r_reg_fit_arena(): arena->size 76
r_reg_fit_arena()
processing lr reg, size 60, newsize 60
processing pc reg, size 64, newsize 64
processing r0 reg, size 4, newsize 64
processing r1 reg, size 8, newsize 64
processing r2 reg, size 12, newsize 64
processing r3 reg, size 16, newsize 64
processing r4 reg, size 20, newsize 64
processing r5 reg, size 24, newsize 64
processing r6 reg, size 28, newsize 64
processing r7 reg, size 32, newsize 64
processing r8 reg, size 36, newsize 64
processing r9 reg, size 40, newsize 64
processing r10 reg, size 44, newsize 64
processing r11 reg, size 48, newsize 64
processing r12 reg, size 52, newsize 64
processing r13 reg, size 56, newsize 64
processing r14 reg, size 60, newsize 64
processing r15 reg, size 64, newsize 64
processing f0 reg, size 76, newsize 76
processing f1 reg, size 88, newsize 88
processing f2 reg, size 100, newsize 100
processing f3 reg, size 112, newsize 112
processing f4 reg, size 124, newsize 124
processing f5 reg, size 136, newsize 136
processing f6 reg, size 148, newsize 148
processing f7 reg, size 160, newsize 160
processing fps reg, size 172, newsize 172
processing cpsr reg, size 176, newsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
newsize 0 < oldsize 176
r_reg_fit_arena(): arena->size 176
Debugging pid = 7, tid = 7 now
Attached debugger to pid = 96822672, tid = 1
Debugging pid = 96822672, tid = 1 now
send_command(): before: ret 5
send_command(): after: ret 5
before parsing
after parsing
0x0000000000000000: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000010: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000020: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000030: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000040: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000050: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000060: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000070: 30 30 30 30 30 30 30 30 30 30 34 30 30 31 34 30 - 0000000000400140
0x0000000000000080: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000090: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000a0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000b0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000c0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000d0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000e0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x00000000000000f0: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000100: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000110: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000120: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000130: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 - 0000000000000000
0x0000000000000140: 30 30 30 30 30 30 30 30 64 33 30 31 30 30 34 30 - 00000000d3010040
0x0000000000000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 40 01 40 - .............@.@
0x0000000000000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x0000000000000090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0x00000000000000a0: 00 00 00 00 d3 01 00 40                         - .......@
r_debug_gdb_reg_read(): type 0 size 176, data_len 168
r_debug_gdb_reg_read(): copy_size 168 ; buflen 176; data_len 168

0x00000000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000030  00 00 00 00 00 00 00 00 00 00 00 00 00 40 01 40 
0x00000040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x00000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x000000a0  00 00 00 00 d3 01 00 40 
r_debug_gdb_reg_read(): data_len 168
r_debug_reg_sync(): size 168, bufsize 176
r_reg_get_list(): processing reg lr
GET sz=32 off 56  off = 448 56
regset->arena->size = 168
GET sz=32 off 56  off = 448 56
regset->arena->size = 168
r_reg_get_list(): processing reg pc
GET sz=32 off 60  off = 480 60
regset->arena->size = 168
GET sz=32 off 60  off = 480 60
regset->arena->size = 168
r_reg_get_list(): processing reg r0
GET sz=32 off 0  off = 0 0
regset->arena->size = 168
GET sz=32 off 0  off = 0 0
regset->arena->size = 168
r_reg_get_list(): processing reg r1
GET sz=32 off 4  off = 32 4
regset->arena->size = 168
GET sz=32 off 4  off = 32 4
regset->arena->size = 168
r_reg_get_list(): processing reg r2
GET sz=32 off 8  off = 64 8
regset->arena->size = 168
GET sz=32 off 8  off = 64 8
regset->arena->size = 168
r_reg_get_list(): processing reg r3
GET sz=32 off 12  off = 96 12
regset->arena->size = 168
GET sz=32 off 12  off = 96 12
regset->arena->size = 168
r_reg_get_list(): processing reg r4
GET sz=32 off 16  off = 128 16
regset->arena->size = 168
GET sz=32 off 16  off = 128 16
regset->arena->size = 168
r_reg_get_list(): processing reg r5
GET sz=32 off 20  off = 160 20
regset->arena->size = 168
GET sz=32 off 20  off = 160 20
regset->arena->size = 168
r_reg_get_list(): processing reg r6
GET sz=32 off 24  off = 192 24
regset->arena->size = 168
GET sz=32 off 24  off = 192 24
regset->arena->size = 168
r_reg_get_list(): processing reg r7
GET sz=32 off 28  off = 224 28
regset->arena->size = 168
GET sz=32 off 28  off = 224 28
regset->arena->size = 168
r_reg_get_list(): processing reg r8
GET sz=32 off 32  off = 256 32
regset->arena->size = 168
GET sz=32 off 32  off = 256 32
regset->arena->size = 168
r_reg_get_list(): processing reg r9
GET sz=32 off 36  off = 288 36
regset->arena->size = 168
GET sz=32 off 36  off = 288 36
regset->arena->size = 168
r_reg_get_list(): processing reg r10
GET sz=32 off 40  off = 320 40
regset->arena->size = 168
GET sz=32 off 40  off = 320 40
regset->arena->size = 168
r_reg_get_list(): processing reg r11
GET sz=32 off 44  off = 352 44
regset->arena->size = 168
GET sz=32 off 44  off = 352 44
regset->arena->size = 168
r_reg_get_list(): processing reg r12
GET sz=32 off 48  off = 384 48
regset->arena->size = 168
GET sz=32 off 48  off = 384 48
regset->arena->size = 168
r_reg_get_list(): processing reg r13
GET sz=32 off 52  off = 416 52
regset->arena->size = 168
GET sz=32 off 52  off = 416 52
regset->arena->size = 168
r_reg_get_list(): processing reg r14
GET sz=32 off 56  off = 448 56
regset->arena->size = 168
GET sz=32 off 56  off = 448 56
regset->arena->size = 168
r_reg_get_list(): processing reg r15
GET sz=32 off 60  off = 480 60
regset->arena->size = 168
GET sz=32 off 60  off = 480 60
regset->arena->size = 168
r_reg_get_list(): processing reg cpsr
GET sz=32 off 172  off = 1376 172
regset->arena->size = 168
r_reg_get_value: 32bit oob read 172
GET sz=32 off 172  off = 1376 172
regset->arena->size = 168
r_reg_get_value: 32bit oob read 172
send_command(): before: ret 5
send_command(): after: ret 5
before parsing
```

**Comment by Maijin** [comment] 2016-04-28 11:41
Duplicate of #518

**Comment by radare** [comment] 2017-03-10 17:23
this is no longer an issue, at least from my tests

**Comment by radare** [comment] 2017-03-10 17:24
i dont think #518 is exactly a dupe

**Closed by radare** 2017-03-10 17:23 UTC
Labels: bug, wrkshp
