### ISSUE TITLE
Search command broke disasm avr code

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3664] opened 2015-11-05 17:31 UTC
I try find addresses for command "in" but after search is finished disasm code print with errors
```
$ r2 -a avr ~/radare2-regressions/bins/firmware/arduino_avr.bin 
[0x00000000]> pd 15
        ,=< 0x00000000    0c94ac00       jmp 0x158
       ,==< 0x00000004    0c94db00       jmp 0x1b6
      ,===< 0x00000008    0c94db00       jmp 0x1b6
     ,====< 0x0000000c    0c94db00       jmp 0x1b6
    ,=====< 0x00000010    0c94db00       jmp 0x1b6
   ,======< 0x00000014    0c94db00       jmp 0x1b6
  ,=======< 0x00000018    0c94db00       jmp 0x1b6
  ========< 0x0000001c    0c94db00       jmp 0x1b6
  ========< 0x00000020    0c94db00       jmp 0x1b6
  ========< 0x00000024    0c94db00       jmp 0x1b6
  ========< 0x00000028    0c94db00       jmp 0x1b6
  ========< 0x0000002c    0c94db00       jmp 0x1b6
  ========< 0x00000030    0c94db00       jmp 0x1b6
  ========< 0x00000034    0c94db00       jmp 0x1b6
  |||||||   0x00000038    0c94db00       jmp 0x1b6
[0x00000000]> /c in
...
0x00000167   # 2: in r30, 0x00
0x0000016d   # 2: invalid
0x00000179   # 2: in r19, 0x02
0x00000181   # 2: in r14, 0x12
0x00000189   # 2: in r3, 0x18
0x00000193   # 2: invalid
0x0000019b   # 2: invalid
0x000001b7   # 2: invalid
0x000001c6   # 2: in r28, 0x3d
0x000001c8   # 2: in r29, 0x3e
0x000001ce   # 2: in r0, 0x3f
...
0x00003738   # 2: invalid
0x0000373e   # 2: invalid
[0x00000000]> pd 15
        ,=< 0x00000000    0c94ac00       jmp 0x158
        |   ;-- hit0_0:
        |   0x00000002    ac00           invalid
       ,==< 0x00000004    0c94db00       jmp 0x1b6
       ||   ;-- hit0_1:
       ||   0x00000006    db00           invalid
      ,===< 0x00000008    0c94db00       jmp 0x1b6
      |||   ;-- hit0_2:
      |||   0x0000000a    db00           invalid
     ,====< 0x0000000c    0c94db00       jmp 0x1b6
     ||||   ;-- hit0_3:
     ||||   0x0000000e    db00           invalid
    ,=====< 0x00000010    0c94db00       jmp 0x1b6
    |||||   ;-- hit0_4:
    |||||   0x00000012    db00           invalid
   ,======< 0x00000014    0c94db00       jmp 0x1b6
   ||||||   ;-- hit0_5:
   ||||||   0x00000016    db00           invalid
  ,=======< 0x00000018    0c94db00       jmp 0x1b6
  |||||||   ;-- hit0_6:
  |||||||   0x0000001a    db00           invalid
  ========< 0x0000001c    0c94db00       jmp 0x1b6
```

**Comment by dukebarman** [comment] 2015-11-05 18:54
If I choose option "e asm.midflags=false" then code isn't broke. But it isn't normally / expected behavior

**Comment by radare** [comment] 2015-11-06 02:59
Is this issue only happening in avr?

**Comment by radare** [comment] 2015-11-06 03:00
Cna u add a test with the correct output? (Build r2 with an older commit)

**Comment by dukebarman** [comment] 2015-11-06 18:51
```
NAME="command for search broke disasm"
FILE=../../bins/firmware/arduino_avr.bin
ARGS='-a avr'
BROKEN=
CMDS='/c in ~ 0x12
pd 5
'
EXPECT='        ,=< 0x00000000    0c94ac00       jmp 0x158
       ,==< 0x00000004    0c94db00       jmp 0x1b6
      ,===< 0x00000008    0c94db00       jmp 0x1b6
     ,====< 0x0000000c    0c94db00       jmp 0x1b6
     ||||   0x00000010    0c94db00       jmp 0x1b6
'
run_test
```

**Comment by XVilka** [comment] 2015-11-06 18:55
@dukebarman please exclude reflines, bytes and offsets using the corresponding config variables

**Comment by radare** [comment] 2015-11-06 21:29
Use asm.lines, asm.bytes... Also test if this happens with pi.

Thanks, ill look as soon as possible

**Comment by XVilka** [comment] 2015-11-10 11:34
@dukebarman 
```
e asm.bytes=false
e asm.lines=false
e asm.offsets=false
```
or, use the `pi` instead of `pd`.

**Comment by radare** [comment] 2015-11-11 07:32
Please, push to test this asap, i want this ready for the release. Thanks

**Comment by radare** [comment] 2015-11-12 09:53
@dukebarman test plz?

**Comment by radare** [comment] 2015-11-12 09:55
Just `asm.midflags=false` to get proper disasm here. im investigating a bit more

**Comment by radare** [comment] 2015-11-12 09:57
Do avr have some kind of specific memory alignment like ARM/MIPS does? because /c is searching on every single byte, not only the aligned addresses

**Comment by radare** [comment] 2015-11-13 10:31
i'm going to move this issue to 1.0 if i get no more feedback as long as the issue can be "fixed" by properly configuring r2. I'm giving you 24h more :P

**Comment by dukebarman** [comment] 2015-11-13 16:26
```
e asm.bytes=false
e asm.lines=false
e asm.offsets=false
```

doesn't help:
```
[0x00000000]> pd 15
   jmp 0x158
  hit0_0:
   invalid
   jmp 0x1b6
  hit0_1:
   invalid
   jmp 0x1b6
  hit0_2:
   invalid
   jmp 0x1b6
  hit0_3:
   invalid
   jmp 0x1b6
...
```

`pi` helped in all cases:
```
[0x00000000]> pi 15
jmp 0x158
jmp 0x1b6
jmp 0x1b6
jmp 0x1b6
...
```

**Comment by radare** [comment] 2015-11-13 19:32
This is because of asm.midflags not being false. And because the hits are not aligned to instructions, i have already said that few commwnts ago. Can you please tell me if avr have some kind of alignment restrictions for code addresses?

**Comment by Darkkey** [comment] 2015-11-14 16:43
For branch commands (call/jmp/...) alignment is word (2 bytes).

**Comment by Darkkey** [comment] 2015-11-14 16:44
I.e., jmp 0x68 in reality encoded as jmp 0x34 (because jmp opcode stores only 16 bits of address), so you can't jmp/call to odd address.

**Comment by radare** [comment] 2015-11-14 17:30
Ok so this must be specified in the asm/anal plugin to tell the disassembler not to disassemble odd addresses as valid instructions.

Also, "in" is part of invalid, so some invalid instructions will be catched in that rop search i think

**Comment by radare** [comment] 2015-11-15 08:38
I have updated the anal plug to expose that opcode size info. Didnt tried yet if that affects this issue. Can we have a test case? Or should i do it?

**Comment by dukebarman** [comment] 2015-11-15 14:18
More better. Disasm code wasn't break
```
[0x00000000]> pd 15
        ┌─< 0x00000000    0c94ac00       jmp 0x158
        │   ;-- hit0_0:
        │   0x00000002    ac00           invalid
       ┌──< 0x00000004    0c94db00       jmp 0x1b6
       ││   ;-- hit0_1:
       ││   0x00000006    db00           invalid
      ┌───< 0x00000008    0c94db00       jmp 0x1b6
      │││   ;-- hit0_2:
      │││   0x0000000a    db00           invalid
     ┌────< 0x0000000c    0c94db00       jmp 0x1b6
     ││││   ;-- hit0_3:
     ││││   0x0000000e    db00           invalid
    ┌─────< 0x00000010    0c94db00       jmp 0x1b6
    │││││   ;-- hit0_4:
    │││││   0x00000012    db00           invalid
   ┌──────< 0x00000014    0c94db00       jmp 0x1b6
...
```

But invalid commands confuse users (they think it's diffreant commands). Is it possible correct this?

**Comment by radare** [comment] 2015-11-15 15:40
Write a test marked as broken and send a pr for the r2r repo

**Comment by dukebarman** [comment] 2015-11-15 20:23
ROP search work with errors after patch:
```
# r2 -a avr bins/firmware/arduino_avr.bin
[0x00000000]> /R in r24
  0x0000027e       0e947304  call 0x8e6
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000280           7304  cpc r7, r3
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000283     , r24  (null)
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000292       0e947304  call 0x8e6
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x00000294           7304  cpc r7, r3
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x00000297     , r24  (null)
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x000005c4           12c0  rjmp 0x5ea
  0x000005c6           8fb5  in r24, 0x2f
  0x000005c8           8f77  andi r24, 0x7f
  0x000005ca           02c0  rjmp 0x5d0

  0x000005c5             d0  (null)
  0x000005c4           12c0  rjmp 0x5ea
  0x000005c6           8fb5  in r24, 0x2f
  0x000005c8           8f77  andi r24, 0x7f
  0x000005ca           02c0  rjmp 0x5d0

  0x000005c7             d0  (null)
  0x000005c6           8fb5  in r24, 0x2f
  0x000005c8           8f77  andi r24, 0x7f
  0x000005ca           02c0  rjmp 0x5d0

  0x000005cc           8fb5  in r24, 0x2f
  0x000005ce           8f7d  andi r24, 0xdf
  0x000005d0           8fbd  out 0x2f, r24
  0x000005d2           0895  ret

  0x000005cd     , r24  (null)
  0x000005cc           8fb5  in r24, 0x2f
  0x000005ce           8f7d  andi r24, 0xdf
  0x000005d0           8fbd  out 0x2f, r24
  0x000005d2           0895  ret

  0x000005d4           85b5  in r24, 0x25
  0x000005d6           8f7d  andi r24, 0xdf
  0x000005d8           85bd  out 0x25, r24
  0x000005da           0895  ret

  0x000005d5     , r24  (null)
  0x000005d4           85b5  in r24, 0x25
  0x000005d6           8f7d  andi r24, 0xdf
  0x000005d8           85bd  out 0x25, r24
  0x000005da           0895  ret
```

**Comment by dukebarman** [comment] 2015-11-15 21:23
https://github.com/radare/radare2-regressions/pull/255

**Comment by radare** [comment] 2015-11-16 21:01
shuold be fixed too. the tests seems to return more results, tests are marked as broken, but returning more results instead of less.

can you verify them and fix the tests with the new output if they look good for you?

thanks!

**Comment by dukebarman** [comment] 2015-11-16 21:14
It wasn't fixed. I marked wrong lines on image

![wrong_rop](https://cloud.githubusercontent.com/assets/1186777/11194926/09bc2ee6-8cc0-11e5-8cac-c53d2b3b2200.png)

**Comment by radare** [comment] 2015-11-16 21:17
I wasnt getting them on osx. Let me try on linux. Thanks

**Comment by radare** [comment] 2015-11-16 21:17
Looks like a bug in the disassembler

**Comment by radare** [comment] 2015-11-16 23:53
and i cant reproduce it :/ can you try again?

**Comment by dukebarman** [comment] 2015-11-17 00:05
A bit better. Need delete strange strings "unaligned":
```
[0x00000000]> /R in r24
  0x0000027e       0e947304  call 0x8e6
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000280           7304  cpc r7, r3
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000281             04  unaligned
  0x00000282           82b3  in r24, 0x12
  0x00000284           8058  subi r24, 0x80
  0x00000286           82bb  out 0x12, r24
  0x00000288           0895  ret

  0x00000292       0e947304  call 0x8e6
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x00000294           7304  cpc r7, r3
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x00000295             04  unaligned
  0x00000296           88b3  in r24, 0x18
  0x00000298           8058  subi r24, 0x80
  0x0000029a           88bb  out 0x18, r24
  0x0000029c           0895  ret

  0x000005c4           12c0  rjmp 0x5ea
  0x000005c6           8fb5  in r24, 0x2f
  0x000005c8           8f77  andi r24, 0x7f
  0x000005ca           02c0  rjmp 0x5d0

  0x000005c5             c0  unaligned
  0x000005c6           8fb5  in r24, 0x2f
  0x000005c8           8f77  andi r24, 0x7f
  0x000005ca           02c0  rjmp 0x5d0

  0x000005cb             c0  unaligned
  0x000005cc           8fb5  in r24, 0x2f
  0x000005ce           8f7d  andi r24, 0xdf
  0x000005d0           8fbd  out 0x2f, r24
  0x000005d2           0895  ret

  0x000005d3             95  unaligned
  0x000005d4           85b5  in r24, 0x25
  0x000005d6           8f7d  andi r24, 0xdf
  0x000005d8           85bd  out 0x25, r24
  0x000005da           0895  ret
```

**Comment by radare** [comment] 2015-11-17 01:18
I think asm.pcalign fixes this. Maybe @crowell can take a look

**Comment by radare** [comment] 2015-11-17 12:54
can you confirm those unaligned disssapear if you set asm.pcalign=2 ?

**Comment by dukebarman** [comment] 2015-11-17 13:11
asm.pcalign doesn't fix this :(

**Comment by radare** [comment] 2015-11-17 13:18
then its a bug in the bwdisasm code used in /R , @crowell can you check this out?

**Comment by radare** [comment] 2015-11-17 15:42
the thing is that the backward disassembler takes into account invalid instructions, but not unaligned ones.

**Comment by radare** [comment] 2015-11-20 00:03
@crowell ping

**Comment by radare** [comment] 2015-11-20 00:04
do we have a test for this pcalign issue in /R?

**Comment by dukebarman** [comment] 2015-11-22 18:33
I think that problem was fixed so I correct tests https://github.com/radare/radare2-regressions/pull/261

**Comment by crowell** [comment] 2015-11-22 18:52
@dukebarman can we close this?

**Comment by dukebarman** [comment] 2015-11-22 18:59
Yes, for now...

**Closed** 2015-11-22 19:09 UTC
Labels: disassembly, regression

**Comment by radare** [comment] 2015-11-22 19:57
\o/
