### ISSUE TITLE
Project file of raw ARM binary has broken scrolling in visual mode

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#4473] opened 2016-03-31 18:25 UTC
I've been having an odd issue recently related to analyzing raw code binaries. Whenever I open a raw code ARM binary in radare2, run program analysis on it (`aaa`), then save things as a project (`Ps`) and then close radare and open that project again, scrolling will be broken for me in visual mode. With "broken", I mean that the "up" arrow key doesn't scroll the view by one instruction but rather by multiple ones (presumably a full basic block). The "down" arrow key works just fine though, scrolling down by one instruction as one would expect.

I'm not sure what specific circumstances specifically trigger it, but it seems that the main components are
* Working on a raw binary
* Running program analysis
* Saving to a project (and reopening it)

I've found a straightforward pattern that triggers the issue consistently:
* Download and extract http://blargsnes.kuribo64.net/download/blargSnes_1.3.zip (this should work for any other ARM binary, though)
* Extract the program's text section using `objcopy --dump-section .text=raw_code ../blargSnes.elf` (the issue only manifests on raw code!)
* Open `raw_code` in radare2, make sure to set `asm.arch=arm` and `asm.bits=32`
* Run program analysis: `aaa`
* Save the project: `Ps some_project`
* Quit radare2 and reopen the project:  `radare2 -p some_project`
* Enter visual mode: `V`, press `p` to show the disassembly
* Scroll down to e.g. offset 0x00000038. Note that the "down" arrow key works just fine. Press "up" now: The view will scroll to 0x00000020 instead of 0x00000034.

**Comment by Maijin** [comment] 2016-03-31 21:46
See asciinema, much more efficient: https://asciinema.org/a/2xyoc93m7dps97t7yl74qpp1b

**Comment by radare** [comment] 2016-03-31 22:33
Should be fixed now, not the root cause, because i think functions are wrongnly restored. and we should use sdb for storing function information for performance.. but having r2 commands format is still useful and must be fixed

**Comment by Maijin** [comment] 2016-03-31 22:42
Is fixed for arm, I can reproduced on x86_64

**Comment by neobrain** [comment] 2016-04-01 11:49
Confirmed fixed for me, thanks!

**Comment by radare** [comment] 2016-04-04 09:11
@Maijin pls confirm

**Closed** 2016-04-04 09:11 UTC
