### ISSUE TITLE
Debug Issue (posix_spawnp: Unsupported architecture)

### ISSUE THREAD

**Issue by watermeloness** [radare/radare2#3155] opened 2015-08-24 05:32 UTC
Hey,

So basically what I tried was to use radare2 as a debugger but it sadly didn't work as I imagined.
I am the above error message after running this command: "r2 -d ./executable" 
```
posix_spawnp: Unsupported architecture
PID = 12845
Failed to get task 0 for pid 12845.
Reason: 0x5: (os/kern) failure
You probably need to add user to procmod group.
 Or chmod g+s radare && chown root:procmod radare
FMI: http://developer.apple.com/documentation/Darwin/Reference/ManPages/man8/taskgated.8.html
p/io_mach.c:234 ptrace: Cannot attach: Invalid argument
ERRNO: 22 (EINVAL)
r_io_open_nomap: Unable to open file: dbg://./output.bin
Cannot open 'dbg://./output.bin' for writing.
```
I wasn't sure what the issue was but since the executable was an x86 one and r2 gave an error message something about unsupported architecture I guess it's because r2 has been compiled for x64 bit hosts.

I tried to search the wiki about how to compile radare2 in x86 mode under a x64 bit system (OSX) but didn't find anything. I also tried this command above but it didn't succeed.
`./configure --host=i686-unknown-darwin`

**Comment by radare** [comment] 2015-08-24 08:10
Please uninstall with make uninstall and use sys/install.sh, which is the prefered installstion for all platforms.

It fails becaise you have forced the build for 32 bits instead of the 32-64 debugger.

**Comment by condret** [comment] 2015-08-24 19:52
@radare why are u telling everyone to use that script, where u cannot specify the libdir?

**Comment by radare** [comment] 2015-08-24 21:33
Because before that script everyone was installing r2 from distro in /usr, then installing r2 from git in usr/local, then everything was failig or people was reporting 10 times more issues because they was using the old pkg from debian than the version they installed.. And well u will be surprised by the amount of people that just doesnt knows how to run configure or forget about git pull.

This script reduced my time spent in explaining people how to build or fix their distro considerabily. Everyone is free to use the instal method they want. But having a single script for this is better than explaining everything and much less error friendly

**Comment by radare** [comment] 2015-08-26 16:51
i would close this issue as long as i cannot reproduce it, so i guess that's just a build problem. please reopen if not the case

**Closed by radare** 2015-08-26 16:51 UTC
