### ISSUE TITLE
radare2 crashes at exit.

### ISSUE THREAD

**Issue by ret5et** [radare/radare2#8369] opened 2017-08-28 16:15 UTC
session log
```
LD_LIBRARY_PATH=./preload/ radare2/radare2 
Usage: r2 [-ACdfLMnNqStuvwzX] [-P patch] [-p prj] [-a arch] [-b bits] [-i file]
          [-s addr] [-B baddr] [-M maddr] [-c cmd] [-e k=v] file|pid|-|--|=
thistle@desertwitch:binr$ LD_LIBRARY_PATH=./preload/ gdb radare2/radare2 
...
...
(gdb) r gdb://192.168.56.101:9090
Starting program: /home/thistle/src/radare2/binr/radare2/radare2 gdb://192.168.56.101:9090
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
= attach 14032 0
= attach 0 0
[0x00000000]> q
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)

Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xa1) at malloc.c:2966
2966	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0xa1) at malloc.c:2966
#1  0x0000555555bb572e in ?? ()
#2  0x0000555555a76838 in ?? ()
#3  0x0000555555a6f556 in ?? ()
#4  0x0000555555b78e0d in ?? ()
#5  0x0000555555a6f5ab in ?? ()
#6  0x0000555555a6b257 in ?? ()
#7  0x0000555555a69b5f in ?? ()
#8  0x00005555557b2b26 in ?? ()
#9  0x00005555557aa087 in ?? ()
#10 0x00007ffff71322b1 in __libc_start_main (main=0x5555557a716a, argc=2, argv=0x7fffffffe078, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe068)
    at ../csu/libc-start.c:291
#11 0x00005555557a657a in ?? ()
```
Versions
```
(gdb) r -v
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/thistle/src/radare2/binr/radare2/radare2 -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
radare2 1.7.0-git 15893 @ linux-x86-64 git.1.6.0-620-g38786dfa5
commit: 38786dfa58b6f5c9e5160388554cd0df47de5ad6 build: 2017-08-28__19:04:08
[Inferior 1 (process 1389) exited normally]
(gdb) r -V
Starting program: /home/thistle/src/radare2/binr/radare2/radare2 -V
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1.6.0-620-g38786dfa5  r2
1.6.0-620-g38786dfa5  r_anal
1.6.0-620-g38786dfa5  r_lib
1.6.0-620-g38786dfa5  r_egg
1.6.0-620-g38786dfa5  r_asm
1.6.0-620-g38786dfa5  r_bin
1.6.0-620-g38786dfa5  r_cons
1.6.0-620-g38786dfa5  r_flag
1.6.0-620-g38786dfa5  r_core
1.6.0-620-g38786dfa5  r_crypto
1.6.0-620-g38786dfa5  r_bp
1.6.0-620-g38786dfa5  r_debug
1.6.0-620-g38786dfa5  r_hash
1.6.0-620-g38786dfa5  r_fs
1.6.0-620-g38786dfa5  r_io
1.6.0-620-g38786dfa5  r_magic
1.6.0-620-g38786dfa5  r_parse
1.6.0-620-g38786dfa5  r_reg
1.6.0-620-g38786dfa5  r_sign
1.6.0-620-g38786dfa5  r_search
1.6.0-620-g38786dfa5  r_syscall
1.6.0-620-g38786dfa5  r_util
[Inferior 1 (process 1430) exited normally]
(gdb) 
```

**Comment by radare** [comment] 2017-08-28 16:23
cant reproduce. can you show the valgrind log?

**Comment by ret5et** [comment] 2017-08-28 16:35
log
[0v.txt](https://github.com/radare/radare2/files/1257517/0v.txt)

**Comment by radare** [comment] 2017-08-28 16:50
this log is useless. how are you building and running r2? because i doubt all the backraces show addresses from the binr executable.

you just need to run sys/install.sh

**Comment by radare** [comment] 2017-08-28 16:51
default build contains debug information, so it should show file:line at least, unless you did a static and stripped build

**Comment by Maijin** [comment] 2017-09-10 23:16
Im closing until proper log is sent.

**Closed by Maijin** 2017-09-10 23:16 UTC

**Comment by ret5et** [comment] 2017-09-12 09:25
Sry for a long response.
I can't reproduce this bug on new build.
I have tried to check this bug special for the static build but seems static build is broken.

```
collect2: error: ld returned 1 exit status
../rules.mk:78: recipe for target 'ragg2' failed
make[2]: *** [ragg2] Error 1
make[2]: Leaving directory '/home/thistle/src/radare2/binr/ragg2'
Makefile:14: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/thistle/src/radare2/binr'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Maijin** [comment] 2017-09-12 09:28
That is still not proper log. Please provide full log of ./sys/install.sh in a pastebin style website or attach .txt file. 

Please also provide full configuration of the OS you're using (arch/bits/OS)
