### ISSUE TITLE
2.7.0 update fails with __x86.get_pc_thunk.bx errors on debian 7 x86

### ISSUE THREAD

**Issue by apollo3691** [radare/radare2#10171] opened 2018-05-23 15:36 UTC
Hi,

When update reaches:
CC_AR libr_core.a

I get the following errors:
ar: creating libr_core.a
`__x86.get_pc_thunk.bx' referenced in section `.text' of .libr/libr_anal.o: defined in discarded section `.text.__x86.get_pc_thunk.bx[__x86.get_pc_thunk.bx]' of .libr/libr_anal.o
(several lines of this type of error)

Logs
[stderr.log](https://github.com/radare/radare2/files/2031741/stderr.log)
[stdout.log](https://github.com/radare/radare2/files/2031742/stdout.log)

**Comment by radare** [comment] 2018-05-30 10:47
should be good in master now because we are no longer building the merged libr by default (use --with-libr to reproduce the same issue)

**Closed by radare** 2018-05-30 10:47 UTC
Labels: bug, buildsystem, release
