### ISSUE TITLE
ctype.c: In function ‘r_type_get_enum’: ctype.c:58:40: warning: ‘snprintf’ output may be truncated before the last format character

### ISSUE THREAD

**Issue by hktalent** [radare/radare2#11658] opened 2018-09-26 05:49 UTC
kali linux
```
# sys/install.sh

ctype.c: In function ‘r_type_get_enum’:
ctype.c:58:40: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
   snprintf (var2, sizeof (var2), "%s.%s", var, p);
                                        ^
ctype.c:58:3: note: ‘snprintf’ output 2 or more bytes (assuming 131) into a destination of size 130
   snprintf (var2, sizeof (var2), "%s.%s", var, p);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


make -C tcc
tccpp.c: In function ‘preprocess’:
tccpp.c:1600:20: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1011 [-Wformat-truncation=]
      "/usr/include/%s", buf);
                    ^~   ~~~
tccpp.c:1599:5: note: ‘snprintf’ output between 14 and 1037 bytes into a destination of size 1024
     snprintf (filepath, sizeof (filepath),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      "/usr/include/%s", buf);
      ~~~~~~~~~~~~~~~~~~~~~~~

CC canvas.c
In file included from magic.c:32:
/root/mytools/radare2/libr/include/r_magic.h:12:22: warning: prototype for ‘r_magic_version’ follows non-prototype definition
 R_LIB_VERSION_HEADER(r_magic);
                      ^~~~~~~
/root/mytools/radare2/libr/include/r_types.h:272:19: note: in definition of macro ‘R_LIB_VERSION_HEADER’
 R_API const char *x##_version(void)
                   ^

CC lang.c
SDB dos-x86-16.sdb.txt
In file included from lang.c:9:
p/vala.c: In function ‘lang_vala_file’:
p/vala.c:60:87: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 465 [-Wformat-truncation=]
   snprintf (buf, sizeof (buf) - 1, "valac --disable-warnings -d %s %s --pkg r_core -C %s %s", srcdir, pkgs, name, tail);
                                                                                       ^~                    ~~~~
p/vala.c:60:3: note: ‘snprintf’ output 48 or more bytes (assuming 559) into a destination of size 511
   snprintf (buf, sizeof (buf) - 1, "valac --disable-warnings -d %s %s --pkg r_core -C %s %s", srcdir, pkgs, name, tail);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p/vala.c:55:99: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 454 [-Wformat-truncation=]
    snprintf (buf, sizeof (buf)-1, "valac --disable-warnings -d %s --vapidir=%s --pkg r_core %s -C %s %s",
                                                                                                   ^~
     srcdir, vapidir, pkgs, name, tail);
                            ~~~~
p/vala.c:55:4: note: ‘snprintf’ output 59 or more bytes (assuming 570) into a destination of size 511
    snprintf (buf, sizeof (buf)-1, "valac --disable-warnings -d %s --vapidir=%s --pkg r_core %s -C %s %s",
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     srcdir, vapidir, pkgs, name, tail);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p/vala.c:71:50: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 494 [-Wformat-truncation=]
  snprintf (buf, sizeof (buf), "gcc -fPIC -shared %s.c -o lib%s."R_LIB_EXT
                                                  ^~
   " $(pkg-config --cflags --libs r_core gobject-2.0 %s)", name, libname, libs);
                                                           ~~~~
p/vala.c:71:2: note: ‘snprintf’ output 81 or more bytes (assuming 592) into a destination of size 512
  snprintf (buf, sizeof (buf), "gcc -fPIC -shared %s.c -o lib%s."R_LIB_EXT
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   " $(pkg-config --cflags --libs r_core gobject-2.0 %s)", name, libname, libs);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p/vala.c:94:38: warning: ‘.c’ directive output may be truncated writing 2 bytes into a region of size between 0 and 511 [-Wformat-truncation=]
  snprintf (buf, sizeof (buf) - 1, "%s.c", name); // remove .c
                                      ^~
p/vala.c:94:2: note: ‘snprintf’ output between 3 and 514 bytes into a destination of size 511
  snprintf (buf, sizeof (buf) - 1, "%s.c", name); // remove .c
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC io_r2pipe.c
p/io_r2pipe.c: In function ‘__write’:
p/io_r2pipe.c:31:3: warning: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size between 4043 and 4062 [-Wformat-truncation=]
   "{\"op\":\"write\",\"address\":%"PFMT64d",\"data\":[%s]}",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   io->off, bufnum);
            ~~~~~~
p/io_r2pipe.c:31:55: note: format string is defined here
   "{\"op\":\"write\",\"address\":%"PFMT64d",\"data\":[%s]}",
                                                       ^~
p/io_r2pipe.c:30:2: note: ‘snprintf’ output between 37 and 4151 bytes into a destination of size 4096
  snprintf (fmt, sizeof (fmt),
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   "{\"op\":\"write\",\"address\":%"PFMT64d",\"data\":[%s]}",
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   io->off, bufnum);
   ~~~~~~~~~~~~~~~~

...
```

**Comment by XVilka** [comment] 2018-09-26 06:34
Duplicate of https://github.com/radare/radare2/issues/10338

**Closed by XVilka** 2018-09-26 06:34 UTC
