### ISSUE TITLE
sp based vars are sometimes recognized as args

### ISSUE THREAD

**Issue by Nevsor** [radare/radare2#6923] opened 2017-03-05 20:00 UTC
When analyzing a x86-binary (filename: celen_unpatched) which uses `add esp, -0x80` instead of the three bytes longer `sub esp, 0x80` in the function prolog, all sp based variables are shown as arguments instead of variables.

I verified that the analysis is correct, if I change the instruction to `sub esp, 0x79` (filename: celen_patched).

The used binaries are in [celen.zip](https://github.com/radare/radare2/files/819672/celen.zip), the disassembled function is:

```
┌ (fcn) main 250
│   main (int arg_4h, int arg_8h, int arg_14h, int arg_18h, int arg_19h, int arg_1ah, int arg_1bh, int arg_1ch, int arg_1dh, int arg_1eh, int arg_1fh, int arg_20h, int arg_21h, int arg_22h, int arg_23h, int arg_24h, int arg_25h, int arg_26h, int arg_27h, int arg_28h, int arg_29h, int arg_2ah, int arg_2bh, int arg_2ch, int arg_2dh, int arg_7ch);
│           ; var int local_ch @ ebp-0xc
│           ; arg int arg_4h @ esp+0x4
│           ; arg int arg_8h @ esp+0x8
<removed many "arguments">
│           ; arg int arg_2dh @ esp+0x2d
│           ; arg int arg_7ch @ esp+0x7c
│              ; DATA XREF from 0x08048d21 (entry0)
│           0x08048e60      push ebp
│           0x08048e61      mov ebp, esp
│           0x08048e63      push edi
│           0x08048e64      push esi
│           0x08048e65      push ebx
│           0x08048e66      and esp, 0xfffffff0
│           0x08048e69      add esp, -0x80
│           0x08048e6c      mov eax, dword gs:[0x14]                   ; [0x14:4]=1
│           0x08048e72      mov dword [esp + arg_7ch], eax
│           0x08048e76      xor eax, eax
│           0x08048e78      lea ebx, [esp + arg_18h]                   ; 0x18
<removed rest of function>
```

PS: This is my first bug report, please ask me, if any information is missing.

**Comment by Maijin** [comment] 2017-03-05 20:09
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Nevsor** [comment] 2017-03-05 20:40
Hi, 

thanks for your quick response.
After upgrading to the newest version from git the bug is still there. 

```
$ r2 -v
radare2 1.3.0-git 13970 @ linux-x86-64 git.1.2.0-304-g87bc1e8
commit: 87bc1e8fd48b1e05a4ebf5a249efd0a8d4e8a1b0 build: 2017-03-05__21:37:13
```

**Comment by Maijin** [comment] 2017-03-05 20:57
@oddcoder ^

**Comment by oddcoder** [comment] 2017-03-05 22:04
Hi,
I believe the reason for that is that stack frame size for `main` guessing was not done accurately in your case,
you can view the current stack frame size for main using this command 
```
afll~main[13-14]
```
and edit the frame size using
```
afS [New_size] @ main
```

**Comment by Nevsor** [comment] 2017-03-05 22:15
Yes this seems to be the problem:

```
[0x08048d0a]> afll~main[13-14]
0 main
```

After using `afS 0x80 @ main`, everything was correct.

**Comment by Nevsor** [comment] 2017-03-05 22:31
I think I found the bug. 

In libr/anal/p/anal_x86_cs.c line 2181ff
``` C
case X86_INS_SUB:
		op->type = R_ANAL_OP_TYPE_SUB;
		if (INSOP(0).type == X86_OP_REG && INSOP(1).type == X86_OP_IMM) {
			if (INSOP(0).reg == X86_REG_RSP || INSOP(0).reg == X86_REG_ESP) {
				op->stackop = R_ANAL_STACK_INC;
				op->stackptr = INSOP(1).imm;
			}
		}
		if (INSOP(1).type == X86_OP_IMM) {
			op->val = INSOP(1).imm;
		}
		break;
```

It should check if `INSOP(1).imm` is positive before executing `op->stackop = R_ANAL_STACK_INC;` and do the same thing for `case X86_INS_ADD:` and negative values in `INSOP(1).imm`.

Is my reasoning right?

I think I could submit a pull request tomorrow. Do you want me to do this or do you want to fix the bug yourself?

**Comment by oddcoder** [comment] 2017-03-05 22:36
I am not sure if it could help, there is one way to find out, feel free to do it ;)

**Comment by Nevsor** [comment] 2017-03-05 22:51
Ok, I will try something like this (from libr/anal/p/anal_x86_udis.c) tomorrow:

```C
	case UD_Iadd:
	case UD_Isub:
		op->type = (u.mnemonic==UD_Iadd)? R_ANAL_OP_TYPE_ADD: R_ANAL_OP_TYPE_SUB;
		op->ptr = 0;
		op->stackptr = 0;
		if (u.operand[0].type == UD_OP_REG) {
			if (u.operand[0].base == UD_R_RSP) {
				int o = (int)getval (&u.operand[1]);
				op->stackop = R_ANAL_STACK_INC;
				if (u.mnemonic ==UD_Iadd) {
					op->stackptr = -o;
				} else {
					op->stackptr = o;
				}
			}
			if (u.operand[1].type != UD_OP_REG)
				op->val = getval (&u.operand[1]);
		}
		op->stackptr = 4;
		break;
```

**Comment by Nevsor** [comment] 2017-03-07 00:04
@oddcoder sorry, you are right that would not help. I mixed something up.

But I found another part of the code, which seems to be causing the bug (libr/anal/fcn.c:670-679):

```libr/anal/fcn.c
                switch (op.stackop) {
                case R_ANAL_STACK_INC:
                        if (R_ABS (op.val) < 8096) {
                                fcn->stack += op.val;
                                if (fcn->stack > 0 && (int)op.val > 0) {
                                        fcn->maxstack = fcn->stack;
                                }
                        }
                        bb->stackptr += op.stackptr;
                        break;
```

`op.val` is unsigned, so that R_ABS has no effect and gdb shows, that the `if` does not get executed for underflown values of op.val (like in my example with `add esp, -0x80`).

If I change the three occurences of `op.val` to `op.stackptr` (which holds the correct value according to my above snippets), the calculated stack frame size for `main` is 144 which matches my manual calculation. Is this the intended use of `op.stackptr`?

Now all the local variables are recognized correctly except for `esp+0x7c` which is still shown as arg. After manually setting `afS 144 @ main` all variables are shown as var. Any ideas what could cause this?

**Comment by alvarofe** [comment] 2017-03-07 08:32
You made a reference in `anal_x86_cs.c` and then tried to fix in  `anal_x86_udis.c`. By default is capstone and it might be the reason why didn't work. However, I think the fix should be in `fcn.c` as you have said in the last comment. About the use of `op.val` vs `op.stackptr` i should check, perhap others know better.

**Comment by radare** [comment] 2017-03-07 15:58
Please send a PR to see what travis thinks of that change. Seems correct to me. But there also some inconsistencies in the use of val and ptr because sometimes the imm is used as a pointer (mov vs lea).

**Comment by Nevsor** [comment] 2017-03-07 19:29
I uploaded a pull request: #6933

@alvarofe, the code in anal_x86_cs.c seems fine to me. I actually mixed up two `case`s and posted the code in anal_x86_udis.c as a comparison, I did not want to change anything there. The PR I submitted only makes changes to the code in the last snippet (fcn.c). 

@radare, Travis shows many broken [tests](https://travis-ci.org/radare/radare2/jobs/208418979). My change can only affect `fcn->stack` and `fcn->maxstack`, therefore I don't think that it could break a test like

```
Regression: run_tests.sh
Command:  /home/travis/build/radare/radare2/install/bin/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_print-GKCo7E/rad   - > /tmp/r2-regressions//cmd_print-GKCo7E/out 2> /tmp/r2-regressions//cmd_print-GKCo7E/err
File: -
Script: 
b 2
wx 0xff
p= 2@0
Diff: --- /tmp/r2-regressions//cmd_print-GKCo7E/exp	2017-03-07 00:35:14.258769588 +0000
+++ /tmp/r2-regressions//cmd_print-GKCo7E/out	2017-03-07 00:35:14.258769588 +0000
@@ -1,3 +0,0 @@
-         ___________________________________________________
-00 00ff | __________________________________________________|
-01 0000 ||
[  ]  11  cmd_project: Breakpoints in project file   
[BR]
```

Did I do something wrong while submitting my PR?

**Comment by Maijin** [comment] 2017-03-07 19:34
BR doesn't mean you broke it.

The one you broke are [XX] and there are 4 of them

**Comment by Nevsor** [comment] 2017-03-07 19:53
Thank you for the explanation. 

I believe that at least one of the tests is wrong. Should I open a new issue for this or post the test here?

**Comment by Maijin** [comment] 2017-03-07 19:55
If the test is wrong, fix the test -> PR here https://github.com/radare/radare2-regressions

**Comment by Nevsor** [comment] 2017-03-07 21:19
I submitted a [PR](https://github.com/radare/radare2-regressions/pull/738) for two of the tests ("reflines ascii" and "reflines ascii (offset)").
I don't know whether the other two are wrong too or whether they show bugs introduced by my PR. Actually I am not even completely sure about the first two.

Could someone with more experience than me take a look at the tests?

**Comment by radare** [comment] 2017-03-07 22:02
Looks good to me

**Comment by Nevsor** [comment] 2017-03-07 22:03
Do you mean the tests or my PRs?

**Comment by oddcoder** [comment] 2017-03-09 13:27
fixed by https://github.com/radare/radare2/commit/43b1530ffc528d2d1c5d43e06e84b18b9fca6700

**Closed by oddcoder** 2017-03-09 13:27 UTC
Labels: bug, types
