### ISSUE TITLE
Cannot punycode decode/encode emojis

### ISSUE THREAD

**Issue by radare** [radare/radare2#4837] opened 2016-05-09 23:30 UTC
```
$ node -e "console.log(punycode.decode('yp8h'))"
👍
$ rahash2 -E punycode -s yp8h
M
```

**Comment by Maijin** [comment] 2016-05-10 10:55
@P4N74 ^

**Comment by P4N74** [comment] 2016-05-10 19:32
Yes I will try looking at this and see what can be done. Currently I am not able to decide how to set ut32 into ut8 format without any loss. I mean the input/output should match the signature of the function `R_API ut8 *r_punycode_decode(ut8 *src, int srclen, int *dstlen)` and yet have something that takes in ut32 and returns the result ut32 when required. I hope what I wrote makes sense.

**Comment by radare** [comment] 2016-06-14 12:43
ping @P4N74

**Comment by radare** [comment] 2016-06-28 23:09
moving to 0.10.5? @P4N74

**Comment by P4N74** [comment] 2016-06-29 06:30
yes. sorry for not being able to spend time on this earlier.

**Comment by radare** [comment] 2016-10-06 14:00
ping @P4N74

**Comment by P4N74** [comment] 2016-10-06 19:35
@radare I will look into https://github.com/radare/radare2/issues/3512#issuecomment-217127978 code and fix this issue. The problem is of unicode only iirc.

**Comment by radare** [comment] 2016-12-14 12:10
uh @P4N74 ?

**Comment by radare** [comment] 2017-02-28 00:53
ping

**Comment by P4N74** [comment] 2017-02-28 12:35
I will try to close this issue in 1.3.0 release (I spent some time reading about utf8 to utf32 conversion and reverse and I have written a working code myself from scratch. So now I will have to do some minor changes in punycode file and this would get closed I guess) but please don't change milestone as of now :) It is safe to have 1.4.0

**Comment by P4N74** [comment] 2017-02-28 13:45
@radare created a [PR](https://github.com/radare/radare2/pull/6864) regarding this issue. It would be nice if you test it further and let me know in case something goes wrong :smile:

**Closed** 2017-03-01 08:56 UTC
Labels: enhancement, rahash2
