### ISSUE TITLE
Invalid instruction errors

### ISSUE THREAD

**Issue by davidpolverari** [radare/radare2#12112] opened 2018-11-10 02:13 UTC
# Invalid instruction errors

Since the last builds, r2 is issuing several `Invalid instruction (possibly truncated) at 0x...` errors when ran with `-dA` command line switches. When either analysis or debugging only is specified, such errors do not occur.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian testing (Buster) x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 19992 @ linux-x86-64 git.3.0.1-180-g6c7bfd846 commit: 6c7bfd846a28c3494c01850943aa2bf5e84c5800 build: 2018-11-09__23:51:56

### Expected behavior
```
$ r2 -dA /bin/true
...
(analysis happens with no errors)
...
```

### Actual behavior
```
$ r2 -dA /bin/true
Process with PID 29696 started...
= attach 29696 29696
bin.baddr 0x55731f490000
Using 0x55731f490000
asm.bits 64
[Invalid instruction (possibly truncated) at 0x55731f499060
Invalid instruction (possibly truncated) at 0x55731f490131
Invalid instruction (possibly truncated) at 0x55731f490131
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
...

```
### Steps to reproduce the behavior 
- Use `r2 -dA` with any ELF64 binary under Debian testing (Buster) x86-64.

**Comment by radare** [comment] 2018-11-10 09:58
Works without the -A?

**Comment by davidpolverari** [comment] 2018-11-11 03:34
Using only `-d` (without `-A`) it doesn't show any errors. But as soon as an `aaaa` is issued, the same errors are shown.

**Comment by davidpolverari** [comment] 2018-11-11 03:35
If only debugging or only analysis is attempted, everything is fine.

**Comment by radare** [comment] 2018-11-11 10:18
Thats because theres one analysis command being executed by aaa that is enabling emulation and breaking the process state. An if would be enough to cover this

Cc @maijin

**Comment by davidpolverari** [comment] 2018-11-11 18:35
Those errors didn't happen before 4a5048f7f4bf233653029e0b60bd5d2ab8517b0e

**Comment by radare** [comment] 2018-11-11 22:36
Can we have a static test? So @kazarmy can check it out and test it to avoid future reressions?

Thanks

**Comment by davidpolverari** [comment] 2018-11-12 21:40
Yes, I can write a test on radare2-regressions for this case, in the event there is none.

**Comment by samrg472** [comment] 2018-11-19 06:45
This issue is still happening as of 9931f0f even with the above PR merged. I can confirm 4a5048f is the cause.
```
radare2 3.1.0-git 20098 @ darwin-x86-64 git.3.0.1-279-g9931f0f35
commit: 9931f0f35cc4f6e066c52d98e03f74c444c495d5 build: 2018-11-18__22:33:29
```

However, in my case (no debugging):
- Running `aaaa` the first time will cause the invalid instruction error
- Run the command a second time immediately after and the error doesn't appear

**Comment by radare** [comment] 2018-11-19 12:38
can anyone reproduce? because i cant

**Comment by samrg472** [comment] 2018-11-19 17:10
@kazarmy 
Here's the environment:

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS Mojave / x86_64 / 64
| File format of the file you reverse (mandatory)      | MACH064
| Architecture/bits of the file (mandatory)            | x86 / 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20115 @ darwin-x86-64 git.3.0.1-287-g23fb5bc19 commit: 23fb5bc197ded5a9179f54cf502945332932c38e build: 2018-11-19__09:04:25

Note: r2 has been updated since making this comment

#### Code:
```c++
#include <iostream>

using namespace std;

int main(int argc, char const *argv[]) {
  cout << "test" << endl;
  return 0;
}
```

#### Compile options:
```
$ clang++ test.cpp
```

#### Compiler information:
```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

# xcode version
10.1 beta 3 (10O45e)
```

#### Binary:
[a.out.zip](https://github.com/radare/radare2/files/2596298/a.out.zip)

#### Reproducing
```
$ r2 ./a.out 
[0x100000f90]> aaaa
[Invalid instruction (possibly truncated) at 0x100001fe8
Invalid instruction (possibly truncated) at 0x100001fe4
Invalid instruction (possibly truncated) at 0x100001f72
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Enable constraint types analysis for variables

[0x100000f90]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Enable constraint types analysis for variables
```

**Comment by kazarmy** [comment] 2018-11-19 17:42
Apparently this is because r2 thinks there's code in the .gcc_except_table section.

**Comment by kazarmy** [comment] 2018-11-20 03:34
You need to submit 2 separate issues for the above along with repro instructions. Hopefully somebody that is more familiar with the debug code will have a look.

I've looked at the source code and there doesn't seem to be any theoretical explanation as to why 4a5048f7f4bf233653029e0b60bd5d2ab8517b0e would cause `Register not found` errors, so repro instructions are needed here.

**Comment by samrg472** [comment] 2018-11-20 03:54
@kazarmy I may be stretching out on a limb here thinking they're related, but I really have no idea since that's when the issue appears or they may be more going on. I'll have another issue posted for this specific case of invalid instruction errors.

**Comment by radare** [comment] 2019-03-31 20:10
should be fixed already, pls confirm if not

**Closed by radare** 2019-03-31 20:10 UTC
Labels: bug

**Comment by davidpolverari** [comment] 2019-04-01 01:17
AFAIK it has been already fixed.
