### ISSUE TITLE
Several Radare2 tiny issues

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#7210] opened 2017-04-06 12:03 UTC
I figured this was overdue since I've seen this for a while.  Situation:  Below is some example code from [http://flatassembler.net/](url) for Windows:

[blehx32.zip](https://github.com/radare/radare2/files/902452/blehx32.zip)

~~~
; example of simplified Windows programming using complex macro features

include 'win32ax.inc' ; you can simply switch between win32ax, win32wx, win64ax and win64wx here

.code

  start:
        invoke  MessageBox,HWND_DESKTOP,"Hi! I'm the example program!",invoke GetCommandLine,MB_OK
        invoke  ExitProcess,0

.end start
~~~

This creates a simple dialog box with the sentence above and an Ok button.  First some screenshots from the latest Radare2 (using the sys/install.sh method):
![screenshot from 2017-04-05 20-26-36](https://cloud.githubusercontent.com/assets/947191/24735081/5a0cd406-1a3e-11e7-9ef4-62345ea56de1.png)

![screenshot from 2017-04-05 20-27-03](https://cloud.githubusercontent.com/assets/947191/24735089/65561d04-1a3e-11e7-95f0-fe25d0dddb8c.png)

Radare2 shows some interesting behavior when analyzing this:

1. The string isn't seen as a string.  The strings command sees the string:
![screenshot from 2017-04-05 20-29-14](https://cloud.githubusercontent.com/assets/947191/24735139/9849d2a0-1a3e-11e7-9398-a5325a063823.png)

2.  I will usually never see the source, but in this case I'm cheating and I know that from the source the string is 28 bytes long.  However when I set the bytes at 0x0040100e as a string, it appears to to set 29 bytes as shown with adding the next 0x00.  How do I manually set the length in this case to 28 bytes?
![define](https://cloud.githubusercontent.com/assets/947191/24752939/550b6a72-1a8d-11e7-9ffc-3c8cc43533a2.gif)

3.  At 0x0040109 there's a call to 0x0040102b, but after setting the string I just did above, 0x0040102b is now part of the string.  I'm going to bet that calls to strings is bad form ;)  Is there a way to build in logic to radare2 to not do a call to a string?
![screenshot from 2017-04-06 05-49-59](https://cloud.githubusercontent.com/assets/947191/24753112/0f18d602-1a8e-11e7-87b2-4e00ba725fbc.png)
 
4.  Lastly, after setting the string, when scrolling up and down the string will revert back to the code and back...it cause me thinky pain :):
![peek 2017-04-06 05-50](https://cloud.githubusercontent.com/assets/947191/24753162/3d5e1108-1a8e-11e7-97c4-2b1feda0bac4.gif)

**Comment by Maijin** [comment] 2017-04-06 12:08
Share the bin, zip it and drag and drop here.

**Comment by DigiAngel** [comment] 2017-04-06 12:13
Done :)

[blehx32.zip](https://github.com/radare/radare2/files/902452/blehx32.zip)

**Comment by radare** [comment] 2017-04-07 17:21
this is only 1 issue and has been reported several times and its known thing (if i understood you correctly).

**Comment by DigiAngel** [comment] 2017-04-07 17:43
Ok cool...which issue is it then?  As I see it I see three:

1.  Not seeing strings
2.  Setting strings sets more bytes then the actual string
3.  Flip flop of strings/code when scrolling

Unless these are all related and I've missed something.  Thank you.

**Comment by radare** [comment] 2017-04-07 17:48
all those things are just 1 issue: if you disassemble in the middle of a string it is not considered a string so it shows code. making this correct will make the disasm 10 or 20 times slower. and this really affects very few use cases and there are some workaround to solve that, but its a known issue

**Comment by DigiAngel** [comment] 2017-04-07 17:51
Ok cool....two things then:  What's the workaround, and could we get a feature to define the amount of bytes to set as a string?  This would at least allow me to control the bytes...unless the workaround does that already :)

**Comment by radare** [comment] 2017-04-15 18:20
dupe of https://github.com/radare/radare2/issues/2712

**Closed by radare** 2017-04-15 18:20 UTC
Labels: bug, consoleui, disassembly, visual
