### ISSUE TITLE
"asm.emu" does not work after open a saved project

### ISSUE THREAD

**Issue by daniel-rome** [radare/radare2#3835] opened 2015-12-11 23:38 UTC
Once a project has been saved, closed and opened again, it does not load the "asm.emu" var properly.

// We load a binary, enable the "asm.emu" variable and save the project
$ r2 binary
 -- Change the registers of the child process in this way: 'dr eax=0x333'
[0x000099b8]> e asm.emu=true
[0x000099b8]> pd 5 @ 0xe920
            0x0000e920      000053e3       cmp r3, 0                  
        ,=< 0x0000e924      0800000a       beq 0xe94c                 ; unlikely
        |   0x0000e928      fc0f0be3       movw r0, 0xbffc            ; r0=0xbffc -> 0xe3a02000
        |   0x0000e92c      020040e3       movt r0, 2                 ; r0=0x2bffc str.devconf_put__f__var_config.xml.gz
        |   0x0000e930      03ebffeb       bl sym.imp.system          ; lr=0xe938 -> 0xe3400000; pc=0x9544 sym.imp.system
; CALL: 0xebffeb6c, 0xe51b304c, 0xe2833001, 0xe50b304c
[0x000099b8]> Ps test
test
[0x000099b8]> q
Do you want to save the 'test' project? (Y/n)

// We open the project again, check the "asm.emu" variable (enabled) and print the above address.
$ r2 -
 -- Use hasher to calculate hashes of portion blocks of a file
[0x00000000]> Po test
Close current session? (Y/n)
[0x000099b8]> e asm.emu
true
[0x000099b8]> pd 5 @ 0xe920
            0x0000e920      000053e3       cmp r3, 0 
        ,=< 0x0000e924      0800000a       beq 0xe94c                 ; unlikely
        |   0x0000e928      fc0f0be3       movw r0, 0xbffc 
        |   0x0000e92c      020040e3       movt r0, 2
        |   0x0000e930      03ebffeb       bl sym.imp.system
; CALL: 0x10101, 0x0, 0x0, 0x280002
[0x000099b8]>

**Comment by daniel-rome** [comment] 2015-12-12 11:25
I have noticed that if the project is saved and closed with the "asm.emu" variable equal to false and it is set to "true" once the project is reopened, r2 shows the following error messages:

[0x00000000]> Po test
Close current session? (Y/n)
[0x0000e930]> e asm.emu
false
[0x0000e930]> e asm.emu=true
[0x0000e930]> pd -10
**esil_sub: src is broken**
**esil_add: invalid parameters**
**esil_sub: src is broken**
|       ,=< 0x0000e908      0100000a       beq 0xe914                 ; unlikely
|       |   0x0000e90c      10001be5       ldr r0, [fp, -0x10]
|       |   0x0000e910      bfebffeb       bl sym.imp.fclose

**Comment by radare** [comment] 2015-12-12 12:10
Cant reproduce

**Comment by Maijin** [comment] 2015-12-12 12:13
@daniel-rome Are you sure to use the latest git version ?

**Comment by daniel-rome** [comment] 2015-12-12 12:18
Yes, I guess!

I am using the r2(x64) to open an arm(x32) binary.

If I do the same process with a x64 binary it is working properly, but it fails with a arm(x32) binary.

**Comment by Maijin** [comment] 2015-12-12 12:32
Yes I can reproduce using an arm32 binary https://github.com/radare/radare2-regressions/blob/master/bins/elf/simpleARM.elf

**Comment by radare** [comment] 2015-12-16 14:11
can we have a test?

**Comment by daniel-rome** [comment] 2015-12-16 18:51
What do you need? the binary?

**Comment by Maijin** [comment] 2015-12-16 18:56
@daniel-rome no, writing a testcase in https://github.com/radare/radare2-regressions

**Comment by Maijin** [comment] 2015-12-16 21:07
Tested here => https://github.com/radare/radare2-regressions/blob/master/t/cmd_project#L111

**Comment by Maijin** [comment] 2015-12-16 21:32
@daniel-rome should be fixed

**Comment by daniel-rome** [comment] 2015-12-20 13:39
I have tested it again and it is working properly! :D 

Thanks!!

**Closed** 2015-12-20 13:54 UTC
Labels: bug, has-test

**Comment by radare** [comment] 2015-12-20 15:38
👍
