### ISSUE TITLE
-R flag seems to be broken

### ISSUE THREAD

**Issue by redfast00** [radare/radare2#8460] opened 2017-09-08 10:43 UTC
Steps to reproduce:
content of `script.rr2`:
```
#!/usr/bin/rarun2
program=/bin/ls
arg1=/bin
```
When running `r2 -R script.rr2 -d /bin/ls`, r2 seems to ignore the script and when running the binary with the `dc` command, it just prints the contents of the current directory instead of `/bin`.

**Comment by Maijin** [comment] 2017-09-08 11:17
arg[0-3]    set value for argument N passed to the program

Isn't the first argument arg0 in this case ?

**Comment by redfast00** [comment] 2017-09-08 11:33
After investigating further, `r2 -e dbg.profile=script.rr2 /bin/ls` seems to work. When reading trough the source code (`radare2.c`), I think the `-r` flag should be used for an entire profile, and the `-R` flag should be used for individual values. And @Maijin, arg0 is the name of the program, arg1 is the first "real" argument. (if I run `ls test1 test2`, `ls` is arg0, `test1` is arg1 and `test2` is arg2). The `dgb.profile` trick works. Only thing I am still struggeling with is that apparently the `!` to run a command in a profile seems broken, but I can work around this.

**Comment by Maijin** [comment] 2017-09-08 14:29
@redfast00  - 

Then man rarun2 is wrong:

```
     Sample rarun2 script

       $ cat foo.rr2
       #!/usr/bin/rarun2
       program=./pp400
       arg0=10
      ....
```

**Comment by Maijin** [comment] 2017-09-10 22:15
For ! the issue is duplicate of https://github.com/radare/radare2/issues/2710

**Closed by Maijin** 2017-09-10 22:15 UTC
