### ISSUE TITLE
parsing cmd with semicolon in quotes treated wrong

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1745] opened 2014-11-26 01:20 UTC
Currently doing something like 

```
/R/ "pop;pop;pop" 
```

will run rop search for `"pop`

and then will run `pop;pop"` 

the quoting for commands with semicolons in it should just be able to be on the argument, not on the entire command.

**Comment by radare** [comment] 2015-03-18 22:46
You have to quote the whole command like this:
```
"/R/ pop;pop;pop"
```

**Comment by radare** [comment] 2015-03-18 22:51
This requires rewriting the parser, which can bring back some regressions, so i'm moving it for 1.0

**Comment by Maijin** [comment] 2016-03-17 11:05
@crowell Is the "/R/ pop;pop;pop" ok ? Because there are already tests for "/R/..." maybe that issue can be closed

**Closed** 2016-03-25 13:33 UTC
Labels: blocker, enhancement, test-required
