### ISSUE TITLE
Impossible disassembly?

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#6410] opened 2017-01-01 11:28 UTC
This seems to be an old trick:
![image](https://cloud.githubusercontent.com/assets/6576335/21581025/a93908ee-d01d-11e6-9020-f0cc98856c0e.png)

**Comment by Maijin** [comment] 2017-01-01 13:57
Well it is.

**Comment by Maijin** [comment] 2017-01-01 13:57
Use radare2

**Comment by MariasStory** [comment] 2017-01-01 14:04
Hi @Maijin,

Can you please explain why did you close the issue?

To me, it is a big problem to deal with.

Example:
rasm2 'mov ax, 05EBh; XOR eax, eax; JZ -7; add ax,5; sub ax,5'
b8eb05000031c00f84ecffffffc005e805
Output:
rasm2 -d 'b8eb05000031c00f84ecffffffc005e805'
**mov eax, 0x5eb
xor eax, eax
je 0xfffffff9
invalid
invalid
invalid
invalid**

**Comment by Maijin** [comment] 2017-01-01 14:06
Well you didn't explain what is the problem just pasted a slide without any reproducer without any tests.
Also the assembly shown in the slide is not the same as the one you provided.

**Comment by Maijin** [comment] 2017-01-01 14:09
+ It's not a bug, if you follow the disassembly using arrow left/right in visual mode this trick doesn't work so it's not a problem for radare2.

**Comment by Maijin** [comment] 2017-01-01 14:10
See https://asciinema.org/a/3l290l0jxe13firaq51psxudk

**Comment by radare** [comment] 2017-01-02 13:17
pd does linear disasm, pdr or agf do graph/recursive disasm, also you can enable asm.midflags to solve that disasm trick

also, iirc there are tests for this

**Comment by Maijin** [comment] 2017-01-02 14:44
Yes midflags have tests iirc. So closing this.

**Closed by Maijin** 2017-01-02 14:44 UTC
Labels: antidisasm

**Comment by radare** [comment] 2017-01-02 14:58
please confirm that pdr and agf works fine for this case and write tests for them if needed, not sure if its a regression yet

**Comment by j123123** [comment] 2017-01-07 08:50
#6012 - relevant issue
