### ISSUE TITLE
Repainting small areas of the screen is inefficient

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4820] opened 2016-05-09 07:51 UTC
It should be possible to only re-draw part of the screen in many cases.

For example:

In "V!" mode, if you're scrolling down the menu items in an expanded menu bar. There should be no reason to repaint the entire screen. Instead, it should be possible to do a minimal update by either redrawing only the contents of the expanded menu or -- even better -- just erasing and drawing a new indicator of which item is highlighted.

**Comment by radare** [comment] 2016-05-09 08:48
repainting the whole terminal is fast, the problem is that this operation is done while urnning the commands to fill all the panels (pd, graph, ..) which produces the flickering. RCons adds some buffering in the console io, but this is not enough to make this fancier.

Having partial console refreshes will be faster in some situations, but it will not in many others because at the end is faster to just perform a single write() syscall than having to process all the console buffer, output all the gotoxyes in ansi code and so on.. and this is even worst in the case of windows.

the best solution for this would be to not clean the screen until all the buffers are filled and ready to draw, which only happens in V! because the way its filling them. Also, bear in mind that this flickering will be gone if you use VTE, some terminals already do that caching

**Comment by jduck** [comment] 2016-05-09 17:41
Understood. Also, adding smarts might replace repainting/flickering with input delay... As for Windows, it shouldn't be that difficult, but that depends on what's being used for emulating a terminal. When I was working for Rapid7 that was a big pain in the ass and I think they eventually used Console2. My experience with that stuff goes way back to directly manipulating the VGA frame buffer in DOS. Not much in between heheh

**Comment by Vane11ope** [comment] 2018-09-21 09:27
this is not happening anymore now. the panels indeed updates only the panels that need to be updated with refresh flag on. so i think this can be closed now.

**Comment by radare** [comment] 2018-09-21 09:29
weare not updating portions of the screen, we are always repainting everything, thats the idea of this issue and we dont do that because usually repainting everything is fast enough unless you are on a serial console

**Comment by XVilka** [comment] 2019-04-03 04:49
We should measure it and evaluate if it worth the trouble. @Vane11ope @radare @jduck 
I personally think it is not a bottleneck at all and can be closed.

**Comment by Vane11ope** [comment] 2019-04-03 05:38
yup close this plz

**Closed** 2019-04-17 10:39 UTC
Labels: consoleui, enhancement
