### ISSUE TITLE
Fail to save the settings in the cygwin while quitting

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2768] opened 2015-06-15 19:00 UTC
Failing to create a directory:

```
[0x100401000]> q
r_sys_rmkdir: fail '/cygdrive/d' of '/cygdrive/d/Work/.config/radare2'
```

**Comment by radare** [comment] 2015-10-13 03:05
can you try again?

**Comment by XVilka** [comment] 2015-10-14 11:45
@radare bug is still here

**Comment by radare** [comment] 2015-10-14 12:09
Can u try to run mkdir -p to create this and identify if the problem is in r2 mkdirp code or this path is just impossible to create in cygwinland?

**Comment by XVilka** [comment] 2015-10-14 12:25
@radare `mkdir -p` worked flawlessly.

**Comment by radare** [comment] 2015-10-23 02:13
Please confirm if this is fixed now

**Comment by radare** [comment] 2016-11-02 02:34
let's consider this fixed

**Closed by radare** 2016-11-02 02:34 UTC
Labels: bug, easy, Windows
