### ISSUE TITLE
Regression in 7fe4084b328ae4a25931d865da360b39a149af2c

### ISSUE THREAD

**Issue by leberus** [radare/radare2#5892] opened 2016-10-01 08:21 UTC
The patch given in that commit is wrong, is checking the bad pointer, and because of that, every coredump is failing:

if (!elf_proc_note->n_threads || elf_proc_note->n_threads < 1 ) {
                eprintf ("problem in elf_proc_note\n");
                free (elf_proc_note);
                free (proc_data->per_process);
                free (proc_data);
                return false;
        }
        elf_proc_note->n_threads = proc_data->per_process->num_threads;

The check is wrong. Is trying to check the value before getting it.

The segfault described here https://github.com/radare/radare2/issues/5812 was because in the version @zonkzonk was using, one check was wrong:

```
1485            proc_data->per_process = get_proc_process_content (dbg);
1486            if (!proc_data) {
1487                    free (elf_proc_note);
1488                    return false;
1489            }
```

It should check (proc_data->per_process), instead of (proc_data).
btw this function returns only NULL if:
1- proc/pid/stat does not exist
2- proc/pid/status does not exist
3- can't allocate memory for the structures

In the current version that check code is already fixed:

```
        proc_data->per_process = get_proc_process_content (dbg);
        if (!proc_data->per_process) {
                free (elf_proc_note);
                free (proc_data);
                return false;
        }
```
So I guess @zonkzonk was using an old version of radare2.

I will fix the regression introduced by this commit, and then I'll tell to @zonkzonk if he can try to reproduce the segfault with the new version (I guess not because of the old check)

**Comment by radare** [comment] 2016-10-01 08:29
Can you send a pr?

**Comment by leberus** [comment] 2016-10-01 08:43
Yes, I will, but right now I'm afk. I will try in the afternoon

El dia 01/10/2016 10:29, "radare" <notifications@github.com> va escriure:

> Can you send a pr?
>

**Comment by leberus** [comment] 2016-10-01 08:48
Btw, the check which was not  checking properly the null pointer was fixed by @alvarofe two days ago(so was not fixed at the time @zonkzonk was trying.
This is way @zonkzonk was confused i think.

I'l make my PR

**Comment by alvarofe** [comment] 2016-10-01 09:06
I pushed a fix to master my apologies because i didn't see it when merging his PR

**Comment by leberus** [comment] 2016-10-01 13:30
@alvarofe no problem! was first my fault to not check the right pointer xD.
I've created a new PR:

https://github.com/radare/radare2/pull/5895

**Comment by zonkzonk** [comment] 2016-10-01 13:50
reproduced: wrong patch, stops fault, but does not let do any more coredumps

**Comment by leberus** [comment] 2016-10-01 13:59
@zonkzonk , what do you mean? With the check @avarofe was adding, and without your check, should work. Could you try with the code I've changed in my PR?

**Comment by alvarofe** [comment] 2016-10-01 14:02
but is weird when i tried the patch i was able to generate coredump with `dg` will look better at night, maybe linux issue?

**Comment by leberus** [comment] 2016-10-01 14:09
I was trying to dump yesterday and it was failing for me, once i removed the check for the num_threads was working fine again.
Let me know your findings ;)

**Comment by leberus** [comment] 2016-10-01 14:28
@alvarofe anyway, I see that you already fixed the regression, that's terrific ;)!
My PR removes this check:

if (!elf_proc_note->n_threads || elf_proc_note->n_threads < 1 ) {
                eprintf ("problem in elf_proc_note\n");
                free (elf_proc_note);
                free (proc_data->per_process);
                free (proc_data);
                return false;
        }

In my PR I explain why it's not needed, but since it doesn't hurt I don't mind.

Then I've added two eprintf, because I think the problem @zonkzonk was hitting was:

- couldn't allocate memory for the struct
-  or /proc/pid/stat didn't exist
- or /proc/pid/status didn't exist

In that case, I've added two eprintf in case were the files (so user can better know why it was failing).

**Comment by zonkzonk** [comment] 2016-10-01 15:20
as I said, just remove my patch and it segfaults at that revision. with my wrong patch it did not segfault but also dit not write any coredumps. sorry.

**Comment by leberus** [comment] 2016-10-01 16:40
It shoulndt segfault with the last version. Do a git pull and try it please :)

**Comment by alvarofe** [comment] 2016-10-02 00:06
I get the coredump correctly and don't get any segfault so far. Regarding the check you removed (in your PR) i would maintain it since it doesn't hurt and imagine if there is some kind of race condition that we are not aware, I'd rather to be safe.

**Comment by leberus** [comment] 2016-10-02 13:43
Hi @alvarofe , i'm with you, it doesn't hurt. But what about move the check inside of get_proc_process_content function?
In that case, all checks belonging to that function are being performed there, and if num_threads is 0 o less, we just return NULL (as we do if the something fails in that function).
If you give me the ok, I can do another PR for it, if not, feel free to close the issue as you fixed it already. Thanks ;)

**Closed** 2016-10-02 19:16 UTC
Labels: regression

**Comment by alvarofe** [comment] 2016-10-02 22:14
done your comment ;)

**Comment by leberus** [comment] 2016-10-03 06:55
Great, thanks ;)

El dia 03/10/2016 00:15, "Álvaro Felipe Melchor" <notifications@github.com>
va escriure:
