### ISSUE TITLE
ds fails to step

### ISSUE THREAD

**Issue by MapleLeaf-X** [radare/radare2#14063] opened 2019-05-14 08:28 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Win7 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 4 @ windows-x86-64 git.3.6.0-git commit: f76bb81d1cba9ab001535365d12f4d2635618560 build: Tue 05/14/2019__ 5:40:25.82

### Expected behavior
ds should step in code.

### Actual behavior
ds fails with the error 'Stepping failed!'.

### Steps to reproduce the behavior 
- load any pe in r2. (r2 file.exe)
- set dbg.bep to entry. (e dbg.bep=entry)
- set dbg.bpsysign to true. (e dbg.bmsysign=true)
- run with doo/ood
- use ds

**Comment by XVilka** [comment] 2019-07-30 04:00
@MapleLeaf-X can you please retest it with the latest master?

**Comment by XVilka** [comment] 2019-09-07 10:25
@GustavoLCR can you please check this one, and close if is irrelevant/fixed?

**Comment by GustavoLCR** [comment] 2019-09-11 02:14
I cannot reproduce this, probably got fixed in the refactor.

**Closed by GustavoLCR** 2019-09-11 02:14 UTC
Labels: RDebug, Windows
