### ISSUE TITLE
multiple strings in ragg2 egg files doesn't work

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3235] opened 2015-09-06 01:48 UTC
```
minishwoods /tmp » cat hi.r
write@syscall(4)

main@global(128) {
.var0 = "hi!";
.var1 = "sup";
write(1, .var0, 3);
write(1, .var1, 3);
}
minishwoods /tmp » qemu-arm -strace ./hi 
406 write(1,0x40074,3)sup = 3
406 write(1,0x40074,3)sup = 3
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[1]    406 segmentation fault (core dumped)  qemu-arm -strace ./hi
```

should print `"hi!sup"`

**Comment by radare** [comment] 2015-09-07 17:32
this works for me on osx:
```
$ cat test0.r
write@syscall(0x2000004)
exit@syscall(0x2000001)

main@global(128) {
	.var0 = "hi!\n";
	.var20 = "ho!\n";
	write(1, .var0, 4);
	write(1, .var20, 4);
	exit(0);
}
```
which archbitsos are you using?

**Comment by radare** [comment] 2015-09-07 17:33
note that .var0 and .var1 are not valijd variable names for what you are trying to do. the number after .var is the offset in the stack (>=0 && <128). remember, ragg2 is lowlevel :)

but this is also broken, this was perfectly working in old.rarc2 that now is available in r2e.

**Comment by radare** [comment] 2015-09-09 09:05
@crowell ping

**Comment by crowell** [comment] 2015-09-09 18:01
target is arm 32 bit

but my host os is ubuntu amd64

i've been too busy to fix this this week and won't have time until next week

On Wed, Sep 9, 2015 at 5:05 AM, radare <notifications@github.com> wrote:

> @crowell <https://github.com/crowell> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3235#issuecomment-138844034>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment] 2015-09-09 19:58
Test my snippet on arm please, it works on x86-64 at least

**Comment by crowell** [comment] 2015-09-09 20:28
this doesn't work on arm for me

```
jeff@lostwoods ~ $ strace ./hi 
execve("./hi", ["./hi"], [/* 17 vars */]) = 0
write(1, 0x400, 4)                      = -1 EFAULT (Bad address)
write(1, 0x400, 4)                      = -1 EFAULT (Bad address)
exit(0)                                 = ?
+++ exited with 0 +++
```

```
jcrowell0 /tmp » cat hi.r 
write@syscall(4)
exit@syscall(1)

main@global(128) {
    .var0 = "hi!";
    .var20 = "ho!";
    write(1, .var0, 4);
    write(1, .var20, 4);
    exit(0);
}
```

```
jcrowell0 /tmp » ragg2 -a arm -b 32 -s hi.r   
WARNING: probably a bug?

.global main
main:
  push {fp,lr}
  add fp, sp, $4
  sub sp, 128
# encode filtered string (hi!) ((null))
  add pc, 0
.string "hi!"
  sub r0, pc, 12
  str r0, [sp, 7]
# encode filtered string (ho!) ((null))
  add pc, 0
.string "ho!"
  sub r0, pc, 12
  str r0, [sp, 27]
# rcc_fun 1 (write)
  mov r0, 4
  str r0, [sp, 12]
  mov r0, 1
  str r0, [sp, 20]
# set syscall args
  ldr r1, [sp, 8]
  ldr r2, [sp, 12]
  ldr r3, [sp, 20]
# syscall
 mov r7, 4
 svc 0x0
# rcc_fun 1 (write)
  mov r0, 4
  str r0, [sp, 12]
  mov r0, 1
  str r0, [sp, 20]
# set syscall args
  ldr r1, [sp, 8]
  ldr r2, [sp, 12]
  ldr r3, [sp, 20]
# syscall
 mov r7, 4
 svc 0x0
# rcc_fun 1 (exit)
  mov r0, 0
  str r0, [sp, 12]
# set syscall args
  ldr r1, [sp, 8]
# syscall
 mov r7, 1
 svc 0x0
  __end_0_1_1:
  add sp, fp, 128
  pop {fp,pc}
```

**Comment by XVilka** [comment] 2015-11-10 15:34
@crowell ping, is this still an issue? What about writing a test for it?

**Comment by radare** [comment] 2015-11-11 07:34
No one tried again, also, that issue depends on arch/os

**Comment by Gromimousse** [comment] 2018-03-08 10:28
The issue is not about having multiple strings in ragg2, but the variable names, as said before.
But ragg2 bugs anyway, I tried to run the code snippet on several machines, and the behaviour is quite messy : 
On my own computer (debian x86-64), when I compile with 
```
ragg2 -O -F hi.r
```
 it doesn't recognize the 64 bits architecture and compiles it on 32 bits. So there is one issue here (and by the way it works on 32 bits, the only one that worked actually !).
On my university computers (which is also debian 64, I have to check the exact difference between the two versions), ragg2 detects the 64 bits and compiles it appropriately, but it seems that the compilation fails anyway, because the asm is badly generated : there are two weird instructions at the beginning that causes a segfault on runtime (before it even does any write syscall)  : 
```
0x40007c:	sub    rsp,0x1045c780
0x400083:	push   0xffffffffc7002169
```
And last try was on my raspberry pi (arm architecture), and the result I've got is the same as crowell : 
```
write(1, 0x400, 4)                      = -1 EFAULT (Bad address)
write(1, 0x400, 4)                      = -1 EFAULT (Bad address)
```
I will try to check r_egg compiler, but can't promise anything (it looks complicated at first view :o)

**Comment by radare** [comment] 2018-03-19 11:11
the number after .var specifies the offset .var0 and .var1 are 1 byte away, and ragg realign those pointers, to be 0 both, so just use proper naming and it should work

**Comment by ret2libc** [comment] 2018-04-06 08:11
@radare I'd move this to next release if you are ok with it.

**Comment by radare** [comment] 2018-04-06 10:02
Sure no hurry for this

**Comment by radare** [comment] 2018-05-10 09:25
the x86 assembler seems to be pretty broken right now
```
[0x100001200]> /a jmp rax
Cannot assemble 'jmp rax' at line 3
```

**Comment by Maijin** [comment] 2018-05-10 15:10
Can't reproduce this /a jmp rax problem

**Comment by radare** [comment] 2018-05-10 19:41
Yeah seems fixed in master now

**Closed** 2018-06-27 16:32 UTC
Labels: ragg2, test-required
