### ISSUE TITLE
mach0  versioninfo not parsed

### ISSUE THREAD

**Issue by radare** [radare/radare2#12619] opened 2019-01-03 11:41 UTC
```
$ rabin2 -H
0x00000624  cmd       9 0x32 LC_BUILD_VERSION
0x00000628  cmdsize     32
0x00000644  cmd      10 0x2a LC_SOURCE_VERSION
0x00000648  cmdsize     16
```

**Comment by radare** [comment] 2019-01-03 11:41
Also:

```
$ rabin2 -V  /bin/ls
$
```

**Comment by Maijin** [comment] 2019-01-03 21:18
Duplicate of https://github.com/radare/radare2/issues/4216

**Closed by Maijin** 2019-01-03 21:18 UTC
Labels: MACH0, RBin, good first issue
