### ISSUE TITLE
bits auto detection breaks ARM bits override

### ISSUE THREAD

**Issue by yawkat** [radare/radare2#6922] opened 2017-03-05 12:10 UTC
When a section in a file is detected to be ARM (for example because of a bx instruction to it), temporary bits overrides (i.e. `pd arm 16`) break for the *first* time executing the command, but work fine afterwards.

This is because, in `r_anal_op` *after* the temporary override is placed in the anal config, [the bit size table is queried](https://github.com/radare/radare2/blob/master/libr/anal/op.c#L101). This function then [overrides](https://github.com/radare/radare2/blob/master/libr/core/cio.c#L278) the `asm.bits` config, but only if its own static variable `oldbits` says a change is required. Since `oldbits` is not updated when other parts of the program set asm.bits, for example the temporary override, it will not wrongly change the config in the second command run.

## Commands

I unfortunately cannot provide a binary to reproduce this with.

```
// 11499368 is registered to be ARM-32 (non-thumb) because of disassembly of a previous branch-exchange instruction.
> pd 1 arm 16 @ 8886742
// asm.bits set to 16 by r_core_seek_archbits
            0x008799d6      1146           mov r1, r2
> pd 1 arm 16 @ 11499368
// asm.bits set to 32 by r_core_seek_archbits
            0x00af7768      7847c046       uxtab16mi r4, r0, r8, ror 8
> pd 1 arm 16 @ 11499368
// asm.bits not changed because r_core_seek_archbits' oldbits static variable is already 32
            0x00af7768      7847           bx pc
```

All commands should yield 16-bit (thumb) disassembly.

## Impact on pdj

Because `pdj` is implemented slightly differently, the `opcode` of the wrongly-analyzed instruction is correct, but the `type` and `esil` are not.

## Workaround

A simple workaround is to run every `pd` command twice. The second iteration will always yield correct results.

**Comment by radare** [comment] 2017-03-06 09:42
Thats because anal hints are not overriding the ranalop call. Which i think it may be interesting to have and then create a new function that does what ranalop does roght now. This way we can avoid having to handle the hints everytime we analyze an opcode. Can you identify where is this happening for your usecase?

**Comment by alvarofe** [comment] 2017-03-06 10:01
I need to simplify `r_core_seek_archbits` I think there is not need to have oldbits any more, cause that is the old way to handle arm/thumb. Will try to refactor and send you a patch so you can test against that binary

**Comment by yawkat** [comment] 2017-03-06 12:57
@alvarofe While removing the `oldbits` check would fix the bug that external changes are not reflected in that field, it would not fix the original issue (temp override) and it would break the workaround.

**Comment by alvarofe** [comment] 2017-03-07 08:10
Is not that just removing the check but rewrite the function because the logic is old. I need to explore it. Yesterday was a rough day and I didn't have time, let see if I can today.

**Comment by alvarofe** [comment] 2017-03-08 21:15
Try with this patch and tell me, i tested on r2r and it pass all of them though i wrote it quickly

```
diff --git a/libr/core/cio.c b/libr/core/cio.c
index ad881ee0d..1f16e379a 100644
--- a/libr/core/cio.c
+++ b/libr/core/cio.c
@@ -247,7 +247,7 @@ beach:
 }
 
 
-static void _set_bits(RCore *core, ut64 addr, int *bits) {
+static void choose_bits_anal_hints(RCore *core, ut64 addr, int *bits) {
 	RAnalRange *range;
 	RListIter *iter;
 	r_list_foreach (core->anal->bits_ranges, iter, range) {
@@ -260,50 +260,18 @@ static void _set_bits(RCore *core, ut64 addr, int *bits) {
 
 
 R_API void r_core_seek_archbits(RCore *core, ut64 addr) {
-	static char *oldarch = NULL;
-	static int oldbits = 0;
-	bool flag = false;
 	int bits = 0;
-	char *arch = (char *)r_io_section_get_archbits (core->io, addr, &bits);
+	const char *arch = r_io_section_get_archbits (core->io, addr, &bits);
 	if (!bits) {
-		_set_bits (core, addr, &bits);
+		//if we found bits related with anal hints pick it up
+		choose_bits_anal_hints (core, addr, &bits);
 	}
-	if (!arch) {
-		arch = strdup (r_config_get (core->config, "asm.arch"));
-		flag = true;
-	} else {
-		arch = strdup (arch);
-	}
-	if (arch && bits) {
-		if (bits != oldbits) {
-			r_config_set_i (core->config, "asm.bits", bits);
-			oldbits = bits;
-		}
-		if (!oldarch) {
-			RBinInfo *info = r_bin_get_info (core->bin);
-			if (info && info->arch) {
-				oldarch = strdup (info->arch);
-			} else {
-				oldarch = strdup (r_config_get (core->config, "asm.arch"));
-				oldbits = r_config_get_i (core->config, "asm.bits");
-			}
-			if (strcmp (arch, oldarch)) {
-				r_config_set (core->config, "asm.arch", arch);
-			}
-		}
-		free (arch);
-		return;
-	}
-	if (oldarch) {
-		if (!(flag && arch && oldarch && !strcmp (oldarch, arch))) {
-			r_config_set (core->config, "asm.arch", oldarch);
-		}
-		R_FREE (oldarch);
+	if (bits) {
+		r_config_set_i (core->config, "asm.bits", bits);
 	}
-	if (oldbits) {
-		r_config_set_i (core->config, "asm.bits", oldbits);
+	if (arch) {
+		r_config_set (core->config, "asm.arch", arch);
 	}
-	free (arch);
 }
 
 R_API bool r_core_seek(RCore *core, ut64 addr, bool rb) {

```

**Comment by radare** [comment] 2017-03-09 09:20
What about a Pr instead

**Comment by yawkat** [comment] 2017-03-09 13:42
@alvarofe I don't think this fixes the original issue, and I believe this breaks the workaround. It just makes the issue appear all the time instead of once.

**Comment by alvarofe** [comment] 2017-03-09 14:36
Did you find  an instance where this behaviour happen? can you cook some test for r2r? check binaries on r2r and tests there, I would appreciate it

**Comment by yawkat** [comment] 2017-03-09 15:38
As I mentioned in the issue, I cannot share the original binary.

A simple test case could be:
```
NAME='bits override for arm'
FILE=-
ARGS=
CMDS='
e asm.arch=arm
e asm.bits=32
wa mov r0, r0
e asm.bits=16
ahb 16
pd 1 arm 32
pd 1 arm 32
'
EXPECT='<...>'
run_test
```

This prints 16 bit output even though 32 bits has been specified on the first try, and on the second try prints the correct 32 bit output. `pdj` also behaves as described in the issue (opcode correct, ESIL and type incorrect).

**Comment by alvarofe** [comment] 2017-03-09 16:15
but when you specify asm.bits=32 but then ahb 16, is used 16 and that is the intended behaviour, about the second time you do pd 1 it should use again 16 bits so i will take a look.

**Comment by yawkat** [comment] 2017-03-09 19:48
@alvarofe but I am manually specifying 32 bits in the `pd` command

**Comment by alvarofe** [comment] 2017-03-09 19:53
almost two years here and i didn't know pd support that hahahah, so that shed some light in order to fix it thanks!

**Comment by Maijin** [comment] 2017-03-11 22:17
Sorry don't know why I closed this apparently @sferrini also got this problem

**Comment by sferrini** [comment] 2017-03-11 22:33
Yep, I have a similar problem with `seek`:

Seems like when I seek to a Thumb function the lowest bit is considered too

```
[0x00008128]> s main
[0x00008261]>
``` 

Instead should be `0x00008260`.

I guess it's because the ARM/Thumb detection is somewhat broken/not implemented..

Can we consider my issue, related to this?

**Comment by yawkat** [comment] 2017-03-12 08:03
That does not sound related. Thumb detection could be better, but this issue is not about thumb detection or seeking, it is about bits overrides for single commands.

**Comment by alvarofe** [comment] 2017-03-12 09:50
which binary is this? it should be substrate 1 already when detecting a thumb symbol so it should be easy to fix. Can you share the bin?

**Comment by sferrini** [comment] 2017-03-12 11:09
Sure, this is the binary: [thumb.zip](https://github.com/radare/radare2/files/836455/thumb.zip)

**Comment by alvarofe** [comment] 2017-03-12 12:05
Fixed in master i am gonna create a test

**Closed by alvarofe** 2017-03-12 12:05 UTC
Labels: ARM, bug
