### ISSUE TITLE
Arm thumb incorrect base of PC-rel load

### ISSUE THREAD

**Issue by aeickho** [radare/radare2#5347] opened 2016-07-18 23:46 UTC
with:
radare2 0.10.5-git 11894 @ linux-x86-64 git.0.10.4-43-g5c4b292
commit: 5c4b292f772cdba2dc03fa0ca4d33264753b29b4 build: 2016-07-19

r2 -a arm -m 0x0800C000 -b 16 

the same problem...  see #4158 
`
0x08020a62      dff8680e       ldr.w r0, [pc, 0xe68]       ; [0x80218d0:4]=0x2001affc 
` 

**calc of 0x80218d0 is incorrect ... correct is 0x80218cc**

see output from:
`arm-none-eabi-objdump  --adjust-vma 0x0800C000 --disassembler-options=force-thumb  -D -b binary -marm
` 

8020a62:       f8df 0e68       ldr.w   r0, [pc, #3688] ; 0x80218cc

**Comment by Maijin** [comment] 2016-07-19 09:05
Did you tried with keystone ? You can install it using `r2pm -i keystone-libs && r2pm -i keystone`
then `r2 -a arm.ks -m 0x0800C000 -b 16` ?

**Comment by radare** [comment] 2016-07-20 09:31
Please add a testcase. Theres a bunch of arm-pc-relative test cases in the r2r repo

Also compare the output with the resulting pointer computed with esil by enabling asm.emu

**Comment by aeickho** [comment] 2016-07-20 13:08
Tnx four your assistance...

I'm looking for other arm-pc-relative tests on "radare2-regressions"  but i can't find, please let me know place for example tests the correct place for "my" test
```

 0x08020a62      dff8680e       8,$$,+,3688,+,[4],r0,=      ; [0x80218d0:4]=0x2001affc
                                ^ is this the problem  8 ?


```

**Comment by aeickho** [comment] 2016-07-20 13:30
#4158
> Try again, i added 3 more tests and tested on real hardware with thumb code, i should test the unaligned loads because i guess the arm mmu is being strict on that. I have changed the analop info and the esil expression. In esil, the pc is preincremented like in real cpus, so theres no need to increment the value of pc

please let me know the place of this tests

**Comment by Maijin** [comment] 2016-07-20 13:31
https://github.com/radare/radare2-regressions/blob/master/t.anal/arm/arm_16

**Comment by aeickho** [comment] 2016-07-20 13:42
your existing test cases working fine .. and there are detecting the problem fine

 https://gist.github.com/aeickho/11e2e46dc86d46e6bfd207b5e0da0f5e

**Comment by aeickho** [comment] 2016-07-21 23:50
the problem was added with 3d9bea75ab6b0ed1ab47ae98e4e4e3ff34cf2f19

see my tests 
https://gist.github.com/aeickho/e0a82aeef271492a53f2b27dbab2ebb0

**Comment by aeickho** [comment] 2016-07-22 00:14
8f6c4716e0b1272eebff9cb74c289b1033a6da9b  is the complete working version

**Comment by XVilka** [comment] 2016-08-09 12:43
Is that this file?

assembly soure
```
        .syntax unified
        .cpu cortex-m4
        .eabi_attribute 27, 3
        .eabi_attribute 28, 1
        .fpu fpv4-sp-d16
        .eabi_attribute 20, 1
        .eabi_attribute 21, 1
        .eabi_attribute 23, 3
        .eabi_attribute 24, 1
        .eabi_attribute 25, 1
        .eabi_attribute 26, 1
        .eabi_attribute 30, 2
        .eabi_attribute 34, 1
        .eabi_attribute 18, 2
        .thumb
        .file   "nullprog.c"
        .section        .text.startup,"ax",%progbits
        .align  2
        .global main
        .thumb
        .thumb_func
        .type   main, %function
 main:
        @ args = 0, pretend = 0, frame = 0
        @ frame_needed = 0, uses_anonymous_args = 0
        @ link register save eliminated.
        ldr.w   r0, [pc, #0] @wide load-instruction, 4-byte aligned
        .word 0
        .word -1
        .short 0
        ldr     r0, [pc, #0] @narrow load-instruction, 2-byte aligned
        .word 0
        .word -1
        bx      lr
        .size   main, .-main
        .ident  "GCC: (4.8.4-1+11-1) 4.8.4 20141219 (release)"
```

Assembled with
```
arm-none-eabi-gcc -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar -c nullprog.s -O2
```

**Comment by radare** [comment] 2016-08-13 11:33
It is fixed already?

**Comment by aeickho** [comment] 2016-08-13 17:34
Temporary I'm on holiday ..  I'll check it on Tuesday.
-alex

Am 13. August 2016 13:33:52 MESZ, schrieb radare <notifications@github.com>:

**Comment by radare** [comment] 2016-08-14 17:40
Release is on monday, so lets put this on 0.10.6, hope its ok because we have some tests and other ppl used it and seems to be fine

**Comment by Maijin** [comment] 2016-08-14 17:42
The existing tests are passing at least now

**Comment by aeickho** [comment] 2016-08-15 21:14
my problem is fixed :) tnx 

but test 5 from "radare2-regressions/t.anal/arm> ./arm_16"  makes **XX**. 
I do not understand the test and the idea of the test. :(

**Comment by Maijin** [comment] 2016-08-16 03:25
@aeickho hum test pass on travis, here too.

**Comment by radare** [comment] 2016-09-18 20:44
so we can close this

**Closed by radare** 2016-09-18 20:44 UTC
Labels: anal, ARM, test-required
