### ISSUE TITLE
Reads only the first 50 bytes of the  ihex:// file

### ISSUE THREAD

**Issue by karones** [radare/radare2#5222] opened 2016-06-28 14:30 UTC
R2 reads only first 50 bytes while opening ihex://, after that all values are just filled with 0xFF. 

> r2 ihex://3.hex 
>  -- Change the UID of the debugged process with child.uid (requires root)
> [0x00000000]> pd 100
>         ,=< 0x00000000      7980           jns 0xffffffffffffff82
>         |   0x00000002      1000           adc byte [rax], al
>        ,==< 0x00000004      7980           jns 0xffffffffffffff86
>        ||   0x00000006      4da7           cmpsq qword [rsi], qword ptr [rdi] ; [0x2700000000:8]=-1 ; 0
>       ,===< 0x00000008      7980           jns 0xffffffffffffff8a
>       |||   0x0000000a      4d6879804d6e   push 0x6e4d8079
>      ,====< 0x00000010      7980           jns 0xffffffffffffff92
>      ||||   0x00000012      4d6879804d68   push 0x684d8079
>     ,=====< 0x00000018      7980           jns 0xffffffffffffff9a
>     |||||   0x0000001a      4d6879804d68   push 0x684d8079
>    ,======< 0x00000020      7980           jns 0xffffffffffffffa2
>    ||||||   0x00000022      4d6879804d68   push 0x684d8079
>   ,=======< 0x00000028      7980           jns 0xffffffffffffffaa
>   |||||||   0x0000002a      4d6879804d68   push 0x684d8079
>   ========< 0x00000030      7980           jns 0xffffffffffffffb2
>   |||||||   0x00000032      4d6879804d68   push 0x684d8079
>   ========< 0x00000038      7980           jns 0xffffffffffffffba
>   |||||||   0x0000003a      4d6879804d68   push 0x684d8079
>   |||||||   0x00000040      ff             invalid
>   |||||||   0x00000041      ff             invalid
>   |||||||   0x00000042      ff             invalid
>   |||||||   0x00000043      ff             invalid

Original string:
:200000007980100079804DA779804D6879804D6E79804D6879804DD979804D6879804D685F

**Comment by Maijin** [comment] 2016-06-28 14:33
我不会说俄语 @XVilka ？

**Comment by XVilka** [comment] 2016-06-28 14:39
我翻译了俄语。

**Comment by radare** [comment] 2016-06-28 14:58
are you using r2 from git? the string you pasted is much smaller than 50 bytes. you can also try changing the block size before calling `pd`. any file to reproduce this?

**Comment by karones** [comment] 2016-06-28 15:24
yes, r2 -version
radare2 0.10.4-git 11658 @ linux-x86-64 git.0.10.3-271-gb03c1e2
commit: b03c1e2b3e6671a1b844fbc3d1d9b1aa6bb463e9 build: 2016-06-20

I tried different block size


[3.txt](https://github.com/radare/radare2/files/337385/3.txt)

**Comment by Maijin** [comment] 2016-06-28 15:25
? Closing ?

**Comment by radare** [comment] 2016-06-28 15:28
its fine, there’s a gap between 0x40 and 0x800

isnt this whats expected?

**Comment by XVilka** [comment] 2016-07-02 19:10
So it's not a bug.

**Comment by XVilka** [comment] 2016-07-02 19:11
@karones write here if you think it's a bug.

**Closed by XVilka** 2016-07-02 19:10 UTC
