### ISSUE TITLE
dyldcache file format support broken

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4392] opened 2016-03-22 16:24 UTC
It takes 100% cpu and extracts no files at all.
The fileformat has changed and the current api changes broke the plugin

**Comment by radare** [comment] 2016-03-22 17:15
it was supporting only 32bit dyldcaches, now they are 64bit (because of arm64).

**Comment by alvarofe** [comment] 2016-03-22 17:18
This can be useful  http://newosxbook.com/tools/joker.html the source code is available

**Comment by radare** [comment] 2016-03-30 13:01
assigned to @lionaneesh

**Comment by radare** [comment] 2016-04-04 22:57
This is fixed now by @alvarofe

**Comment by radare** [comment] 2016-04-04 22:57
we need tests for this, but there are no distributable dyldcache's out there.. so we will need to cook our one. moving this to https://github.com/radare/radare2-regressions/issues/360

**Closed by radare** 2016-04-04 22:57 UTC
Labels: file-format, regression, test-required
