### ISSUE TITLE
wa is broken

### ISSUE THREAD

**Issue by jjdredd** [radare/radare2#1472] opened 2014-10-01 08:46 UTC
`:> s 0x0891c5b1`

**before:**

`0x0891c5b1    668178041f03 cmp word [eax+0x4], 0x31f`
`0x0891c5b7    76df                 jbe 0x891c598 ;[1] `

**command:**

`:> wa cmp word [eax+0x4], 0x190`

**result:**

`Written 3 bytes (cmp word [eax+0x4], 0x190) = wx 83ff00`

`0x0891c5b1    83ff00        cmp edi, 0x0`
`0x0891c5b4    041f           add al, 0x1f`
`0x0891c5b6    0376df       add esi, [esi-0x21]`

**Comment by radare** [comment] 2015-03-23 10:13
Closing, as long as its not a bug in `wa`, but something to enhace in the default assembler if needed.

**Closed by radare** 2015-03-23 10:13 UTC
Labels: architecture, bug
