### ISSUE TITLE
Grep (~) doesn't work on windows

### ISSUE THREAD

**Issue by wargio** [radare/radare2#6895] opened 2017-03-03 16:35 UTC
it simply doesn't work.

```
[0x80000000]> pd 10
            0x80000000      1d000a00       j 0x80000014
            0x80000004      8c80           ld.h d15, [a8]0
            0x80000006      0000           nop
            0x80000008      8c80           ld.h d15, [a8]0
            0x8000000a      0000           nop
            0x8000000c      8c80           ld.h d15, [a8]0
            0x8000000e      0000           nop
            0x80000010      8c80           ld.h d15, [a8]0
            0x80000012      0000           nop
            0x80000014      85f12000       ld.w d1, 0xf0000020
[0x80000000]> pd 10~nop
            0x80000000      1d000a00       j 0x80000014
            0x80000004      8c80           ld.h d15, [a8]0
            0x80000006      0000           nop
            0x80000008      8c80           ld.h d15, [a8]0
            0x8000000a      0000           nop
            0x8000000c      8c80           ld.h d15, [a8]0
            0x8000000e      0000           nop
            0x80000010      8c80           ld.h d15, [a8]0
            0x80000012      0000           nop
            0x80000014      85f12000       ld.w d1, 0xf0000020
```

**Comment by radare** [comment] 2017-03-03 16:43
Wtf is this master or last release?

**Comment by wargio** [comment] 2017-03-03 16:43
master.

**Comment by Maijin** [comment] 2017-03-03 17:09
May explain why lot of tests fail on windows ...

**Comment by radare** [comment] 2017-03-03 17:17
Rconspush/pop regression maybe?

**Comment by radare** [comment] 2017-03-09 20:52
@skuater cant reproduce. which is your environment?

**Comment by skuater** [comment] 2017-03-09 20:58
Yes the problem is present in lastest build from git. Im looking to solve

**Comment by skuater** [comment] 2017-03-10 11:16
fixed on  pr #6976

**Closed** 2017-03-10 11:16 UTC
Labels: bug, Windows
