### ISSUE TITLE
Issue Compiling on i686

### ISSUE THREAD

**Issue by codingHahn** [radare/radare2#10193] opened 2018-05-26 15:26 UTC
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Void Linux x86_64

### Expected behavior
I expect the program to compile on all architectures mentioned in the README.

### Actual behavior
Compilation on i686 failes at line 3700 in this log: https://travis-ci.org/voidlinux/void-packages/jobs/382622408
Even compilation on aarch64-musl completes. I expect it to be something minor that I missed.

### Steps to reproduce the behavior 
- Try to ~~cross~~ compile using the void-linux infrastructure

### Additional Logs, screenshots, source-code,  configuration dump, ...

Compilation on x86_64 completing: https://travis-ci.org/voidlinux/void-packages/jobs/382622407 (Line: 3735)
Compilation in i686 failing: https://travis-ci.org/voidlinux/void-packages/jobs/382622408 (Line: 3700)

**Comment by radare** [comment] 2018-05-26 17:05
`__x86.get_pc_thunk.bx' referenced in section `.text' of .libr/libr_syscall.o: defined in discarded section `.text.__x86.get_pc_thunk.bx[__x86.get_pc_thunk.bx]' of .libr/libr_syscall.o

**Comment by XVilka** [comment] 2018-05-29 12:51
It is because of the mixing PIC and nonPIC code afaik.

**Comment by radare** [comment] 2018-05-29 13:09
Nope its not. The problem is another and its a bug in the toolchains not us. I can do hacks to solve this but is better to just drop the visbilitity bit for the platforms that are failing

**Comment by radare** [comment] 2018-05-30 13:46
should be building now because merged lib is not built by default

**Closed by radare** 2018-05-30 13:46 UTC
Labels: buildsystem, release
