### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#13785] opened 2019-04-16 12:08 UTC
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| r2 -v full output, **not truncated** (mandatory)     |  Latest git

### Expected behavior
Compile

### Actual behavior
Errors out

### Steps to reproduce the behavior 
git clone the repo, sudo sys/install.sh

~~~
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c: In function ‘vas_name’:
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:467:7: error: ‘ARM64_VAS_1B’ undeclared (first use in this function); did you mean ‘ARM64_VAS_1Q’?
  case ARM64_VAS_1B:
       ^~~~~~~~~~~~
       ARM64_VAS_1Q
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:467:7: note: each undeclared identifier is reported only once for each function it appears in
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:469:7: error: ‘ARM64_VAS_4B’ undeclared (first use in this function); did you mean ‘ARM64_VAS_1B’?
  case ARM64_VAS_4B:
       ^~~~~~~~~~~~
       ARM64_VAS_1B
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:471:7: error: ‘ARM64_VAS_2H’ undeclared (first use in this function); did you mean ‘ARM64_VAS_2D’?
  case ARM64_VAS_2H:
       ^~~~~~~~~~~~
       ARM64_VAS_2D
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:473:7: error: ‘ARM64_VAS_1H’ undeclared (first use in this function); did you mean ‘ARM64_VAS_2H’?
  case ARM64_VAS_1H:
       ^~~~~~~~~~~~
       ARM64_VAS_2H
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:475:7: error: ‘ARM64_VAS_1S’ undeclared (first use in this function); did you mean ‘ARM64_VAS_1H’?
  case ARM64_VAS_1S:
       ^~~~~~~~~~~~
       ARM64_VAS_1H
SDB types-x86-windows-64.sdb
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c: In function ‘anop64’:
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2252:7: error: ‘ARM64_INS_PACDA’ undeclared (first use in this function); did you mean ‘ARM64_INS_UADDW’?
  case ARM64_INS_PACDA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_UADDW
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2253:7: error: ‘ARM64_INS_PACDB’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDA’?
  case ARM64_INS_PACDB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2254:7: error: ‘ARM64_INS_PACDZA’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDA’?
  case ARM64_INS_PACDZA:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2255:7: error: ‘ARM64_INS_PACDZB’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDZA’?
  case ARM64_INS_PACDZB:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACDZA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2256:7: error: ‘ARM64_INS_PACGA’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDA’?
  case ARM64_INS_PACGA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2257:7: error: ‘ARM64_INS_PACIA’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACGA’?
  case ARM64_INS_PACIA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACGA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2258:7: error: ‘ARM64_INS_PACIA1716’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA’?
  case ARM64_INS_PACIA1716:
       ^~~~~~~~~~~~~~~~~~~
       ARM64_INS_PACIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2259:7: error: ‘ARM64_INS_PACIASP’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA’?
  case ARM64_INS_PACIASP:
       ^~~~~~~~~~~~~~~~~
       ARM64_INS_PACIA
SDB types-linux.sdb
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2260:7: error: ‘ARM64_INS_PACIAZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA’?
  case ARM64_INS_PACIAZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2261:7: error: ‘ARM64_INS_PACIB’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA’?
  case ARM64_INS_PACIB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2262:7: error: ‘ARM64_INS_PACIB1716’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA1716’?
  case ARM64_INS_PACIB1716:
       ^~~~~~~~~~~~~~~~~~~
       ARM64_INS_PACIA1716
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2263:7: error: ‘ARM64_INS_PACIBSP’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIASP’?
  case ARM64_INS_PACIBSP:
       ^~~~~~~~~~~~~~~~~
       ARM64_INS_PACIASP
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2264:7: error: ‘ARM64_INS_PACIBZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIB’?
  case ARM64_INS_PACIBZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACIB
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2265:7: error: ‘ARM64_INS_PACIZA’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA’?
  case ARM64_INS_PACIZA:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2266:7: error: ‘ARM64_INS_PACIZB’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIZA’?
  case ARM64_INS_PACIZB:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_PACIZA
CC anal_arm_gnu.c
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2267:7: error: ‘ARM64_INS_AUTDA’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDA’?
  case ARM64_INS_AUTDA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2268:7: error: ‘ARM64_INS_AUTDB’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTDA’?
  case ARM64_INS_AUTDB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_AUTDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2269:7: error: ‘ARM64_INS_AUTDZA’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTDA’?
  case ARM64_INS_AUTDZA:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2270:7: error: ‘ARM64_INS_AUTDZB’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTDZA’?
  case ARM64_INS_AUTDZB:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTDZA
CC arc-ext.c
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2271:7: error: ‘ARM64_INS_AUTIA’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTDA’?
  case ARM64_INS_AUTIA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_AUTDA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2272:7: error: ‘ARM64_INS_AUTIA1716’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACIA1716’?
  case ARM64_INS_AUTIA1716:
       ^~~~~~~~~~~~~~~~~~~
       ARM64_INS_PACIA1716
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2273:7: error: ‘ARM64_INS_AUTIASP’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIA’?
  case ARM64_INS_AUTIASP:
       ^~~~~~~~~~~~~~~~~
       ARM64_INS_AUTIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2274:7: error: ‘ARM64_INS_AUTIAZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIA’?
  case ARM64_INS_AUTIAZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2275:7: error: ‘ARM64_INS_AUTIB’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIA’?
  case ARM64_INS_AUTIB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_AUTIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2276:7: error: ‘ARM64_INS_AUTIB1716’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIA1716’?
  case ARM64_INS_AUTIB1716:
       ^~~~~~~~~~~~~~~~~~~
       ARM64_INS_AUTIA1716
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2277:7: error: ‘ARM64_INS_AUTIBSP’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIASP’?
  case ARM64_INS_AUTIBSP:
       ^~~~~~~~~~~~~~~~~
       ARM64_INS_AUTIASP
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2278:7: error: ‘ARM64_INS_AUTIBZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIB’?
  case ARM64_INS_AUTIBZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTIB
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2279:7: error: ‘ARM64_INS_AUTIZA’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIA’?
  case ARM64_INS_AUTIZA:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTIA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2280:7: error: ‘ARM64_INS_AUTIZB’ undeclared (first use in this function); did you mean ‘ARM64_INS_AUTIZA’?
  case ARM64_INS_AUTIZB:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_AUTIZA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2281:7: error: ‘ARM64_INS_XPACD’ undeclared (first use in this function); did you mean ‘ARM64_INS_PACDB’?
  case ARM64_INS_XPACD:
       ^~~~~~~~~~~~~~~
       ARM64_INS_PACDB
CC arc-opc.c
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2282:7: error: ‘ARM64_INS_XPACI’ undeclared (first use in this function); did you mean ‘ARM64_INS_XPACD’?
  case ARM64_INS_XPACI:
       ^~~~~~~~~~~~~~~
       ARM64_INS_XPACD
SDB types-x86-macos-64.sdb
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2283:7: error: ‘ARM64_INS_XPACLRI’ undeclared (first use in this function); did you mean ‘ARM64_INS_XPACI’?
  case ARM64_INS_XPACLRI:
       ^~~~~~~~~~~~~~~~~
       ARM64_INS_XPACI
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2528:7: error: ‘ARM64_INS_BLRAA’ undeclared (first use in this function); did you mean ‘ARM64_INS_BLR’?
  case ARM64_INS_BLRAA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_BLR
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2529:7: error: ‘ARM64_INS_BLRAAZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_BLRAA’?
  case ARM64_INS_BLRAAZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_BLRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2530:7: error: ‘ARM64_INS_BLRAB’ undeclared (first use in this function); did you mean ‘ARM64_INS_BLRAA’?
  case ARM64_INS_BLRAB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_BLRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2531:7: error: ‘ARM64_INS_BLRABZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_BLRAB’?
  case ARM64_INS_BLRABZ:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_BLRAB
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2534:7: error: ‘ARM64_INS_BRAA’ undeclared (first use in this function); did you mean ‘ARM64_INS_BLRAA’?
  case ARM64_INS_BRAA:
       ^~~~~~~~~~~~~~
       ARM64_INS_BLRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2535:7: error: ‘ARM64_INS_BRAAZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_BRAA’?
  case ARM64_INS_BRAAZ:
       ^~~~~~~~~~~~~~~
       ARM64_INS_BRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2536:7: error: ‘ARM64_INS_BRAB’ undeclared (first use in this function); did you mean ‘ARM64_INS_BRAA’?
  case ARM64_INS_BRAB:
       ^~~~~~~~~~~~~~
       ARM64_INS_BRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2537:7: error: ‘ARM64_INS_BRABZ’ undeclared (first use in this function); did you mean ‘ARM64_INS_BRAB’?
  case ARM64_INS_BRABZ:
       ^~~~~~~~~~~~~~~
       ARM64_INS_BRAB
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2540:7: error: ‘ARM64_INS_LDRAA’ undeclared (first use in this function); did you mean ‘ARM64_INS_BRAA’?
  case ARM64_INS_LDRAA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_BRAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2541:7: error: ‘ARM64_INS_LDRAB’ undeclared (first use in this function); did you mean ‘ARM64_INS_LDRAA’?
  case ARM64_INS_LDRAB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_LDRAA
SDB types-arm-ios-16.sdb
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2544:7: error: ‘ARM64_INS_RETAA’ undeclared (first use in this function); did you mean ‘ARM64_INS_RET’?
  case ARM64_INS_RETAA:
       ^~~~~~~~~~~~~~~
       ARM64_INS_RET
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2545:7: error: ‘ARM64_INS_RETAB’ undeclared (first use in this function); did you mean ‘ARM64_INS_RETAA’?
  case ARM64_INS_RETAB:
       ^~~~~~~~~~~~~~~
       ARM64_INS_RETAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2546:7: error: ‘ARM64_INS_ERETAA’ undeclared (first use in this function); did you mean ‘ARM64_INS_RETAA’?
  case ARM64_INS_ERETAA:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_RETAA
/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.c:2547:7: error: ‘ARM64_INS_ERETAB’ undeclared (first use in this function); did you mean ‘ARM64_INS_ERETAA’?
  case ARM64_INS_ERETAB:
       ^~~~~~~~~~~~~~~~
       ARM64_INS_ERETAA
CC be_arm.c
/opt/radare2/libr/../global.mk:36: recipe for target '/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.o' failed
make[3]: *** [/opt/radare2/libr/..//libr/anal/p/anal_arm_cs.o] Error 1
make[3]: *** Waiting for unfinished jobs....
<truncated>
sm.c: In function ‘r_asm_rasm_assemble’:
asm.c:1101:12: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   out.cout = r_strbuf_new ("");
            ^
asm.c:1102:18: warning: passing argument 1 of ‘r_strbuf_init’ from incompatible pointer type [-Wincompatible-pointer-types]
   r_strbuf_init (out.cout);
                  ^~~
In file included from /opt/radare2/libr/include/r_util.h:62:0,
                 from /opt/radare2/libr/include/r_io.h:7,
                 from /opt/radare2/libr/include/r_core.h:9,
                 from asm.c:4:
/opt/radare2/libr/include/r_util/r_strbuf.h:31:12: note: expected ‘RStrBuf * {aka struct <anonymous> *}’ but argument is of type ‘SStrBuf * {aka struct s_strbuf_t *}’
 R_API void r_strbuf_init(RStrBuf *sb);
            ^~~~~~~~~~~~~
asm.c:1109:32: warning: passing argument 1 of ‘r_strbuf_get’ from incompatible pointer type [-Wincompatible-pointer-types]
   lbuf = strdup (r_strbuf_get (out.cout));
                                ^~~
In file included from /opt/radare2/libr/include/r_util.h:62:0,
                 from /opt/radare2/libr/include/r_io.h:7,
                 from /opt/radare2/libr/include/r_core.h:9,
                 from asm.c:4:
/opt/radare2/libr/include/r_util/r_strbuf.h:26:13: note: expected ‘RStrBuf * {aka struct <anonymous> *}’ but argument is of type ‘SStrBuf * {aka struct s_strbuf_t *}’
 R_API char *r_strbuf_get(RStrBuf *sb);
             ^~~~~~~~~~~~
CC op.c
LD libr_asm.so
Makefile:22: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
~~~

**Comment by radare** [comment] 2019-04-16 12:30
do you have capstone from git installed system wide? because capstone-master is broken

cant reproduce this issue anywhere, are you using a clean checkout? or reusing an old clone without doing git clean -xdf ?

**Comment by DigiAngel** [comment] 2019-04-16 13:35
Yes, I do have it installed system wide..my process (which I just updated today):
~~~
for capstone and unicorn:
git clone https://github.com/aquynh/capstone.git
git clone https://github.com/unicorn-engine/unicorn.git
./make.sh
sudo make.sh install
sudo ldconfig
cd bindings/python && python ./setup.py build && sudo python ./setup.py install

keystone
git clone https://github.com/keystone-engine/keystone.git
mkdir -p keystone/build && cd keystone/build
../make-share.sh
sudo make install
sudo ldconfig
cd ../bindings/python && python ./setup.py build && sudo python ./setup.py install
~~~

This has been working fine for a couple years now.  I deleted the radare2 dir and did a fresh git clone.  Pip list shows the below:
~~~
capstone (5.0.0)
keystone-engine (0.9.1.post3)
unicorn (1.0.2)
~~~

Is there another way to validate these are installed correctly?  Thank you.

**Comment by radare** [comment] 2019-04-16 13:39
the problem which i reported already to them, capstone from git in the master branch reports v5, but it actually contains code from v4, so it misses a lot of instructions and oesnt have the changes of the next branch .ive been hitting my head against the wall for several months with all those messy capstone branch usages that was breaking the r2 builds.. the answer is "only use vX branches or releases", everything else is suposed to break and not be stable.

i dont see how do you build r2 in here. r2 should use its own copy of capstone by default unless you use --with-syscapstone

its not about installing it well or wrong. its just that capstone from git is broken beacuse it reports some features it doesnt have. how are you building r2?

**Comment by DigiAngel** [comment] 2019-04-16 13:49
sudo sys/install.sh :)
~~~
WARNING: Updating from remote repository
Already up to date.
Building on Linux : computing number of allowed parallel jobs.
Maximum allowed RAM memory per job is 150000 kB.
Number of CPUs is 4 and current free RAM allows us to run 48 jobs in parallel.
So, the build will run on 4 job(s).

export USE_R2_CAPSTONE=

/opt/radare2
configure-plugins: Loading ./plugins.cfg ..
configure-plugins: Generating libr/config.h ..
configure-plugins: Generating libr/config.mk ..
SHARED: io.shm
STATIC: anal.6502 anal.6502_cs anal.8051 anal.arc anal.arm_cs anal.arm_gnu anal.avr anal.bf anal.chip8 anal.cr16 anal.cris anal.dalvik anal.ebc anal.gb anal.h8300 anal.hexagon anal.i4004 anal.i8080 anal.java anal.m680x_cs anal.m68k_cs anal.malbolge anal.mcore anal.mips_cs anal.mips_gnu anal.msp430 anal.nios2 anal.null anal.pic anal.ppc_cs anal.ppc_gnu anal.riscv anal.rsp anal.sh anal.snes anal.sparc_cs anal.sparc_gnu anal.sysz anal.tms320 anal.v810 anal.v850 anal.vax anal.wasm anal.ws anal.x86_cs anal.xap anal.xcore_cs anal.xtensa anal.z80 asm.6502 asm.6502_cs asm.8051 asm.arc asm.arm_as asm.arm_cs asm.arm_gnu asm.arm_winedbg asm.avr asm.bf asm.chip8 asm.cr16 asm.cris_gnu asm.dalvik asm.dcpu16 asm.ebc asm.gb asm.h8300 asm.hexagon asm.hppa_gnu asm.i4004 asm.i8080 asm.java asm.lanai_gnu asm.lh5801 asm.lm32 asm.m680x_cs asm.m68k_cs asm.malbolge asm.mcore asm.mcs96 asm.mips_cs asm.mips_gnu asm.msp430 asm.nios2 asm.null asm.pic asm.ppc_cs asm.ppc_gnu asm.propeller asm.riscv asm.rsp asm.sh asm.snes asm.sparc_cs asm.sparc_gnu asm.spc700 asm.sysz asm.tms320 asm.tricore asm.v810 asm.v850 asm.vax asm.wasm asm.ws asm.x86_as asm.x86_cs asm.x86_nasm asm.x86_nz asm.xap asm.xcore_cs asm.xtensa asm.z80 bin.any bin.art bin.avr bin.bf bin.bflt bin.bios bin.bootimg bin.cgc bin.coff bin.dex bin.dol bin.dyldcache bin.elf bin.elf64 bin.fs bin.java bin.mach0 bin.mach064 bin.mbn bin.mdmp bin.menuet bin.mz bin.nes bin.nin3ds bin.ninds bin.ningb bin.ningba bin.nro bin.nso bin.omf bin.p9 bin.pe bin.pe64 bin.pebble bin.psxexe bin.qnx bin.sfc bin.smd bin.sms bin.spc700 bin.symbols bin.te bin.vsf bin.wasm bin.xbe bin.xnu_kernelcache bin.z64 bin.zimg bin_ldr.ldr_linux bin_xtr.xtr_dyldcache bin_xtr.xtr_fatmach0 bin_xtr.xtr_pemixed bp.arm bp.bf bp.mips bp.ppc bp.x86 core.a2f core.java crypto.aes crypto.aes_cbc crypto.base64 crypto.base91 crypto.blowfish crypto.cps2 crypto.des crypto.punycode crypto.rc2 crypto.rc4 crypto.rc6 crypto.rol crypto.ror crypto.rot crypto.serpent crypto.xor debug.bf debug.bochs debug.esil debug.gdb debug.io debug.native debug.null debug.qnx debug.rap debug.windbg egg.exec egg.xor fs.ext2 fs.fat fs.fb fs.hfs fs.hfsplus fs.io fs.iso9660 fs.jfs fs.minix fs.ntfs fs.posix fs.r2 fs.reiserfs fs.sfs fs.tar fs.udf fs.ufs fs.xfs io.ar io.bfdbg io.bochs io.debug io.default io.gdb io.gprobe io.gzip io.http io.ihex io.mach io.malloc io.mmap io.null io.procpid io.ptrace io.qnx io.r2k io.r2pipe io.r2web io.rap io.rbuf io.self io.shm io.sparse io.tcp io.w32 io.w32dbg io.windbg io.winedbg io.zip lang.vala parse.6502_pseudo parse.arm_pseudo parse.att2intel parse.avr_pseudo parse.chip8_pseudo parse.dalvik_pseudo parse.m68k_pseudo parse.mips_pseudo parse.mreplace parse.ppc_pseudo parse.sh_pseudo parse.wasm_pseudo parse.x86_pseudo parse.z80_pseudo
cp: './plugins.cfg' and 'plugins.cfg' are the same file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for dynamic library... required
checking for patch... /usr/bin/patch
checking for git... /usr/bin/git
checking for libmagic ... no
Using PKGCONFIG: pkg-config
checking pkg-config flags for capstone... yes
checking for libz ... yes
checking for libzip ... no
checking for libxxhash ... no
checking declaration of ADDR_NO_RANDOMIZE in sys/personality.h... yes
checking function arc4random_uniform() in c... no
checking function explicit_bzero() in c... yes
checking function explicit_memset() in c... no
checking function clock_nanosleep() in c... yes
checking for libssl ... yes
checking pkg-config flags for openssl... yes
checking version of library libuv >= 1.0.0... no
creating ./config-user.mk
creating libr/include/r_userconf.h
creating pkgcfg/r_io.pc
creating pkgcfg/r_magic.pc
creating pkgcfg/r_asm.pc
creating pkgcfg/r_bin.pc
creating pkgcfg/r_anal.pc
creating pkgcfg/r_hash.pc
creating pkgcfg/r_cons.pc
creating pkgcfg/r_core.pc
creating pkgcfg/r_lang.pc
creating pkgcfg/r_socket.pc
creating pkgcfg/r_debug.pc
creating pkgcfg/r_reg.pc
creating pkgcfg/r_config.pc
creating pkgcfg/r_flag.pc
creating pkgcfg/r_syscall.pc
creating pkgcfg/r_util.pc
creating pkgcfg/r_search.pc
creating pkgcfg/r_bp.pc
creating pkgcfg/r_parse.pc
creating pkgcfg/r_fs.pc
creating pkgcfg/r_egg.pc
creating pkgcfg/r_crypto.pc
cleaning temporally files... done

Final report:
 - R_CHECKS_LEVEL = 2
 - PREFIX = /usr
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - HAVE_LIBUV = 0
 - USE_CAPSTONE = 1
 - HAVE_PTRACE = 1
 - USE_PTRACE_WRAP = 1
 - HAVE_FORK = 1
 - VERSION = 3.5.0-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - USE_LIB_XXHASH = 0
 - DEBUGGER = 1
 - CC = gcc
 - USERCC = gcc
 - HAVE_ARC4RANDOM_UNIFORM = 0
 - HAVE_EXPLICIT_BZERO = 1
 - HAVE_EXPLICIT_MEMSET = 0
 - USEROSTYPE = gnulinux
 - LIBVERSION = 3.5.0-git
 - BUILD = x86_64-unknown-linux-gnu
 - HOST = x86_64-unknown-linux-gnu
 - TARGET = x86_64-unknown-linux-gnu
~~~

**Comment by radare** [comment] 2019-04-16 13:58
dont run sys/install.sh as root, otherwise you are building as root , and you only need root to install.

the USE_CAPSTONE line is the one that informs that it is going to build against the system-wide capstone. i will just comment out the code that adds this flag and this way we will avoid people to use systemwide capstone unless specified on purpose.

ive pushed a pr https://github.com/radare/radare2/pull/13786

**Comment by DigiAngel** [comment] 2019-04-16 14:08
Thank you....I'll try again later today.

**Comment by radare** [comment] 2019-04-16 14:55
merged, should be fixed now

**Comment by DigiAngel** [comment] 2019-04-16 14:58
Works like a champ, and compiled as a standard user as well..thanks so much!

**Comment by 0ki** [comment] 2019-06-04 09:53
The problem is back. ./sys/user.sh does fails with this error and cripples r2. Please reopen.

Meanwhile my workaround is:
```
git checkout b453df6
./sys/user.sh
git checkout master
```

**Comment by 0ki** [comment] 2019-06-04 15:07
Full fix:
```
git checkout b453df6
./sys/user.sh
git checkout master
./sys/user.sh
```


Apparently there's something that prevented updating directly from the 6-7 month old version that I had. Sorry, I don't know what.

**Comment by radare** [comment] 2019-06-04 15:20
Proper fix: rm -rf shlr/capstone; sys/install.sh

**Closed** 2019-07-05 10:13 UTC
