### ISSUE TITLE
radare2 can't analyse a DOS binary.

### ISSUE THREAD

**Issue by marespiaut** [radare/radare2#6045] opened 2016-10-26 22:28 UTC
Hello,
I've tried analyzing the french version of the DOS video game **Versailles 1685**, but r2 doesn't recognise it as a 16-bits DOS binary, and can't find an entry point.

```
% rahash2 VERSAILL.EXE
VERSAILL.EXE: 0x00000000-0x000922ee sha256: d00dd09d1a1998686f63419af01b3a7e7818ee4c736739eb14e9a07905988a25
```

According to DOSBox, the entry point should be set to **[0000:03ec]**.

I'm using the latest version of r2 from git.
I don't know if I can share the binary as the game is apparently still sold by the current copyright holder.

**Comment by radare** [comment] 2016-10-27 12:32
can you reproduce this in a binary that can be shared or it is easily available? can you paste the output of `rabin2 -I` ?

**Comment by marespiaut** [comment] 2016-10-27 12:54
@radare Apparently, this is caused by the DOS extender DOS/4G. If I can find a freeware DOS software using DOS/4G, maybe the bug could be reproduced.

```
% rabin2 -I VERSAILL.EXE
havecode false
pic      false
canary   false
nx       false
crypto   false
va       false
bits     64
minopsz  1
maxopsz  16
pcalign  0
endian   little
stripped false
static   true
linenum  false
lsyms    false
relocs   false
binsz    598767
```

**Comment by radare** [comment] 2016-10-27 15:35
awesome! please share it in a PR for the radare2-regressions repo.

**Comment by marespiaut** [comment] 2016-10-27 15:43
> awesome! please share it in a PR for the radare2-regressions repo.

I'm sorry, I don't understand what you mean. Do you want me to share the VERSAILL.EXE binary as a pull request for radare2-regressions?

**Comment by radare** [comment] 2016-10-27 15:44
nope, another bin that can be shared without legal problems and reproduces the same issue

**Comment by marespiaut** [comment] 2016-10-29 12:29
It turns out the freeware DOS game [Cyberdogs 2 (also know as C-Dogs)](https://web.archive.org/web/20050212133345/http://www.orcsoftware.com/~ronny/C-Dogs.html) have the same characteristics as Versailles 1685. I'll upload the binary as soon as possible.

**Comment by marespiaut** [comment] 2016-10-29 12:43
@radare The binary has been merged by @Maijin
https://github.com/radare/radare2-regressions/commit/5176fc1bdeff29449f64856cd20eacd319c45b73

**Comment by Maijin** [comment] 2016-10-29 12:45
Can you add a regression test ? 
Something which test entrypoint is correct:

See example - https://github.com/radare/radare2-regressions/blob/master/t.formats/pe/appendeddata

Do same in a t.formats/mz/XXX

**Comment by marespiaut** [comment] 2016-10-29 16:09
@Maijin Done, I hope I've done it correctly.

**Comment by radare** [comment] 2016-10-30 09:52
Please confirm with other binaries, it was just a silly header check

**Comment by marespiaut** [comment] 2016-10-30 12:15
@radare Everything seems to be OK so far. DOS4G binaries are recognized fine.
However, r2 outputs nothing when I use the command `iz`. Is this normal?

**Comment by Maijin** [comment] 2016-10-30 12:22
Try izz

**Comment by marespiaut** [comment] 2016-10-30 12:23
@Maijin `izz` do work.

**Comment by Maijin** [comment] 2016-10-30 12:23
| iz                 Strings in data sections
| izz                Search for Strings in the whole binary

**Comment by Maijin** [comment] 2016-10-30 12:23
I never use the first one.

**Comment by Maijin** [comment] 2016-10-30 12:24
Add tests for the other issue please 👍

**Comment by marespiaut** [comment] 2016-10-30 12:27
@Maijin It's problematic that `iz` doesn't work, because for all the DOS4G binaries I could get my hands on, the entry point is located on a jump, and the next bytes are a long string of text about the Watcom compiler. r2 reads the string as instructions.

**Comment by Maijin** [comment] 2016-10-30 12:45
Can you create a test ?

**Comment by radare** [comment] 2016-10-30 20:30
Because there's no string sections in mz binaries

**Comment by marespiaut** [comment] 2016-11-01 17:31
@radare I didn't know about that. Thank you.

radare2 is broken again on that issue.

**Comment by radare** [comment] 2016-11-01 17:42
oh, the test you pushed was missing +x so it was not running and got broken later. it’s now corrected. just pull :)

**Comment by marespiaut** [comment] 2016-11-02 14:02
I made a new pull request about a DJGPP DOS binary. rabin2 doesn't even recognise it as a proper MZ binary.

```
$ rabin2 -I ddriving.exe
Warning: File is not MZ
Error in r_bin_object_new: load_bytes failed for mz plugin
Warning: File is not MZ
Error in r_bin_object_new: load_bytes failed for mz plugin
r_bin: Cannot open file
```
https://github.com/radare/radare2-regressions/pull/609

**Comment by alvarofe** [comment] 2016-11-02 16:03
fixed in master

**Closed** 2016-11-02 16:03 UTC
