### ISSUE TITLE
pz arg ignored

### ISSUE THREAD

**Issue by radare** [radare/radare2#7110] opened 2017-03-24 02:51 UTC
Always shows blocksize zoom

**Comment by jroimartin** [comment] 2017-03-26 18:11
Cannot reproduce. Looks like it's working fine here.

**Comment by radare** [comment] 2017-03-27 08:21
Not working at all

**Comment by Maijin** [comment] 2017-03-27 08:50
From @jroimartin 
![image](https://cloud.githubusercontent.com/assets/1408600/24348219/3d86d6b6-12db-11e7-978b-bb3a05c16c87.png)

**Comment by radare** [comment] 2017-03-27 09:19
<img width="506" alt="screen shot 2017-03-27 at 11 16 27" src="https://cloud.githubusercontent.com/assets/917142/24349406/43fa7b2a-12df-11e7-9641-67be76c5b8f3.png">

**Comment by radare** [comment] 2017-03-27 09:20
also if you see the output you will notice that the offset doesnt reflects the reality, its just linear, because of the regression in the step implementation in px. we need tests for pz too. @Maijin wanna help on this?

**Comment by radare** [comment] 2017-03-27 09:20
basically pz breaks hard with va/pa/ -m, -B, ... just play a bit with all this and youll get broken pz quickly

**Comment by jroimartin** [comment] 2017-06-06 00:48
Fixed via #7686

**Closed** 2017-06-06 09:57 UTC
Labels: easy, print

**Comment by jroimartin** [comment] 2017-06-06 10:00
![screen shot 2017-06-06 at 11 59 34](https://cloud.githubusercontent.com/assets/1223476/26823915/a937380e-4aaf-11e7-84f0-821aef9c4ebb.png)
