### ISSUE TITLE
rabin2 -s doesn't list exports of a dll

### ISSUE THREAD

**Issue by Hi-Angel** [radare/radare2#5870] opened 2016-09-28 07:17 UTC
`rabin2 -s` doesn't list exports from a dll *(attached)*, e.g.:

	% rabin2 -s ~/.wine/drive_c/windows/system32/kernel32.dll    
	[Symbols]

	0 symbols
	% rabin2 -version 
	rabin2 0.10.6 12511 @ linux-x86-64 git.0.10.6-5-ge78b561
	commit: e78b56166944dc306be875926fef8ad84d020013 build: 2016-09-28

**Additional information**: the attached kernel32 isn't the vanilla one, but the one from WINE, [specifically this package](https://aur.archlinux.org/packages/wine-gaming-nine/). Also, from the #radare channel:

> (09:12:20) defragger: Hi-Angel: seems to be related to this wine version of kernel32.dll, idapro is also not able to handle this
> (09:12:34) defragger: the real kernel32.dll shows all exports

[kernel32.dll.zip](https://github.com/radare/radare2/files/497315/kernel32.dll.zip)

**Comment by radare** [comment] 2016-09-28 07:58
Tried with -E?

**Comment by Hi-Angel** [comment] 2016-09-28 08:00
/me looks the manual: oh, undocumented feature!

	% rabin2 -E ~/.wine/drive_c/windows/system32/kernel32.dll
	[Exports]

	0 exports
	% rabin2 -sE ~/.wine/drive_c/windows/system32/kernel32.dll
	[Symbols]

	0 symbols
	[Exports]

	0 exports

Alas, this didn't help :/

**Comment by radare** [comment] 2016-09-28 08:18
Its in the help and its also documented in C. If its not in the manpage send a pr

Can you share this dll?

**Comment by Maijin** [comment] 2016-09-28 08:23
Probably duplicate of #5750

**Comment by Hi-Angel** [comment] 2016-09-28 08:31
> If its not in the manpage send a pr

I'm on my way. I'm wondering, how to describe it better than `Show globally exportable symbols`? E.g. in ELF libraries there's no such a term as import/export, shall I add that it's specific to DLLs?

**Comment by Maijin** [comment] 2016-09-28 09:15
`i?` documents iE:
`| iE                 Exports (global symbols)`
Just reuse that

**Comment by Hi-Angel** [comment] 2016-09-28 09:26
@Maijin that's almost what I said.

Anyway, I guess I'll just paste the text as it is in the help, because I found with diff more undocumented options, and they're too poorly documented in the help to understand them without experimenting.

For example, `-G [addr]       load address . offset to header`: what header? Binary, or the `.h` one *(as radare supports both)*? Most likely the latest, because in case of binary one I have no idea how it's supposed to work. Then, what happens if the `.h` has multiple structs?

**Comment by Hi-Angel** [comment] 2016-09-28 09:37
…I mean, I don't mind documenting them in a better way, as well as I understand that `--help` option is not the place for big and detailed docs *(it is what manual is supposed for)*.

But then I'd be glad if someone could answer here how to document them in a better way because experimenting with them for me makes no sense, given there's a bunch of peoples knowing beforehand what the options do.

**Comment by Hi-Angel** [comment] 2016-09-28 10:24
@Maijin what test? dll is attached.

**Comment by rlaemmert** [comment] 2016-09-28 10:31
This seems just a problem with wine dll`s. the real kernel32.dll is working fine. Anyway idapro has the same problems with this dll.

**Comment by Maijin** [comment] 2016-09-28 10:36
Test is writing a proper test for here https://github.com/radare/radare2-regressions

**Comment by Hi-Angel** [comment] 2016-09-28 10:44
Ah, that is. No, it is very unlikely to be a regression, because first time I noticed it, it was yesterday on a very old system with radare2 of version 0.9.6 as maximum.

**Comment by Maijin** [comment] 2016-09-28 10:51
The purpose of this repo is you to write test on testing this functionnality, this can be done without the functionnality currently working it's called TDD, that's what we tried to do on this project so please, send a PR with a test testing this functionality please 👍

**Comment by pinkflawd** [comment] 2016-10-04 16:23
example binary, after aaa the command iE still delivers 0 exports (should have more than 6000 though):
[mfc42u.dll.zip](https://github.com/radare/radare2/files/508980/mfc42u.dll.zip)

**Comment by radare** [comment] 2016-10-05 02:51
Cc @skuater @alvarofe

**Comment by alvarofe** [comment] 2016-10-05 22:58
mmm well the thing with this binary is that export directory is null as just can see 

```
air:pe-fuzz alvaro$ r2 -nn kernel32.dll
 -- Finnished a beer
[0x00000000]> pf.pe_dos_header
    e_magic : 0x00000000 = MZ
     e_cblp : 0x00000002 = 0x0040
       e_cp : 0x00000004 = 0x0001
     e_crlc : 0x00000006 = 0x0000
  e_cparhdr : 0x00000008 = 0x0006
 e_minalloc : 0x0000000a = 0x0000
 e_maxalloc : 0x0000000c = 0xffff
       e_ss : 0x0000000e = 0x0000
       e_sp : 0x00000010 = 0x00b8
     e_csum : 0x00000012 = 0x0000
       e_ip : 0x00000014 = 0x0000
       e_cs : 0x00000016 = 0x0000
   e_lfarlc : 0x00000018 = 0x0060
     e_ovno : 0x0000001a = 0x0000
      e_res : 0x0000001c = [ 0x0000, 0x0000, 0x0000, 0x0000 ]
    e_oemid : 0x00000024 = 0x0000
  e_oeminfo : 0x00000026 = 0x0000
     e_res2 : 0x00000028 = [ 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 ]
   e_lfanew : 0x0000003c = 0x00000060
[0x00000000]> s 0x00000060
[0x00000060]> pf.pe_nt_image_headers64
....
                                     numberOfRvaAndSizes : 0x000000e4 = 0x00000010
                                           dataDirectory :
[
                      struct<pe_image_data_directory>
                               virtualAddress : 0x000000e8 = 0x00000000
                                         size : 0x000000ec = 0x00000000

```

`PE_IMAGE_DIRECTORY_ENTRY_EXPORT` is `0` so the first entry. Thus, it seems this dll doesn't have export information and likely the same reason why ida pro fails.


In a normal dll isn't null

```
                                     numberOfRvaAndSizes : 0x00000184 = 0x00000010
                                           dataDirectory :
[
                      struct<pe_image_data_directory>
                               virtualAddress : 0x00000188 = 0x00017f50
                                         size : 0x0000018c = 0x000000e9
```

Don't know if obscured somehow to hide its content and we can get export in another way.

**Closed** 2016-10-05 23:20 UTC
Labels: bug, test-required
