### ISSUE TITLE
debugger race condition

### ISSUE THREAD

**Issue by Daniele-B** [radare/radare2#11425] opened 2018-09-06 17:25 UTC
I think the debugger has a race condition when you try to script in r2pipe and put breakpoints.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19370 @ linux-x86-64 git.2.9.0-15-ga7122b006  commit: a7122b0062fb306bee53d7a0b8787840a1679ee0 build: 2018-09-06__11:44:45
### Actual behavior
it prints this sometimes
```
Traceback (most recent call last):
  File "ch6_brute.py", line 94, in <module>
    print int(r2.cmd('dr rax'),16) 
ValueError: invalid literal for int() with base 16: hit breakpoint at: 402f08
```

### Steps to reproduce the behavior 

```import r2pipe
r2 = r2pipe.open('whatever',flags=['-2'])

r2.cmd('db 0x4...')
r2.cmd('dc')
print int(r2.cmd('dr rax'),16)
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

![bello](https://user-images.githubusercontent.com/24483823/45174178-73fa4a00-b20a-11e8-8586-f273bf57479e.png)

**Comment by Maijin** [comment] 2018-09-07 08:39
If you are retrieving values, did you tried use r2.cmdj("drj") instead ?

**Comment by Daniele-B** [comment] 2018-09-07 08:53
i tried `r2.cmdj('drj')['rax']`, now i get this:

```
r2pipe.cmdj.Error: No JSON object could be decoded
Traceback (most recent call last):
  File "ch6_brute.py", line 67, in <module>
    check_fun_len = magic.cmdj('drj')['rsi']
TypeError: 'NoneType' object has no attribute '__getitem__'```

**Comment by Daniele-B** [comment] 2018-09-10 13:31
Is there a temporary workaround for this bug?

**Comment by radare** [comment] 2018-09-10 13:47
cant reproduce., and i cant understand why this is considered a race condition at all, when r2pipe for python is syncronous

<img width="729" alt="screen shot 2018-09-10 at 15 46 46" src="https://user-images.githubusercontent.com/917142/45301231-d015e480-b510-11e8-83ee-cf2abd5fc8c8.png">

**Comment by Daniele-B** [comment] 2018-09-10 15:12
I build a script to reproduce the behavior + i've attached the binary i was working on
can you test now?
```
import r2pipe

def r2_write(r2, addr, val):
    r2.cmd('s ' + str(addr))
    r2.cmd('w ' + val.replace(' ', '\\x20'))
    r2.cmd('s-')

def hook_fgets(r2, user_input):
    addr_user_input = int(r2.cmd('dr rdi'), 16)
    r2_write(r2, addr_user_input, user_input)
    magic.cmd('dr rip = 0x00403b28')
    return addr_user_input

magic = r2pipe.open('magic', flags=['-2'])

magic.cmd('aaa')
magic.cmd('ood')

magic.cmd('db 0x00403b23') 
magic.cmd('db 0x00402ef9')
magic.cmd('db 0x00402f03') 

magic.cmd('dc')
user_input = hook_fgets(magic, 'A'*69 +'\00') 
magic.cmd('dc')

for _ in xrange(2):
    input_shift = int(magic.cmd('dr rdx'), 16)
    magic.cmd('dc')
    num_check_chars = int(magic.cmd('dr rsi'), 16)
    right_char_addr = int(magic.cmd('dr rdx'), 16)
    magic.cmd('s ' + str(right_char_addr))
    magic.cmd('pr ' + str(num_check_chars * 8 + 1))
    r2_write(magic, user_input + input_shift, 'ds ')
    magic.cmd('dc')
```
[magic.zip](https://github.com/radare/radare2/files/2367195/magic.zip)

**Comment by Daniele-B** [comment] 2018-09-11 12:43
i think so too, if i remove ` magic.cmd('pr ' + str(num_check_chars * 8 + 1))` line it works.

**Comment by radare** [comment] 2018-10-07 21:30
yeah using pr is not recommended because this can contain any character, even a null byte which will break the r2pipe protocol. its better to use other commands like p8 pr ps to get the data in a 'safe' form and decode it in the proper encoding in the host side.

The solution to fix this would be to implement another protocol (or r2pipe2) which each message contains the length instead of having to find the null byte.

I'm closing this issue and referencing it from the new r2pipe2 issue

**Closed by radare** 2018-10-07 21:30 UTC
Labels: bug, debugger
