### ISSUE TITLE
Memory leak in ag command

### ISSUE THREAD

**Issue by davidt99** [radare/radare2#4692] opened 2016-04-24 08:44 UTC
I'm analyzing a file and calling ag command to each function.
It's seems that there is a memory leak or some cache not been cleared because after each function, the process consumes more and more memory until os kills the process or I finished to go through all the functions, depends on the file size and the amount of the functions.
I'm using the latest version from git.

**Comment by radare** [comment] 2016-04-24 10:21
i have no problems with ag, but i have 32GB of ram and im not using debian, which enforces pretty low memory presures. So if you have a test case to reproduce this let me know :)

does the memory gets freed after ag?

one of the reasons can be because RCons have an al-ways-growing internal framebuffer. which may be quite big depending on the graph size. and we should proabbly shrink it at some point

**Comment by davidt99** [comment] 2016-04-26 17:20
Sorry it took me a long time to find a suitable file.
The file is a dll from skype: [RtmPal](http://www.filedropper.com/rtmpal)
I'm analyzing with aa;aac;aan;
With r2pipe in python, I'm using afl to get all the function and then on by one calling to agj with the function's address.
After some time the process consume 8GB of ram, and then the os (ubuntu server) terminate the process and the memory get freed, but the process becomes a zombie (defunct).

**Comment by Maijin** [comment] 2016-10-25 12:42
@davidt99 can you upload the file on github by drag and dropping .zip here ?

**Comment by Maijin** [comment] 2016-10-25 12:42
Also, is this still reproducible ?

**Comment by dequis** [comment] 2016-11-06 09:36
Reuploaded that file here: [RtmPal.dll.zip](https://github.com/radare/radare2/files/573709/RtmPal.dll.zip)

I worked on agj leaks before (#5213) so it's probably not as bad as before.

Here it gets from 100mb to 250mb RES after 2000ish calls to agj (total of that file is 5473). I used `afl~[0]|sed 's/^/agj /'` and copypasted the commands because lazy.

**Comment by radare** [comment] 2018-04-28 21:13
i think we can close this, after 2 years, this code changed a lot and many memleaks has been fixed. and more will do

**Closed by radare** 2018-04-28 21:13 UTC
Labels: PE, anal, bug
