### ISSUE TITLE
Cursor support in the graph view

### ISSUE THREAD

**Issue by io12** [radare/radare2#10924] opened 2018-08-05 00:47 UTC
Many people prefer to use the graph view most of the time when reversing, but it's annoying to have to switch to the "flat" visual mode, then enable the cursor in order to add comments at a specific place. The graph view supports comments, but you can only control the basic block they're placed in, not the position within the basic block.

**Comment by cyanpencil** [comment] 2018-08-05 16:49
I believe this was already what issue #7248 was about, even if a bit old

**Comment by Maijin** [comment] 2018-08-05 18:06
Duplicate of #7248

**Closed by Maijin** 2018-08-05 18:06 UTC
Labels: consoleui, enhancement, graph, visual
