### ISSUE TITLE
Analysis: After end of BB consider it as data

### ISSUE THREAD

**Issue by cynecx** [radare/radare2#4007] opened 2016-01-23 11:25 UTC
Hello,

I would like to ask if a specific behavior of radare is a bug or not an implemented feature.
So basically what I am doing is to run radare's analysis on a executable which contains obfuscated code.
The analysis works fine but with a catch. It doesn't stop the analysis after an unconditional jump, so it considers the following code (junk code) as a part of the function. But I think that's just a side effect of the actual problem. Please see the code above as explanation.

```
0x00560e67   0      56                    push esi
0x00560e68   4+     e9 10 00 00 00        jmp 0x560e7d ;[1]

0x00560e6d   4      51                    push ecx
0x00560e6e   8+     e5 d6                 in eax, 0xd6
0x00560e70   8      1d 31 ea ce 05        sbb eax, 0x5ceea31
0x00560e75   8      06                    push es
0x00560e76  12+     3b d4                 cmp edx, esp
0x00560e78  12      d4 1b                 aam 0x1b
0x00560e7a  12   3  00 85 96 5e 50 52     add byte [ebp + 0x52505e96], al ; *middle* -1
0x00560e80  12      e9 11 00 00 00        jmp 0x560e96 ;[2]
```

As you can see the last instruction of the first basic block is doing a jump straight into the "middle" of the instruction. IDA on the other hand gives us this code:

```
push    esi
jmp     loc_560E7D
; END OF FUNCTION CHUNK FOR Blah

; ---------------------------------------------------------------------------
db 51h, 0E5h, 0D6h
dd 0CEEA311Dh, 0D43B0605h, 85001BD4h
; ---------------------------------------------------------------------------

xchg    eax, esi

; START OF FUNCTION CHUNK FOR Blah
loc_560E7D:
pop     esi
```

Is it possible to get the same analysis behavior just like IDA ?

Note:
I tried setting these settings for false but still got the old results:

```
e anal.hasnext = false
e anal.afterjump = false
e asm.middle = false
```

**Comment by radare** [comment] 2016-01-23 12:31
Probably eobjmp=true will
Help here. The analysis doesnt marks anything as data (yet)

**Comment by cynecx** [comment] 2016-01-23 13:51
I forgot to include that setting in the post but it's set to true here. Unfortunately it's not working even with that flag enabled.

**Comment by radare** [comment] 2016-01-23 14:14
Can you provide a test script to exemplify it bwtter and ease the testing for fixing

**Comment by cynecx** [comment] 2016-01-23 14:28
Sorry but what do you mean by test script? I would really like to help here but I am not sure what I should provide? (Do you need my radare2rc file? The sample file?)

**Comment by Maijin** [comment] 2016-01-24 08:51
See https://github.com/radare/radare2-regressions

**Comment by cynecx** [comment] 2016-01-24 17:59
Well thank you for that @Maijin but I am not sure how I can describe this behavior with that kind of script.
I tried to dig into the source of radare (disasm part) and my conclusion was that it might be difficult to fix it because of the fact that when radare is disassembling, it's not building basic blocks (although this isn't the part of disassembling, IDA is building basic blocks though). The problem with the example code is that instructions aren't properly aligned, well, they are, but using different alignments to fool disassemblers (Because the instructions after the jump are basically junk). This problem can be solved by building basic blocks, then marking instructions outside the basic blocks as data (This doesn't requires analysis. IDA is doing this.).
I noticed in the source that it has a TODO which describes this problem (disasm.c:2428->support in-the-middle-of-instruction too).

**Comment by radare** [comment] 2016-01-25 15:23
This is very easy to fix and to write a test. im just having no time to focus on this. will queue it in my infinite todo list

**Comment by radare** [comment] 2016-01-25 16:23
I just had 20m before leaving... so i did the adf and adfg commands you are looking for. This should be fixing your issue. Please test.

**Comment by radare** [comment] 2016-01-25 16:24
To close this issue we need:

* [ ] Write tests for this
* [ ] Add config vars to choose word size rules
* [ ] Confirm this fixes the issue
* [ ] Run it automatically from `aaa`

**Comment by radare** [comment] 2016-01-25 16:40
adf is not working properly. i have a partial fix in localhost. will push later

**Comment by cynecx** [comment] 2016-01-26 13:38
@radare are you referring to this commit d2e6ab5 ? It's still not working.
I tried this:

    e anal.eobjmp = true
    e anal.calls = true
    e anal.hasnext = true
    e anal.noncode = true
    o sample
    aaa
    adf @ 0x00401030
    adfg @ 0x00401030
    pd @ 0x560e67
    ; JMP XREF from 0x00401058 (unk)
            0x00560e67      56             push esi
        ┌─< 0x00560e68      e910000000     jmp 0x560e7d
        │   0x00560e6d      51             push ecx
        │   0x00560e6e      e5d6           in eax, 0xd6
        │   0x00560e70      1d31eace05     sbb eax, 0x5ceea31
        │   0x00560e75      06             push es
        │   0x00560e76      3bd4           cmp edx, esp
        │   0x00560e78      d41b           aam 0x1b
        │   0x00560e7a      0085965e5052   add byte [ebp + 0x52505e96], al
        ┌─< 0x00560e80      e911000000     jmp 0x560e96

0x00401030 is the function address and 0x560e67 is a basic block in the functions graph.
Am I calling adf & adfg wrong ?

**Comment by radare** [comment] 2016-01-26 18:03
adf and adfg must be called with after a dot. Because those commands dont do anything, just show thencommands that must be executed. This is useful for testing and debugging until Everything works fine. Please confirm this

**Comment by cynecx** [comment] 2016-01-26 18:43
It didn't work.

[0x00560e67 94% 325 (0x1:-1=1)]> pd $r @ fcn.00408399+1411791 # 0x560e68                     
    ; JMP XREF from 0x00401058 (unk)                                                         
            0x00560e67      56             push esi                                          
        ┌─< 0x00560e68   *  e910000000     jmp 0x560e7d                ;[1]                  
        │   0x00560e6d .dword 0x1dd6e551                                                     
        │   0x00560e71 .dword 0x05ceea31                                                     
        │   0x00560e75 .dword 0xd4d43b06                                                     
        │   0x00560e79 .dword 0x9685001b                                                     
        └─> 0x00560e7d .dword 0xe952505e                                                     
        │   0x00560e81 .dword 0x00000011                                                     
        │   0x00560e85 .dword 0xd160ddbb

**Comment by radare** [comment] 2016-01-27 01:02
Works for me:

https://asciinema.org/a/4z36kxsek4wdebjvgi0qpewl2

**Comment by cynecx** [comment] 2016-01-27 01:27
O.o
https://asciinema.org/a/52higq5s7g6ngbsggi1j0t9iw

**Comment by radare** [comment] 2016-01-27 02:37
do you have a custom radare2rc?

**Comment by cynecx** [comment] 2016-01-27 13:14
Contents of my .radare2rc file

    e scr.utf8 = true
    e anal.eobjmp = true

**Comment by radare** [comment] 2016-01-27 13:15
the eobjmp is the reason of your behaviour

**Comment by cynecx** [comment] 2016-01-27 13:41
Okay I disabled it. It works with the plain wx example but not with the actual sample file.
https://asciinema.org/a/at8tdjmeum419rqo7q218pv8g

**Comment by cynecx** [comment] 2016-01-28 17:05
Am I doing it wrong? Or why is it not working on analyzing that function?

**Comment by radare** [comment] 2016-02-16 11:49
Please try again, i have added some tests. this is happening with anal.afterjmp. we should add more analysis tests feel free to send one for your case

**Comment by cynecx** [comment] 2016-02-16 15:22
https://asciinema.org/a/f3bfa2jt067asmhty7l8c0cas
It's still not working with that file. I also disabled anal.afterjmp. Is it possible to upload that file?

**Comment by radare** [comment] 2016-02-16 15:25
just add .jpg to the file and drag it to github, or just post it somehwere :)

**Comment by cynecx** [comment] 2016-02-16 15:30
Here you go: https://cloud.githubusercontent.com/assets/5961244/13080727/3ba51ca4-d4ca-11e5-906b-78db8180b654.png

:)

**Comment by radare** [comment] 2016-02-16 15:32
oh i see, the patch i posted yesterday was for UJMP instructions not JMPs itself. having the binary would be good for testing, or at least a simple testcase using r2 malloc:// and wx, af...

**Comment by Maijin** [comment] 2016-02-16 20:44
@cynecx Can this binary shared on radare2-regressions, not malware nor copyrighted?

**Comment by cynecx** [comment] 2016-02-16 21:07
Well, this is just an executable containing virtualized code of some hello messageboxes so yes, sure.


On 16 Feb 2016, at 21:44, Maijin <notifications@github.com<mailto:notifications@github.com>> wrote:


@cynecx<https://github.com/cynecx> Can this binary shared on radare2-regressions, not malware nor copyrighted?

-

**Comment by cynecx** [comment] 2016-03-03 17:00
Is there any update on this?

**Comment by itbroz** [comment] 2016-03-03 22:08
Hey sorry for off-topic but is this cynecx the same guy who goes on forums with username nL2TP ? 
i want to ask something if it is............!

**Comment by cynecx** [comment] 2016-03-03 22:33
@itbroz
Sorry but no I am not nL2TP.

**Comment by Maijin** [comment] 2016-03-27 14:22
@cynecx well, was waiting for you to add tests :P

**Comment by cynecx** [comment] 2016-03-27 18:31
@Maijin Oh, I though the asciinema and the sample would be sufficient as I have no idea how to actually write a test for this.

    #!/bin/sh
    
    for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
    
    NAME='adf analysis on an obfuscated executable'
    BROKEN=
    FILE=../../bins/pe/cmd_adf_sample0.exe
    ARGS=
    CMDS='
    e asm.arch=x86
    e asm.bits=32
    e asm.os=linux
    e anal.afterjmp=false
    e anal.bbsplit=true
    e anal.calls=false
    e anal.cjmpref=false
    e anal.jmpabove=true
    e anal.jmpref=true
    e anal.split=true
    aaa
    adf @ sym.testObf27.exe_VirtMe
    .adf @ sym.testObf27.exe_VirtMe
    adf @ 0x00560e67
    .adf @ 0x00560e67
    pi 10 @ 0x00560e67
    '

I came this far as I am not sure how I can EXPECT something that I don't know what I should expect, in terms of I am not sure how the expected return string should look like.

For example:

    0x00000000      push rsi                                                      
    0x00000001      jmp 0x16                                             ;[1]     
    0x00000006 hex length=16 delta=0                                              
    x00000006  51e5 d61d 31ea ce05 063b d4d4 1b00 8596  Q...1....;......           
                                                                               
     ; JMP XREF from 0x00000001 (fcn.00000000)                                     
     0x00000016      pop rsi                                                       
     0x00000017      push rax                                                      

This is the correct output (This is when I am using "wx [...code extracted from binary...]" as input code, but it doesn't work with the executable itself) but the docs about tests says that I should use "pi".

When using pi it gives me this:

    push rsi
    jmp 0x16
    push rcx
    in eax, 0xd6
    sbb eax, 0x5ceea31
    invalid
    cmp edx, esp
    invalid
    sbb eax, dword [rax]
    test dword [rsi - 0x16adafa2], edx

The adf analysis command works on this extracted code:
"wx 56e91000000051e5d61d31eace05063bd4d41b0085965e5052e911000000bbdd60d14f"
but not on the executable itself. The code is an extract from this function: sym.testObf27.exe_VirtMe.

**Comment by cynecx** [comment] 2016-03-27 18:36
I have uploaded the file again in a branch:
https://github.com/cynecx/radare2-regressions/commit/da89db032e02c5af69f29ce3f3cdf5f2efc8319c

**Comment by Maijin** [comment] 2016-03-27 19:28
What about creating a Pull request?

**Comment by cynecx** [comment] 2016-03-27 20:10
@Maijin Sure.

**Comment by radare** [comment] 2016-03-30 11:40
Moving for 0.10.3 because release is inminent and fixing this can result in more regressions. if i have some time ill try to fix it in a PR. but if not, please feel free to suggest fixes to this problem.

**Comment by radare** [comment] 2016-05-04 18:18
See aav

**Comment by radare** [comment] 2016-05-16 02:12
ping

**Comment by cynecx** [comment] 2016-05-18 21:09
Sorry about the delay I was kinda busy. I will test this tomorrow and report back.

**Comment by cynecx** [comment] 2016-05-19 22:43
I am sorry but it seems that I am still getting that old behavior aka. it's still not working.
I basically tried to repeat the same commands as I did before (and the test) plus the additional aav command but it seems that there is no change at all.

**Comment by radare** [comment] 2016-08-08 10:14
can anyone else confirm/test? @alvarofe ?

**Comment by XVilka** [comment] 2018-08-05 16:53
Would be nice to fix it finally.

**Comment by kazarmy** [comment] 2018-08-06 13:42
If the problem is incorrect disassembly, then `pdr.` works:

```
$ r2 bins/pe/cmd_adf_sample0.exe 
 -- Wow, my cat knows radare2 hotkeys better than me!
[0x00401005]> s 0x00560e67
[0x00560e67]> af
[0x00560e67]> pdr.
/ (fcn) fcn.00560e67 6412
|   fcn.00560e67 ();
| ; var int local_4h @ esp+0x4
| ; var int local_8h @ esp+0x8
| ; var int local_10h @ esp+0x10
| ; var int local_24h @ esp+0x24
| ; var int local_28h @ esp+0x28
| 0x00560e67      56             push esi
| 0x00560e68      e910000000     jmp 0x560e7d
| ----------- true: 0x00560e7d
| ; CODE XREF from fcn.00560e67 (0x560e68)
| 0x00560e7d      5e             pop esi
| 0x00560e7e      50             push eax
| 0x00560e7f      52             push edx
| 0x00560e80      e911000000     jmp 0x560e96
| ----------- true: 0x00560e96
| ; CODE XREF from fcn.00560e67 (0x560e80)
| 0x00560e96      0f31           rdtsc
| 0x00560e98      e914000000     jmp 0x560eb1
| ----------- true: 0x00560eb1
| ; CODE XREF from fcn.00560e67 (0x560e98)
| 0x00560eb1      5a             pop edx
```
Graph mode works too.

**Comment by Maijin** [comment] 2018-08-06 13:49
yeah pdr is ok for recursive, but it doesn't fix the issue of data that should be marked as data using `Cd`

**Comment by Maijin** [comment] 2018-08-06 13:51
adfg seems to do the trick

<img width="932" alt="image" src="https://user-images.githubusercontent.com/1408600/43720373-94273f82-9990-11e8-93af-184a660378a6.png">

Should be added to aaa after testing and documentation #10960

**Comment by Maijin** [comment] 2018-11-16 12:58
Currently:

![2018-11-16 12 07 58](https://user-images.githubusercontent.com/1408600/48622647-a7deb200-e9a7-11e8-87eb-bc5d300d33b1.jpg)

In other tool:

<img width="578" alt="screen shot 2018-11-16 at 12 01 49" src="https://user-images.githubusercontent.com/1408600/48622651-a9a87580-e9a7-11e8-9423-c01b824b5cc8.png">

**Comment by radare** [comment] 2018-11-16 13:38
So this is not a jmptbl. But data refrences. The basic aar one should be able to do this

**Comment by kazarmy** [comment] 2018-11-16 13:39
After `af` you get this:

![after_af](https://user-images.githubusercontent.com/12002672/48624642-e7c58980-e9e7-11e8-8ad4-678c57ff177a.png)

which is slightly better

**Comment by Maijin** [comment] 2018-11-16 14:14
@kazarmy ? I don't see the different appart from having the fcn.XXX.

The problem here is that the data should be define with a dword (`Cd` command)

**Comment by kazarmy** [comment] 2018-11-17 09:50
k

**Comment by Maijin** [comment] 2019-02-05 14:19
This is fixed already
<img width="522" alt="image" src="https://user-images.githubusercontent.com/1408600/52279238-67188880-2959-11e9-97eb-8a50002c893d.png">

**Closed by Maijin** 2019-02-05 14:19 UTC
Labels: anal, question, test-required

**Comment by radare** [comment] 2019-02-05 22:46
the first dword looks unaligned, anyone?
