### ISSUE TITLE
Looks like debugger only works on x86

### ISSUE THREAD

**Issue by jpenalbae** [radare/radare2#2464] opened 2015-04-29 10:49 UTC
### Errors

Trying to debug under Linux arm you will find this error when trying to set a breakpoint:

```
[0x76ee4c90]> e asm.bits=16
[0x76ee4c90]> pd 4
           ;-- pc:
           ;-- r15:
           0x76ee4c90    dff868a0     ldr.w sl, [pc, 0x68]              ; [0x76ee4cfc:4]=0x1d304 
           0x76ee4c94    dff86840     ldr.w r4, [pc, 0x68]              ; [0x76ee4d00:4]=0x938 
           0x76ee4c98    6846         mov r0, sp
           0x76ee4c9a    02f0ddfe     bl 0x76ee7a58
              0x76ee7a58() ; pc
[0x76ee4c90]> db 0x76ee4c98
No matching bpsize
Cannot get breakpoint bytes. No r_bp_use()?
Cannot set breakpoint (0x76ee4c98)
[0x76ee4c90]>
```

Stepping also doesn't seem to be working:

```
[0x76ee4c90]> ds
r_debug_select: 1824 1
[+] signal 28 aka SIGWINCH received 0
[0x76ee4c90]> ds
[+] signal 11 aka SIGSEGV received 0
[0x76ef2a78]> ds
[+] signal 11 aka SIGSEGV received 0
```

---
### Source code

Looking at the source code you will find that calls to `r_bp_add_hw` and `r_bp_add_sw` always use a fixed breakpoint size of 1 byte:

https://github.com/radare/radare2/blob/master/libr/core/cmd_debug.c#L1244

``` c
        } else {
            if (hwbp) bpi = r_bp_add_hw (core->dbg->bp, addr, 1, R_BP_PROT_EXEC);
            else bpi = r_bp_add_sw (core->dbg->bp, addr, 1, R_BP_PROT_EXEC);
            if (!bpi) eprintf ("Cannot set breakpoint (%s)\n", input+2);
        }
```

https://github.com/radare/radare2/blob/master/libr/core/cmd_debug.c#L1275

``` c
        } else {
            addr = r_num_math (core->num, input+2);
            if (validAddress (core, addr)) {
                if (hwbp) bpi = r_bp_add_hw (core->dbg->bp, addr, 1, R_BP_PROT_EXEC);
                else bpi = r_bp_add_sw (core->dbg->bp, addr, 1, R_BP_PROT_EXEC);
                if (!bpi) eprintf ("Cannot set breakpoint (%s)\n", input+2);
            } else eprintf ("Can't place a breakpoint here. No mapped memory\n");
        }
```

https://github.com/radare/radare2/blob/master/libr/core/cmd_debug.c#L1641

``` c
        if (addr) {
            eprintf ("Continue until 0x%08"PFMT64x"\n", addr);
            bypassbp (core);
            r_reg_arena_swap (core->dbg->reg, R_TRUE);
            r_bp_add_sw (core->dbg->bp, addr, 1, R_BP_PROT_EXEC);
            r_debug_continue (core->dbg);
            checkbpcallback (core);
            r_bp_del (core->dbg->bp, addr);
        } else eprintf ("Cannot continue until address 0\n");
```

---

This prevents radare from finding a suitable breakpoint for archs other than x86 which do not support 1 byte instructions:

https://github.com/radare/radare2/blob/master/libr/bp/bp.c#L46

``` c
R_API int r_bp_get_bytes(RBreakpoint *bp, ut8 *buf, int len, int endian, int idx) {
    int i;
    struct r_bp_arch_t *b;
    if (bp->cur) {
        // find matching size breakpoint
        for (i=0; i<bp->cur->nbps; i++) {
            b = &bp->cur->bps[i];
            if (bp->cur->bps[i].length == len) {
                memcpy (buf, b->bytes, b->length);
                return b->length;
            }
        }
        // TODO: this must be reworked to work better
        /* if not found try to pad with the first one */
        b = &bp->cur->bps[0];
        if (len % b->length) {
            eprintf ("No matching bpsize\n");
            return 0;
        }
        for (i=0;i<len;i++) {
            memcpy (buf+i, b->bytes, b->length);
        }
        return b->length;
    }
    return 0;
}
```

---

Only x86 and brainfuck support 1 byte lenght breakpoints as can be seen here:
https://github.com/radare/radare2/tree/master/libr/bp/p

``` c
#include <r_bp.h>
#include <r_lib.h>

static struct r_bp_arch_t r_bp_plugin_arm_bps[] = {
    { 4, 0, (const ut8*)"\x01\x00\x9f\xef" }, // le         - linux only? (undefined instruction)
    { 4, 1, (const ut8*)"\xef\x9f\x00\x01" }, // be
#if 0
    { 4, 0, (const ut8*)"\xfe\xde\xff\xe7" }, // arm-le     - from a gdb patch
    { 4, 1, (const ut8*)"\xe7\xff\xde\xfe" }, // arm-be
        { 4, 0, (const ut8*)"\xf0\x01\xf0\xe7" }, // eabi-le    - undefined instruction - for all kernels
    { 4, 1, (const ut8*)"\xe7\xf0\x01\xf0" }, // eabi-be
#endif
    { 2, 0, (const ut8*)"\xde\x01" },         // thumb-le
    { 2, 1, (const ut8*)"\x01\xde" },         // thumb-be
    { 2, 0, (const ut8*)"\xfe\xdf" },         // arm-thumb-le
    { 2, 1, (const ut8*)"\xdf\xfe" },         // arm-thumb-be
    { 0, 0, NULL }
};

struct r_bp_plugin_t r_bp_plugin_arm = {
    .name = "arm",
    .arch = "arm",
    .nbps = 6,
    .bps = r_bp_plugin_arm_bps,
};

#ifndef CORELIB
struct r_lib_struct_t radare_plugin = {
    .type = R_LIB_TYPE_BP,
    .data = &r_bp_plugin_arm,
};
#endif
```

So I'm assuming debugger is broken for ppc, arm, mips and sh.

---
### Conclusions

All the code to support multiple archs is already there, but for some reason calls to `r_bp_add_sw` always use a hardcoded bp lenght of 1 byte. Have breakpoints worked ever before? Did anyone changed this? why?

To fix this, we could always assume the following bp lengths based on arch:
- x86: 1 byte
- ppc: 4 bytes
- bf: 1 byte
- mips: 4 bytes
- sh: 2 bytes
- sparc: 4 bytes
- arm: 2/4 bytes

The major problem would be arm cause we should be aware if the program is using arm or thumb mode before choosing a breakpoint length.

Any ideas?

**Comment by jvoisin** [comment] 2015-04-29 11:05
Let the user chose between arm or thumb?

The code used to set software breakpoints with a size of `1` is pretty old, more than 3 years.

**Comment by radare** [comment] 2015-04-29 11:07
Blame @skuater for this breakage :p

**Comment by jpenalbae** [comment] 2015-04-29 11:11
For ARM we could lookup asm.bits in order to check if user enabled thumb or not. Most of the time thumb code is mixed with arm code, and I'm not sure if we should look for the length of the opcode where the breakpoint is to be set, instead of checking  asm.bits.

I should do some testing to see which approach works better.

**Comment by jpenalbae** [comment] 2015-04-29 11:21
Besides, I'm not sure if its worth to set bp size as argument in `r_bp_add_sw()` and `r_bp_add_hw()`, or we should remove that argument and make a new helper function inside `bp.c`to calculate the proper bp size and call it from `r_bp_add()`

**Comment by radare** [comment] 2015-04-29 12:25
The bp api allows to specify the bp size already. If the bp is for thumb it will be 2 byte length. Maybe this should be done explictly by the user or implicit by checking fcn->bits or section->bits if available

**Comment by jvoisin** [comment] 2015-04-29 16:13
Checking `fcn->bits` or `section->bits` seems nice to me.
We can even check both, and warn if they don't match.

**Comment by radare** [comment] 2015-05-31 20:40
Uhm, this looks like a good bug to fix before release

**Comment by radare** [comment] 2015-06-01 14:19
The problem is only related to breakpoints, see last commit, its not correct, but may help to understand the issue

**Comment by jpenalbae** [comment] 2015-06-01 16:49
I don't understand why stepping wasn't working for me...

**Comment by radare** [comment] 2015-06-01 17:14
Softstepping will not work. So stepping will fail on mips, sparc, .. Because it depends on breakpoints, if u have some time check out the current head to see if it works for u

**Comment by radare** [comment] 2015-10-29 13:15
uh? isnt it working for arm already? can you retest?

**Comment by radare** [comment] 2015-11-18 23:19
Hello? :p it works on arm64 and was working on arm32 too, buti just neednconfirmation. Run the latest android r2 in console, type ood enter visual mode and do some steps

**Comment by jpenalbae** [comment] 2015-11-19 04:04
I was talking about linux, not android.

Stepping seems to be working fine, but breakpoints do not. After hitting a break point if you try to step or continue you get this:
```
[0xb6f1b894]> db 0xb6f1b8b0
[0xb6f1b894]> dc
[+] signal 4 aka SIGILL received 0
[0xb6f1b894]> dr pc
0xb6f1b8b0
[0xb6f1b894]> ds
Breakpoint already set at this address.
Interrupted by a breakpoint
[+] signal 4 aka SIGILL received 0
[0xb6f1b894]> ds
Breakpoint already set at this address.
Interrupted by a breakpoint
[+] signal 4 aka SIGILL received 0
[0xb6f1b894]> ds
Breakpoint already set at this address.
Interrupted by a breakpoint
[+] signal 4 aka SIGILL received 0
[0xb6f1b894]> dc
Breakpoint already set at this address.
[+] signal 4 aka SIGILL received 0
[+] signal 4 aka SIGILL received 0
[0xb6f1b894]> 
```

Also looks like there is some problem with conditional jumps, they look fine when opening the binary without `-d` but when using `-d` everything looks like a mess...

```
            0xb6f1b8a4    0022           movs r2, 0
            0xb6f1b8a6    7944           add r1, pc
            0xb6f1b8a8    2b46           mov r3, r5
            0xb6f1b8aa    a0a8           add r0, sp, 0x280
            0xb6f1b8ac    03f8012b       strb r2, [r3], 1
            ;-- pc:
            ;-- r15:
            0xb6f1b8b0 b  8342           cmp r3, r0
        ,=< 0xb6f1b8b2    fad3           blo 0xb6f1b8aa                ;[1]
        |   0xb6f1b8b4    dff85024       ldr.w r2, [pc, 0x450]         ; [0xb6f1bd0c:4]=0x2473a
        |   0xb6f1b8b8    dff85034       ldr.w r3, [pc, 0x450]         ; [0xb6f1bd10:4]=0x242de
        |   0xb6f1b8bc    aff22c04       subw r4, pc, 0x2c
        |   0xb6f1b8c0    8a58           ldr r2, [r1, r2]
        |   0xb6f1b8c2    7b44           add r3, pc
        |   0xb6f1b8c4    22f00102       bic r2, r2, 1
        |   0xb6f1b8c8    1b68           ldr r3, [r3] |   0xb6f1b8ca    a41a           subs r4, r4, r2
```

That jump should point upwards instead of downwards. If you follow the jump pressing the key `[1]` it takes you to `0xffffffffb6f1b8aa` instead of `0xb6f1b8aa`.

Entry point also seems to be messed up when using debug mode:

```
$ r2  ./test
[0x000102f4]> pd 1 @ entry0
            ;-- entry0:
            ;-- _start:
            ;-- section_end..plt:
            ;-- section..text:
            0x000102f4    4ff0000b       mov.w fp, 0                   ; [12] va=0x000102f4 pa=0x000002f4 sz=368 vsz=368 rwx=--r-x .text

$ r2 -d  ./test
Process with PID 15232 started...
Attached debugger to pid = 15232, tid = 15232
Debugging pid = 15232, tid = 15232 now
Using BADDR 0x10000
Assuming filepath /usr/bin/./test
bits 16
Attached debugger to pid = 15232, tid = 15232
 -- Insert coin to continue..
[0xb6fa5bc0]> pd 1 @ entry0
            ;-- entry0:
            0x0001113c    ffffffff       invalid
```

**Comment by radare** [comment] 2015-11-19 08:52
what if you drop the breakpoint before continuing?

**Comment by jpenalbae** [comment] 2015-11-19 11:02
After removing the bp, stepping works as long you do not set the breakpoint again...

```
[0xb6f95894]> db 0xb6f958b0
[0xb6f95894]> dc
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b0
[0xb6f95894]> ds
Breakpoint already set at this address.
Interrupted by a breakpoint
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b0
[0xb6f95894]> ds
Breakpoint already set at this address.
Interrupted by a breakpoint
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b0
[0xb6f95894]> db- 0xb6f958b0
[0xb6f95894]> ds
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b2
[0xb6f95894]> db 0xb6f958b0
[0xb6f95894]> ds
Breakpoint already set at this address.
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b2
[0xb6f95894]> dr pc
0xb6f958b2
[0xb6f95894]> ds
Breakpoint already set at this address.
[+] signal 4 aka SIGILL received 0
[0xb6f95894]> dr pc
0xb6f958b2
```

**Comment by radare** [comment] 2015-11-19 11:07
so thats clearly an issue with the breakpoint size, because on x86 bps are 1 byte, and here they are 2-4.. if you have some time for experimentation i guess that adding some printfs will help to find the root of the issue.

**Comment by radare** [comment] 2015-11-25 21:18
I tried on ubuntutouch, naitve linux-arm, debugging in thumb worked perfectly fine, with breakpoints, steps, etc.. i will close this issue for now. when the ios port is done we can do more testing. android builds seems to be fine too, for arm and arm64

**Comment by alvarofe** [comment] 2016-02-20 17:09
I think i am experiencing the same issue with iOS. When i set a breakpoint i get `EXC_BAD_INSTRUCTION`, because it can't find a breakpoint and it fallback https://github.com/radare/radare2/blob/63956d67af9223f680942aa83f3ea8c0aea4d04c/libr/bp/bp.c#L69 i think we should look this with more care to set the breakpoint smarter at least with arm due to its idiosyncrasy.

skimming through gdb source code `arm-tdep.c`


```C
static const unsigned char *
arm_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
{
  struct gdbarch_tdep *tdep = gdbarch_tdep (gdbarch);
  enum bfd_endian byte_order_for_code = gdbarch_byte_order_for_code (gdbarch);

  if (arm_pc_is_thumb (gdbarch, *pcptr))
    {
      *pcptr = UNMAKE_THUMB_ADDR (*pcptr);

      /* If we have a separate 32-bit breakpoint instruction for Thumb-2,
	 check whether we are replacing a 32-bit instruction.  */
      if (tdep->thumb2_breakpoint != NULL)
	{
	  gdb_byte buf[2];
	  if (target_read_memory (*pcptr, buf, 2) == 0)
	    {
	      unsigned short inst1;
	      inst1 = extract_unsigned_integer (buf, 2, byte_order_for_code);
	      if (thumb_insn_size (inst1) == 4)
		{
		  *lenptr = tdep->thumb2_breakpoint_size;
		  return tdep->thumb2_breakpoint;
		}
	    }
	}

      *lenptr = tdep->thumb_breakpoint_size;
      return tdep->thumb_breakpoint;
    }
  else
    {
      *lenptr = tdep->arm_breakpoint_size;
      return tdep->arm_breakpoint;
    }
}

```

gdb checks `CPSR` to see the bit T, the destination address to know if the LSB is 0 and so on

Furthermore i've noticed that in `libr/bp/p/bp_arm.c`

```C
         { 16, 2, 0, (const ut8*)"\xde\x01" },         // thumb-le                                                                                                           |@
         { 16, 2, 1, (const ut8*)"\x01\xde" },         // thumb-be                                                                                                           |@
         { 16, 2, 0, (const ut8*)"\xfe\xdf" },         // arm-thumb-le
```

so if in the function `r_bp_get_bytes` `bp->bits == 16, bp->size == 2, endian == 0` will pick the first one even though there is an another candidate that could be the correct one.

So the question how would we approach this? the same as gdb does adding functionality to RBreakpointPlugin?

**Comment by radare** [comment] 2016-02-20 22:20
right now the bp sequence is defined by the value in asm.bits.

there’s one arm hex instruction that is a breakpoint for thumb and arm at the same time, so it is ok to useit unless the next instruction is the destination of a branch. this logic cant be predicted in the current api, but this opens the door to much more complex breakpoint machinery. not sure if really matters to overengineer this part.

the asm.bits should be automatically changed depending on the cpu state. see output of dr*

**Comment by unixfreaxjp** [comment] 2016-04-11 08:57
Just installed the commit d1530d54115e31bff64f768c38b83390c40d803b on: 
```
vmlinuz-3.2.0-4-versatile
```
All seem works except the step up. I searched the web & found this thread.
Using sample of x32 ARM. Snips for the error part is:
```asm
-armel:~/test$ r2 -d sample.mmd
Process with PID 2962 started...
attach 2962 2962
bin.baddr 0x00008000
Assuming filepath ./sample.mmd
Warning: Cannot initialize dynamic strings
asm.bits 32
 -- Use the '[' and ']' keys in visual mode to adjust the screen width
[0x00008190]>
[0x00008190]> ie
[Entrypoints]
vaddr=0x00008190 paddr=0x00000190 baddr=0x00008000 laddr=0x00000000 type=program

1 entrypoints

[0x00008190]> ds
p/native/linux/linux_debug.c:71 native-singlestep: Input/output error
Stepping failed!
[0x00008190]> !locate linux_debug.c
/home/MMD/radare2/libr/debug/p/native/linux/linux_debug.c
[0x00008190]> !nl /home/MMD/radare2/libr/debug/p/native/linux/linux_debug.c |head -88|tail -30
    56  }
    57  int linux_step (RDebug *dbg) {
    58          int ret = false;
    59          ut64 addr = 0; /* should be eip */
    60          //ut32 data = 0;
    61          //printf("NATIVE STEP over PID=%d\n", pid);
    62          addr = r_debug_reg_get (dbg, "pc");
    63          ret = ptrace (PTRACE_SINGLESTEP, dbg->pid,
    64                  (void*)(size_t)addr, 0);
    65          linux_handle_signals (dbg);
    66          if (ret == -1) {
    67           perror ("native-singlestep");
    68           ret = false;
    69          } else {
    70           ret = true;
    71          }
    72          return ret;
    73  }
    74  int linux_attach (RDebug *dbg, int pid) {
    75          int ret = -1;
    76          int traceflags = 0;
    77          if (dbg->trace_forks) {
    78           traceflags |= PTRACE_O_TRACEFORK;
    79           traceflags |= PTRACE_O_TRACEVFORK;
    80           traceflags |= PTRACE_O_TRACEVFORKDONE;
    81          }
    82          if (dbg->trace_clone) {
    83           // threads
[0x00008190]>
```
breakpoints seems fine:
```asm
[0x00008190]> pd 14
            ;-- entry0:
            ;-- pc:
            ;-- r15:
            0x00008190      00b0a0e3       mov fp, 0
            0x00008194      00e0a0e3       mov lr, 0
            0x00008198      04109de4       pop {r1}
            0x0000819c      0d20a0e1       mov r2, sp
            0x000081a0      04202de5       str r2, [sp, -4]!
            0x000081a4      04002de5       str r0, [sp, -4]!
            0x000081a8      10c09fe5       ldr ip, [pc, 0x10]          ; [0x81c0:4]=0x12f6c section..fini
            0x000081ac      04c02de5       str ip, [sp, -4]!
            0x000081b0      0c009fe5       ldr r0, [pc, 0xc]           ; [0x81c4:4]=0xfabc
            0x000081b4      0c309fe5       ldr r3, [pc, 0xc]           ; [0x81c8:4]=0x8094 section..init
        ,=< 0x000081b8      c22700ea       b 0x120c8
        |   0x000081bc      ba2400eb       bl 0x114ac
        |   0x000081c0      6c2f0100       andeq r2, r1, ip, ror 30
        |   0x000081c4      bcfa0000       strheq pc, [r0], -ip
[0x00008190]> db 0x000081c4
[0x00008190]> db
0x000081c4 - 0x000081c84 --x sw break enabled cmd="" name="0x000081c4"
[0x00008190]> dbc 0x000081c4 nop
[0x00008190]> db
0x000081c4 - 0x000081c84 --x sw break enabled cmd="nop" name="0x000081c4"
```
↑except can't step up.

Eliminating the ptrace() call since the gdb stepping works:
```asm
(gdb) x/6i 0x00008190
   0x8190:      mov     r11, #0
   0x8194:      mov     lr, #0
   0x8198:      pop     {r1}    ; (ldr r1, [sp], #4)
=> 0x819c:      mov     r2, sp
   0x81a0:      push    {r2}    ; (str r2, [sp, #-4]!)
   0x81a4:      push    {r0}    ; (str r0, [sp, #-4]!)
(gdb) si 1
(gdb) x/6i 0x00008190
   0x8190:      mov     r11, #0
   0x8194:      mov     lr, #0
   0x8198:      pop     {r1}    ; (ldr r1, [sp], #4)
   0x819c:      mov     r2, sp
=> 0x81a0:      push    {r2}    ; (str r2, [sp, #-4]!)
   0x81a4:      push    {r0}    ; (str r0, [sp, #-4]!)
(gdb)
```
adjustment is needed in /libr/debug/p/native/linux/linux_debug.c, but maybe is not related to this thread.

**Comment by radare** [comment] 2016-04-11 09:10
this arm cpu probably doesnt have hardware stepping feature. so you can use the software stepping by enableing it this way:

e dbg.swstep = true

**Comment by unixfreaxjp** [comment] 2016-04-11 09:31
> this arm cpu probably doesnt have hardware stepping feature. so you can use the software stepping by enableing it this way: 
```
e dbg.swstep = true
```
works! thank you.

**Comment by radare** [comment] 2017-01-31 21:16
I think this is fixed already, but maybe @leberus can't have a look at it to confirm that

**Comment by leberus** [comment] 2017-01-31 22:58
Its working on x86/x86_64. I'll check it out tomorrow on arm/arm64

El dia 31/01/2017 22:16, "radare" <notifications@github.com> va escriure:

**Comment by unixfreaxjp** [comment] 2017-02-01 04:15
From my side, confrimed, fixed. Do we need to bring the tests to linux MIPS and PPC too?

**Comment by radare** [comment] 2017-02-01 09:46
it was forking for mips last time i tried.. as well as osxppc, didnt tried on linux-ppc, but i think we can close the issue and open others if debugger fails in other specific platforms

**Closed by radare** 2017-02-01 09:46 UTC
Labels: bug, debugger, question

**Comment by unixfreaxjp** [comment] 2017-02-01 11:28
I will pin heavy tests on ppc/mips/arm linux after release. Upgrading & preparing full platform for it now.
> it was forking for mips last time i tried.. as well as osxppc, didnt tried on linux-ppc, 
> but i think we can close the issue and open others if debugger fails in other specific platforms
