### ISSUE TITLE
Request debug help changes pc

### ISSUE THREAD

**Issue by q6r** [radare/radare2#3183] opened 2015-08-27 13:34 UTC
```
➜  tmp  r2 -D gdb ./rev     
Debugging pid = 8, tid = 8 now
 -- Use 'e asm.offset=true' to show offsets in 16bit segment addressing mode.
[0x00400410]> ds?
|Usage: ds Step commands
| ds             Step one instruction
| ds <num>       Step <num> instructions
| dsf            Step until end of frame
| dsi <cond>     Continue until condition matches
| dsl            Step one source line
| dsl <num>      Step <num> source lines
| dso <num>      Step over <num> instructions
| dsp            Step into program (skip libs)
| dss <num>      Skip <num> step instructions
| dsu <address>  Step until address
| dsui <instr>   Step until an instruction that matches `instr`
| dsue <esil>    Step until esil expression matches
| dsuf <flag>    Step until pc == flag matching name
[0x00000000]> # wtf
^D
```

as seen in libr/core/cmd_debug.c. follow is no matter what's passed as input to the cmd_debug_* functions, which will cause pc to change at the end of the function.

eg:
```
2610     case 's':                                                                                                                                                                 
2611         cmd_debug_step (core, input);                                                                                                                                         
2612         follow = r_config_get_i (core->config, "dbg.follow");                                                                                                                 
2613         break; 
```

r2 bb7774ce3...

**Comment by radare** [comment] 2015-08-27 13:38
reproduced without GDB too. it’s just an esil step. nothing to worry, but will be fixed soon.

**Comment by radare** [comment] 2015-08-27 13:41
sorry, its because of dbg.follow, if you set that to false it will not change the current seek. neither esil or the selected debugger backend execute any step at all.

**Closed** 2015-08-27 13:57 UTC
