### ISSUE TITLE
bokken: installing python bindings using anaconda

### ISSUE THREAD

**Issue by BogusLogin** [radare/radare2#3404] opened 2015-10-02 08:24 UTC
I'm trying to run bokken using radare2, therefore I installed python-bindings via radare2/sys/python.sh

Because I'm using anaconda, the r2 modules ended up in the wrong directory, so I had to manually copy them over to my conda directory. When I try to run bokken I still get the message "Radare availability... D'oh!"

any ideas?

**Comment by alvarofe** [comment] 2015-10-02 13:25
if i remember properly bokken has an option to specify the directory where you have the radare2 dir

**Comment by BogusLogin** [comment] 2015-10-02 18:49
that's interesting since radare is callable from the console, but  bokken.py can't find it. I tried to pass the radare dir as an argument to the script, but that failed too.

**Comment by radare** [comment] 2015-10-03 10:47
bokken uses the r2 valabind bindings, it doesnt needs any executable from r2. so you need to have r2-bindings-python installed and r2 libs. What is anaconda? Try to run the python test programs to see if your python can import r_core for example

**Comment by BogusLogin** [comment] 2015-10-03 19:48
thx for your comment. I tried to import r_core and it failed with the following msg:
ImportError: ./_r_core.so: undefined symbol: r_anal_state_set_depth

**Comment by radare** [comment] 2015-10-04 07:26
How did you build the bindings? Can you compile them again, now that the system is clean?

**Comment by radare** [comment] 2015-10-12 13:14
Maybe @hteso can add some comments on this, as long as he is the author of bokken

**Comment by Maijin** [comment] 2015-11-06 16:05
ping @hteso

**Comment by radare** [comment] 2015-11-20 00:29
Closing this bug as long as its clearly not a bug in r2, please open the issue in radare2-bindings or bokken itself. because bindings are working, and bokken is also working fine, so it's a problem in your installation or linux distro

**Closed by radare** 2015-11-20 00:29 UTC
