### ISSUE TITLE
r2 "That's too deep" although the file is not that deep

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4746] opened 2016-05-02 09:05 UTC
Hi,
 
When I'm analyzing this file (Legit windows file):
http://www.filedropper.com/iertutil

I get this output:
[x] Analyze all flags starting with sym. and entry0 (aa)
That's too deep
That's too deep
That's too deep
That's too deep
That's too deep
....

I looked at the source and found that there is a #define called FCN DEPTH in libr/anal/fcn.c
The default value is 512, but you can change it.

The thing is, that in IDA the depth of the file is no longer than 512, which means that the current FCN_DEPTH value (512) should be enough,  but in r2 I get the 'Too deep' message. 

Thanks!

**Comment by radare** [comment] 2016-05-02 17:17
this happens because every conditional branch decreases the depth, and this binary is abusing them. because it performs a recursive analysis.. if i remove that limit i get an stack exhaustion crash.

i can confirm this issue can be reproduced like this too:

```
s 0x00012374
af
```

i tried to increase the FCN_DEPTH from anal/fcn.c but this results in the same issue, because as long as the analysis is recursive the functions here have more than 10.000 branches which causes the stack to die.

The solution for this would be to drop the recursive nature of RAnal and use an iterative + heap form

**Comment by radare** [comment] 2016-05-02 17:19
Also, i have noticed that the offsets where the analysis is stopping because its asuming there's too many function depth is not really code.. its in fact text in utf16 which is embedded inside the .text section, so r2 can't recognize this as non-executable code and analyzes wide strings as code..

**Comment by radare** [comment] 2016-05-02 17:20
Are we missing some kind of PE parsing here? are resources embedded inside the section code with executable permissions?

**Comment by radare** [comment] 2016-05-02 17:27
Wide text can be easily identified but its a bit ugly to have to find it that way, im sure this crap is inside the .text section for some reason

**Comment by ret2libc** [comment] 2016-05-03 13:21
I also got this error on a binary :(

**Comment by AriEi4** [comment] 2016-05-03 13:26
@ret2libc what is the error message?

**Comment by ret2libc** [comment] 2016-05-03 13:36
"That's too deep"

**Comment by AriEi4** [comment] 2016-05-10 12:44
@radare so what do we do with it?

**Comment by radare** [comment] 2016-05-11 09:55
This happens because its analyzing data as code. so its not a real code analysis issue. The problem is that this binary embeds text inside the code and r2 analyzes it because its executable.

I dont have yet a solution for this, but one option would be to look for strings in the .text section before performing the analysis, and `af``will not try to analyze code if it is marked as data even if its in a section with the executable bit set

**Comment by ret2libc** [comment] 2016-05-11 16:18
The question is: why r2 analyzes it? It shouldn't (unless the code contains some obfuscation technique, but even in that case the analysis shouldn't do infinite recursion). The fact that some data is in the executable segment doesn't mean that should be analysed by r2. So, why in this binary r2 is analysing some things that is not called and neither jumped to?

**Comment by radare** [comment] 2016-05-11 16:30
why? because it is inside the .text section

it is mixed with real code

there’s nothing to stop r2 to analyze something that looks like code and its inside a section with executable permissions.

this depends on the analysis you run. if you do the stupid aaaaaa thing you will probably fall in this and other problems, because some of the analysis bound to the .text section instead of following entrypoints recursively.

think in aac for example. or anal.hasnext, or aa itself, which analyzes all symbols in executable sections..

what do ida does here?

**Comment by ret2libc** [comment] 2016-05-11 17:07
IDA doesn't fail in those cases. The fact that you have data in the text section shouldn't be an issue at all *IF* you use recursive disassembly. Indeed in recursive disassembly you analyse only code that is referenced by calls and so on.  This makes me understand that r2 doesn't do this.... and it's not `aaaaa` that is stupid, is just how all analyses are implemented that is wrong :) 

It's r2 that does wrong things by analysing everything that is in the code section... being in code section doesn't mean being code.

**Comment by radare** [comment] 2016-05-11 17:18
Then just use afr and the problem is gone. Having different ways to anayze code is a good thing. I hate not being able to modify how the anaysis is done or create custom analysises for specific problems in other tools. In r2 you can do what you want and maybe we should be more careful in detecting data references before going deeper in code. But this doesnt means the other approaches are wrong because they work well in the rest of cases

**Comment by ret2libc** [comment] 2016-05-11 18:14
Unfortunately even `afr` doesn't work. It's not recursive at all (indeed after two level of calls it doesn't identify functions). I agree that it's cool that you can analyse just the function you want and so on, but I (and many other users) expect that the "default analysis" just analyse everything at best as it can. And recursive disassembly is one common technique that can really do a decent job at that.

**Comment by Maijin** [comment] 2016-06-18 23:04
@AriEi4 Link dead

**Comment by radare** [comment] 2016-06-25 01:44
ping

**Comment by radare** [comment] 2016-08-08 23:50
I think this can be closed because the afr issue is tracked somewhere else and the error is no longer there

**Closed by radare** 2016-08-08 23:50 UTC
Labels: anal, bug, enhancement
