### ISSUE TITLE
Reopening file in RW mode results in sharing violation error (on Windows)

### ISSUE THREAD

**Issue by 1aNam** [radare/radare2#8840] opened 2017-11-15 12:15 UTC
- Start radare of some binary
- Reopen current file in RW mode (oo+)
- No error reported in radare, but the file is still opened in RX mode. Looking to Process monitor log I can see sharing violation error as a result of RW open attempt.

I use Win7 x64, meson MSVC build of latest radare git commit.
When examinining file handles of radare, there are 2 file handles for the inspected binary. After forcefully closing one of them the oo+ command is successful.

**Comment by condret** [comment] 2017-11-19 02:49
hm, does anyone know if #!c works on windows?

**Comment by radare** [comment] 2017-11-19 04:47
Any windows user can check that please?

**Comment by radare** [comment] 2017-11-19 04:53
Nobody tried and my guess is that gcc will not be available in PATH so no

**Comment by XVilka** [comment] 2017-11-19 07:26
Will check tomorrow in VM

**Comment by skuater** [comment] 2017-11-26 17:02
the problem come how windows handle the openfiles , u cant open 2 times same file using "open", in r2 code the problem is at r_io_reopen:

  if (!(new = r_io_open_nomap (io, uri, flags, mode))) {
    return false;
  }
  r_io_desc_exchange (io, old->fd, new->fd);
  return r_io_desc_close (old); // magic

File need be closed before  r_io_open_nomap invocation, to fix this is needed a full remake for  r_io_open_nomap

**Comment by radare** [comment] 2017-11-27 00:34
Thats hairy to fix because in linux/mac thats fine and we open the new file before closing to avoid opening something wrong and losing all your current session

I would go for a #if __WINDOWS__ solution

**Comment by radare** [comment] 2017-12-03 22:12
My idea is that.. on windows we should be closing the file before opening the file again, or ignoring the error and then check if it fails because of sharing and then close to open again. What do you think?

**Comment by radare** [comment] 2017-12-18 16:04
@skuater can you do this change and test it on windows please?

**Comment by radare** [comment] 2017-12-18 16:04
just check if the file is the same before closing the old fd and also check if the file can be opened in rw before doing so.

**Comment by radare** [comment] 2017-12-24 17:16
@skuater ping?

**Comment by radare** [comment] 2018-02-27 22:22
@mrexodia can you take a look at this?

**Comment by mrexodia** [comment] 2018-02-28 19:56
![](https://i.imgur.com/BrcXrrI.png)

Duncan (mrexodia), [28.02.18 20:22]
Closefile is the io-desc-close

Duncan (mrexodia), [28.02.18 20:22]
And then successfully opened

Duncan (mrexodia), [28.02.18 20:23]
But then some “locked with writers”

Duncan (mrexodia), [28.02.18 20:23]
(Which appears to be a failure of r-file-mmap-windows)

Duncan (mrexodia), [28.02.18 20:24]
im still confirming but I think file mapping is broken before this patch too

**Closed** 2018-03-02 10:41 UTC
Labels: Windows, bug, io, release

**Comment by condret** [comment] 2018-03-13 23:23
I just saw the fix, now it doesn't behave as expected

**Comment by mrexodia** [comment] 2018-03-14 12:11
What exactly goes wrong @condret?
