### ISSUE TITLE
some local stack variables don't get a name after running analyzer with 'aa' command

### ISSUE THREAD

**Issue by mrpink17** [radare/radare2#3150] opened 2015-08-23 13:55 UTC
try it with radare2 executable main() function. Most of the stack variables don't get a name

**Comment by radare** [comment] 2015-08-23 14:34
Provie arch/bits/info info. R2 builds for tons of platforms and local var analysis is not supported for all of them

**Comment by mrpink17** [comment] 2015-08-23 15:40
Linux  3.2.0-0.bpo.4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.68-1+deb7u3~bpo60+1 x86_64 GNU/Linux

**Comment by condret** [comment] 2015-08-24 01:53
mrpink17: local_2 is a name

**Comment by radare** [comment] 2015-08-24 02:48
paste a screenshot oor output of wrong `pd`

**Comment by mrpink17** [comment] 2015-08-25 20:02
https://asciinema.org/a/6lk2hqnyi6gxfrwh8oqdso5gc

**Comment by radare** [comment] 2015-08-25 23:05
i think that’s because the localvar analysis considers this a buffer or array and doesnt sets a var for each byte.. this needs to be implemented.

**Comment by oddcoder** [comment] 2016-05-12 11:39
9 months ago ? 
too old that I was not even here ... 
just use fresh r2 from git and it will be fine 
I am sure all the local vars and args offsets are detected
watch this one ;)
https://asciinema.org/a/dcj61vy98aionwjq4kg8vj15e

**Comment by radare** [comment] 2016-05-12 11:43
> On 12 May 2016, at 13:39, Ahmed Mohamed Abd El-MAwgood <notifications@github.com> wrote:
> 
> 9 months ago ? 
> too old that I was not even here ... 
> 

That sounds like u are a newborn :p

**Comment by oddcoder** [comment] 2016-05-12 11:47
I think this issue can be safely closed
the new `aa` detects lots of args and vars more than the one detected in the past you can check it your self

**Comment by XVilka** [comment] 2016-05-12 11:54
@oddcoder yes, asked you just in case you will have any objections. Closing. Don't forget to add more tests in radare2-regressions! ;)

**Closed by XVilka** 2016-05-12 11:54 UTC
Labels: anal, test-required
