### ISSUE TITLE
add a way for ahi to hint second immediate in the instruction

### ISSUE THREAD

**Issue by gordon-quad** [radare/radare2#12421] opened 2018-12-06 10:00 UTC
```
[0x00000000]> pd 1
            0x00000000      48c7450c3412.  mov qword [rbp + 0xc], 0x1234
[0x00000000]> ahi d
[0x00000000]> pd 1
            0x00000000      48c7450c3412.  mov qword [rbp + 12], 0x1234
[0x00000000]>
```
In this example ahi d hints only first immediate 0xc but not the second 0x1234.

It would be great to have a way to specify which immediate do you want to hint with ahi. Something like optional third parameter: `ahi d 1` in this case (opposed to `ahi d 0` by default).

**Comment by radare** [comment] 2018-12-10 10:46
Dupe of https://github.com/radare/radare2/issues/5608

**Closed by radare** 2018-12-10 10:46 UTC
Labels: anal, enhancement

**Comment by radare** [comment] 2018-12-16 22:32
fixed in https://github.com/radare/radare2/pull/12494
