### ISSUE TITLE
Broken project loading?

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5140] opened 2016-06-15 14:35 UTC
I guess this is a followup/regression on: https://github.com/radare/radare2/issues/5087 ?

After loading back an ARM project which worked fine before, I got this never ending string of messages right after loading the project via `r2 -p name_of_project`

![skarmavbild 2016-06-14 kl 12 28 48](https://cloud.githubusercontent.com/assets/175587/16083700/48237f66-3316-11e6-8def-e48644775448.png)

That was the case for a couple of sessions, but then I stupidly saved the project and lost a lot of labels/sessions via `Y` at the exit and message:  `Do you want to save the 'name_of_project' project? (Y/n)`... dooh. So no way to reproduce this one like in #5087, sorry :/ But perhaps given the message above, one can find the infinite loop?

**Comment by alvarofe** [comment] 2016-06-15 16:36
Did you use breakpoints? i mean was only a static analysis? Maybe this is breaking for a commit i did yesterday to save breakpoint into project that need more work by my side and test.

**Comment by brainstorm** [comment] 2016-06-15 17:03
Nope, it was all static analisys, so that's why I'm blaming @radare ;P

**Comment by oddcoder** [comment] 2016-06-15 17:42
well this error message looks familiar. 
actually I what I recomment is deleting any line that starts with afa or afv or afe and you should be ready to go.
this is due to update in some commands with no backward compatiablily

**Comment by radare** [comment] 2016-06-15 19:56
Can anyone reproduce the issue?

**Comment by jduck** [comment] 2016-06-16 20:38
Seems like these error messages are not very descriptive and further are missing a newline.

**Comment by brainstorm** [comment] 2016-06-16 20:51
Sorry, that's all I've got so far :-/ From a quick GH repo search:

https://github.com/radare/radare2/search?utf8=%E2%9C%93&q=%22Register+not+found%22&type=Code

From the 4 matches, the only eprintf's directly inside a loop or `r_list_foreach` are in:

`libr/anal/var.c`
`libr/core/disasm.c`

My best guess is switching to `Vv` mode? But OTOH I recall that it happened right after `r2 -p prj_name`, so could be sth while loading the project calling `r_anal_var_list_show`.

**Comment by jduck** [comment] 2016-06-16 20:53
I'm not sure what the project file looks like but I do remember some time ago there was a change to uppercase register names instead of using lowercase. IMHO it should be case-insensitive.

**Comment by Maijin** [comment] 2016-06-28 14:29
Is it happening again? Cause some stuff has been fixed with oddcoder fix, see 

```
well this error message looks familiar. 
actually I what I recomment is deleting any line that starts with afa or afv or afe and you should be ready to go.
this is due to update in some commands with no backward compatiablily
```

**Comment by brainstorm** [comment] 2016-06-28 14:44
Haven't seen it myself again since I overwrote my project accidentally, sorry :-S

**Comment by Maijin** [comment] 2016-06-28 15:24
kk closing then

**Closed by Maijin** 2016-06-28 15:24 UTC
Labels: projects
