### ISSUE TITLE
Issue with aaaa and stack initialization

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2#8918] opened 2017-11-30 09:00 UTC
I'm noticing a bunch of stack isn't initialized errors when loading a binary and executing aaaa command
```
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
Stack isn't initiatized.
Try running aei and aeim commands before aftm for default stack initialization
```
`radare2 2.1.0-git 16623 @ linux-x86-64 git.2.0.1-331-g1960a2c`

I continue to have this issue, I also try to run r2.cmd("aei") and r2.cmd("aeim") before 'aaaa' but there are not any changes

**Comment by radare** [comment] 2017-11-30 14:09
you are using a very old version of r2. please update before reporting any issue. i cant reproduce it

**Comment by GiuseppeLaurenza** [comment] 2017-11-30 14:46
I cloned radare2 from GitHub repository, how I can install a newer version?

**Comment by radare** [comment] 2017-11-30 15:26
sys/install.sh

**Comment by GiuseppeLaurenza** [comment] 2017-11-30 15:27
I made a docker with different tools, one is radare2.
I install it cloning the repository and than using the install.sh script.

**Comment by Maijin** [comment] 2017-11-30 23:18
ok then closing

**Comment by GiuseppeLaurenza** [comment] 2017-12-01 08:43
Sorry for misunderstanding, io wrote that my installation is updated though install.sh and there is the bug not that the upgrading fix the bug
I install in a docker cloning the repository and using the install script, in that docker I obtain the version of the first post

**Comment by Maijin** [comment] 2017-12-01 10:30
what is output of r2 -v and r2 -V after you upgraded

**Comment by GiuseppeLaurenza** [comment] 2017-12-01 15:37
It was already updated
`r2 -v
radare2 2.1.0-git 16623 @ linux-x86-64 git.2.0.1-331-g1960a2c
commit: 1960a2c9f71c3ff90e1ea7e8d17b538dc97f35d5 build: 2017-11-26__17:48:12`
`r2 -V 
2.0.1-331-g1960a2c  r2
2.0.1-331-g1960a2c  r_anal
2.0.1-331-g1960a2c  r_lib
2.0.1-331-g1960a2c  r_egg
2.0.1-331-g1960a2c  r_asm
2.0.1-331-g1960a2c  r_bin
2.0.1-331-g1960a2c  r_cons
2.0.1-331-g1960a2c  r_flag
2.0.1-331-g1960a2c  r_core
2.0.1-331-g1960a2c  r_crypto
2.0.1-331-g1960a2c  r_bp
2.0.1-331-g1960a2c  r_debug
2.0.1-331-g1960a2c  r_hash
2.0.1-331-g1960a2c  r_fs
2.0.1-331-g1960a2c  r_io
2.0.1-331-g1960a2c  r_magic
2.0.1-331-g1960a2c  r_parse
2.0.1-331-g1960a2c  r_reg
2.0.1-331-g1960a2c  r_sign
2.0.1-331-g1960a2c  r_search
2.0.1-331-g1960a2c  r_syscall
2.0.1-331-g1960a2c  r_util`

**Comment by radare** [comment] 2017-12-01 22:09
That looks wrong you are using r2.1 from git and libs from 2.0 and git version is 2.2

So you have a messed up installation

**Comment by GiuseppeLaurenza** [comment] 2017-12-04 09:57
Hi,
I clean the installation, clone the repository and install with install.sh script

r2 -v
radare2 2.2.0-git 16646 @ darwin-x86-64 git.2.1.0-62-g410ca0980
commit: 410ca098030e18f9cff00d49c45499fa33b4f1db build: 2017-12-04__10:40:40

r2 -V
2.1.0-62-g410ca0980  r2
2.1.0-62-g410ca0980  r_anal
2.1.0-62-g410ca0980  r_lib
2.1.0-62-g410ca0980  r_egg
2.1.0-62-g410ca0980  r_asm
2.1.0-62-g410ca0980  r_bin
2.1.0-62-g410ca0980  r_cons
2.1.0-62-g410ca0980  r_flag
2.1.0-62-g410ca0980  r_core
2.1.0-62-g410ca0980  r_crypto
2.1.0-62-g410ca0980  r_bp
2.1.0-62-g410ca0980  r_debug
2.1.0-62-g410ca0980  r_hash
2.1.0-62-g410ca0980  r_fs
2.1.0-62-g410ca0980  r_io
2.1.0-62-g410ca0980  r_magic
2.1.0-62-g410ca0980  r_parse
2.1.0-62-g410ca0980  r_reg
2.1.0-62-g410ca0980  r_sign
2.1.0-62-g410ca0980  r_search
2.1.0-62-g410ca0980  r_syscall
2.1.0-62-g410ca0980  r_util

i had the same error with "Stack isn't initiatized.s for all functions (afta)" also if I run lei and aeim before aaaa

**Comment by GiuseppeLaurenza** [comment] 2017-12-04 13:58
sorry for the question,
in these cases is better to wrote under the issue or open a new one?

**Comment by radare** [comment] 2017-12-04 14:06
please share the binary and we will try to reproduce the issue, but for now it seemsm like the problem is in your side

**Comment by radare** [comment] 2017-12-04 16:12
here is ok

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:08
Sorry about the delay
[stack_error.zip](https://github.com/radare/radare2/files/1534427/stack_error.zip)
password infected

Making more test I found that it happens
the error happened after I use "aaaa" and "aaaap" command

**Comment by Maijin** [comment] 2017-12-06 09:28
aaaap ? That doesn't exist.

**Comment by Maijin** [comment] 2017-12-06 09:29
You are basically typing aaaa twice

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:30
which is the correct command to analyze prelude?
How the problem happens only with some binaries and it does not happen with all?

**Comment by Maijin** [comment] 2017-12-06 09:40
aap

**Comment by Maijin** [comment] 2017-12-06 09:40
just read the doc `aa?`

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:44
Ok, so which is the best way to analyze a binary and extract details about all the functions? because I find different binaries in which I find same functions number with aaaa and aap and other in which only with prelude I can find functions

**Comment by Maijin** [comment] 2017-12-06 09:46
stop using `aaaa`, configure your analysis properly using the eval variable and the proper aa* and a* commands, read the docs like http://radare.today/posts/analysis-by-default/ , understand what you are doing.

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:48
thanks for the link, hopefully I can understand how to set my analysis
problem is that I have to automatically analyze different binaries so it is not possible to adapt it on each of them and I design some analysis in order to work with many samples as possible

**Comment by Maijin** [comment] 2017-12-06 09:53
"I can understand how to set my analysis" - The fact you are using aaaa shows you don't sadly 😿

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:54
I mean after the reading of your link :D

**Comment by Maijin** [comment] 2017-12-06 09:54
ok

**Comment by Maijin** [comment] 2017-12-06 09:55
Well you can do some checks to know what kind of binary it is, which architectures/bitsize, matching on various stuff and engage analysis depending on that.

**Comment by Maijin** [comment] 2017-12-06 09:56
Nothing really that can be solved on r2 for now though, aaa/aaaa will eventually do this kind of check.

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:57
I hope to discover and understand which checks I have to do

**Closed by Maijin** 2017-12-06 09:56 UTC
Labels: anal, esil, test-required

**Comment by Maijin** [comment] 2017-12-06 09:57
check e??~anal

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 09:58
what do you mean with aaa/aaaa will eventually do this kind of check? Are you referring to future development?

**Comment by Maijin** [comment] 2017-12-06 10:00
Yes

**Comment by GiuseppeLaurenza** [comment] 2017-12-06 10:00
ok,
thanks for the support

**Comment by radare** [comment] 2017-12-07 09:49
You can try aab. Sometimes results in good stuff
