### ISSUE TITLE
dxr <opcode> segfault

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3020] opened 2015-07-29 23:09 UTC
morrn,

on OpenBSD I get the following core dump:

http://sprunge.us/IbJZ

Greetings
--zlul

also happens on Linux 64bit/32bit

**Comment by crowell** [comment] 2015-07-30 04:49
how do you reproduce this on linux...

On Wed, Jul 29, 2015 at 7:09 PM, zonkzonk <notifications@github.com> wrote:

> morrn,
>
> on OpenBSD I get the following core dump:
>
> http://sprunge.us/IbJZ
>
> Greetings
> --zlul
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3020>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by zonkzonk** [comment] 2015-07-30 12:47
same thing, just send a bunch of chairs as argument:

r2 -c "dxr `bash -c 'for ((i=0;i<10248;i++)) { printf "A"; }'`" /bin/ls
Segmentation fault

**Comment by alvarofe** [comment] 2015-07-30 16:37
How did you install radare2 on OpenBSD?  `sys/install.sh` doesn't work for me. I'm getting issues like
`Parse error` when doing make. In Linux I don't get a segmentation fault.

**Comment by crowell** [comment] 2015-07-30 16:50
i don't get a segfault on linux either (ubuntu 14.04 64 bit)

On Thu, Jul 30, 2015 at 12:37 PM, Álvaro Felipe Melchor <
notifications@github.com> wrote:

> How did you install radare2 on OpenBSD? sys/install.sh doesn't work for
> me. I'm getting issues like
> Parse error when doing make. In Linux I don't get a segmentation fault.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3020#issuecomment-126396337>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by zonkzonk** [comment] 2015-07-30 19:01
@alvarofe just ./configure && gmake && gmake install

@crowell the crash happens on archlinux 64bit current and on debian 7.8 32bit

**Comment by alvarofe** [comment] 2015-07-30 20:54
OpenBSD working and getting segfaults but doing others things.

Now setting the ulimit options I am able to reproduce it on Linux (before I forgot those steps)
`Linux void 4.1.3_1 #1 SMP PREEMPT Wed Jul 22 06:07:23 UTC 2015 x86_64 GNU/Linux`

I will look at this, it seems a good issue :). Thanks @zonkzonk 

```
Address 0xaaaaaaaaaaaaab6a is not stack'd, malloc'd or (recently) free'd
```

**Comment by alvarofe** [comment] 2015-07-30 21:05
I am able to reproduce it in Mac OS X too

**Comment by zonkzonk** [comment] 2015-07-31 19:11
will test

**Comment by zonkzonk** [comment] 2015-07-31 19:21
doesn't work here, (checked out your branch):

zlul@debian:~$ r2 -q -c "dxr `cat A`" /bin/ls
Segmentation fault (core dumped)
zlul@debian:~$ r2 -v
radare2 0.10.0-git 8584 @ linux-little-x86-32 git.0.9.8-2170-g1541477
commit: 1541477ae98e3e1806c0443948f6a5436c0f543c build: 2015-07-31

**Comment by alvarofe** [comment] 2015-07-31 19:45
It's not merged yet although with the changes I've introduced I don't get seg fault. 
I didn't merged because I'm working on other issues and I want to make a PR with all of them.

**Closed** 2015-07-31 22:15 UTC

**Comment by alvarofe** [comment] 2015-07-31 22:16
Test it now and tell me if the issue persist ;)

**Comment by zonkzonk** [comment] 2015-07-31 22:56
@alvarofe indeed fixed :)

```
r2 -c "dxr bash -c 'for ((i=0;i<10248;i++)) { printf "A"; }'" /bin/ls; r2 -vSlurping file '10248;i++)) { printf A; }''cannot open file-- 💺
```
