### ISSUE TITLE
Add missing 6502 instructions

### ISSUE THREAD

**Issue by radare** [radare/radare2#9830] opened 2018-04-08 14:27 UTC
yeah those are "undocumented", but pretty common from what i see

http://nesdev.com/undocumented_opcodes.txt

**Comment by radare** [comment] 2018-04-08 14:29
see also https://www.pagetable.com/?p=3

**Comment by mscherer** [comment] 2018-09-12 23:59
Linked to https://github.com/radare/radare2/issues/9671  (and the pagetable.com link should be https://www.pagetable.com/?p=39 )

**Comment by Maijin** [comment] 2018-09-13 08:30
Duplicate of #9671

**Closed by Maijin** 2018-09-13 08:30 UTC
Labels: disassembly, enhancement
