### ISSUE TITLE
Arm / thumb switching badness

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7134] opened 2017-03-25 11:52 UTC
First of all, asm.bits initialises to 64, even though I saved my project with asm.bits set to 16. Really, it's neither, though, because armv7l constantly alternates between 16 and 32. Also, for some reason, only the arm64 calling convention is known, even though it is the only arm calling convention that can't be used.
```
[0x81e20814]> e asm.bits=16
[0x81e20814]> afCl
arm64
```
Sometimes, afr just *really* does not want to use thumb to analyse a function.
```
[0x81e20814]> e asm.bits=16
[0x81e20814]> afr @shell
[0x81e20814]> s shell
[0x81e20814]> pd
/ (fcn) shell 16
|   shell ();
|              ; CALL XREF from 0x81e20814 (shell)
|           0x81e20814      724b2de9       push {r1, r4, r5, r6, r8, sb, fp, lr}
|           0x81e20818      f04ff7b0       ldrshtlt r4, [r7], 0xf0
|           0x81e2081c      714836ac       ldcge p8, c4, [r6], -0x1c4
\           0x81e20820      7b444ff0       invalid
            0x81e20824      00090093       movwls r0, 0x900            ; 2304
            0x81e20828      6f4b7844       ldrbtmi r4, [r8], -0xb6f
            0x81e2082c      dff8bc81       ldrsbhi pc, [ip, pc]!
            0x81e20830      7b440193       movwls r4, 0x147b
            0x81e20834      f8446e4b       blmi 0x839b1c1c
```
Clearly, shell() is not arm32. Force 16 bits.
```
[0x81e20814]> af-shell
[0x81e20814]> afr @shell@e:asm.bits=16
[0x81e20814]> pd
/ (fcn) shell 16
|   shell ();
|              ; CALL XREF from 0x81e20814 (shell)
|           0x81e20814      724b2de9       push {r1, r4, r5, r6, r8, sb, fp, lr}
|           0x81e20818      f04ff7b0       ldrshtlt r4, [r7], 0xf0
|           0x81e2081c      714836ac       ldcge p8, c4, [r6], -0x1c4
\           0x81e20820      7b444ff0       invalid
            0x81e20824      00090093       movwls r0, 0x900            ; 2304
            0x81e20828      6f4b7844       ldrbtmi r4, [r8], -0xb6f
            0x81e2082c      dff8bc81       ldrsbhi pc, [ip, pc]!
            0x81e20830      7b440193       movwls r4, 0x147b
[0x81e20814]> 
```
Still arm32. Great.

**Comment by alvarofe** [comment] 2017-03-25 12:09
Use anal hints to handle arm/thumb. Though if this file is amrv7 should be recognized as such, is this binary sharable to take a look? Which platform? version of r2?

This should work 
```
ahb 16 @ shell
afr @shell
```

**Comment by ewtoombs** [comment] 2017-03-25 12:38
[uboot.zip](https://github.com/radare/radare2/files/870004/uboot.zip)

Open with r2 -a arm -m 0x81dffe00 uboot.

It's not actually uboot. It's an LK-derived android bootloader for the HTC Desire 320 (telus). The original LK code is [here](https://android.googlesource.com/kernel/lk/), but it's been heavily modified. Trying the hint now...

**Comment by ewtoombs** [comment] 2017-03-25 12:41
Hey, there it goes! Still, that hint was really not necessary. The disassembler ran into an invalid instruction way before the function was over on its first attempt using arm32.

**Comment by alvarofe** [comment] 2017-03-25 12:42
```
air:Downloads alvaro$ r2 -a arm -m 0x81dffe00 uboot
 -- This computer has gone to sleep.
[0x81dffe00]> e asm.bits=16
[0x81dffe00]> s 0x81e20814
[0x81e20814]> afr
[0x81e20814]> pd 16
┌ (fcn) fcn.81e20814 458
│              ; CALL XREF from 0x81e20814 (fcn.81e20814)
│              ; [0x81e209e0:4]=0x15a74
│           0x81e20814      724b           ldr r3, [0x81e209e0]
│           0x81e20816      2de9f04f       push.w {r4, r5, r6, r7, r8, sb, sl, fp, lr}
│           0x81e2081a      f7b0           sub sp, 0x1dc
│              ; [0x81e209e4:4]=0x15a4a
│           0x81e2081c      7148           ldr r0, [0x81e209e4]
│           0x81e2081e      36ac           add r4, sp, 0xd8
│           0x81e20820      7b44           add r3, pc
│           0x81e20822      4ff00009       mov.w sb, 0
│           0x81e20826      0093           str r3, [sp]
│              ; [0x81e209e8:4]=0x15a64
│           0x81e20828      6f4b           ldr r3, [0x81e209e8]
│           0x81e2082a      7844           add r0, pc
│              ; [0x81e209f0:4]=0x15a64
│           0x81e2082c      dff8bc81       ldr.w r8, [0x81e209f0]
│           0x81e20830      7b44           add r3, pc
│           0x81e20832      0193           str r3, [sp + local_4h]
│           0x81e20834      f844           add r8, pc
│              ; [0x81e209f0:4]=0x15a64
│           0x81e20836      6e4b           ldr r3, [0x81e209f2]
│           0x81e20838      7b44           add r3, pc
```

Which version are you using???

**Comment by Maijin** [comment] 2017-03-25 12:56
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by ewtoombs** [comment] 2017-03-25 12:59
Sorry, forgot to say the version.
```
% r2 -v
radare2 1.3.0 0 @ linux-x86-64 git.1.3.0
commit: HEAD build: 2017-03-14__12:12:32
```

**Comment by Maijin** [comment] 2017-03-25 13:35
that's too old. Always use the git version prior to report issues otherwise it's waste of time if it's already fix 👎

**Comment by radare** [comment] 2017-03-25 15:05
It initialized to 64bits because you are on 64 bits. Use -b16 to change that. Default arch/os/bits is host

**Comment by radare** [comment] 2017-03-25 15:05
Use anal hints to force thumb ranges or functions

**Comment by alvarofe** [comment] 2017-03-25 21:38
I would close this since is working. I would create an issue for `afCl`

```
air:Downloads alvaro$ r2 -b 16 -a arm -m 0x81dffe00 uboot
 -- I thought we were friends. :_
[0x81dffe00]> s 0x81e20814
[0x81e20814]> afr
[0x81e20814]> pd 4
┌ (fcn) fcn.81e20814 458
│              ; CALL XREF from 0x81e20814 (fcn.81e20814)
│              ; [0x81e209e0:4]=0x15a74
│           0x81e20814      724b           ldr r3, [0x81e209e0]
│           0x81e20816      2de9f04f       push.w {r4, r5, r6, r7, r8, sb, sl, fp, lr}
│           0x81e2081a      f7b0           sub sp, 0x1dc
│              ; [0x81e209e4:4]=0x15a4a
│           0x81e2081c      7148           ldr r0, [0x81e209e4]
[0x81e20814]> afCl
arm64
```

**Comment by radare** [comment] 2017-03-26 07:52
Ok

**Comment by ewtoombs** [comment] 2017-03-26 18:50
Um really, Maijin? It's only about two weeks old... And anyway, this software is buggy enough without trying to use the development version. You expect too much of your users. At least consider the possibility that the bug I'm posting hasn't been fixed in the past two weeks, as unlikely as that may seem to you.

**Comment by ewtoombs** [comment] 2017-03-26 18:59
I don't consider this solved, when r2 fails to recognise such an obviously thumb-encoded function as such, even though you can force thumb encoding with an analysis hint. Also, this wasn't an init from nothing. It was an init from a project file, where asm.bits was already set correctly. Either asm.bits wasn't saved when the project was saved, or asm.bits was ignored when the project was reopened.

**Comment by ewtoombs** [comment] 2017-03-26 19:03
I do realise though that I should have made two or three separate bugs here. One for calling convention badness, one for asm.bits project saving and loading badness, and one for thumb autodetect badness. So sorry about conflating the issues.

**Comment by alvarofe** [comment] 2017-03-26 21:30
First of all is a raw dump so it could be anything since there is not file format to extract info from. Therefore you have to specify bits and architecture. If the issue is when saving the project open one there not related with thumb/arm cause it does work as you can see in my snippets.

Issues

* Save project lost e asm.bits
* Call convention say arm64 when is arm/thumb

**Comment by alvarofe** [comment] 2017-03-28 07:54
@Maijin could you please create those issues on their corresponding meta and closing this one?

**Comment by Maijin** [comment] 2017-09-11 11:25
See meta then

**Closed by Maijin** 2017-09-11 11:25 UTC
Labels: ARM
