### ISSUE TITLE
wrong analysis of 16bit jumps

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#36] opened 2012-11-20 03:33 UTC
For example, see this code:

```nasm
f000:0540   6633c0     xor eax, eax
f000:0543   0fa2          cpuid
f000:0545   6681fb47656e75  cmp ebx, 0x756e6547
f000:054c   7404         jz 0xf0552
f000:054e   fa              cli
f000:054f    f4              hlt
f000:0550   ebfc          jmp 0xf054e
f000:0552   0f08          invd
f000:0554   0f6eff        movd mm7, edi
f000:0557   668bc4     mov eax, esp
f000:055a   e9c806     jmp word 0xc25
```

Here radare2 can recognize deadloop:

```
-> f000:054f f4  hlt
.=< f000:0550 ebfc jmp 0xf054e
```

but not this normal jump:

```
f000:054c     jz 0xf0552
...
f000:0552     invd
```

**Comment by XVilka** [comment] 2015-03-16 16:23
will do

**Comment by XVilka** [comment] 2015-04-10 23:54
Fixed for
```
[f000:fff0]> pd 1
           ;-- entry0:
           f000:fff0    eaaaff00f0   ljmp 0xffaa, 0xf000
[f000:fff0]>
```
but still present to 
```
|      |   f000:4747    8ad4         mov dl, ah
|     ,==< f000:4749    724d         jb 0xf4798
|     ||   f000:474b    8ac2         mov al, dl
|     ||   f000:474d    b405         mov ah, 5 ; 5
|     ||   f000:474f    90           nop
```

**Comment by radare** [comment] 2015-04-11 08:40
Shouldnt be discussed with capstone?

**Comment by radare** [comment] 2015-05-20 19:03
This thing depends partly on a capstone bug that is taking more time to get fixed that the expected.. so lets move this to 1.0

**Comment by jvoisin** [comment] 2015-09-01 20:42
What capstone bug?

**Comment by radare** [comment] 2015-09-01 21:25
https://github.com/aquynh/capstone/issues/352 <https://github.com/aquynh/capstone/issues/352>
https://github.com/aquynh/capstone/issues/111 <https://github.com/aquynh/capstone/issues/111>

Also see: https://github.com/aquynh/capstone/issues/111#issuecomment-130788282 <https://github.com/aquynh/capstone/issues/111#issuecomment-130788282>

**Comment by Maijin** [comment] 2015-12-07 13:21
@XVilka looks like the 
```
ljmp 0xf000:0xffaa                                    ;[1]
```
Regressed again, it needs a test definitely, see the result of $j => 

```
[f000:fff0]> ? $j
61440 0xf000 0170000 60K 0000:0000 61440 00000000 61440.0 0.000000f 0.000000
[f000:fff0]> 
```

**Comment by radare** [comment] 2015-12-08 00:38
Capstone issue again? Is there a test?

**Comment by Maijin** [comment] 2015-12-10 21:37
@radare 
https://github.com/radare/radare2-regressions/commit/be31f7ecb39d6726fcaca01b99847f89d9199176

**Comment by radare** [comment] 2016-10-27 11:07
is this still an issue? is this a capstone bug?

**Comment by radare** [comment] 2016-10-27 11:10
Moving to 9999 release because i guess capstone will never fix this

**Comment by Maijin** [comment] 2016-10-28 19:30
And no that's not fixed in r2 patch see the broken test

**Closed** 2016-11-05 19:19 UTC
Labels: bug, has-test, regression
