### ISSUE TITLE
slc  - Prompt jumps to 0x00000000?

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3899] opened 2016-01-01 18:05 UTC
morrn,

```
$ r2  /bin/ls
 -- Connection lost with the license server, your r2 session will terminate soon.
[0x00404870]> slc
Found 407 lines
[0x00404870]> sl 1
Found 407 lines
[0x00000000]> q
$
```

@zlowram is this bug ? :)

Greetings
--zlul

r2 -v
radare2 0.10.0-git 10020 @ linux-little-x86-64 git.0.9.9-1912-g5355af8
commit: 5355af818a9f67016d05c32b1cb257a02c2b1142 build: 2015-12-31

**Comment by zlowram** [comment] 2016-01-02 16:46
Hi there,

It is not a bug, the `sl` command was thought to be used to move around plaintext within binary or a memory region. If you type `sl 1` you are telling r2 to go the the first line, therefore it seeks to offset 0x0. If you find a plaintext region you can define `lines.from` and `lines.to` vars and then move round it with the `sl` command.

**Comment by zlowram** [comment] 2016-01-03 02:23
The bug should be now fixed, thanks!

**Closed by zlowram** 2016-01-03 02:23 UTC
