### ISSUE TITLE
Reopening a file in debug mode with 'ood' does not work

### ISSUE THREAD

**Issue by mrpink17** [radare/radare2#3255] opened 2015-09-08 20:54 UTC
This is the error message:
p/io_debug.c:345 fork_and_attach: execv: No such file or directory

**Comment by mrpink17** [comment] 2015-09-08 20:57
Linux i5k 3.2.0-0.bpo.4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.68-1+deb7u3~bpo60+1 x86_64 GNU/Linux

**Comment by radare** [comment] 2015-09-09 08:59
Works for me, are you using r2 from git? I can confirm this works fine on linux and osx

**Comment by radare** [comment] 2015-09-09 09:05
can you strace to see what's trying to execve? are you using latest git? record an asciinema maybe?

**Comment by mrpink17** [comment] 2015-09-14 20:56
If you give the absolute path of the opened file as argument to r2, the command works fine.
If the file is in you current working directory and you give just the name as argument to r2 then you get the error message

**Comment by crowell** [comment] 2015-09-14 21:01
works for me.

```
jcrowell0 ~ » ./a.out 
0
0
1
jcrowell0 ~ » r2 ./a.out 
 -- This is a compressed PDF. Why the hell are you opening this in r2 ? SIGSEGV
[0x004004d0]> ood
Process with PID 5025 started...
File dbg://./a.out reopened in read-only mode
Debugging pid = 5025, tid = 5025 now
Assuming filepath ./a.out
[0x7fa9969ce2d0]> dc
0
0
1

==> Process finished

Child 5025 is dead
[0x7fa9969ce2d0]> 
```

are you using the latest r2 from git? this bug may have been fixed with one in project management.

**Comment by Maijin** [comment] 2015-09-14 21:03
https://github.com/radare/radare2/issues/3118 ?

**Comment by mrpink17** [comment] 2015-09-14 21:41
I'm using latest git compiled few hours ago. crowell is right ",/a.out" works also for me, just tested. Try "a.out" without "./", for me it does not work

**Closed** 2015-09-15 00:46 UTC
Labels: debugger, regression

**Comment by radare** [comment] 2015-09-15 01:34
👍
