### ISSUE TITLE
Description of stack.size configuration variable suggests it only applies if stack.anotated=true

### ISSUE THREAD

**Issue by pgrohe** [radare/radare2#5541] opened 2016-08-17 00:34 UTC
The description of configuration variable stack.size reads:

> Size of anotated hexdump in visual debug

This lets you specify the total number of bytes of hex dump you want to see at the top of the visual debug mode.

There is also a configuration variable named stack.anotated which inserts comments & labels into the stack hex dump, ex: 

> /section_end.GNU_STACK.  

The stack.size value applies to the visual mode debugger hex dump regardless of the state of stack.anotated variable.

The description of stack.size should not mention anotated hexdump.

I will modify the string in libr/core/config.c to reflect this and submit a pull request.

**Comment by pgrohe** [comment] 2016-08-17 00:48
PR #5542

Please let me know if individual issues / PRs is not the appropriate way to handle minor documentation issues like this.  Looking to contribute to the project and I'm happy to help out with this type of minor stuff as I get more familiar with the codebase.  If you'd rather these types of minor edits are batched together let me know.

Cheers.

**Comment by Maijin** [comment] 2016-08-17 13:08
Well `stack.anotated` just differ that it uses a different command. 
If `stack.anotated = true` then stack is using `pxa`
If `stack.anotated = false` then stack is using `px`

**Comment by Maijin** [comment] 2016-08-17 13:08
But yeah your PR makes sense

**Comment by Maijin** [comment] 2016-08-17 13:09
Next time use "Fix #XXX" so the issue is closed as soon as it is merged.

**Closed** 2016-08-17 13:09 UTC
