### ISSUE TITLE
radare2 doesn't work from msys2 console

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#5244] opened 2016-06-30 12:25 UTC
Cannot work with radare2 from msys2 console:

```
$ wget http://bin.rada.re/radare2-w32-0.10.3-git.zip
$ unzip radare2-w32-0.10.3-git.zip
$ cd radare2-w32-0.10.3-git
$ ./radare2.exe sample.exe
```

From msys2 shell start to print random chars:
![2016-06-29_15-49-35](https://cloud.githubusercontent.com/assets/1186777/16487914/4d1ebf3c-3ed6-11e6-85a4-63b02bee0543.png)

From msys2 shell+conemu:
address start to blink very fast and I cannot enter command

OS: Windows 7 x64 + msys2

**Comment by Maijin** [comment] 2016-06-30 20:12
http://bin.rada.re/radare2-w32-0.10.3-git.zip ? it's http://bin.rada.re/radare2-w32-0.10.4-git.zip now.

**Comment by dukebarman** [comment] 2016-07-04 17:18
In 0.10.4-git doesn't work too :'(

**Comment by radare** [comment] 2016-07-04 17:57
@skuater plz take a look at this

**Comment by skuater** [comment] 2016-07-04 21:41
into a cmd.exe,  work correctly plz try to compile r2 under cygwin enviroment.

**Comment by radare** [comment] 2016-07-04 23:12
? R2 should work fine in mingw builds too

**Comment by pandasauce** [comment] 2016-11-18 16:40
Windows version still not particularly useful.

radare2-w32-1.0.2

On cmd.exe, Windows 7 x64:
Buggy with limited functionality. Colors only partially work, those codes below are actually printed out.

```
[0x140358be8]> ii | grep str
r_core_cmd_pipe: unimplemented for this platform
[0x140358be8]> aa
←[32m[x]←[0m Analyze all flags starting with sym. and entry0 (aa)
```

MSYS2-x86_64-20161025:
I get a black screen with no cursor and random characters jumping across the screen now and then. Similar to OP.

On MinGW32 1.0:
Buggy with limited functionality. Colors only partially work, those codes below are actually printed out.

```
Cannot find share/radare2/1.0.2/format/dll/shell32.sdb
Cannot find share/radare2/1.0.2/format/dll/shell32.sdb
Cannot find share/radare2/1.0.2/format/dll/shell32.sdb
Cannot find share/radare2/1.0.2/format/dll/shell32.sdb
[0x140358be8]> ii | grep str
r_core_cmd_pipe: unimplemented for this platform
[0x140358be8]> aa
←[32m[x]←[0m Analyze all flags starting with sym. and entry0 (aa)
```

Please let me know if I can be of any further help.

**Comment by radare** [comment] 2016-11-18 16:42
dont use | grep, you have ~which is internal to r2, so its faster and works everywhere

the sdbs that cant be find is because you should run r2 from that directory.

maybe @skuater can find some time to implement the pipe on windows.

about the screen issues, skuater fixed some issues related to this, can you try the last build from git?

**Comment by pandasauce** [comment] 2016-11-25 12:59
Managed to build a working executable from latest Git on MinGW-w64-win32 MSYS2 using ```sys/mingw32.bat``` with adjusted paths.

The issue is still there exactly as before with the exception of sdbs - I followed the advice and ran it from the correct directory.

**Comment by XVilka** [comment] 2016-11-28 13:57
@pandasauce I've fixed sys/mingw32.bat, you can set `MINGW_PATH` and `GIT_PATH` to any before running the script.

**Comment by dukebarman** [comment] 2017-03-09 14:20
```
wget http://cloud.radare.org/get/1.2.0/radare2-w32-1.2.0.zip
unzip radare2-w32-1.2.0.zip                                 
cd radare2-w32-1.2.0/                                       
./radare2.exe ragg2.exe                                     
```

From msys2 shell+conemu:
address start to blink very fast and I cannot enter command

OS: Windows 7 x64 + msys2 + conemu

**Comment by pandasauce** [comment] 2017-03-09 19:21
I think it's safe to say that Win32 is not currently supported and hasn't been supported for a while.

**Comment by Maijin** [comment] 2017-03-09 19:25
@skuater ^

**Comment by Maijin** [comment] 2017-03-09 19:25
This is false because I use win32 and @skuater too

**Comment by pandasauce** [comment] 2017-03-09 19:27
@Maijin can you share some details of your known-working setup? Windows version, MinGW version, 32/64bit build type, radare version? I would be eager to try it out.

**Comment by Maijin** [comment] 2017-03-09 19:30
Windows 7 x64 + http://bin.rada.re/radare2-w32-1.3.0-git.zip

**Comment by Maijin** [comment] 2017-03-09 19:30
and conemu

**Comment by pandasauce** [comment] 2017-03-10 13:15
Can confirm works well in Conemu + cmd shell, colors don't get messed up when used this way, no blinking screen. Still getting "r_core_cmd_pipe: unimplemented for this platform" when using it with Conemu + cmd shell, but that is a different problem.

@dukebarman would that be acceptable to you (please close the issue if so) or do you have a requirement for it to work in msys2?

**Comment by akorchemniy** [comment] 2017-04-26 03:19
The latest 1.5 build from bin.rada.re only works with window pseudo terminal (cmd). The output goes crazy in cygwin, msys2. Full terminal support from mintty would be so much better.

**Comment by radare** [comment] 2017-04-26 10:35
Not this again :_________

**Comment by Maijin** [comment] 2017-04-26 10:39
Closing here. Please reopen an issue if necessary describing precisely with asciinema, command typed, screenshot, scripts etc. the issues with full specs of the configuration architecture, OS, Shell used, Terminal Emulator used.

**Closed by Maijin** 2017-04-26 10:39 UTC
Labels: consoleui, regression, Windows
