### ISSUE TITLE
Search for string gives wrong results in bigger files

### ISSUE THREAD

**Issue by xambroz** [radare/radare2#2960] opened 2015-07-16 13:45 UTC
Searching string in 25MB windows binary with radare on Linux system gives bogus results.
I am not sure whether this is some generic issue with bigger files or specifics of this particular binary.

For example searching for a string GETIFSOBJ gives address 0x01539c4c, but the string is not located there. It is actually at 0x01108C4C (as found by mona.py in ImmunityDebugger)

BTW this binary was obtained from http://www.edm.it/ as "Download Webgate400 client v8".
http://62.97.32.135:4400/webgate400/applet/downloadv8/webgate400i.htm
The binary WEBGATE400I.EXE was originally packed with upx, the analysis is being done on the unpacked binary by command "upx -d WEBGATE400I.EXE". 

```
$ radare2 WEBGATE400I.EXE 
[0x00513d71]> /i GETIFSOBJ
Searching 9 bytes from 0x00401000 to 0x01c528c0: 47 45 54 49 46 53 4f 42 4a 
# 6 [0x401000-0x1c528c0]
hits: 1
0x01539c4c hit0_0 "\\u00a4q\\u00a1\\u00c3\\u0012o\\u0093I\\u00c0"

[0x00513d71]> s 0x01539c4c
[0x01539c4c 70% 752 WEBGATE400I.EXE]> x @ hit0_0                                                                                                                                                 
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF                                                                                                                            
0x01539c4c  a471 a1c3 126f 9349 c069 139b 2a4a 174a  .q...o.I.i..*J.J                                                                                                                            
0x01539c5c  3994 ca03 f9a8 6355 128b 0315 ade6 a215  9.....cU........                                                                                                                            
0x01539c6c  1883 8acd 9b80 d29e 8f32 1ea2 40ac 25d5  .........2..@.%. 

[0x00000048]> s 0x01108C4C
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF                                                                                                                            
0x01108c4c  4745 5449 4653 4f42 4a00 0000 7800 6600  GETIFSOBJ...x.f.                                                                                                                            
0x01108c5c  3400 3000 3000 4300 6800 6500 6300 6b00  4.0.0.C.h.e.c.k.                                                                                                                            
0x01108c6c  5500 7300 6500 7200 4300 6f00 6e00 6e00  U.s.e.r.C.o.n.n.                                                                                                                            
0x01108c7c  6500 6300 7400 6900 6f00 6e00 5000 7200  e.c.t.i.o.n.P.r.                                                                                                                            
0x01108c8c  6f00 7000 6500 7200 7400 6900 6500 7300  o.p.e.r.t.i.e.s.

```

**Comment by radare** [comment] 2015-07-16 14:03
I guess thats only an issue with iova mode. Can u confirm with r2 -n?

**Comment by xambroz** [comment] 2015-07-16 14:44
Yes your guess is right with "-n" it finds the offset 0x00d06e4c in the file, which is correct offset in the exe file. So the issue seems to be somewhere with counting the virtual addresses during search.

'''
$ radare2 -n WEBGATE400I.EXE 
 -- Of course r2 runs FreeBSD
[0x00000000]> / GETIFSOBJ
Searching 9 bytes from 0x00000000 to 0x018247a8: 47 45 54 49 46 53 4f 42 4a 
# 6 [0x0-0x18247a8]
hits: 1
0x00d06e4c hit0_0 "GETIFSOBJ"
'''

BTW when executed without "-n" it throws warning 
WARNING: bin_strings buffer is too big (0x00393c00)

'''
$ radare2 WEBGATE400I.EXE 
DLLNAME(COMCTL32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(COMCTL32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(COMCTL32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(COMCTL32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(OLEAUT32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(SHELL32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
DLLNAME(WS2_32.dll)
WARNING: bin_strings buffer is too big (0x00393c00)
 -- Everytime you run radare2, a random file is removed :)
[0x00513d71]> 
'''

**Comment by radare** [comment] 2015-07-16 18:58
The current io implementation have some tiny bugs that can cause some missreads when two sections overlap or contain a gap between them. Theres another bug related to this and in theory its all fixed with the condret branch, but im waiting for him to integrate slowly and properly test everything to avoid other regressions.

**Comment by radare** [comment] 2015-07-21 10:11
I fixed a bug and if you set e io.va=false after normal load you can search in pa mode and then go back to iova=1.

I'll look into this issue if @condret branch takes more time to come.

**Comment by xambroz** [comment] 2015-07-27 13:03
The workaround with io.va=false works giving offset from the beginning of the file. 
Problem is - the non-va address probably wont help you much in identifing the code referencing this string address. You still would have to have idea about different sections being mapped to memory from different address to be able to manually recalculate the offset (+ 0x401E00 in this case)

```
Example:
$ radare2 WEBGATE400I.EXE 
[0x00513d71]> e io.va=false
[0x00513d71]> / GETIFSOBJ
Searching 9 bytes from 0x00513d71 to 0x03048f50: 47 45 54 49 46 53 4f 42 4a 
# 6 [0x513d71-0x3048f50]
hits: 1
0x00d06e4c hit0_0 "GETIFSOBJ"
[0x00d06e5c]> s 0x00d06e4c
[0x00d06e4c]> V
[0x00d06e4c 37% 800 WEBGATE400I.EXE]> x @ hit0_0                                       
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF                  
0x00d06e4c  4745 5449 4653 4f42 4a00 0000 7800 6600  GETIFSOBJ...x.f.                  
0x00d06e5c  3400 3000 3000 4300 6800 6500 6300 6b00  4.0.0.C.h.e.c.k.                  
0x00d06e6c  5500 7300 6500 7200 4300 6f00 6e00 6e00  U.s.e.r.C.o.n.n.                  
0x00d06e7c  6500 6300 7400 6900 6f00 6e00 5000 7200  e.c.t.i.o.n.P.r.                  
0x00d06e8c  6f00 7000 6500 7200 7400 6900 6500 7300  o.p.e.r.t.i.e.s.                  
0x00d06e9c  2000 4500 4e00 4400 0000 0000 7800 6600   .E.N.D.....x.f.         

[0x00d06e4c]> /x 4c6ed000
Searching 4 bytes...
# 6 [0xd06e4c-0x3048f50]
hits: 0

[0x00d06e4c]> e io.va=true
[0x00d06e4c]> V
[0x00d06e4c 37% 800 WEBGATE400I.EXE]> x @ hit0_0                                       
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF                  
0x00d06e4c  894e 0c89 4e04 ff37 ff75 dcff 1528 dc45  .N..N..7.u...(.E                  
0x00d06e5c  0183 460c 02eb 696a 0ae8 0771 71ff 8bd8  ..F...ij...qq...                  
0x00d06e6c  83fb ff75 128b 078b 48f4 b803 0100 003b  ...u....H......;                  
0x00d06e7c  c87f 0d8b c1eb 09b8 0301 0000 3bd8 7e02  ............;.~.   

[0x00d06e4c]> s 0x01108C4C
[0x01108C4C]> V
[0x01108c4c 53% 800 WEBGATE400I.EXE]> x @ reloc.oledlg.dll_OleUIPasteSpecialW_104+50762
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF                  
0x01108c4c  4745 5449 4653 4f42 4a00 0000 7800 6600  GETIFSOBJ...x.f.                  
0x01108c5c  3400 3000 3000 4300 6800 6500 6300 6b00  4.0.0.C.h.e.c.k.                  
0x01108c6c  5500 7300 6500 7200 4300 6f00 6e00 6e00  U.s.e.r.C.o.n.n.                  
0x01108c7c  6500 6300 7400 6900 6f00 6e00 5000 7200  e.c.t.i.o.n.P.r.    

#Searching for the address
[0x01108c4c]> /x 4c8c1001
Searching 4 bytes...
# 6 [0x401000-0x1c528c0]
hits: 2
0x00c808b1 hit0_0 45f8e8bb
0x00f44231 hit0_1 c38b4424

```

**Comment by radare** [comment] 2015-07-27 21:38
You can rebase the flags using the fb command. 

But va search should work as expected if io worked fine in this case. Maybe @condret can have a look at this

**Comment by radare** [comment] 2015-07-28 17:57
i have found a "workaround" for another bug similar to this but it
breaks some tests and it requires some testing. i dont have much time
right now, but maybe i can push that workaround if anyone wants to test

maybe condret can find some time between exam and exam to verify if the
VIO branch fixes this issue, and maybe others.

**Comment by radare** [comment] 2015-11-20 00:47
Can someone verify this is still happening?

**Comment by Maijin** [comment] 2016-05-24 09:11
The bin is not the same looks like

**Comment by Maijin** [comment] 2016-09-11 21:18
ping 1

**Comment by Maijin** [comment] 2016-09-19 18:42
ping 2

**Closed** 2016-10-09 17:02 UTC
Labels: bug, io
