### ISSUE TITLE
enhance Vd: option to rename flags used in current instruction

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3745] opened 2015-11-23 19:12 UTC
It should allow to rename functions used in the instruction referenced by the cursor and also rename local var/args.

We can introduce 'Vdv' to rename local vars and 'Vdn' to rename functions or just use 'Vdn' to rename everything (a little bit more complicated because the command has to understand the type of the flag).

A possible issue can arise if there are multiple flags used in one instruction.

Thoughts?

**Comment by Maijin** [comment] 2016-02-18 15:29
Duplicate of https://github.com/radare/radare2/issues/2805

**Comment by ret2libc** [comment] 2016-02-21 14:19
It's not a duplicate IMO, because what i want to do here is to add a new option to the 'Vd' menu that should be able to rename the flag/variable/argument under the cursor, like what you do when you are in IDA, you select a symbol on an instruction and press 'n'

**Comment by radare** [comment] 2016-02-21 20:03
👍

**Closed** 2016-02-23 08:25 UTC
Labels: consoleui, enhancement, question
