### ISSUE TITLE
Better xrefs in disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#9028] opened 2017-12-16 00:25 UTC
now:
```
 ; XREFS: CALL 0x0052cc22  CALL 0x0056b650  CALL 0x0056bb08  CALL 0x0056bc90  CALL 0x0058af26  CALL 0x0058b43e  CALL 0x0058b61a  CALL 0x0060c60a
```

should be:
```
; XREFS: CALL 0x0052cc22 0x0056b650 0x0056bb08 0x0056bc90 0x0058af26 0x0058b43e 0x0058b61a 0x0060c60a
```

**Comment by Maijin** [comment] 2017-12-16 00:59
Duplicate of https://github.com/radare/radare2/issues/8815

**Closed by Maijin** 2017-12-16 00:59 UTC
Labels: enhancement, good first issue, release
