### ISSUE TITLE
Rethink types storage

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10905] opened 2018-08-03 04:07 UTC
Currently it uses SDB which is perfectly fine for plain C types.
It might become inefficient as is for storing C++ classes, methods and inheritance information, especially for something big like Qt types.
We need to design better (still uniform between C and C++ (or alike)) types storage (can be on top of SDB, just with maybe additional API/abstraction).

Summoning @radare @sivaramaaa @thestr4ng3r @ret2libc for discussion (Telegram discussion is not suitable for something complex like this).

**Comment by Maijin** [comment] 2018-08-03 07:06
It also needs to be **easy** to contribute to and documented, otherwise nobody will use it

**Comment by radare** [comment] 2018-08-03 11:40
You can represent literally anything with k=v.

What kind of extra information you need to store? You can also store a json in sdb as a value to put the extra c++ specific info for a type. That will not break current implementation and allow extra details to be added to any type

**Comment by XVilka** [comment] 2018-08-03 12:37
@radare I mentioned in the initial message it can be stored on top of the SDB. Problem not in the "low-level" storage. Problem of the uniform format between C and C++ types (and possibly other kinds of types), effective parsing (with monstrous classes hierarchy in programs compiled with Boost for example), etc.

**Comment by radare** [comment] 2018-08-03 13:00
can we have a list of things extra to store that we are not storing now? just to understand how hard is to make this happen

**Comment by Maijin** [comment] 2018-08-03 13:13
(examples could help)

**Comment by thestr4ng3r** [comment] 2018-08-03 13:19
Just off the top of my head, a C++ class needs at the very least the following info:
* name
* namespace (would be nice to have a consistent format across languages for java packages, c++ namespaces or whatever)
* List of methods with the following info per method:
  * address/reference to function
  * name (name of the function is probably most likely not enough)
  * offset in the vtable if it is virtual
* List of fields (struct?)
* List of base classes, not just a single one + the offset of each base in the class (or maybe let that offset to be derived from the list of fields and include the base as a field there?)

**Comment by radare** [comment] 2018-08-03 13:49
is this type or class information ? :P

> On 3 Aug 2018, at 15:41, Florian Märkl <notifications@github.com> wrote:
> 
> Just off the top of my head, a C++ class needs at the very least the following info:
> 
> name
already there
> namespace (would be nice to have a consistent format across languages for java packages, c++ namespaces or whatever)
just another value in the kv of the type
> address of the vtable if there is one
thats totally unrelated to the type, i see this more associated to a specific bind of the type. its not a binded type.

type information must be generic and static for all binaries, the associated location of a type is specific to each binary. which can be in many situations found more than once in the same binary. so its not an unique association.

> List of methods with the following info per method:
> address/reference to function
> name (name of the function is probably most likely not enough)
> offset in the vtable if it is virtual
> flags for constructor/destructor?

this is already in the sdb information of class/methods 
> 
> List of fields (struct?)
same
> List of base classes, not just a single one + the offset of each base in the class (or maybe let that offset to be derived from the list of fields and include the base as a field there?)

can be added to sdb.

so. from what i see, few tweaks will be needed, dont overenginner with json for just this please.

**Comment by thestr4ng3r** [comment] 2018-08-03 14:34
Well of course it is class info. The question is do we want to store all the class info inside the types or should we have another storage for classes and then define types that reference those classes?

>> address of the vtable if there is one
>
> thats totally unrelated to the type, i see this more associated to a specific bind of the type. its not a binded type.
> 
> type information must be generic and static for all binaries, the associated location of a type is specific to each binary. which can be in many situations found more than once in the same binary. so its not an unique association.

That's a good argument. Then, if we want to separate types and type binds, how do we design that?

> > List of methods with the following info per method:
> > address/reference to function
> > name (name of the function is probably most likely not enough)
> > offset in the vtable if it is virtual
> > flags for constructor/destructor?
>
> this is already in the sdb information of class/methods

Where? All I am aware of is `anal/types/*`, I see no way of storing that stuff there right now.

>> namespace (would be nice to have a consistent format across languages for java packages, c++ namespaces or whatever)
>
> just another value in the kv of the type

>> List of base classes, not just a single one + the offset of each base in the class (or maybe let that offset to be derived from the list of fields and include the base as a field there?)
>
> can be added to sdb.

How exactly would you do that? Add more keys to `anal/types/ like` `class.Test.baseclasses` and store the list as an sdb array, which separates the entries with commas?
To be honest, I think this approach with the . syntax for keys is really a bad idea and unsafe af. I already pointed that out on telegram. Consider the following situation:
I save the type `uint32_t`, so the keys `uint32_t=type` and `type.uint32_t=d` will be set. Now I save a type called `type.uint32_t`, so the keys `type.uint32_t=type` and `type.type.uint32_t=d` will be set and everything is fucked up. How do you prevent cases like that? Escape it? Use base64? Not to mention the fact that you can't use commas in array elements. There's definitly possibilities to work around these issues, but it just makes everything more complicated and messy trying to force everything into kv.

That's why I am proposing to save these complex things into sdb, each "object" (type, class, whatever) must have some unique id (the name or whatever, but it must really be unique) and keys are only considered to be these ids, not `type.<id>.size` or anything else and all these attributes are saved in the value in a well-defined format like json or msgpack.

**Comment by radare** [comment] 2018-08-03 17:14
> On 3 Aug 2018, at 16:41, Florian Märkl <notifications@github.com> wrote:
> 
> Well of course it is class info. The question is do we want to store all the class info inside the types or should we have another storage for classes and then define types that reference those classes?
> 
> 
from what you said i dont see the point on having another storage for the new info you are showing
> address of the vtable if there is one
> 
> thats totally unrelated to the type, i see this more associated to a specific bind of the type. its not a binded type.
> 
> type information must be generic and static for all binaries, the associated location of a type is specific to each binary. which can be in many situations found more than once in the same binary. so its not an unique association.
> 
> That's a good argument. Then, if we want to separate types and type binds, how do we design that?
> 
> 
well types are binded to a specific address with the `tl` command, to link a type at a given offset. which can be global or local to a function.. we need to bind or link the vtable of a type. maybe @sivaramaa have another idea to avoid reinventing the wheel here.
> List of methods with the following info per method:
> address/reference to function
> name (name of the function is probably most likely not enough)
> offset in the vtable if it is virtual
> flags for constructor/destructor?
> 
> this is already in the sdb information of class/methods
> 
> Where? All I am aware of is anal/types/*, I see no way of storing that stuff there right now.
> 
the class is coming from RBin right now. maybe we should allow to define such thing from anal/types.. and maybe extend the TCC parser to support some kind of object-orientied sugar to have this info from a C-style syntax too.
> namespace (would be nice to have a consistent format across languages for java packages, c++ namespaces or whatever)
> 
> just another value in the kv of the type
> 
> List of base classes, not just a single one + the offset of each base in the class (or maybe let that offset to be derived from the list of fields and include the base as a field there?)
> 
> can be added to sdb.
> 
> How exactly would you do that? Add more keys to anal/types/ like class.Test.baseclasses and store the list as an sdb array, which separates the entries with commas?
> 
imho classes are not types, or at least not in the way we think about types. they are more like a struct with an vtable of pointers and some fields inside, to point to the rest of the data. so they are some kind of meta-type. if we add stuff into anal/types we should extend tcc to support that info too. otherwise it will be impaired by design. 

> To be honest, I think this approach with the . syntax for keys is really a bad idea and unsafe af. I already pointed that out on telegram. Consider the following situation:
> I save the type uint32_t, so the keys uint32_t=type and type.uint32_t=d will be set. Now I save a type called type.uint32_t, so the keys type.uint32_t=type and type.type.uint32_t=d will be set and everything is fucked up. How do you prevent cases like that? Escape it? Use base64? Not to mention the fact that you can't use commas in array elements. There's definitly possibilities to work around these issues, but it just makes everything more complicated and messy trying to force everything into kv.
> 
> 
wat, i dont see why prefixing type. will fuck anything because it will be just prefixed, it looks wrong because its type is doubled but nothing will be fucked up. also, types CANT contain a dot. its specified by the language semantics., neither C, Swift, C++ Java or any other lang i know allows users to do that. maybe java at binary level or c# can,. but not at language level. and the source of those types is from C files parsed by shlr/tcc.

array elements? you cant use a comma as a name for a type either. thats just an invalid type

> That's why I am proposing to save these complex things into sdb, each "object" (type, class, whatever) must have some unique id (the name or whatever, but it must really be unique) and keys are only considered to be these ids, not type.<id>.size or anything else and all these attributes are saved in the value in a well-defined format like json or msgpack.
> 
> 
sdb have a  fmt api that allows to do that already, no need to reinvent the wheel or use bloated or external formats.

but still i dont see the reason for escaping dots and commas, when those should be invalid chars for a type name.

**Comment by XVilka** [comment] 2018-08-03 17:25
I can add classes support in tcc if you will care about r2 storage. I have
so ideas how to implement this without big refactoring. I think we need to
unify classes and types, and make vtables generic, so they won't be just
C++ specific.

**Comment by XVilka** [comment] 2018-08-10 09:12
@kriw , @HMPerson1 @sushant94 and @chinmaydd might be interested in this as well.

**Comment by thestr4ng3r** [comment] 2018-08-10 09:59
>> To be honest, I think this approach with the . syntax for keys is really a bad idea and unsafe af. I already pointed that out on telegram. Consider the following situation: I save the type uint32_t, so the keys uint32_t=type and type.uint32_t=d will be set. Now I save a type called type.uint32_t, so the keys type.uint32_t=type and type.type.uint32_t=d will be set and everything is fucked up. How do you prevent cases like that? Escape it? Use base64? Not to mention the fact that you can't use commas in array elements. There's definitly possibilities to work around these issues, but it just makes everything more complicated and messy trying to force everything into kv.
>
> wat, i dont see why prefixing type. will fuck anything because it will be just prefixed, it looks wrong because its type is doubled but nothing will be fucked up. also, types CANT contain a dot. its specified by the language semantics., neither C, Swift, C++ Java or any other lang i know allows users to do that. maybe java at binary level or c# can,. but not at language level. and the source of those types is from C files parsed by shlr/tcc.

Yes, it will. Both `type.uint32_t=d` and `type.uint32_t=type` use the same key despite being two different things. This could theoretically be solved though if you prefix everything. For example if you say instead of using `typename=d`, you could also use `kind.typename=d` or whatever, then you will always have unique keys.

But overall you can't just say "types won't ever contain dots" just because most languages don't allow it or tcc doesn't support it. If you forbid dots, you have to explicitly specify that and add input validation at the right places. If that is done, it can be considered safe.

> array elements? you cant use a comma as a name for a type either. thats just an invalid type

Same thing, of course a comma doesn't make much sense in practice. And since we know how sdb arrays work we can validate the input correctly if we have to.

However in general, if I use a function like `sdb_array_append()` for example, I expect it to append the string I give to it to the array no matter what the string contains. How should I possibly know that I can't pass commas if I am not familiar with the sdb internals?

That's why I think it will be better to use a well-defined format like json for things like that. Whether it will be the json support that's inside sdb already or msgpack or whatever doesn't really matter as long as it really is safe. But the prefixing-comma approach that is currently used will sooner or later break if we add more complex stuff.

**Comment by radare** [comment] 2018-08-10 13:36
answering inline

> On 10 Aug 2018, at 11:59, Florian Märkl <notifications@github.com> wrote:
> 
> To be honest, I think this approach with the . syntax for keys is really a bad idea and unsafe af. I already pointed that out on telegram. Consider the following situation: I save the type uint32_t, so the keys uint32_t=type and type.uint32_t=d will be set. Now I save a type called type.uint32_t, so the keys type.uint32_t=type and type.type.uint32_t=d will be set and everything is fucked up. How do you prevent cases like that? Escape it? Use base64? Not to mention the fact that you can't use commas in array elements. There's definitly possibilities to work around these issues, but it just makes everything more complicated and messy trying to force everything into kv.
> 
> wat, i dont see why prefixing type. will fuck anything because it will be just prefixed, it looks wrong because its type is doubled but nothing will be fucked up. also, types CANT contain a dot. its specified by the language semantics., neither C, Swift, C++ Java or any other lang i know allows users to do that. maybe java at binary level or c# can,. but not at language level. and the source of those types is from C files parsed by shlr/tcc.
> 
> Yes, it will. Both type.uint32_t=d and type.uint32_t=type use the same key despite being two different things. This could theoretically be solved though if you prefix everything. For example if you say instead of using typename=d, you could also use kind.typename=d or whatever, then you will always have unique keys.
> 
> 
yep. that looks like it shuold be type.uint32_t.format=d instead of =d
> But overall you can't just say "types won't ever contain dots" just because most languages don't allow it or tcc doesn't support it. If you forbid dots, you have to explicitly specify that and add input validation at the right places. If that is done, it can be considered safe.
> 

why not seems like a correct assumption and not that bad restriction to me. we can use : and other chars even emojis to represent types. its just the dot.
> array elements? you cant use a comma as a name for a type either. thats just an invalid type
> 
> Same thing, of course a comma doesn't make much sense in practice. And since we know how sdb arrays work we can validate the input correctly if we have to.
> 
> 
well i should write tests for this but i think theres nothing to forbid you to do that
> However in general, if I use a function like sdb_array_append() for example, I expect it to append the string I give to it to the array no matter what the string contains. How should I possibly know that I can't pass commas if I am not familiar with the sdb internals?
> 
> That's why I think it will be better to use a well-defined format like json for things like that. Whether it will be the json support that's inside sdb already or msgpack or whatever doesn't really matter as long as it really is safe. But the prefixing-comma approach that is currently used will sooner or later break if we add more complex stuff.
> 
> 
lets just improve sdb and add more tests for proper/discussed/expected behaviour instead

**Comment by qrux0** [comment] 2018-08-18 22:58
Hello. 

If we want to let user modify types in C representation (https://github.com/radare/radare2/issues/10457), add support for c++ types (https://github.com/radare/radare2/issues/7710) and let user modify existing types in convenient way we need extend current sdb types storage schema.

Bellow you may read my proposal for this. Dunno is it good enough.

All types, structures, enums, functions and typedefs must have unique identifier (type id, or **tid**). Structures store **tid** for all related fields. So, if user changes name of already defined strucure/type r2 don't lost link to it.  With `sdb_foreach_match` one could get information about type from **tid**.

**tid** for all base types (void, char, int, void\*, float, double, ...) need to be predefined. Because r2 should be able to load different base types sdb's (if user wants to do so).. 

**tid** is stored only in r2 instance, binary or text representation does not save it (if sdb have **tid**, it will be ignored at db load).

Field sizes and structure offsets are calculated at the time of use (but, we may store cached offset/size in sdb and update all related structures on type size change).

Structures need additional fields for extra attributes (like alignment, for example).

New scheme example
==================

This structure:

```
struct list {
	struct list *next;
	int32_t val;
};
```

will be mapped to

```
list=struct
struct.list=next,val		//
struct.list.attrs=		//optional field, Maybe vtables, classes, needs this
struct.list.id=42		//internal unique identifier, this field exists only in loaded type sdb's
struct.list.alignment=0		//structure alignment, 0 for default/unknown structure alignment 
struct.list.field.next=42,1,0	//(tid,ptrdepth,arrsz) previous format (typestr,offset,arrsz) 
				//ptrdepth is integer, 0 for original `type`, 1 for `type *`, 2 for `type **`, ...

struct.list.field.next.meta=4	//TCC type info, don't know who uses it
struct.list.field.val=2,0,0	//Base types (int,char,void*, etc) have some predefined identifiers
struct.list.field.val.meta=0
```

For comparison, current sdb format for that structure is
```
list=struct
struct.list=next,val
struct.list.next=struct list *,0,0
struct.list.next.meta=4
struct.list.val=int32_t,4,0
struct.list.val.meta=0
```

Reasons for that changes:
- Extending of types/structures storage;
- Types db is *related* database, and better to use integers  for references, than strings. 
- I belive changes will simplify type propagation analysis, because now analysis functions have to parse string with type name on execution (https://github.com/radare/radare2/blob/master/libr/core/anal_tp.c#L114)

Open questions:
- Do we have to use type sdb for every indirect function call interface?
	 
Downsides:
- Type sdb, loaded in r2 slightly differs from on-file version. r2 will need to convert **tid** to string representation on db dump.
- New schema is not backwards compatible with current, so migration to new one could be pain in the ass.

P.S.: I'm not mature r2 contributor and maybe my proposal is crap, but I believe current sdb scheme is not just good enough.

**Comment by XVilka** [comment] 2018-08-19 07:03
@qrux0 in general I like your idea, it needs better structure for classes/inheritance. @thestr4ng3r @sivaramaaa what do you think?

**Comment by radare** [comment] 2019-04-09 13:08
any updates on here?

**Comment by thestr4ng3r** [comment] 2019-04-09 18:04
Well anal classes are in sdb now, so not sure if this is still relevant.

**Comment by radare** [comment] 2019-04-09 19:41
Yeah i think we can close it unless we have any other complain .. we can always reopen it :p

**Closed** 2019-07-05 10:07 UTC
Labels: RAnal, refactor, sdbtization, types
