### ISSUE TITLE
multiple eip pointers when debugging

### ISSUE THREAD

**Issue by q6r** [radare/radare2#2628] opened 2015-05-27 02:47 UTC
When debugging "r2 -d ..." r2 shows multiple "; eip --" pointers which makes things confusing. eg : 
![multiple_eip](https://cloud.githubusercontent.com/assets/1616882/7827765/0508fe10-03e0-11e5-9166-92a48b4430ad.jpg)

**Comment by radare** [comment] 2015-05-27 07:38
Can you provide version of r2 and operating system/arch/target?

**Comment by q6r** [comment] 2015-05-27 07:50
@radare commit 6ab745d6.... Linux x86_64 and debugging an elf 32bit binary.

**Comment by radare** [comment] 2015-05-27 08:23
Cannot reproduce. What are you doing to get multiple eips?

**Comment by q6r** [comment] 2015-05-27 08:43
@radare https://asciinema.org/a/dv66b6q8r3lfq4dndgdsdqa71 took me sometime to reproduce. Only used ">" arrow and step. Also it shows that something bad happened probably due the binary beign obfuscated. The binary used was simpleVM from reverse.kr

**Comment by radare** [comment] 2015-05-28 12:21
Can anyone else reproduce? it would be great to have a 100% reproducible test case. Looks like a bug in rflags, which should be fixable when moving to sdb.

**Closed** 2015-05-28 23:03 UTC
