### ISSUE TITLE
r2 webgui ARM displaying loc instead of function sym name

### ISSUE THREAD

**Issue by Jegeva** [radare/radare2#4484] opened 2016-04-01 09:04 UTC
binary attached
[main.elf.zip](https://github.com/radare/radare2/files/199267/main.elf.zip)
 : 

radare2 0.10.0-git 10428 @ linux-little-x86-64 git.0.10.0-264-g1d4b715
commit: 1d4b7156dbc52ebad8e6b594cc1c39eb392a2d2b build: 2016-02-27

command r2 -c=H -a arm.gnu main.elf
problem is that if a sym is also a loc, r2 displays the loc instead of the sym name ***in the web gui***
ex: (indicated by < 
0x8003052 strh r3, [r6, 0x14]
0x8003054 bl loc._t_109 **<**
0x8003058 mov r0, r7
0x800305a bl loc._t_79 **<**
0x800305e mov r0, r4
0x8003060 bl loc._t_80 **<**
0x8003064 ldr r0, [pc, 0x1e4]
0x8003066 mov r1, r4
0x8003068 bl sym.USART_Cmd
0x800306c mov r2, r4
0x800306e movw r1, 0x525
0x8003072 ldr r0, [pc, 0x1d8]
0x8003074 bl sym.USART_ITConfig
0x8003078 bl loc._t_108
0x800307c ldr r0, [r5]
0x800307e bl loc._t_102
0x8003082 bl loc._t_97

from command line:
pdf@sym.main
 0x08003052      b382           strh r3, [r6, 0x14]
|           0x08003054      fff76afd       bl sym.usart_init
|           0x08003058      3846           mov r0, r7
|           0x0800305a      fef769ff       bl sym.STM_EVAL_LEDInit
|           0x0800305e      2046           mov r0, r4
|           0x08003060      fef78aff       bl sym.STM_EVAL_LEDOn
|           0x08003064      7948           ldr r0, [pc, 0x1e4]         ; [0x800324c:4]=0x40013800 
|           0x08003066      2146           mov r1, r4
|           0x08003068      fef732fe       bl sym.USART_Cmd
|           0x0800306c      2246           mov r2, r4
|           0x0800306e      40f22551       movw r1, 0x525
|           0x08003072      7648           ldr r0, [pc, 0x1d8]         ; [0x800324c:4]=0x40013800 
|           0x08003074      fef706ff       bl sym.USART_ITConfig
|           0x08003078      fff752fd       bl sym.usart_clrscrn
|           0x0800307c      2868           ldr r0, [r5]
|           0x0800307e      fff78dfc       bl sym.usart_set_receive_buff
|           0x08003082      fff7c7fa       bl sym.eeprom_init

**Comment by radare** [comment] 2016-04-01 09:18
a quick workaround would be to remove all locs with `f-loc*`

**Comment by radare** [comment] 2016-04-01 09:18
@Maijin can you add a test, and put it with other tests related to autonaming functions and such, so we can have a proper look at this issue without breaking much stuff?

**Comment by radare** [comment] 2016-04-01 09:19
uhm, wait, you are using a very old version of r2. it works fine with master. can you update your r2 from git please? or at least use the last release

**Comment by Maijin** [comment] 2016-04-01 09:33
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Jegeva** [comment] 2016-04-01 13:11
just updated 
same binary, same problem with the binary attached (see attached screenshot side by side of the webgiu and console)

radare2 0.10.2-git 10782 @ linux-little-x86-64 git.0.10.1-327-gc917f12
commit: c917f128fdc0298fb4dfc652402022a78f756fc4 build: 2016-04-01

![r2_lastver](https://cloud.githubusercontent.com/assets/4939609/14207669/de26db38-f81b-11e5-83fc-951dc624b776.png)

**Comment by Jegeva** [comment] 2016-04-01 13:40
btw, if i f-loc* like pancake said before launching the gui it's fine (but all locs are obviously missing)

**Comment by radare** [comment] 2016-04-01 13:49
ah! you mean that the issue is only happening in the webui? the only difference i can think of is that the webui uses pdj instead of pd, so the JSON disassembly is not correct.

**Comment by XVilka** [comment] 2016-04-01 13:54
@radare if you see the sources - pd and pdj are using different functions in libr/core/disasm.c, this can be the reason - someone fixed pd's one, but not the another.

**Comment by radare** [comment] 2016-04-04 09:10
The /p webui replaces the numbers instead of letting this be done by r2, so its a problem in the javascript side. not in r2 core or in pdj.. we can probably let pdj spit out the original instruction and the substituted string one in the JSON, which can be probably handy for some frontends. What do you think?

**Comment by radare** [comment] 2016-04-04 22:18
As long as this issue is /p-specific, can you close this issue and open it in the radare2-webui repo?

**Closed** 2016-04-04 22:59 UTC
Labels: disassembly, question, regression
