### ISSUE TITLE
radiff2 -g should output in ascii art too

### ISSUE THREAD

**Issue by radare** [radare/radare2#3508] opened 2015-10-18 21:53 UTC
we need another flag to specify which kind of output we want: graphviz or asciiart. and maybe sdb-k/v, csv, etc..

**Comment by radare** [comment] 2015-10-18 21:54
we should implement this in R_API int r_core_anal_graph(RCore *core, ut64 addr, int opts) {

**Comment by radare** [comment] 2015-10-18 22:03
Would be cool to have an interactive asciiart graphdiff from `radiff2 -g` too

**Comment by XVilka** [comment] 2019-07-09 15:25
Duplicate of https://github.com/radare/radare2/issues/7332

**Closed by XVilka** 2019-07-09 15:25 UTC
Labels: RGraph, radiff2
