### ISSUE TITLE
t->pf unions not working properly

### ISSUE THREAD

**Issue by radare** [radare/radare2#12267] opened 2018-11-22 03:01 UTC
i have implemented union support in pf in a separate pr 
https://github.com/radare/radare2/pull/12265

the thing is that if we define a union with td the output is not correct:

```
$ r2 -
"t -- Coffee time!
[0x00000000]> "td union foo {int a;char b;}"
[0x00000000]> tu*
[0x00000000]> ts*
[0x00000000]> t*~foo
tk foo=union
tk union.foo=a,b
tk union.foo.a=int32_t,0,0
tk union.foo.a.meta=0
tk union.foo.b=char,0,0
tk union.foo.b.meta=2
[0x00000000]> t foo
pf dc a b
[0x00000000]>
```

also before merging we need to discuss if , and ; are good chars here. imho they are

btw this tu* is not working:
```
[0x00000000]> tu* foo
pf.foo dc a b
[0x00000000]> tu*
[0x00000000]>
```

should iterate overa ll of them like is happening with ts and te

**Comment by XVilka** [comment] 2018-11-22 05:02
Well, for the output I agree. The trickiest thing is to print a member, which one to choose?

**Comment by radare** [comment] 2018-11-22 09:52
Nope just print them all, unless specified by accessing the field by name

**Comment by XVilka** [comment] 2018-11-22 11:21
We should add a tests for this case too.

**Comment by radare** [comment] 2018-11-22 14:19
Let's move this to 3.2 because we need to discuss and fix other things related to unions support. At least the pf ,; syntax is now merged and ready. ill add tests later

**Comment by XVilka** [comment] 2018-11-22 16:29
@radare in fact it is probably just duplicate of https://github.com/radare/radare2/issues/10032

**Comment by radare** [comment] 2018-11-22 18:43
Maybe but i would keep both for now. Should be easy to implement after release

**Comment by radare** [comment] 2019-04-17 11:23
i think its fixed, but enotime to verify, anyone? also pls add testss

**Comment by XVilka** [comment] 2019-05-05 22:26
@oxcabe can you please check and write tests for this?

**Comment by radare** [comment] 2019-05-07 11:01
ping

**Comment by oxcabe** [comment] 2019-05-07 14:22
will do

**Comment by XVilka** [comment] 2019-07-31 09:31
Will be fixed by https://github.com/radare/radare2/pull/14712

**Comment by XVilka** [comment] 2019-07-31 10:42
@oxcabe please create a test for this for the 3.7.0 release. It is very important!

**Comment by oxcabe** [comment] 2019-07-31 17:56
I'm finishing https://github.com/radare/radare2/issues/14541 then will create tests!

**Comment by XVilka** [comment] 2019-08-03 05:57
Now it is fixed, thanks everyone.

**Closed by XVilka** 2019-08-03 05:57 UTC
Labels: RAnal, test-required, types
