### ISSUE TITLE
Add command to save/restore visual eval configurations

### ISSUE THREAD

**Issue by radare** [radare/radare2#6251] opened 2016-11-23 12:41 UTC
this is:

* asm.emu
* asm.emustr
* asm.cmtcol
* eco theme
* ...

this must go into the default startup script of r2

**Comment by radare** [comment] 2016-12-10 01:20
Maybe having a config_push method that accepts a null terminated array of fields to save

**Comment by Maijin** [comment] 2017-12-03 16:27
Duplicate of #3692

**Closed by Maijin** 2017-12-03 16:27 UTC
Labels: consoleui, good first issue, question
