### ISSUE TITLE
radare2 segfaults when analysing a large ELF x86_64 binary.

### ISSUE THREAD

**Issue by marespiaut** [radare/radare2#5972] opened 2016-10-14 19:27 UTC
Hello,

I've compiled the latest revision for [ResidualVM](https://github.com/residualvm/residualvm/commit/1a8773f3ab3217430a5bc038db1f436f28002019) under Debian Stretch x86_64 (GCC v6.1.1) with a Makefile generated as follow
```
./configure --enable-all-engines --enable-debug
```
which generated a 21Mb binary.

when running `r2 -AAAA residualvm` Radare2 takes a very long time (approximately 45 minutes on a Intel Xeon CPU E3-1240 v3) analysing all flags starting with sym. and entry0 (aa) and then segfaults.

**Comment by Maijin** [comment] 2016-10-14 20:13
Can you share the bin here ?

**Comment by radare** [comment] 2016-10-14 21:24
are you using r2 frmo git? can you paste a backtrace? debian sucks at offering memory to the applications and it kills them as soon as they eat too much. so im quite sure this is not a bug in r2, a part that r2 memory consumption could be better and analysis faster

**Comment by radare** [comment] 2016-10-18 12:28
hello?

**Comment by marespiaut** [comment] 2016-10-24 07:54
Hello,

Sorry for the late reply. Here is the binary that is causing me problems.
I'm using the following radare2 version
```
radare2 0.10.5 9999999 @ linux-x86-64 git.0.10.5
commit: HEAD build: 2016-09-01
```
I cannot use another radare2 version on this computer for now.

[residualvm.xz.zip](https://github.com/radare/radare2/files/547170/residualvm.xz.zip)
Note: I'm bypassing Github restriction by storing a `.xz` into a `.zip`. The MD5 checksum should be
```
78ff101c45e6d63aeeba58b86dcff582  residualvm
```

**Comment by marespiaut** [comment] 2016-10-24 14:38
I've ran radare2 through valgrind using the following command:
```
valgrind --leak-check=full -v --trace-children=yes --log-file=radarelogfile.txt r2 -AA residualvm
```
and I got the following log file:
[radarelogfile.txt.zip](https://github.com/radare/radare2/files/548131/radarelogfile.txt.zip)

Unfortunately I haven't got any coredump file, even with `ulimit` set to unlimited.

**Comment by radare** [comment] 2016-10-24 14:48
afaik this is fixed in master, we don't fix bugs in old versions

**Comment by radare** [comment] 2016-10-25 18:38
> On 24 Oct 2016, at 09:54, Marc-Alexandre Espiaut <notifications@github.com> wrote:
> 
> Hello,
> 
> Sorry for the late reply. Here is the binary that is causing me problems.
> I'm using the following radare2 version
> 
> radare2 0.10.5 9999999 @ linux-x86-64 git.0.10.5
> commit: HEAD build: 2016-09-01
> I cannot use another radare2 version on this computer for now.
> 
> 

why? not using r2 from git is against our r2ligion

**Closed** 2016-10-27 10:58 UTC
Labels: anal, bug

**Comment by marespiaut** [comment] 2016-10-27 13:18
I forgot to mention that I've tested this again with the lastest git revision and r2 works perfectly. So, this is good.
