### ISSUE TITLE
/C sux. here is the solution

### ISSUE THREAD

**Issue by 0ki** [radare/radare2#11490] opened 2018-09-11 22:34 UTC
This neat tool is in the public domain and works nicely.
Could probably be integrate to replace /Ca
https://github.com/mmozeiko/aes-finder

For /Cr this MIT licensed tool is worth integrating:
https://github.com/cryptolok/CryKeX
I haven't tested it though.

**Comment by Maijin** [comment] 2018-09-12 19:37
Duplicate of #8989,  please continue here.

**Closed by Maijin** 2018-09-12 19:37 UTC
Labels: search
