### ISSUE TITLE
Visual disassembling registers

### ISSUE THREAD

**Issue by joaquinferrero** [radare/radare2#7486] opened 2017-05-13 18:02 UTC
Decompiling a z80 binay file, the visual disassembling show this lines:

;-- ah:
;-- al:
;-- bh:
;-- bl:
;-- ch:
;-- cl:
;-- dh:
;-- dl:
;-- r8b:                                                   
;-- r9b:
;-- r10b:
;-- r11b:
;-- r12b:
;-- r13b:
;-- r14b:
;-- r15b:
;-- sil:
;-- dil:
;-- spl:
;-- bpl:

They aren't z80 registers.

The file is opened with
r2 -a z80 file
or
r2 -p project

> i
blksz    0x0
block    0x113
fd       6
file     /home/explorer/Proyectos/Pengo/radare2/pengo2u.bin
format   any
iorw     false
mode     ——
size     0x8000
humansz  32K

radare2 1.5.0-git 14717 @ linux-x86-64 git.1.4.0-173-g11e8da3
commit: 11e8da31ed2ea3c229269ddcc6498c58a21be704 build: 2017-05-13__00:41:08

**Comment by Maijin** [comment] 2017-05-13 18:15
For the "blind" @radare, the Post has been updated email is outdated.

**Comment by radare** [comment] 2017-05-13 19:48
Yep i read that from the mail. Agree that looks better now, but will be good to clean that patch before merging. Good work :) this pdc thing is a hack after a hack :D and its hacky to get in touch with it

**Comment by radare** [comment] 2017-05-18 22:09
please describe the steps you do to reproduce this, record an asciinema, share the bin, or use any other random file if not needed

**Comment by radare** [comment] 2017-05-20 10:13
this happens because there's no reg profile for z80

**Comment by radare** [comment] 2017-05-20 10:16
Fixed in 815b9c0171628c600a96d2c82e01776e24a09652

**Closed by radare** 2017-05-20 10:16 UTC
Labels: bug, easy, test-required
