### ISSUE TITLE
Wrong lib folder name for Bochs when building radare2 on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#5232] opened 2016-06-28 20:41 UTC
After running sys/install.sh on a clean repo there's an error in the console saying: 
```
gcc: error: /home/pawlos/radare2/libr/../shlr/bochs/lib/libbochs.a: No such file or directory
gcc: error: /home/pawlos/radare2/libr/../shlr/bochs/lib/libbochs.a: No such file or directory
```
inspecting the path `/shlr/bochs` reveals that there is no lib folder. Instead there's a folder named: `libDESKTOP-6CCCM8K`
![hackpad com_qtknbwz39gk_p 102670_1467145445177_undefined](https://cloud.githubusercontent.com/assets/1296768/16431103/3f7c0982-3d7f-11e6-9d8c-6c51b2a51760.png)
as you can see `DESKTOP-6CCCM8K` is my hostname and somehow it's appended to the lib folder. Trying to trace where the folder get's created I found out the line 35 in the `Makefile` (inside `shlr/bochs`) where the folder gets created and added a ln there
`ln -s $(LIB) lib `
After this ugly-fix radare2 build ok.

I've tried to locate where this `$LIB` variable is set to properly fix this but my grep skills are not that good.

OS: Windows 10 Pro Insider Preview, Build: 14372.rs1_release.160620-2342

**Comment by XVilka** [comment] 2016-06-28 21:01
Can you please use [remake](https://github.com/rocky/remake) to get the value of this variable using debugger (gdb e.g.)?

**Comment by radare** [comment] 2016-06-28 22:06
can you paste the full build log?

**Comment by pawlos** [comment] 2016-06-29 04:52
@radare here's the full log https://gist.github.com/pawlos/29ff2aed81888cf17281669867ab53e7

@XVilka I'll try today use this remake tool to get the value of LIB, but when `echo`-ing the variable before it is used in mkdir gives me this exact value

**Comment by radare** [comment] 2016-06-29 09:36
it can be a race condition, did you tried with `export MAKE_JOBS=1` before running sys/install.sh ?

**Comment by pawlos** [comment] 2016-06-29 13:51
@radare it doesn't help

**Comment by pawlos** [comment] 2016-06-30 20:52
@XVilka I've installed remake - could you tell me how can I inspect the variable value during the build process with it?

**Comment by XVilka** [comment] 2016-07-01 10:47
@pawlos see this https://github.com/rocky/remake/wiki/Features-and-Using#invocation - just insert $(debugger) in corresponding line

**Comment by pawlos** [comment] 2016-07-06 06:16
@XVilka finally managed to run `rename` - this is the output. I find it interesting - should there be ${NAME} at the end?

```
remake<<<3>>> print LIB
../../libr/config.mk:216 (origin: makefile) LIB = lib${NAME}
```

**Comment by radare** [comment] 2016-07-27 13:07
Ping

**Comment by CoenraadS** [comment] 2016-08-24 09:26
I would also be interested in a fix for this.

**Comment by CoenraadS** [comment] 2016-08-24 10:11
`LIB=lib${NAME}` is defined in `/libr/config.mk.tail`

However after changing it, a new error appears:
`/usr/bin/ld: cannot find -lr_util`

**Comment by pawlos** [comment] 2016-08-24 11:16
@CoenraadS I did not have any issues after spotting this issue and fixing it (locally). I think just needed to clean before the next try

**Comment by radare** [comment] 2016-08-24 14:36
Can we close this issue then?

**Comment by pawlos** [comment] 2016-08-24 15:00
@radare if you think this is ok how it is in the master branch and this doesn't need to be corrected - I'm fine with closing the issue

**Comment by radare** [comment] 2016-08-24 15:17
uhm do you have a local patch to share? what about a pullreq?

**Comment by pawlos** [comment] 2016-08-24 18:00
@radare I'm happy to provide PR but honestly I'm stumbled that this would be the fix (I do not understand all the implications of this change) and wondering whether why I was the first one to spot this

**Comment by CoenraadS** [comment] 2016-08-24 19:38
I can confirm that putting 

`LIB = lib` the line before `all: $(LIB)/$(LIBNAME).a` in `shlr/bochs/Makefile` compiles correctly, but agree it feels like a hack. I'm pretty sure the original issue is in `/libr/config.mk.tail` but can't seem to make that work.

**Comment by pawlos** [comment] 2016-08-25 05:36
@CoenraadS I've run my fix on the latest version and it looks like I have the same issue that you described [here](https://github.com/radare/radare2/issues/5232#issuecomment-242016959). I need to check it and try to fix it

**Comment by 0xbc** [comment] 2016-09-02 12:45
Hi all,

I just ran across this issue and did a bit of digging around. It seems that, for some reason, the environment variable `NAME` is set to the machine's hostname for Bash on Ubuntu on Windows (!). As such, a fairly easy workaround to get r2 building is to unset the variable like so:

`$ NAME= sys/user.sh`

I haven't tried it with `sys/install.sh`, but the same thing should apply. I guess the way to fix it properly would be to add an OS check for BoUoW somewhere in one of the Makefiles and conditionally clear `NAME` if BoUoW is detected, but I don't know what the appropriate check would be off the top of my head.

**Comment by radare** [comment] 2016-09-02 13:09
NAME env var is set by windows?

**Comment by 0xbc** [comment] 2016-09-02 22:34
Yep... in Bash on Ubuntu on Windows, the `NAME` environment variable seems to be set to the hostname. It's not set in the regular Windows shell though.

Would an appropriate fix actually be to just replace all occurrences of `${LIB}` with `lib` in `shlr/bochs/Makefile`? There are a couple of other build scripts where the path for `libbochs.a` is explicitly assumed to be `shlr/bochs/lib/libbochs.a` anyway (e.g. `shlr/bochs/deps.mk` and `libr/io/p/bochs.mk`). This change builds fine on BoUoW... I'll test it on a proper Ubuntu distro when I get some time later. If you think that would be an appropriate/portable fix, I'm happy to put a PR together for it.

**Comment by radare** [comment] 2016-09-03 00:29
I dont have any windows at home, well just few vms with few disk space so i cant really build anything in there so i can do a blind fix, but i would prefer if you can send a pullrequest, so travis will test on linux and osx for you.

**Comment by 0xbc** [comment] 2016-09-04 10:48
PR is up - I didn't get to test it on straight Ubuntu so we'll see how the CI run goes...

**Comment by 0xbc** [comment] 2016-09-04 11:13
Merged, cool! @pawlos / @CoenraadS, does this work for you?

**Comment by CoenraadS** [comment] 2016-09-04 12:14
@0xbc Yes it is working

**Comment by radare** [comment] 2016-09-04 12:14
can we close this issue now?

**Comment by Maijin** [comment] 2016-09-04 12:24
Let's close and reopen if necessary.

**Closed by Maijin** 2016-09-04 12:24 UTC
Labels: Windows

**Comment by pawlos** [comment] 2016-09-04 19:20
@0xbc works for me too.

**Comment by Maijin** [comment] 2016-09-04 19:53
awesome !
