### ISSUE TITLE
Memory references in ESIL

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4429] opened 2016-03-25 21:07 UTC
Seems like ESIL is not emulating memory correctly. Most issues are because of
this. I am opening this as a representative issue for the same. Other memory
issues will be appended to this.

Binary: Ubuntu 14.04 /bin/ls
Instruction: mov rdi, qword [rsi]
ESIL: rsi,[8],rdi,=
Offset: 0x4026b0

| REGISTER | GDB | ESIL |
| --- | --- | --- |
| rdi | 0x1 -> 0x7fffffffe455 | 0x1 -> -0x1 |

**Comment by sushant94** [comment] 2016-03-25 21:31
__MORE__

Binary: Ubuntu 14.04 /bin/ls
Instruction: movzx edx, byte [rdi]
ESIL: rdi,[1],rdx,=
Offset: 0x4109f7

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rdx     | 0x0 -> 0x38                           | 0x0 -> 0xff                           |

**Comment by crowell** [comment] 2016-03-25 21:34
Looks like the memory wasn't set properly. I think reads work but writes
don't?

**Comment by sushant94** [comment] 2016-03-25 22:01
Seems to be the case, but I can't think of a way to test the write alone. These tests only show the effect through a read, which results in giving us an incorrect value.

**Comment by radare** [comment] 2016-03-26 20:21
this gdb vs esil thing is awesome :3

i guess unicorn guise will be happy with it

On 25 March 2016 at 23:01, Sushant Dinesh <notifications@github.com> wrote:

> Seems to be the case, but I can't think of a way to test the write alone.
> These tests only show the effect through a read, which results in giving us
> an incorrect value.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4429#issuecomment-201539081>
>



-- 
--pancake

**Comment by condret** [comment] 2016-06-25 09:46
@sushant94 can provide me the output of ````pxQ 4 @ rsi````? Could this be an issue in io?

**Comment by radare** [comment] 2016-06-29 12:53
ping @sushant94 @condret

**Comment by Svenito** [comment] 2016-11-24 16:36
Seems to work as expected. Using memory range from the automated tests

```
 radare2$ r2 -c "e io.cache=true; aeim 0x7fffffffeb80 0xf0000 Stack" -
[0x00000000]> px 4 @ 0x7fffffffeb80
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7fffffffeb80  0000 0000                                ....                            ....
[0x00000000]> ae 0xbeef,0x7fffffffeb80,=[]
[0x00000000]> px 4 @ 0x7fffffffeb80
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7fffffffeb80  efbe 0000                                ....
[0x00000000]> aer rsi=0x7fffffffeb80
[0x00000000]> wa mov rdi, qword [rsi]
Written 3 bytes (mov rdi, qword [rsi]) = wx 488b3e
[0x00000000]> ao
address: 0x0
opcode: mov rdi, qword [rsi]
prefix: 0
id: 449
bytes: 488b3e
ptr: 0x00000000
refptr: 8
size: 3
type: mov
esil: rsi,[8],rdi,=
stack: null
family: cpu
[0x00000000]> aes
[0x00000000]> aer?rdi
0x0000beef
```

hard to compare to sushant's tests as they don't show context around the instructions. As manual testing and r2r regressions are passing, I am closing.

**Closed by Svenito** 2016-11-24 16:36 UTC
Labels: esil, x86
